Callback.addCallback("PostLoaded", function () {
    Recipes.addShaped({id: ItemID.pot, count: 1, data: 0}, ["a a", "a a", "  a"], ["a", 265, 0]);
    Recipes.addShaped({id: ItemID.uncooked_stock_mix, count: 1, data: 0}, ["ab", "cd"], ["a", ItemID.chicken_bone, 0, "b", ItemID.pot, 0, "c", 325, 8, "d", 392, 0]);
    Recipes.addShaped({id: ItemID.batter, count: 1, data: 0}, ["ab", "cd"], ["a", ItemID.flour, 0, "b", 344, 0, "c", 325, 1, "d", ItemID.pot, 0]);
    Recipes.addShaped({id: ItemID.peeled_potato_in_pot, count: 1, data: 0}, ["ab", "c"], ["a", ItemID.peeled_potato, 0, "b", ItemID.pot, 0, "c", 325, 8]);
    Recipes.addShaped({id: ItemID.water_pot, count: 1, data: 0}, ["ab"], ["a", ItemID.pot, 0, "b", 325, 8]);
    Recipes.addShaped({id: ItemID.knife, count: 1, data: 0}, ["a", "b"], ["a", 265, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.mixing_bowl, count: 1, data: 0}, ["", "aba", " a "], ["a", 5, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.pestle_mortar, count: 1, data: 0}, ["a  ", "bcb", " b "], ["a", 280, 0, "b", 1, 0, "c", 265, 0]);
    Recipes.addShaped({id: ItemID.frying_pan, count: 1, data: 0}, ["aab"], ["a", 265, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.juicer, count: 1, data: 0}, ["aba", "bab"], ["a", 1, 0, "b", 44, 0]);
    Recipes.addShaped({id: ItemID.mincer, count: 1, data: 0}, ["ab ", "cdc", "c  "], ["a", 69, 0, "b", 33, 0, "c", 265, 0, "d", 101, 0]);
    Recipes.addShaped({id: ItemID.flour, count: 1, data: 0}, ["ab"], ["a", ItemID.pestle_mortar, 0, "b", 296, 0]);
    Recipes.addShaped({id: ItemID.dough, count: 8, data: 0}, ["ab", "cd"], ["a", ItemID.mixing_bowl, 0, "b", ItemID.flour, 0, "c", ItemID.salt, 0, "d", 325, 8]);
    Recipes.addShaped({id: ItemID.dough, count: 8, data: 0}, ["aa", "aa", "b"], ["a", 296, 0, "b", 325, 8]);
    Recipes.addShaped({id: ItemID.chopped_tomato, count: 1, data: 0}, ["a", "b"], ["a", ItemID.knife, 0, "b", ItemID.tomato, 0]);
    Recipes.addShaped({id: ItemID.chopped_onion, count: 4, data: 0}, ["a", "b"], ["a", ItemID.knife, 0, "b", ItemID.onion, 0]);
    Recipes.addShaped({id: ItemID.tomato_sauce, count: 1, data: 0}, ["ab", "cd"], ["a", ItemID.tomato, 0, "b", ItemID.mincer, 0, "c", 353, 0, "d", 374, 0]);
    Recipes.addShaped({id: ItemID.uncooked_minced_meat, count: 1, data: 0}, ["ab"], ["a", 363, 0, "b", ItemID.mincer, 0]);
    Recipes.addShaped({id: ItemID.medium_dough_ball, count: 2, data: 0}, ["a", "b"], ["a", ItemID.knife, 0, "b", ItemID.dough, 0]);
    Recipes.addShaped({id: ItemID.small_dough_ball, count: 2, data: 0}, ["a", "b"], ["a", ItemID.knife, 0, "b", ItemID.medium_dough_ball, 0]);
    Recipes.addShaped({id: ItemID.uncooked_pizza, count: 1, data: 0}, ["ab", "c"], ["a", ItemID.dough, 0, "b", ItemID.cheese_slice, 0, "c", ItemID.tomato, 0]);
    Recipes.addShaped({id: ItemID.uncooked_french_toast, count: 1, data: 0}, ["a", "b", "c"], ["a", 344, 0, "b", ItemID.slice_bread, 0, "c", ItemID.frying_pan, 0]);
    Recipes.addShaped({id: ItemID.cheese_sandwich, count: 1, data: 0}, ["a", "b", "a"], ["a", ItemID.slice_bread, 0, "b", ItemID.cheese_slice, 0]);
    Recipes.addShaped({id: ItemID.cheese_tomato_sandwich, count: 1, data: 0}, ["a", "bc", "a"], ["a", ItemID.slice_bread, 0, "b", ItemID.cheese_slice, 0, "c", ItemID.tomato, 0]);
    Recipes.addShaped({id: ItemID.ham_sandwich, count: 1, data: 0}, ["a", "b", "a"], ["a", ItemID.slice_bread, 0, "b", 320, 0]);
    Recipes.addShaped({id: ItemID.beef_sandwich, count: 1, data: 0}, ["a", "b", "a"], ["a", ItemID.slice_bread, 0, "b", 364, 0]);
    Recipes.addShaped({id: ItemID.batter, count: 1, data: 0}, ["ab", "cd"], ["a", ItemID.flour, 0, "b", 344, 0, "c", 325, 8, "d", ItemID.pot, 0]);
    Recipes.addShaped({id: ItemID.uncooked_battered_fish, count: 1, data: 0}, ["ab"], ["a", ItemID.batter, 0, "b", 349, 0]);
    Recipes.addShaped({id: ItemID.uncooked_egg_in_frying_pan, count: 1, data: 0}, ["ab"], ["a", 344, 0, "b", ItemID.frying_pan, 0]);
    Recipes.addShaped({id: ItemID.uncooked_sausage, count: 4, data: 0}, ["ab", "c"], ["a", ItemID.mincer, 0, "b", 319, 0, "c", ItemID.intestines, 0]);
    Recipes.addShaped({id: ItemID.uncooked_mushroom_in_frying_pan_1, count: 1, data: 0}, ["ab"], ["a", ItemID.frying_pan, 0, "b", 39, 0]);
    Recipes.addShaped({id: ItemID.uncooked_mushroom_in_frying_pan_2, count: 1, data: 0}, ["ab", "cd"], ["a", ItemID.frying_pan, 0, "b", 40, 0]);
    Recipes.addShaped({id: ItemID.sandwich_BLT, count: 1, data: 0}, ["a  ", "bcd", "a  "], ["a", ItemID.slice_bread, 0, "b", ItemID.bacon, 0, "c", ItemID.lettuce, 0, "d", ItemID.chopped_tomato, 0]);
    Recipes.addShaped({id: ItemID.footlong, count: 1, data: 0}, ["abc", "de"], ["a", ItemID.bagette, 0, "b", ItemID.cheese, 0, "c", ItemID.tomato, 0, "d", ItemID.lettuce, 0, "e", 366, 0]);
    Recipes.addShaped({id: ItemID.beefburger, count: 1, data: 0}, ["a", "b"], ["a", ItemID.bun, 0, "b", ItemID.cooked_beef_patty, 0]);
    Recipes.addShaped({id: ItemID.cheeseburger, count: 1, data: 0}, ["a", "bc"], ["a", ItemID.bun, 0, "b", ItemID.cooked_beef_patty, 0, "c", ItemID.cheese_slice, 0]);
    Recipes.addShaped({id: ItemID.apple_juice, count: 1, data: 0}, ["ab", "c"], ["a", 260, 0, "b", ItemID.juicer, 0, "c", 374, 0]);
    Recipes.addShaped({id: ItemID.carrot_juice, count: 1, data: 0}, ["ab", "c"], ["a", 391, 0, "b", ItemID.juicer, 0, "c", 374, 0]);
    Recipes.addShaped({id: ItemID.tomato_juice, count: 1, data: 0}, ["ab", "c"], ["a", ItemID.tomato, 0, "b", ItemID.juicer, 0, "c", 374, 0]);
    Recipes.addShaped({id: ItemID.beef_stew_dumplings, count: 1, data: 0}, ["abc", "def"], ["a", ItemID.stock, 0, "b", ItemID.boiled_potato, 0, "c", 391, 0, "d", 364, 0, "e", 281, 0, "f", ItemID.uncooked_dumpling, 0]);
    Recipes.addShaped({id: ItemID.chicken_stew, count: 1, data: 0}, ["abc", "de"], ["a", ItemID.stock, 0, "b", ItemID.boiled_potato, 0, "c", 391, 0, "d", 366, 0, "e", 281, 0]);
    Recipes.addShaped({id: ItemID.mutton_stew, count: 1, data: 0}, ["abc", "de"], ["a", ItemID.stock, 0, "b", ItemID.boiled_potato, 0, "c", 391, 0, "d", 424, 0, "e", 281, 0]);
    Recipes.addShaped({id: ItemID.pork_stew, count: 1, data: 0}, ["abc", "de"], ["a", ItemID.stock, 0, "b", ItemID.boiled_potato, 0, "c", 391, 0, "d", 320, 0, "e", 281, 0]);
    Recipes.addShaped({id: ItemID.butter, count: 1, data: 0}, ["ab", "c"], ["a", ItemID.mixing_bowl, 0, "b", 325, 8, "c", ItemID.salt, 0]);
    Recipes.addShaped({id: ItemID.butter, count: 2, data: 0}, ["aaa", "aba"], ["a", 325, 1, "b", ItemID.salt, 0]);
    Recipes.addShaped({id: ItemID.fish_and_chips, count: 1, data: 0}, ["ab"], ["a", ItemID.battered_fish, 0, "b", ItemID.chips, 0]);
    Recipes.addShaped({id: ItemID.gravy, count: 1, data: 0}, ["ab", "cd"], ["a", ItemID.stock, 0, "b", ItemID.suet, 0, "c", ItemID.flour, 0, "d", 374, 0]);
    Recipes.addShaped({id: ItemID.roast_beef_dinner, count: 1, data: 0}, ["abc", "de"], ["a", ItemID.roast_potato, 0, "b", 364, 0, "c", 391, 0, "d", ItemID.gravy, 0, "e", ItemID.yorkshire_pudding, 0]);
    Recipes.addShaped({id: ItemID.roast_pork_dinner, count: 1, data: 0}, ["abc", "de"], ["a", ItemID.roast_potato, 0, "b", 320, 0, "c", 391, 0, "d", ItemID.gravy, 0, "e", ItemID.apple_sauce, 0]);
    Recipes.addShaped({id: ItemID.roast_mutton_dinner, count: 1, data: 0}, ["ab", "cd"], ["a", ItemID.roast_potato, 0, "b", 424, 0, "c", 391, 0, "d", ItemID.gravy, 0]);
    Recipes.addShaped({id: ItemID.roast_rabbit_dinner, count: 1, data: 0}, ["ab", "cd"], ["a", ItemID.roast_potato, 0, "b", 412, 0, "c", 391, 0, "d", ItemID.gravy, 0]);
    Recipes.addShaped({id: ItemID.cooked_breakfast, count: 1, data: 0}, ["abc", "def"], ["a", ItemID.fried_mushroom, 0, "b", ItemID.fried_egg, 0, "c", ItemID.bacon, 0, "d", ItemID.sausage, 0, "e", ItemID.toast, 0, "f", ItemID.hashbrown, 0]);
    Recipes.addShaped({id: ItemID.chocolate, count: 1, data: 0}, ["ab", "cd"], ["a", ItemID.mixing_bowl, 0, "b", ItemID.butter, 0, "c", 353, 0, "d", 351, 3]);
    Recipes.addShaped({id: ItemID.cheese, count: 4, data: 0}, ["aa", "aa", "aa"], ["a", 325, 1]);
    Recipes.addShaped({id: ItemID.uncooked_stock_mix, count: 1, data: 0}, ["ab", "cd"], ["a", ItemID.chicken_bone, 0, "b", ItemID.pot, 0, "c", 325, 8, "d", 391, 0]);
    Recipes.addShaped({id: ItemID.uncooked_stock_mix, count: 1, data: 0}, ["ab", "cd"], ["a", ItemID.chicken_bone, 0, "b", ItemID.pot, 0, "c", 325, 8, "d", ItemID.onion, 0]);
    Recipes.addShaped({id: ItemID.uncooked_stock_mix, count: 1, data: 0}, ["ab", "cd"], ["a", ItemID.chicken_bone, 0, "b", ItemID.pot, 0, "c", 325, 8, "d", ItemID.lettuce, 0]);
    Recipes.addShaped({id: ItemID.pie_shell, count: 1, data: 0}, ["", "a a", "aaa"], ["a", ItemID.cooked_dough, 0]);
    Recipes.addShaped({id: ItemID.hot_dog, count: 1, data: 0}, [" a ", "aba", " a "], ["a", ItemID.cooked_dough, 0, "b", ItemID.sausage, 0]);
    Recipes.addShaped({id: ItemID.hamburger, count: 1, data: 0}, [" a ", "bcb", " d "], ["a", ItemID.bun_top, 0, "b", ItemID.cucumber, 0, "c", ItemID.ground_beef, 0, "d", ItemID.bun_bottom, 0]);
    Recipes.addShaped({id: ItemID.bagette, count: 1, data: 0}, ["  a", " a ", "a  "], ["a", 296, 0]);
    Recipes.addShaped({id: ItemID.sausage, count: 3, data: 0}, ["a  ", " a ", "  a"], ["a", 320, 0]);
    Recipes.addShaped({id: ItemID.chocolate, count: 2, data: 0}, ["aaa", "aba", "aaa"], ["a", ItemID.chocolate_syrup, 0, "b", 351, 3]);
    Recipes.addShaped({id: ItemID.cucumber_soup, count: 1, data: 0}, ["a", "b", "c"], ["a", 393, 0, "b", ItemID.cucumber, 0, "c", ItemID.salad_bowl, 0]);
    Recipes.addShaped({id: ItemID.chickenburger, count: 1, data: 0}, [" a ", "bcd", " e "], ["a", ItemID.bun_top, 0, "b", ItemID.hot_sauce, 0, "c", 366, 0, "d", ItemID.lettuce, 0, "e", ItemID.bun_bottom, 0]);
    Recipes.addShaped({id: ItemID.cheese, count: 4, data: 0}, ["aa", "aa", "aa"], ["a", 325, 1]);
    Recipes.addShaped({id: ItemID.bun, count: 1, data: 0}, [" a ", "a a", ""], ["a", 296, 0]);
    Recipes.addShaped({id: ItemID.cheeseburger, count: 1, data: 0}, [" a ", "bcd", " e "], ["a", ItemID.bun_top, 0, "b", ItemID.cheese, 0, "c", ItemID.ground_beef, 0, "d", ItemID.cucumber, 0, "e", ItemID.bun_bottom, 0]);
    Recipes.addShaped({id: ItemID.coffee_cup, count: 1, data: 0}, ["aa ", "aab", "aa "], ["a", 265, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.beer, count: 1, data: 0}, ["a", "b", "c"], ["a", ItemID.rice, 0, "b", 376, 0, "c", ItemID.glass_mug, 0]);
    Recipes.addShaped({id: ItemID.pizza_item, count: 1, data: 0}, ["aaa", "aba", "aaa"], ["a", ItemID.cooked_dough, 0, "b", ItemID.cheese, 0]);
    Recipes.addShaped({id: ItemID.potato_bread, count: 1, data: 0}, ["aba"], ["a", 296, 0, "b", 393, 0]);
    Recipes.addShaped({id: ItemID.pancake, count: 1, data: 0}, ["aaa"], ["a", ItemID.cooked_dough, 0]);
    Recipes.addShaped({id: ItemID.waffle, count: 1, data: 0}, ["aa", "aa", ""], ["a", ItemID.cooked_dough, 0]);
    Recipes.addShaped({id: ItemID.spaghetti, count: 1, data: 0}, [" a ", "bcb", " d "], ["a", ItemID.ground_beef, 0, "b", ItemID.cooked_dough, 0, "c", ItemID.tomato_sauce, 0, "d", ItemID.salad_bowl, 0]);
    Recipes.addShaped({id: ItemID.lasagne, count: 1, data: 0}, ["aaa", "bcd", "aaa"], ["a", ItemID.ground_beef, 0, "b", ItemID.cooked_dough, 0, "c", ItemID.tomato_sauce, 0, "d", ItemID.cheese, 0]);
    Recipes.addShaped({id: ItemID.tortilla, count: 1, data: 0}, ["aaa", "aba", "aaa"], ["a", ItemID.cooked_dough, 0, "b", ItemID.corn, 0]);
    Recipes.addShaped({id: ItemID.taco, count: 1, data: 0}, ["a e", "bcd", " f "], ["a", ItemID.onion, 0, "b", ItemID.tomato, 0, "c", ItemID.ground_beef, 0, "d", ItemID.cheese, 0, "e", ItemID.lettuce, 0, "f", ItemID.tortilla, 0]);
    Recipes.addShaped({id: ItemID.burrito, count: 1, data: 0}, [" a ", "bcd", " a "], ["a", ItemID.tortilla, 0, "b", ItemID.tomato, 0, "c", ItemID.ground_beef, 0, "d", ItemID.cheese, 0]);
    Recipes.addShaped({id: ItemID.garden_salad, count: 1, data: 0}, [" a ", "bcd", " e "], ["a", ItemID.lettuce, 0, "b", ItemID.cheese, 0, "c", ItemID.tomato, 0, "d", ItemID.cucumber, 0, "e", ItemID.salad_bowl, 0]);
    Recipes.addShaped({id: ItemID.chicken_salad, count: 1, data: 0}, ["ab ", "cde", " f "], ["a", ItemID.onion, 0, "b", ItemID.cucumber, 0, "c", ItemID.pepper, 0, "d", 366, 0, "e", 344, 0, "f", ItemID.salad_bowl, 0]);
    Recipes.addShaped({id: ItemID.caesar_salad, count: 1, data: 0}, ["ab ", "cde", " f "], ["a", ItemID.lettuce, 0, "b", ItemID.pepper_seeds, 0, "c", ItemID.cheese, 0, "d", ItemID.crouton, 0, "e", 344, 0, "f", ItemID.salad_bowl, 0]);
    Recipes.addShaped({id: ItemID.onion_salad, count: 1, data: 0}, ["", "abc", " d "], ["a", ItemID.lettuce, 0, "b", ItemID.onion, 0, "c", ItemID.tomato, 0, "d", ItemID.salad_bowl, 0]);
    Recipes.addShaped({id: ItemID.garden_salad, count: 1, data: 0}, [" a ", "bcd", " e "], ["a", ItemID.lettuce, 0, "b", ItemID.cheese, 0, "c", ItemID.tortilla, 0, "d", ItemID.tomato, 0, "e", ItemID.salad_bowl, 0]);
    Recipes.addShaped({id: ItemID.vegetable_soup, count: 1, data: 0}, ["abc", "def", " g "], ["a", ItemID.cucumber, 0, "b", 391, 0, "c", ItemID.pepper, 0, "d", ItemID.tomato, 0, "e", ItemID.onion, 0, "f", 392, 0, "g", ItemID.salad_bowl, 0]);
    Recipes.addShaped({id: ItemID.pumpkin_stew, count: 1, data: 0}, [" a ", "bcd", " e "], ["a", ItemID.pepper, 0, "b", 392, 0, "c", ItemID.ground_beef, 0, "d", 391, 0, "e", 86, 0]);
    Recipes.addShaped({id: ItemID.twinkie, count: 1, data: 0}, ["", "aba", " a "], ["a", ItemID.cooked_dough, 0, "b", ItemID.vanilla_cream, 0]);
    Recipes.addShaped({id: ItemID.chocolate_icecream_ball, count: 1, data: 0}, ["ab", "cd", ""], ["a", 351, 3, "b", ItemID.vanilla_cream, 0, "c", 332, 0, "d", 325, 1]);
    Recipes.addShaped({id: ItemID.vanilla_icecream_ball, count: 1, data: 0}, ["ab", "c", ""], ["a", ItemID.vanilla_cream, 0, "b", 332, 0, "c", 325, 1]);
    Recipes.addShaped({id: ItemID.strawberry_icecream_ball, count: 1, data: 0}, ["ab", "c", ""], ["a", ItemID.strawberry, 0, "b", 332, 0, "c", 325, 1]);
    Recipes.addShaped({id: ItemID.icecream_cone, count: 1, data: 0}, ["a a", "a a", " a "], ["a", 296, 0]);
    Recipes.addShaped({id: ItemID.crescent_roll, count: 1, data: 0}, ["a a", " a", ""], ["a", ItemID.cooked_dough, 0]);
    Recipes.addShaped({id: ItemID.donut, count: 4, data: 0}, ["aaa", "a a", "aaa"], ["a", ItemID.cooked_dough, 0]);
    Recipes.addShaped({id: ItemID.paper_cup, count: 3, data: 0}, ["a a", " a ", ""], ["a", 339, 0]);
    Recipes.addShaped({id: ItemID.paper_cup, count: 3, data: 0}, ["", "a a", " a "], ["a", 339, 0]);
    Recipes.addShaped({id: ItemID.chocolate_cupcake, count: 1, data: 0}, ["a", "b", "c"], ["a", ItemID.chocolate, 0, "b", ItemID.cooked_dough, 0, "c", ItemID.paper_cup, 0]);
    Recipes.addShaped({id: ItemID.strawberry_cupcake, count: 1, data: 0}, ["a", "b", "c"], ["a", ItemID.strawberry, 0, "b", ItemID.cooked_dough, 0, "c", ItemID.paper_cup, 0]);
    Recipes.addShaped({id: ItemID.oreo_cupcake, count: 1, data: 0}, ["a", "b", "c"], ["a", ItemID.oreo_cookie, 0, "b", ItemID.cooked_dough, 0, "c", ItemID.paper_cup, 0]);
    Recipes.addShaped({id: ItemID.vanilla_cream, count: 1, data: 0}, ["ab", "b", ""], ["a", ItemID.vanilla_extract, 0, "b", 353, 0]);
    Recipes.addShaped({id: ItemID.empty_can, count: 2, data: 0}, ["a a", "a a", "a a"], ["a", 265, 0]);
    Recipes.addShaped({id: ItemID.speedy_energy_drink, count: 1, data: 0}, ["ab", "cd", ""], ["a", 353, 0, "b", ItemID.rice, 0, "c", ItemID.empty_can, 0, "d", 325, 8]);
    Recipes.addShaped({id: ItemID.healthy_energy_drink, count: 1, data: 0}, ["ab", "cd", "e"], ["a", 370, 0, "b", ItemID.rice, 0, "c", ItemID.empty_can, 0, "d", 325, 8, "e", 382, 0]);
    Recipes.addShaped({id: ItemID.stealthy_energy_drink, count: 1, data: 0}, ["ab", "cd", "e"], ["a", ItemID.rice, 0, "b", ItemID.empty_can, 0, "c", 325, 8, "d", 353, 0, "e", 396, 0]);
    Recipes.addShaped({id: ItemID.strong_energy_drink, count: 1, data: 0}, ["ab", "cd", "e"], ["a", ItemID.rice, 0, "b", ItemID.empty_can, 0, "c", 325, 8, "d", 378, 0, "e", 377, 0]);
    Recipes.addShaped({id: ItemID.deadly_energy_drink, count: 1, data: 0}, ["ab", "cd", "e"], ["a", ItemID.rice, 0, "b", ItemID.empty_can, 0, "c", 325, 8, "d", 376, 0, "e", 375, 0]);
    Recipes.addShaped({id: ItemID.strong_energy_drink, count: 1, data: 0}, ["ab", "cd", "e"], ["a", ItemID.stealthy_energy_drink, 0, "b", ItemID.healthy_energy_drink, 0, "c", ItemID.speedy_energy_drink, 0, "d", ItemID.strong_energy_drink, 0, "e", 264, 0]);
    Recipes.addShaped({id: ItemID.oreo_cookie, count: 1, data: 0}, ["aba", " c ", "aba"], ["a", ItemID.chocolate_syrup, 0, "b", 357, 0, "c", ItemID.marshmallow, 0]);
    Recipes.addShaped({id: ItemID.glass_mug, count: 2, data: 0}, ["a a", "a a", "aaa"], ["a", 20, 0]);
    Recipes.addShaped({id: ItemID.chocolate_cake_item, count: 1, data: 0}, ["aaa", "bcb", "ddd"], ["a", 325, 1, "b", 353, 0, "c", ItemID.chocolate_syrup, 0, "d", 296, 0]);
    Recipes.addShaped({id: ItemID.nether_cake_item, count: 1, data: 0}, ["aaa", "bcb", "ddd"], ["a", 325, 1, "b", 353, 0, "c", 377, 0, "d", 296, 0]);
    Recipes.addShaped({id: ItemID.cheese_cake_item, count: 1, data: 0}, ["aaa", "bcb", "ddd"], ["a", 325, 1, "b", 353, 0, "c", ItemID.cheese, 0, "d", 296, 0]);
    Recipes.addShaped({id: ItemID.pumpkin_cake_item, count: 1, data: 0}, ["aaa", "bcb", "ddd"], ["a", 325, 1, "b", 353, 0, "c", 86, 0, "d", 296, 0]);
    Recipes.addShaped({id: ItemID.strawberry_cake_item, count: 1, data: 0}, ["aaa", "bcb", "ddd"], ["a", 325, 1, "b", 353, 0, "c", ItemID.strawberry, 0, "d", 296, 0]);
    Recipes.addShaped({id: ItemID.oreo_cake_item, count: 1, data: 0}, ["aaa", "bcb", "ddd"], ["a", 325, 1, "b", 353, 0, "c", ItemID.oreo_cookie, 0, "d", 296, 0]);
    Recipes.addShaped({id: ItemID.bun_top, count: 1, data: 0}, ["a a", " a ", ""], ["a", 296, 0]);
    Recipes.addShaped({id: ItemID.bun_bottom, count: 1, data: 0}, [" a ", "a a", ""], ["a", 296, 0]);
    Recipes.addShaped({id: ItemID.enchilada, count: 1, data: 0}, ["abc", "def", " b "], ["a", ItemID.rice, 0, "b", ItemID.tortilla, 0, "c", ItemID.cheese, 0, "d", ItemID.tomato_sauce, 0, "e", ItemID.ground_beef, 0, "f", ItemID.onion, 0]);
    Recipes.addShaped({id: ItemID.kebab, count: 1, data: 0}, [" a ", "bcd", " e "], ["a", ItemID.tomato, 0, "b", ItemID.lettuce, 0, "c", ItemID.ground_beef, 0, "d", ItemID.onion, 0, "e", ItemID.tortilla, 0]);
    Recipes.addShaped({id: ItemID.icecream_sandwich, count: 1, data: 0}, ["aba", "ccc", "aba"], ["a", ItemID.chocolate_syrup, 0, "b", 357, 0, "c", ItemID.vanilla_icecream_ball, 0]);
    Recipes.addShaped({id: ItemID.salad_bowl, count: 2, data: 0}, ["", "a a", " b "], ["a", 265, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.salad_bowl, count: 2, data: 0}, ["a a", " b ", ""], ["a", 265, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.tomato_soup, count: 1, data: 0}, ["", "a", "b"], ["a", ItemID.tomato, 0, "b", ItemID.salad_bowl, 0]);
    Recipes.addShaped({id: ItemID.beef_stew, count: 1, data: 0}, ["", "abc", " d "], ["a", 391, 0, "b", 364, 0, "c", ItemID.onion, 0, "d", ItemID.salad_bowl, 0]);
    Recipes.addShaped({id: ItemID.chicken_soup, count: 1, data: 0}, ["a", "b", "c"], ["a", 391, 0, "b", 366, 0, "c", ItemID.salad_bowl, 0]);
    Recipes.addShaped({id: ItemID.caramel_apple, count: 1, data: 0}, ["aaa", "aba", "aaa"], ["a", 353, 0, "b", 260, 0]);
    Recipes.addShaped({id: ItemID.vanilla_cupcake, count: 1, data: 0}, ["a", "b", "c"], ["a", ItemID.vanilla_cream, 0, "b", ItemID.cooked_dough, 0, "c", ItemID.paper_cup, 0]);
    Recipes.addShaped({id: ItemID.sandwich_BLT_2, count: 1, data: 0}, ["aaa", "bcd", "aaa"], ["a", ItemID.cooked_dough, 0, "b", ItemID.bacon, 0, "c", ItemID.lettuce, 0, "d", ItemID.tomato, 0]);
    Recipes.addShaped({id: ItemID.chicken_sandwich_2, count: 1, data: 0}, ["aaa", "bcb", "aaa"], ["a", ItemID.cooked_dough, 0, "b", ItemID.lettuce, 0, "c", 366, 0]);
    Recipes.addShaped({id: ItemID.beef_jerky, count: 4, data: 0}, ["ab", "a"], ["a", 353, 0, "b", 364, 0]);
    Recipes.addShaped({id: ItemID.jambon_beurre, count: 1, data: 0}, ["a", "b", "c"], ["a", 320, 0, "b", ItemID.butter, 0, "c", ItemID.bagette, 0]);
    Recipes.addShaped({id: ItemID.macaroni_and_cheese, count: 1, data: 0}, [" a ", "bbb", " a "], ["a", ItemID.cheese, 0, "b", ItemID.cooked_dough, 0]);
    Recipes.addShaped({id: ItemID.sandwich_breakfast, count: 1, data: 0}, ["aaa", "bcd", "aaa"], ["a", ItemID.cooked_dough, 0, "b", ItemID.bacon, 0, "c", ItemID.cheese, 0, "d", ItemID.fried_egg, 0]);
    Recipes.addShaped({id: ItemID.sandwich_cheese_grilled, count: 1, data: 0}, ["aaa", "bbb", "aaa"], ["a", ItemID.cooked_dough, 0, "b", ItemID.cheese, 0]);
    Recipes.addShaped({id: ItemID.sausage_roll, count: 1, data: 0}, ["a", "b", "a"], ["a", ItemID.cooked_dough, 0, "b", ItemID.sausage, 0]);
    Recipes.addShaped({id: ItemID.bourbon_biscuit, count: 1, data: 0}, ["a", "b", "a"], ["a", ItemID.chocolate, 0, "b", ItemID.chocolate_icecream_ball, 0]);
});

