Ace3.addFood("tomato", "Tomato", {name: "Tomato", meta: 0}, 1);
Ace3.addFood("onion", "Onion", {name: "Onion", meta: 0}, 1);
Ace3.addFood("lettuce", "Lettuce", {name: "Lettuce", meta: 0}, 1);
Ace3.addFood("gravy", "Gravy", {name: "Gravy", meta: 0}, 2);
Ace3.addFood("yorkshire_pudding", "Yorkshire Pudding", {name: "YorkshirePudding", meta: 0}, 2);
Ace3.addFood("roast_beef_dinner", "Roast Beef Dinner", {name: "RoastBeefDinner", meta: 0}, 10);
Ace3.addFood("roast_potato", "Roast Potato", {name: "RoastPotato", meta: 0}, 4);
Ace3.addFood("cheese_slice", "Slice Of Cheese", {name: "CheeseSlice", meta: 0}, 1);
Ace3.addFood("cheese", "Cheese", {name: "Cheese", meta: 0}, 1);
Ace3.addFood("bagette", "Baguette", {name: "Baguette", meta: 0}, 6);
Ace3.addFood("slice_bread", "Slice Of Bread", {name: "SliceOfBread", meta: 0}, 1);
Ace3.addFood("footlong", "Footlong", {name: "Footlong", meta: 0}, 9);
Ace3.addFood("boiled_potato", "Boiled Potato", {name: "BoiledPotato", meta: 0}, 3);
Ace3.addFood("apple_sauce", "Apple Sauce", {name: "AppleSauce", meta: 0}, 1);
Ace3.addFood("bacon", "Bacon", {name: "Bacon", meta: 0}, 3);
Ace3.addFood("toast", "Toast", {name: "Toast", meta: 0}, 1);
Ace3.addFood("hashbrown", "Hashbrown", {name: "HashBrown", meta: 0}, 3);
Ace3.addFood("carrot_juice", "Carrot Juice", {name: "CarrotJuice", meta: 0}, 2);
Ace3.addFood("tomato_juice", "Tomato Juice", {name: "TomatoJuice", meta: 0}, 2);
Ace3.addFood("apple_juice", "Apple Juice", {name: "AppleJuice", meta: 0}, 2);
Ace3.addFood("cooked_beef_patty", "Cooked Beef Patty", {name: "CookedBeefPatty", meta: 0}, 3);
Ace3.addFood("bacon_sandwich", "Bacon Sandwich", {name: "BaconSandwich", meta: 0}, 4);
Ace3.addFood("butter", "Butter", {name: "Butter", meta: 0}, 1);
Ace3.addFood("battered_fish", "Battered Fish", {name: "BatteredFish", meta: 0}, 6);
Ace3.addFood("pizza", "Pizza", {name: "Pizza", meta: 0}, 6);
Ace3.addFood("bun", "Bun", {name: "Bun", meta: 0}, 1);
Ace3.addFood("beefburger", "Beefburger", {name: "BeefBurger", meta: 0}, 5);
Ace3.addFood("cheeseburger", "Cheeseburger", {name: "CheeseBurger", meta: 0}, 10);
Ace3.addFood("beef_stew_dumplings", "Beefstew Dumplings", {name: "BeefStew-dumplings", meta: 0}, 10);
Ace3.addFood("chips", "Chips", {name: "Chips", meta: 0}, 1);
Ace3.addFood("fried_egg", "Fried Egg", {name: "FriedEgg", meta: 0}, 3);
Ace3.addFood("fried_mushroom", "Fried Mushroom", {name: "FriedMushroom", meta: 0}, 2);
Ace3.addFood("roast_pork_dinner", "Roast Pork Dinner", {name: "RoastPorkDinner", meta: 0}, 10);
Ace3.addFood("roast_mutton_dinner", "Roast Mutton Dinner", {name: "RoastMuttonDinner", meta: 0}, 10);
Ace3.addFood("roast_rabbit_dinner", "Roast Rabbit Dinner", {name: "RoastRabbitDinner", meta: 0}, 10);
Ace3.addFood("chocolate", "Chocolate", {name: "Chocolate", meta: 0}, 1);
Ace3.addFood("double_chocolate_cookie", "Double Chocolate Cookie", {name: "DoubleChocolateCookie", meta: 0}, 6);
Ace3.addFood("cookie_dough", "Cookie Dough", {name: "CookieDough", meta: 0}, 2);
Ace3.addFood("chicken_stew", "Chicken Stew", {name: "ChickenStew", meta: 0}, 10);
Ace3.addFood("mutton_stew", "Mutton Stew", {name: "MuttonStew", meta: 0}, 10);
Ace3.addFood("pork_stew", "Pork Stew", {name: "PorkStew", meta: 0}, 10);
Ace3.addFood("sandwich_BLT", "Sandwich BLT", {name: "SandwichBLT", meta: 0}, 6);
Ace3.addFood("cheese_sandwich", "Cheese Sandwich", {name: "CheeseSandwich", meta: 0}, 4);
Ace3.addFood("cheese_tomato_sandwich", "Cheese-Tomato Sandwich", {name: "CheeseTomatoSandwich", meta: 0}, 4);
Ace3.addFood("ham_sandwich", "Ham Sandwich", {name: "HamSandwich", meta: 0}, 4);
Ace3.addFood("beef_sandwich", "Beef Sandwich", {name: "BeefSandwich", meta: 0}, 4);
Ace3.addFood("chicken_sandwich", "Chicken Sandwich", {name: "ChickenSandwich", meta: 1}, 4);
Ace3.addFood("cooked_french_toast", "Cooked French Toast", {name: "CookedFrenchToast", meta: 0}, 4);
Ace3.addFood("mashed_potato", "Mashed Potato", {name: "MashedPotato", meta: 0}, 3);
Ace3.addFood("cooked_breakfast", "Cooked Breakfast", {name: "CookedBreakfast", meta: 0}, 10);
Ace3.addFood("fish_and_chips", "Fish And Chips", {name: "FishAndChips", meta: 0}, 10);
Ace3.addFood("sausage", "Sausage", {name: "Sausage", meta: 1}, 3);
Ace3.addFood("cooked_flesh", "Cooked Flesh", {name: "CookedFlesh", meta: 0}, 4);
Ace3.addFood("chopped_tomato", "Chopped Tomato", {name: "ChoppedTomato", meta: 0}, 1);
Ace3.addFood("chopped_onion", "Chopped Onion", {name: "ChoppedOnion", meta: 0}, 1);
Ace3.addFood("pepper", "Pepper", {name: "Pepper", meta: 0}, 1);
Ace3.addFood("corn", "Corn", {name: "Corn", meta: 0}, 1);
Ace3.addFood("raw_corn", "Raw Corn", {name: "RawCorn", meta: 0}, 1);
Ace3.addFood("raw_chicken_wing", "Raw Chicken Wing", {name: "RawChickenWing", meta: 0}, 1);
Ace3.addFood("cooked_chicken_wing", "Cooked Chicken Wing", {name: "CookedChickenWing", meta: 0}, 4);
Ace3.addFood("spicy_chicken_wing", "Spicy Chicken Wing", {name: "SpicyChickenWing", meta: 0}, 4);
Ace3.addFood("cheese_pie", "Cheese Pie", {name: "CheesePie", meta: 0}, 8);
Ace3.addFood("cheesy_bread", "Cheesy Bread", {name: "CheesyBread", meta: 0}, 6);
Ace3.addFood("hot_dog", "Hot Dog", {name: "HotDog", meta: 0}, 8);
Ace3.addFood("hamburger", "Hamburger", {name: "Hamburger", meta: 0}, 9);
Ace3.addFood("chickenburger", "Chickenburger", {name: "Chickenburger", meta: 0}, 9);
Ace3.addFood("bacon_pie", "Bacon Pie", {name: "BaconPie", meta: 0}, 8);
Ace3.addFood("chocolate_pie", "Chocolate Pie", {name: "ChocolatePie", meta: 0}, 8);
Ace3.addFood("golden_apple_pie", "Golden Apple Pie", {name: "Golden_apple_pie", meta: 0}, 8);
Ace3.addFood("fish_pie", "Fish Pie", {name: "FishPie", meta: 0}, 8);
Ace3.addFood("cucumber", "Cucumber", {name: "Cucumber", meta: 0}, 1);
Ace3.addFood("cucumber_soup", "Cucumber Soup", {name: "CucumberSoup", meta: 0}, 6);
Ace3.addFood("ground_beef", "Ground Beef", {name: "GroundBeef", meta: 0}, 4);
Ace3.addFood("apple_pie", "Apple Pie", {name: "ApplePie", meta: 0}, 8);
Ace3.addFood("tomato_soup", "Tomato Soup", {name: "TomatoSoup", meta: 0}, 3);
Ace3.addFood("brownie", "Brownie", {name: "Brownie", meta: 0}, 3);
Ace3.addFood("strawberry", "Strawberry", {name: "Strawberry", meta: 0}, 1);
Ace3.addFood("strawberry_pie", "Strawberry Pie", {name: "StrawberryPie", meta: 0}, 8);
Ace3.addFood("coffee", "Coffee", {name: "CoffeeCup", meta: 0}, 1);
Ace3.addFood("cappuccino", "Cappuccino", {name: "Cappuccino", meta: 0}, 2);
Ace3.addFood("chocolate_cupcake", "Chocolate Cupcake", {name: "ChocolateCupcake", meta: 0}, 3);
Ace3.addFood("strawberry_cupcake", "Strawberry Cupcake", {name: "StrawberryCupcake", meta: 0}, 3);
Ace3.addFood("crescent_roll", "Crescent Roll", {name: "CrescentRoll", meta: 0}, 6);
Ace3.addFood("donut", "Donut", {name: "Donut", meta: 0}, 4);
Ace3.addFood("chicken_pot_pie", "Chicken Pot Pie", {name: "ChickenPotPie", meta: 0}, 8);
Ace3.addFood("potato_bread", "Potato Bread", {name: "PotatoBread", meta: 0}, 6);
Ace3.addFood("pancake", "Pancake", {name: "Pancake", meta: 0}, 5);
Ace3.addFood("crouton", "Crouton", {name: "Crouton", meta: 0}, 1);
Ace3.addFood("pumpkin_stew", "Pumpkin Stew", {name: "PumpkinStew", meta: 0}, 6);
Ace3.addFood("tortilla", "Tortilla", {name: "Tortilla", meta: 0}, 4);
Ace3.addFood("cheese_puff", "Cheese Puff", {name: "CheesePuff", meta: 0}, 1);
Ace3.addFood("waffle", "Waffle", {name: "Waffle", meta: 0}, 5);
Ace3.addFood("spicy_chips", "Spicy Chips", {name: "SpicyChips", meta: 0}, 1);
Ace3.addFood("salty_chips", "Salty Chips", {name: "SaltyChips", meta: 0}, 1);
Ace3.addFood("lasagne", "Lasagne", {name: "Lasagne", meta: 0}, 12);
Ace3.addFood("bucket_of_fried_chicken", "Bucket Of Fried Chicken", {name: "Bucket_of_fried_chicken", meta: 0}, 6);
Ace3.addFood("taco", "Taco", {name: "Taco", meta: 0}, 7);
Ace3.addFood("burrito", "Burrito", {name: "Burrito", meta: 0}, 7);
Ace3.addFood("slice_of_pizza", "Slice Of Pizza", {name: "SliceOfPizza", meta: 0}, 7);
Ace3.addFood("spaghetti", "Spaghetti", {name: "Spaghetti", meta: 0}, 9);
Ace3.addFood("marshmallow", "Marshmallow", {name: "Marshmallow", meta: 0}, 1);
Ace3.addFood("roasted_marshmallow", "Roasted Marshmallow", {name: "RoastedMarshmallow", meta: 0}, 2);
Ace3.addFood("twinkie", "Twinkie", {name: "Twinkie", meta: 0}, 4);
Ace3.addFood("corn_bread", "Corn Bread", {name: "CornBread", meta: 0}, 8);
Ace3.addFood("sugar_donut", "Sugar Donut", {name: "SugarDonut", meta: 0}, 4);
Ace3.addFood("chocolate_donut", "Chocolate Donut", {name: "ChocolateDonut", meta: 0}, 4);
Ace3.addFood("garden_salad", "Garden Salad", {name: "GardenSalad", meta: 0}, 5);
Ace3.addFood("chicken_salad", "Chicken Salad", {name: "ChickenSalad", meta: 0}, 8);
Ace3.addFood("caesar_salad", "Caesar Salad", {name: "CaesarSalad", meta: 0}, 6);
Ace3.addFood("onion_salad", "Onion Salad", {name: "OnionSalad", meta: 0}, 4);
Ace3.addFood("taco_salad", "Taco Salad", {name: "TacoSalad", meta: 0}, 10);
Ace3.addFood("vegetable_soup", "Vegetable Soup", {name: "VegetableSoup", meta: 0}, 8);
Ace3.addFood("onion_rings", "Onion Rings", {name: "OnionRings", meta: 0}, 2);
Ace3.addFood("rice", "Rice", {name: "Rice", meta: 0}, 1);
Ace3.addFood("butter_rice", "Butter Rice", {name: "ButterRice", meta: 0}, 4);
Ace3.addFood("fried_rice", "Fried Rice", {name: "FriedRice", meta: 0}, 3);
Ace3.addFood("icecream_cone", "Ice Cream Cone", {name: "IcecreamCone", meta: 0}, 3);
Ace3.addFood("chocolate_icecream", "Chocolate Ice Cream", {name: "ChocolateIcecream", meta: 0}, 4);
Ace3.addFood("vanilla_icecream", "Vanilla Ice Cream", {name: "VanillaIcecream", meta: 0}, 4);
Ace3.addFood("strawberry_icecream", "Strawberry Ice Cream", {name: "StrawberryIcecream", meta: 0}, 4);
Ace3.addFood("oreo_cookie", "Oreo Cookie", {name: "OreoCookie", meta: 0}, 3);
Ace3.addFood("oreo_cupcake", "Oreo Cupcake", {name: "OreoCupcake", meta: 0}, 5);
Ace3.addFood("bun_top", "Bun Top", {name: "BunTop", meta: 0}, 1);
Ace3.addFood("bun_bottom", "Bun Bottom", {name: "BunBottom", meta: 0}, 1);
Ace3.addFood("caramel_apple", "Caramel Apple", {name: "CaramelApple", meta: 0}, 6);
Ace3.addFood("kebab", "Kebab", {name: "Kebab", meta: 0}, 12);
Ace3.addFood("enchilada", "Enchilada", {name: "Enchilada", meta: 0}, 9);
Ace3.addFood("icecream_sandwich", "Ice Cream Sandwich", {name: "IcecreamSandwich", meta: 0}, 6);
Ace3.addFood("vanilla_cupcake", "Vanilla Cupcake", {name: "VanillaCupcake", meta: 0}, 2);
Ace3.addFood("beef_stew", "Beef Stew", {name: "BeefStew", meta: 0}, 12);
Ace3.addFood("chicken_soup", "Chicken Soup", {name: "ChickenSoup", meta: 0}, 10);
Ace3.addFood("dough", "Dough", {name: "Dough", meta: 0}, 1);
Ace3.addFood("cooked_dough", "Cooked Dough", {name: "CookedDough", meta: 0}, 2);
Ace3.addFood("salt", "Salt", {name: "Salt", meta: 0}, 0);
Ace3.addFood("sandwich_BLT_2", "Sandwich BLT", {name: "SandwichBLT2", meta: 0}, 12);
Ace3.addFood("chicken_sandwich_2", "Chicken Sandwich", {name: "ChickenSandwich", meta: 0}, 10);
Ace3.addFood("macaroni_and_cheese", "Macaroni and Cheese", {name: "MacaroniAndCheese", meta: 0}, 9);
Ace3.addFood("beef_jerky", "Beef Jerky", {name: "BeefJerky", meta: 0}, 3);
Ace3.addFood("jambon_beurre", "Jambon-Beurre", {name: "JambonBeurre", meta: 0}, 15);
Ace3.addFood("vanilla_donut", "Vanilla Donut", {name: "VanillaDonut", meta: 0}, 5);
Ace3.addFood("sandwich_cheese_grilled", "Grilled Cheese Sandwich", {name: "SandwichCheeseGrilled", meta: 0}, 11);
Ace3.addFood("sandwich_breakfast", "Breakfast Sandwich", {name: "SandwichBreakfast", meta: 0}, 8);
Ace3.addFood("sausage_roll", "Sausage Roll", {name: "SausageRoll", meta: 0}, 7);
Ace3.addFood("bourbon_biscuit", "Bourbon Biscuit", {name: "BourbonBiscuit", meta: 0}, 3);

