Callback.addCallback("PostLoaded", function () {
    Recipes.addFurnace(ItemID.water_pot, ItemID.salt_pot, 0);
    Recipes.addFurnace(ItemID.uncooked_minced_meat, ItemID.cooked_minced_meat, 0);
    Recipes.addFurnace(ItemID.uncooked_beef_patty, ItemID.cooked_beef_patty, 0);
    Recipes.addFurnace(ItemID.uncooked_french_toast, ItemID.cooked_french_toast_in_frying_pan, 0);
    Recipes.addFurnace(ItemID.uncooked_pizza, ItemID.pizza, 0);
    Recipes.addFurnace(ItemID.uncooked_stock_mix, ItemID.stock, 0);
    Recipes.addFurnace(ItemID.uncooked_egg_in_frying_pan, ItemID.fried_egg_in_frying_pan, 0);
    Recipes.addFurnace(ItemID.uncooked_mushroom_in_frying_pan_1, ItemID.fried_mushroom_in_frying_pan, 0);
    Recipes.addFurnace(ItemID.uncooked_mushroom_in_frying_pan_2, ItemID.fried_mushroom_in_frying_pan, 0);
    Recipes.addFurnace(ItemID.batter, ItemID.yorkshire_pudding_in_pot, 0);
    Recipes.addFurnace(ItemID.peeled_potato_in_pot, ItemID.boiled_potato_in_pot, 0);
    Recipes.addFurnace(ItemID.slice_bread, ItemID.toast, 0);
    Recipes.addFurnace(ItemID.small_dough_ball, ItemID.bun, 0);
    Recipes.addFurnace(ItemID.medium_dough_ball, ItemID.bagette, 0);
    Recipes.addFurnace(ItemID.peeled_chipped_potato, ItemID.chips, 0);
    Recipes.addFurnace(ItemID.peeled_potato, ItemID.roast_potato, 0);
    Recipes.addFurnace(ItemID.batter, ItemID.yorkshire_pudding_in_pot, 0);
    Recipes.addFurnace(ItemID.uncooked_hashbrown, ItemID.hashbrown, 0);
    Recipes.addFurnace(ItemID.uncooked_battered_fish, ItemID.battered_fish, 0);
    Recipes.addFurnace(ItemID.uncooked_bacon, ItemID.bacon, 0);
    Recipes.addFurnace(ItemID.uncooked_sausage, ItemID.sausage, 0);
    Recipes.addFurnace(ItemID.cookie_dough, ItemID.double_chocolate_cookie, 0);
    Recipes.addFurnace(367, ItemID.cooked_flesh, 0);
    Recipes.addFurnace(ItemID.dough, ItemID.cooked_dough, 0);
    Recipes.addFurnace(ItemID.cooked_dough, ItemID.cookie_dough, 0);
    Recipes.addFurnace(ItemID.raw_chicken_wing, ItemID.cooked_chicken_wing, 0);
    Recipes.addFurnace(ItemID.raw_corn, ItemID.corn, 0);
    Recipes.addFurnace(351, ItemID.chocolate_syrup, 3);
    Recipes.addFurnace(ItemID.pepper, ItemID.hot_sauce, 0);
    Recipes.addFurnace(ItemID.rice, ItemID.fried_rice, 0);
    Recipes.addFurnace(ItemID.cheese, ItemID.cheese_puff, 0);
    Recipes.addFurnace(353, ItemID.marshmallow, 0);
    Recipes.addFurnace(ItemID.marshmallow, ItemID.roasted_marshmallow, 0);
    Recipes.addFurnace(ItemID.tomato, ItemID.tomato_sauce, 0);
});

