Ace3.addItem("pestle_mortar", "Pestle & Mortar", {name: "PestleMortar", meta: 0}, {stack: 1});
Ace3.addItem("flour", "Flour", {name: "Flour", meta: 0}, {});
Ace3.addItem("mixing_bowl", "Mixing Bowl", {name: "MixingBowl", meta: 0}, {stack: 1});
Ace3.addItem("pot", "Pot", {name: "Pot", meta: 0}, {stack: 1});
Ace3.addItem("water_pot", "Pot Of Water", {name: "PotOfWater", meta: 0}, {stack: 1});
Ace3.addItem("salt_pot", "Pot Of Salt", {name: "PotOfSalt", meta: 0}, {stack: 1});
Ace3.addItem("chicken_bone", "Chicken Bone", {name: "ChickenBone", meta: 0}, {});
Ace3.addItem("uncooked_stock_mix", "Uncooked Stock Mix", {name: "UncookedStockMix", meta: 0}, {stack: 1});
Ace3.addItem("peeled_potato", "Peeled Potato", {name: "PeeledPotato", meta: 0}, {});
Ace3.addItem("bacon_joint", "Bacon Joint", {name: "BaconJoint", meta: 0}, {});
Ace3.addItem("intestines", "Intestines", {name: "Intestines", meta: 0}, {});
Ace3.addItem("pork_joint", "Pork Joint", {name: "PorkJoint", meta: 0}, {});
Ace3.addItem("beef_joint", "Beef Joint", {name: "BeefJoint", meta: 0}, {});
Ace3.addItem("suet", "Suet", {name: "Suet", meta: 0}, {});
Ace3.addItem("bucket_cheese", "Bucket Cheese", {name: "BucketCheese", meta: 0}, {stack: 1});
Ace3.addItem("medium_dough_ball", "Medium Dough Ball", {name: "MediumDoughBall", meta: 0}, {});
Ace3.addItem("mincer", "Mincer", {name: "Mincer", meta: 0}, {stack: 1});
Ace3.addItem("uncooked_minced_meat", "Uncooked Minced Meat", {name: "UncookedMincedMeat", meta: 0}, {});
Ace3.addItem("tomato_sauce", "Tomato Sauce", {name: "TomatoSauce", meta: 0}, {});
Ace3.addItem("uncooked_sausage", "Uncooked Sausage", {name: "UncookedSausage", meta: 0}, {});
Ace3.addItem("uncooked_bacon", "Uncooked Bacon", {name: "UncookedBacon", meta: 0}, {});
Ace3.addItem("uncooked_hashbrown", "Uncooked Hashbrown", {name: "UncookedHashBrown", meta: 0}, {});
Ace3.addItem("frying_pan", "Frying Pan", {name: "FryingPan", meta: 0}, {stack: 1});
Ace3.addItem("uncooked_french_toast", "Uncooked French Toast", {name: "UncookedFrenchToast", meta: 0}, {});
Ace3.addItem("uncooked_egg_in_frying_pan", "Uncooked Egg In Frying Pan", {name: "UncookedEggInFryingPan", meta: 0}, {});
Ace3.addItem("uncooked_mushroom_in_frying_pan_1", "Uncooked Mushroom In Frying Pan", {name: "UncookedMushroomInFryingPan", meta: 0}, {});
Ace3.addItem("uncooked_mushroom_in_frying_pan_2", "Uncooked Mushroom In Frying Pan", {name: "UncookedMushroomInFryingPan", meta: 1}, {});
Ace3.addItem("juicer", "Juicer", {name: "Juicer", meta: 0}, {stack: 1});
Ace3.addItem("cooked_minced_meat", "Cooked Minced Meat", {name: "CookedMincedMeat", meta: 0}, {});
Ace3.addItem("uncooked_beef_patty", "Uncooked Beef Patty", {name: "UncookedBeefPatty", meta: 0}, {});
Ace3.addItem("small_dough_ball", "Small Dough Ball", {name: "SmallDoughBall", meta: 0}, {});
Ace3.addItem("cooked_french_toast_in_frying_pan", "Cooked French Toast In Frying Pan", {name: "CookedFrenchToastInFryingPan", meta: 0}, {});
Ace3.addItem("batter", "Batter", {name: "Batter", meta: 0}, {stack: 1});
Ace3.addItem("uncooked_battered_fish", "Uncooked Battered Fish", {name: "UncookedBatteredFish", meta: 0}, {});
Ace3.addItem("peeled_chipped_potato", "Peeled And Chipped Potato", {name: "PeeledChippedPotato", meta: 0}, {});
Ace3.addItem("uncooked_dumpling", "Uncooked Dumpling", {name: "UncookedDumpling", meta: 0}, {});
Ace3.addItem("uncooked_pizza", "Uncooked Pizza", {name: "UncookedPizza", meta: 0}, {});
Ace3.addItem("peeled_potato_in_pot", "Peeled Potato In Pot", {name: "PeeledPotatoInPot", meta: 0}, {});
Ace3.addItem("boiled_potato_in_pot", "Boiled Potato In Pot", {name: "BoiledPotatoInPot", meta: 0}, {});
Ace3.addItem("yorkshire_pudding_in_pot", "Yorkshire Pudding In Pot", {name: "YorkshirePuddingInPot", meta: 0}, {});
Ace3.addItem("stock", "Stock", {name: "Stock", meta: 0}, {});
Ace3.addItem("fried_egg_in_frying_pan", "Fried Egg In Frying Pan", {name: "FriedEggInFryingPan", meta: 0}, {});
Ace3.addItem("fried_mushroom_in_frying_pan", "Fried Mushroom In Frying Pan", {name: "FriedMushroomInFryingPan", meta: 0}, {});
Ace3.addItem("knife", "Knife", {name: "Knife", meta: 0}, {stack: 16});
Ace3.addItem("boiled_milk", "Boiled Milk", {name: "bucket", meta: 1}, {stack: 16, isTech: true});
Ace3.addItem("pie_shell", "Pie Shell", {name: "PieShell", meta: 0}, {stack: 16});
Ace3.addItem("chocolate_syrup", "Chocolate Syrup", {name: "ChocolateSyrup", meta: 0}, {});
Ace3.addItem("hot_sauce", "Hot Sauce", {name: "HotSauce", meta: 0}, {});
Ace3.addItem("coffee_cup", "Coffee Cup", {name: "CoffeeCup", meta: 0}, {stack: 1});
Ace3.addItem("vanilla_extract", "Vanilla Extract", {name: "VanillaExtract", meta: 0}, {stack: 16});
Ace3.addItem("vanilla_cream", "Vanilla Cream", {name: "VanillaCream", meta: 0}, {stack: 16});
Ace3.addItem("paper_cup", "Paper Cup", {name: "PaperCup", meta: 0}, {stack: 16});
Ace3.addItem("empty_can", "Empty Can", {name: "EmptyCan", meta: 0}, {stack: 16});
Ace3.addItem("chocolate_icecream_ball", "Chocolate Ice Cream Ball", {name: "ChocolateIcecreamBall", meta: 0}, {});
Ace3.addItem("vanilla_icecream_ball", "Vanilla Ice Cream Ball", {name: "VanillaIcecreamBall", meta: 0}, {});
Ace3.addItem("strawberry_icecream_ball", "Strawberry Ice Cream Ball", {name: "StrawberryIcecreamBall", meta: 0}, {});
Ace3.addItem("glass_mug", "Glass Mug", {name: "GlassMug", meta: 0}, {stack: 16});
Ace3.addItem("salad_bowl", "Salad Bowl", {name: "SaladBowl", meta: 0}, {stack: 16});

