Callback.addCallback("PostLoaded", function () {
    Recipes.addShapeless({id: ItemID.tomato_seeds, count: 1, data: 0}, [{id: ItemID.tomato, data: 0}]);
    Recipes.addShapeless({id: ItemID.lettuce_seeds, count: 1, data: 0}, [{id: ItemID.lettuce, data: 0}]);
    Recipes.addShapeless({id: ItemID.pepper_seeds, count: 1, data: 0}, [{id: ItemID.pepper, data: 0}]);
    Recipes.addShapeless({id: ItemID.corn_seeds, count: 1, data: 0}, [{id: ItemID.corn, data: 0}]);
    Recipes.addShapeless({id: ItemID.cucumber_seeds, count: 1, data: 0}, [{id: ItemID.cucumber, data: 0}]);
    Recipes.addShapeless({id: ItemID.strawberry_seeds, count: 1, data: 0}, [{id: ItemID.strawberry, data: 0}]);
    Recipes.addShapeless({id: ItemID.rice_seeds, count: 1, data: 0}, [{id: ItemID.rice, data: 0}]);
    Recipes.addShapeless({id: ItemID.coffee, count: 1, data: 0}, [{id: ItemID.coffee_cup, data: 0}, {id: 351, data: 3}]);
    Recipes.addShapeless({id: ItemID.cappuccino, count: 1, data: 0}, [{id: ItemID.coffee, data: 0}, {id: 325, data: 1}]);
    Recipes.addShapeless({id: ItemID.butter_rice, count: 1, data: 0}, [{id: ItemID.rice, data: 0}, {id: ItemID.butter, data: 0}]);
    Recipes.addShapeless({id: ItemID.crouton, count: 4, data: 0}, [{id: 297, data: 0}, {id: ItemID.butter, data: 0}]);
    Recipes.addShapeless({id: ItemID.chips, count: 8, data: 0}, [{id: ItemID.cooked_dough, data: 0}, {id: ItemID.salt, data: 0}]);
    Recipes.addShapeless({id: ItemID.salty_chips, count: 8, data: 0}, [{id: ItemID.chips, data: 0}, {id: ItemID.salt, data: 0}]);
    Recipes.addShapeless({id: ItemID.spicy_chips, count: 8, data: 0}, [{id: ItemID.chips, data: 0}, {id: ItemID.hot_sauce, data: 0}]);
    Recipes.addShapeless({id: ItemID.onion_rings, count: 4, data: 0}, [{id: ItemID.onion, data: 0}, {id: ItemID.knife, data: 0}]);
    Recipes.addShapeless({id: ItemID.corn_bread, count: 1, data: 0}, [{id: ItemID.corn, data: 0}, {id: 297, data: 0}]);
    Recipes.addShapeless({id: ItemID.waffle, count: 1, data: 0}, [{id: ItemID.cooked_dough, data: 0}, {id: 325, data: 1}]);
    Recipes.addShapeless({id: ItemID.bucket_of_fried_chicken, count: 1, data: 0}, [{id: 325, data: 0}, {id: 366, data: 0}]);
    Recipes.addShapeless({id: ItemID.slice_of_pizza, count: 2, data: 0}, [{id: ItemID.pizza_item, data: 0}]);
    Recipes.addShapeless({id: ItemID.slice_of_pizza, count: 2, data: 0}, [{id: ItemID.pizza, data: 0}]);
    Recipes.addShapeless({id: ItemID.chocolate_icecream, count: 1, data: 0}, [{id: ItemID.chocolate_icecream_ball, data: 0}, {id: ItemID.icecream_cone, data: 0}]);
    Recipes.addShapeless({id: ItemID.vanilla_icecream, count: 1, data: 0}, [{id: ItemID.vanilla_icecream_ball, data: 0}, {id: ItemID.icecream_cone, data: 0}]);
    Recipes.addShapeless({id: ItemID.strawberry_icecream, count: 1, data: 0}, [{id: ItemID.strawberry_icecream_ball, data: 0}, {id: ItemID.icecream_cone, data: 0}]);
    Recipes.addShapeless({id: ItemID.sugar_donut, count: 1, data: 0}, [{id: ItemID.donut, data: 0}, {id: 353, data: 0}]);
    Recipes.addShapeless({id: ItemID.chocolate_donut, count: 1, data: 0}, [{id: ItemID.donut, data: 0}, {id: ItemID.chocolate_syrup, data: 0}]);
    Recipes.addShapeless({id: ItemID.vanilla_extract, count: 1, data: 0}, [{id: ItemID.vanilla_flower_item, data: 0}, {id: 374, data: 0}]);
    Recipes.addShapeless({id: ItemID.apple_pie, count: 1, data: 0}, [{id: ItemID.pie_shell, data: 0}, {id: 260, data: 0}]);
    Recipes.addShapeless({id: ItemID.cheese_pie, count: 1, data: 0}, [{id: ItemID.pie_shell, data: 0}, {id: ItemID.cheese, data: 0}]);
    Recipes.addShapeless({id: ItemID.golden_apple_pie, count: 1, data: 0}, [{id: ItemID.pie_shell, data: 0}, {id: 322, data: 0}]);
    Recipes.addShapeless({id: ItemID.chocolate_pie, count: 1, data: 0}, [{id: ItemID.pie_shell, data: 0}, {id: ItemID.chocolate_syrup, data: 0}, {id: ItemID.chocolate, data: 0}]);
    Recipes.addShapeless({id: ItemID.fish_pie, count: 1, data: 0}, [{id: ItemID.pie_shell, data: 0}, {id: 350, data: 0}]);
    Recipes.addShapeless({id: ItemID.chicken_pot_pie, count: 1, data: 0}, [{id: ItemID.pie_shell, data: 0}, {id: 366, data: 0}]);
    Recipes.addShapeless({id: ItemID.strawberry_pie, count: 1, data: 0}, [{id: ItemID.pie_shell, data: 0}, {id: ItemID.strawberry, data: 0}]);
    Recipes.addShapeless({id: ItemID.raw_chicken_wing, count: 2, data: 0}, [{id: 365, data: 0}]);
    Recipes.addShapeless({id: ItemID.cooked_chicken_wing, count: 2, data: 0}, [{id: 366, data: 0}]);
    Recipes.addShapeless({id: ItemID.cheesy_bread, count: 1, data: 0}, [{id: ItemID.cheese, data: 0}, {id: 297, data: 0}]);
    Recipes.addShapeless({id: ItemID.brownie, count: 1, data: 0}, [{id: ItemID.chocolate, data: 0}, {id: ItemID.chocolate_syrup, data: 0}]);
    Recipes.addShapeless({id: ItemID.bacon, count: 4, data: 0}, [{id: 320, data: 0}]);
    Recipes.addShapeless({id: ItemID.ground_beef, count: 2, data: 0}, [{id: 364, data: 0}]);
    Recipes.addShapeless({id: ItemID.bacon_pie, count: 1, data: 0}, [{id: ItemID.pie_shell, data: 0}, {id: ItemID.bacon, data: 0}]);
    Recipes.addShapeless({id: ItemID.salt, count: 1, data: 0}, [{id: ItemID.salt_pot, data: 0}]);
    Recipes.addShapeless({id: ItemID.cheese_slice, count: 8, data: 0}, [{id: ItemID.knife, data: 0}, {id: ItemID.cheese, data: 0}]);
    Recipes.addShapeless({id: ItemID.uncooked_beef_patty, count: 4, data: 0}, [{id: ItemID.knife, data: 0}, {id: ItemID.uncooked_minced_meat, data: 0}]);
    Recipes.addShapeless({id: ItemID.cooked_french_toast, count: 1, data: 0}, [{id: ItemID.cooked_french_toast_in_frying_pan, data: 0}]);
    Recipes.addShapeless({id: ItemID.peeled_potato, count: 1, data: 0}, [{id: ItemID.knife, data: 0}, {id: 392, data: 0}]);
    Recipes.addShapeless({id: ItemID.peeled_chipped_potato, count: 1, data: 0}, [{id: ItemID.knife, data: 0}, {id: ItemID.peeled_potato, data: 0}]);
    Recipes.addShapeless({id: ItemID.uncooked_hashbrown, count: 1, data: 0}, [{id: ItemID.knife, data: 0}, {id: ItemID.mashed_potato, data: 0}]);
    Recipes.addShapeless({id: ItemID.uncooked_bacon, count: 8, data: 0}, [{id: ItemID.knife, data: 0}, {id: ItemID.bacon_joint, data: 0}]);
    Recipes.addShapeless({id: ItemID.slice_bread, count: 1, data: 0}, [{id: ItemID.knife, data: 0}, {id: 297, data: 0}]);
    Recipes.addShapeless({id: ItemID.boiled_potato, count: 1, data: 0}, [{id: ItemID.boiled_potato_in_pot, data: 0}]);
    Recipes.addShapeless({id: ItemID.mashed_potato, count: 1, data: 0}, [{id: ItemID.boiled_potato, data: 0}, {id: ItemID.mincer, data: 0}]);
    Recipes.addShapeless({id: ItemID.fried_egg, count: 1, data: 0}, [{id: ItemID.fried_egg_in_frying_pan, data: 0}]);
    Recipes.addShapeless({id: ItemID.fried_mushroom, count: 1, data: 0}, [{id: ItemID.fried_mushroom_in_frying_pan, data: 0}]);
    Recipes.addShapeless({id: ItemID.cookie_dough, count: 1, data: 0}, [{id: ItemID.small_dough_ball, data: 0}, {id: ItemID.chocolate, data: 0}]);
    Recipes.addShapeless({id: ItemID.vanilla_donut, count: 1, data: 0}, [{id: ItemID.vanilla_cream, data: 0}, {id: ItemID.donut, data: 0}]);
});

