ShootLib.addGun({
    id:"ump",
    name:"UMP",
    ammo:"ammo_45Acp",
    accuracy:5,
    recoil:3,
    rate:6,
    texture:{
        name:"UMP",
        meta:0
    },
    shotType:ShotType.NORMAL,
    buttonType:ButtonType.TOUCH,
    bullet:{
        speed:7,
        count:25,
        damage:7.9
    },
    fov:{
        level:0
    },
    sounds:{
        shot:"AKM.ogg",
        empty:"EmptyGun.mp3",
        reload:"reload/MP44Reload.ogg"
    }
});

ShootLib.addGun({
    id:"vector",
    name:"Vector",
    ammo:"ammo9mm",
    accuracy:6,
    recoil:3,
    rate:10,
    texture:{
        name:"Vector",
        meta:0
    },
    shotType:ShotType.NORMAL,
    buttonType:ButtonType.TOUCH,
    bullet:{
        speed:7,
        count:33,
        damage:6.8
    },
    fov:{
        level:0
    },
    sounds:{
        shot:"AKM.ogg",
        empty:"EmptyGun.mp3",
        reload:"reload/MP44Reload.ogg"
    }
});

ShootLib.addGun({
    id:"uzi",
    name:"Micro Uzi",
    ammo:"ammo9mm",
    accuracy:8,
    recoil:6,
    rate:10,
    texture:{
        name:"uzi",
        meta:0
    },
    shotType:ShotType.NORMAL,
    buttonType:ButtonType.TOUCH,
    bullet:{
        speed:7,
        count:35,
        damage:5.2
    },
    fov:{
        level:0
    },
    sounds:{
        shot:"AKM.ogg",
        empty:"EmptyGun.mp3",
        reload:"reload/MP44Reload.ogg"
    }
});

ShootLib.addGun({
    id:"tommyGun",
    name:"Tommy Gun",
    ammo:"ammo_45Acp",
    accuracy:7,
    recoil:5,
    rate:10,
    texture:{
        name:"tommyGun",
        meta:0
    },
    shotType:ShotType.NORMAL,
    buttonType:ButtonType.TOUCH,
    bullet:{
        speed:7,
        count:50,
        damage:8
    },
    fov:{
        level:0
    },
    sounds:{
        shot:"AKM.ogg",
        empty:"EmptyGun.mp3",
        reload:"reload/MP44Reload.ogg"
    }
});