give @s iaf:black_helmet
give @s iaf:black_chestplate
give @s iaf:black_leggings
give @s iaf:black_boot
give @s iaf:amythest_chestplate
give @s iaf:amythest_helmet
give @s iaf:amythest_legging
give @s iaf:amythest_boot
give @s iaf:blue_helmet
give @s iaf:blue_chestplate
give @s iaf:green_helmet
give @s iaf:blue_legging
give @s iaf:green_chestplate
give @s iaf:green_legging
give @s iaf:bronze_chestplate
give @s iaf:blue_boot
give @s iaf:green_boot
give @s iaf:bronze_legging
give @s iaf:bronze_helmet
give @s iaf:bronze_boot
give @s iaf:copper_helmet
give @s iaf:copper_chestplate
give @s iaf:copper_legging
give @s iaf:copper_boot
give @s iaf:electric_helmet
give @s iaf:electric_chestplate
give @s iaf:electric_legging
give @s iaf:electric_boot
give @s iaf:gray_helmet
give @s iaf:gray_chestplate
give @s iaf:gray_legging
give @s iaf:gray_boot
give @s iaf:red_helmet
give @s iaf:red_chestplate
give @s iaf:red_legging
give @s iaf:red_boot
give @s iaf:silver_helmet
give @s iaf:silver_chestplate
give @s iaf:silver_legging
give @s iaf:silver_boot
give @s iaf:sapphire_helmet
give @s iaf:sapphire_chestplate
give @s iaf:sapphire_legging
give @s iaf:sapphire_boot
give @s iaf:white_helmet
give @s iaf:white_chestplate
give @s iaf:white_legging
give @s iaf:white_boot
