IDRegistry.genItemID("zombie");
Item.createItem("zombie", "Кристал Зомбака", {name: "zombie", meta: 0}, {stack: 64});
IDRegistry.genItemID("skelet");
Item.createItem("skelet", "Кристал Скелета", {name: "skelet", meta: 0}, {stack: 64});
IDRegistry.genItemID("spider");
Item.createItem("spider", "Кристал Паука", {name: "spider", meta: 0}, {stack: 64});
IDRegistry.genItemID("creeper");
Item.createItem("creeper", "Кристал Крипера", {name: "creeper", meta: 0}, {stack: 64});
IDRegistry.genItemID("sprut");
Item.createItem("sprut", "Кристал Спрута", {name: "sprut", meta: 0}, {stack: 64});
IDRegistry.genItemID("slime_crystal");
Item.createItem("slime_crystal", "Кристал Слиза", {name: "slime", meta: 0}, {stack: 64});
IDRegistry.genItemID("ocelota");
Item.createItem("ocelota", "Кристал Оцелота", {name: "ocelota", meta: 0}, {stack: 64});
IDRegistry.genItemID("blaze");
Item.createItem("blaze", "Кристал Ифрита", {name: "blaze", meta: 0}, {stack: 64});
IDRegistry.genItemID("enderman");
Item.createItem("enderman", "Кристал Эндермена", {name: "enderman", meta: 0}, {stack: 64});

IDRegistry.genItemID("zombie_ingot");
Item.createItem("zombie_ingot", "Слиток Зомбака", {name: "new_zombieingot", meta: 0}, {stack: 64});
IDRegistry.genItemID("skelet_ingot");
Item.createItem("skelet_ingot", "Слиток Скелета", {name: "new_skeletoningot", meta: 0}, {stack: 64});
IDRegistry.genItemID("spider_ingot");
Item.createItem("spider_ingot", "Слиток Паука", {name: "new_spideringot", meta: 0}, {stack: 64});
IDRegistry.genItemID("creeper_ingot");
Item.createItem("creeper_ingot", "Слиток Крипера", {name: "new_creeperingot", meta: 0}, {stack: 64});
IDRegistry.genItemID("sprut_ingot");
Item.createItem("sprut_ingot", "Слиток Спрута", {name: "new_sprutingot", meta: 0}, {stack: 64});
IDRegistry.genItemID("slime_ingot");
Item.createItem("slime_ingot", "Слиток Слиза", {name: "new_slimeingot", meta: 0}, {stack: 64});
IDRegistry.genItemID("ocelot_ingot");
Item.createItem("ocelot_ingot", "Слиток Оцелота", {name: "new_ocelotingot", meta: 0}, {stack: 64});
IDRegistry.genItemID("blaze_ingot");
Item.createItem("blaze_ingot", "Слиток Ифрита", {name: "new_blazeingot", meta: 0}, {stack: 64});
IDRegistry.genItemID("end_ingot");
Item.createItem("end_ingot", "Слиток Эндермена", {name: "new_endingot", meta: 0}, {stack: 64});

IDRegistry.genItemID("red_coupon");
Item.createItem("red_coupon", "Красный Купон", {name: "red_coupon", meta: 0}, {stack: 64});
IDRegistry.genItemID("green_coupon");
Item.createItem("green_coupon", "Зеленый Купон", {name: "green_coupon", meta: 0}, {stack: 64});
IDRegistry.genItemID("blue_coupon");
Item.createItem("blue_coupon", "Синий Купон", {name: "blue_coupon", meta: 0}, {stack: 64});
IDRegistry.genItemID("yellow_coupon");
Item.createItem("yellow_coupon", "Желтый Купон", {name: "yellow_coupon", meta: 0}, {stack: 64});

IDRegistry.genItemID("mobs_book"); 
Item.createItem("mobs_book", "Mobs Book", {name: "mobs_book", meta: 0}, {stack: 1});