XLRegistry.Seeds("rice", "Rice", 4, true);
XLRegistry.Seeds("pepper", "Pepper Seeds", 7, false);
XLRegistry.Seeds("corn", "Corn Seeds", 7, false);
XLRegistry.Seeds("cucumber", "Cucumber Seeds", 6, false);
XLRegistry.Seeds("lettuce", "Lettuce Seeds", 7, false);
XLRegistry.Seeds("onion", "Onion", 6, true);
XLRegistry.Seeds("tomato", "Tomato Seeds", 6, false);
XLRegistry.Seeds("strawberry", "Strawberry Seeds", 6, false);
XLRegistry.Seeds("lemon", "Lemon Seeds", 6, false);
XLRegistry.Seeds("pineapple", "Pineapple Seeds", 4, false);

XLRegistry.Drops("rice_plant_stage", 4, "rice", "rice");
XLRegistry.Drops("pepper_plant_stage", 7, "pepper_seeds", "pepper");
XLRegistry.Drops("corn_plant_stage", 7, "corn_seeds", "raw_corn");
XLRegistry.Drops("cucumber_plant_stage", 6, "cucumber_seeds", "cucumber");
XLRegistry.Drops("lettuce_plant_stage", 7, "lettuce_seeds", "lettuce");
XLRegistry.Drops("onion_plant_stage", 6, "onion", "onion");
XLRegistry.Drops("tomato_plant_stage", 6, "tomato_seeds", "tomato");
XLRegistry.Drops("strawberry_plant_stage", 6, "strawberry_seeds", "strawberry");
XLRegistry.Drops("lemon_plant_stage", 6, "lemon_seeds", "lemon");
XLRegistry.Drops("pineapple_plant_stage", 4, "pineapple_seeds", "pineapple");

XLRegistry.Grows("rice_plant_stage", 0);
XLRegistry.Grows("rice_plant_stage", 1);
XLRegistry.Grows("rice_plant_stage", 2);
XLRegistry.Grows("rice_plant_stage", 3);
XLRegistry.Grows("pepper_plant_stage", 0);
XLRegistry.Grows("pepper_plant_stage", 1);
XLRegistry.Grows("pepper_plant_stage", 2);
XLRegistry.Grows("pepper_plant_stage", 3);
XLRegistry.Grows("pepper_plant_stage", 4);
XLRegistry.Grows("pepper_plant_stage", 5);
XLRegistry.Grows("pepper_plant_stage", 6);
XLRegistry.Grows("corn_plant_stage", 0);
XLRegistry.Grows("corn_plant_stage", 1);
XLRegistry.Grows("corn_plant_stage", 2);
XLRegistry.Grows("corn_plant_stage", 3);
XLRegistry.Grows("corn_plant_stage", 4);
XLRegistry.Grows("corn_plant_stage", 5);
XLRegistry.Grows("corn_plant_stage", 6);
XLRegistry.Grows("cucumber_plant_stage", 0);
XLRegistry.Grows("cucumber_plant_stage", 1);
XLRegistry.Grows("cucumber_plant_stage", 2);
XLRegistry.Grows("cucumber_plant_stage", 3);
XLRegistry.Grows("cucumber_plant_stage", 4);
XLRegistry.Grows("cucumber_plant_stage", 5);
XLRegistry.Grows("lettuce_plant_stage", 0);
XLRegistry.Grows("lettuce_plant_stage", 1);
XLRegistry.Grows("lettuce_plant_stage", 2);
XLRegistry.Grows("lettuce_plant_stage", 3);
XLRegistry.Grows("lettuce_plant_stage", 4);
XLRegistry.Grows("lettuce_plant_stage", 5);
XLRegistry.Grows("lettuce_plant_stage", 6);
XLRegistry.Grows("onion_plant_stage", 0);
XLRegistry.Grows("onion_plant_stage", 1);
XLRegistry.Grows("onion_plant_stage", 2);
XLRegistry.Grows("onion_plant_stage", 3);
XLRegistry.Grows("onion_plant_stage", 4);
XLRegistry.Grows("onion_plant_stage", 5);
XLRegistry.Grows("tomato_plant_stage", 0);
XLRegistry.Grows("tomato_plant_stage", 1);
XLRegistry.Grows("tomato_plant_stage", 2);
XLRegistry.Grows("tomato_plant_stage", 3);
XLRegistry.Grows("tomato_plant_stage", 4);
XLRegistry.Grows("tomato_plant_stage", 5);
XLRegistry.Grows("strawberry_plant_stage", 0);
XLRegistry.Grows("strawberry_plant_stage", 1);
XLRegistry.Grows("strawberry_plant_stage", 2);
XLRegistry.Grows("strawberry_plant_stage", 3);
XLRegistry.Grows("strawberry_plant_stage", 4);
XLRegistry.Grows("strawberry_plant_stage", 5);
XLRegistry.Grows("lemon_plant_stage", 0);
XLRegistry.Grows("lemon_plant_stage", 1);
XLRegistry.Grows("lemon_plant_stage", 2);
XLRegistry.Grows("lemon_plant_stage", 3);
XLRegistry.Grows("lemon_plant_stage", 4);
XLRegistry.Grows("lemon_plant_stage", 5);
XLRegistry.Grows("pineapple_plant_stage", 0);
XLRegistry.Grows("pineapple_plant_stage", 1);
XLRegistry.Grows("pineapple_plant_stage", 2);
XLRegistry.Grows("pineapple_plant_stage", 3);

XLRegistry.Plants("rice", "rice_plant_stage");
XLRegistry.Plants("pepper_seeds", "pepper_plant_stage");
XLRegistry.Plants("corn_seeds", "corn_plant_stage");
XLRegistry.Plants("cucumber_seeds", "cucumber_plant_stage");
XLRegistry.Plants("lettuce_seeds", "lettuce_plant_stage");
XLRegistry.Plants("onion", "onion_plant_stage");
XLRegistry.Plants("tomato_seeds", "tomato_plant_stage");
XLRegistry.Plants("strawberry_seeds", "strawberry_plant_stage");
XLRegistry.Plants("lemon_seeds", "lemon_plant_stage");
XLRegistry.Plants("pineapple_seeds", "pineapple_plant_stage");