Synthesiser.addRecipe({id: 1, count: 16}, "SMOOTH", [["Si", 1], ["O", 2], null, ["Al", 2], ["O", 3]], true);
Synthesiser.addRecipe({id: 2, count: 16}, "GRASS", [null, ["cellulose", 1], null, null, ["O", 2], ["Si", 1]], true);
Synthesiser.addRecipe({id: 3}, "BLOCK", [["siliconDioxide", 1]], true);
Synthesiser.addRecipe({id: 243}, "BLOCK", [null, null, null, ["siliconDioxide", 1]], true);
Synthesiser.addRecipe({id: 4, count: 16}, "SMOOTH", [["Si", 2], ["O", 4]], true);
Synthesiser.addRecipe({id: 5, data: 0}, "PLANK", [null, null, null, null, null, null, null, ["cellulose", 1], ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 5, data: 1}, "PLANK", [null, null, null, null, null, null, ["cellulose", 1], ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 5, data: 2}, "PLANK", [null, null, null, null, null, ["cellulose", 1], ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 5, data: 3}, "PLANK", [null, null, null, null, ["cellulose", 1], ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 5, data: 4}, "PLANK", [null, null, null, ["cellulose", 1], ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 5, data: 5}, "PLANK", [null, null, ["cellulose", 1], ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 158, data: 0}, "PLANK", [null, null, null, null, null, null, ["cellulose", 1], null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 158, data: 1}, "PLANK", [null, null, null, null, null, ["cellulose", 1], null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 158, data: 2}, "PLANK", [null, null, null, null, ["cellulose", 1], null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 158, data: 3}, "PLANK", [null, null, null, ["cellulose", 1], null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 158, data: 4}, "PLANK", [null, null, ["cellulose", 1], null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 158, data: 5}, "PLANK", [null, ["cellulose", 1], null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 6, data: 0}, "PLANT", [null, null, null, null, null, null, null, null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 6, data: 1}, "PLANT", [null, null, null, null, null, null, null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 6, data: 2}, "PLANT", [null, null, null, null, null, null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 6, data: 3}, "PLANT", [null, null, null, null, null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 6, data: 4}, "PLANT", [null, null, null, null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 6, data: 5}, "PLANT", [null, null, null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 12, data: 0}, "BLOCK", [["siliconDioxide", 4], ["siliconDioxide", 4], null, ["siliconDioxide", 4], ["siliconDioxide", 4]], true);
Synthesiser.addRecipe({id: 12, data: 1}, "BLOCK", [null, ["siliconDioxide", 4], ["siliconDioxide", 4], null, ["siliconDioxide", 4], ["siliconDioxide", 4]], true);
Synthesiser.addRecipe({id: 13}, "BLOCK", [null, null, null, null, null, null, null, null, ["siliconDioxide", 1]], true);
Synthesiser.addRecipe({id: 17, data: 0}, "WOOD", [["cellulose", 2], ["cellulose", 2], ["cellulose", 2], null, ["cellulose", 2]], true);
Synthesiser.addRecipe({id: 17, data: 1}, "WOOD", [null, null, null, null, ["cellulose", 2], null, ["cellulose", 2], ["cellulose", 2], ["cellulose", 2]], true);
Synthesiser.addRecipe({id: 17, data: 2}, "WOOD", [["cellulose", 2], null, ["cellulose", 2], null, null, null, ["cellulose", 2], null, ["cellulose", 2]], true);
Synthesiser.addRecipe({id: 17, data: 3}, "WOOD", [["cellulose", 2], null, null, ["cellulose", 2], ["cellulose", 2], null, ["cellulose", 2]], true);
Synthesiser.addRecipe({id: 162, data: 0}, "WOOD", [null, null, ["cellulose", 2], null, ["cellulose", 2], ["cellulose", 2], null, null, ["cellulose", 2]], true);
Synthesiser.addRecipe({id: 162, data: 1}, "WOOD", [null, ["cellulose", 2], null, ["cellulose", 2], null, ["cellulose", 2], null, ["cellulose", 2]], true);
Synthesiser.addRecipe({id: 18, data: 0}, "BLOCK", [["cellulose", 1], ["cellulose", 1], ["cellulose", 1], null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 18, data: 1}, "BLOCK", [null, null, null, null, ["cellulose", 1], null, ["cellulose", 1], ["cellulose", 1], ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 18, data: 2}, "BLOCK", [["cellulose", 1], null, ["cellulose", 1], null, null, null, ["cellulose", 1], null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 18, data: 3}, "BLOCK", [["cellulose", 1], null, null, ["cellulose", 1], ["cellulose", 1], null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 161, data: 0}, "BLOCK", [null, null, ["cellulose", 1], null, ["cellulose", 1], ["cellulose", 1], null, null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 161, data: 1}, "BLOCK", [null, ["cellulose", 1], null, ["cellulose", 1], null, ["cellulose", 1], null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 351, data: 0}, "ITEM", [["blackPigment", 1]]);
Synthesiser.addRecipe({id: 351, data: 1}, "ITEM", [["redPigment", 1]]);
Synthesiser.addRecipe({id: 351, data: 2}, "ITEM", [["greenPigment", 1]]);
Synthesiser.addRecipe({id: 351, data: 3}, "ITEM", [["theobromine", 1]]);
Synthesiser.addRecipe({id: 351, data: 4}, "ITEM", [["lazurite", 1]]);
Synthesiser.addRecipe({id: 351, data: 5}, "ITEM", [["purplePigment", 1]]);
Synthesiser.addRecipe({id: 351, data: 6}, "ITEM", [["lightbluePigment", 1], ["whitePigment", 1]]);
Synthesiser.addRecipe({id: 351, data: 7}, "ITEM", [["whitePigment", 1], ["blackPigment", 1]]);
Synthesiser.addRecipe({id: 351, data: 8}, "ITEM", [["whitePigment", 1], ["blackPigment", 2]]);
Synthesiser.addRecipe({id: 351, data: 9}, "ITEM", [["redPigment", 1], ["whitePigment", 1]]);
Synthesiser.addRecipe({id: 351, data: 10}, "ITEM", [["limePigment", 1]]);
Synthesiser.addRecipe({id: 351, data: 11}, "ITEM", [["yellowPigment", 1]]);
Synthesiser.addRecipe({id: 351, data: 12}, "ITEM", [["lightbluePigment", 1]]);
Synthesiser.addRecipe({id: 351, data: 13}, "ITEM", [["lightbluePigment", 1], ["redPigment", 1]]);
Synthesiser.addRecipe({id: 351, data: 14}, "ITEM", [["orangePigment", 1]]);
Synthesiser.addRecipe({id: 351, data: 15}, "ITEM", [["whitePigment", 1]]);
Synthesiser.addRecipe({id: 20}, "GLASS", [["siliconDioxide", 4], null, ["siliconDioxide", 4], null, null, null, ["siliconDioxide", 4], null, ["siliconDioxide", 4]], true);
Synthesiser.addRecipe({id: 102}, "PANE", [["siliconDioxide", 1], ["siliconDioxide", 1], ["siliconDioxide", 1], null, null, null, ["siliconDioxide", 1], ["siliconDioxide", 1], ["siliconDioxide", 1]], true);
Synthesiser.addRecipe({id: 22}, "LAPISBLOCK", [["lazurite", 9]], true);
Synthesiser.addRecipe({id: 175, data: 0}, "PLANT", [["shikimicAcid", 2], ["yellowPigment", 1]], true);
Synthesiser.addRecipe({id: 175, data: 1}, "PLANT", [["shikimicAcid", 2], ["redPigment", 1], ["whitePigment", 2]], true);
Synthesiser.addRecipe({id: 175, data: 2}, "PLANT", [["shikimicAcid", 2]], true);
Synthesiser.addRecipe({id: 175, data: 3}, "PLANT", [null, ["shikimicAcid", 2]], true);
Synthesiser.addRecipe({id: 175, data: 4}, "PLANT", [["shikimicAcid", 2], ["redPigment", 1]], true);
Synthesiser.addRecipe({id: 175, data: 5}, "PLANT", [["shikimicAcid", 2], ["redPigment", 1], ["whitePigment", 1]], true);
Synthesiser.addRecipe({id: 24, data: 0}, "BLOCK", [null, null, null, null, ["siliconDioxide", 16]], true);
Synthesiser.addRecipe({id: 24, data: 1}, "BLOCK", [null, null, null, null, null, null, null, ["siliconDioxide", 16]], true);
Synthesiser.addRecipe({id: 24, data: 2}, "BLOCK", [null, ["siliconDioxide", 16]], true);
Synthesiser.addRecipe({id: 35, data: 0}, "WOOL", [["glycine", 2], ["whitePigment", 1]]);
Synthesiser.addRecipe({id: 35, data: 1}, "WOOL", [["glycine", 2], ["orangePigment", 1]]);
Synthesiser.addRecipe({id: 35, data: 2}, "WOOL", [["glycine", 2], ["lightbluePigment", 1], ["redPigment", 1]]);
Synthesiser.addRecipe({id: 35, data: 3}, "WOOL", [["glycine", 2], ["lightbluePigment", 1]]);
Synthesiser.addRecipe({id: 35, data: 4}, "WOOL", [["glycine", 2], ["yellowPigment", 1]]);
Synthesiser.addRecipe({id: 35, data: 5}, "WOOL", [["glycine", 2], ["limePigment", 1]]);
Synthesiser.addRecipe({id: 35, data: 6}, "WOOL", [["glycine", 2], ["redPigment", 1], ["whitePigment", 1]]);
Synthesiser.addRecipe({id: 35, data: 7}, "WOOL", [["glycine", 2], ["whitePigment", 1], ["blackPigment", 2]]);
Synthesiser.addRecipe({id: 35, data: 8}, "WOOL", [["glycine", 2], ["whitePigment", 1], ["blackPigment", 1]]);
Synthesiser.addRecipe({id: 35, data: 9}, "WOOL", [["glycine", 2], ["lightbluePigment", 1], ["whitePigment", 1]]);
Synthesiser.addRecipe({id: 35, data: 10}, "WOOL", [["glycine", 2], ["purplePigment", 1]]);
Synthesiser.addRecipe({id: 35, data: 11}, "WOOL", [["glycine", 2], ["lazurite", 1]]);
Synthesiser.addRecipe({id: 35, data: 12}, "WOOL", [["glycine", 2], ["tannicacid", 1]]);
Synthesiser.addRecipe({id: 35, data: 13}, "WOOL", [["glycine", 2], ["greenPigment", 1]]);
Synthesiser.addRecipe({id: 35, data: 14}, "WOOL", [["glycine", 2], ["redPigment", 1]]);
Synthesiser.addRecipe({id: 35, data: 15}, "WOOL", [["glycine", 2], ["blackPigment", 1]]);
Synthesiser.addRecipe({id: 171, data: 0}, "CARPET", [["glycine", 1], ["whitePigment", 1]]);
Synthesiser.addRecipe({id: 171, data: 1}, "CARPET", [["glycine", 1], ["orangePigment", 1]]);
Synthesiser.addRecipe({id: 171, data: 2}, "CARPET", [["glycine", 1], ["lightbluePigment", 1], ["redPigment", 1]]);
Synthesiser.addRecipe({id: 171, data: 3}, "CARPET", [["glycine", 1], ["lightbluePigment", 1]]);
Synthesiser.addRecipe({id: 171, data: 4}, "CARPET", [["glycine", 1], ["yellowPigment", 1]]);
Synthesiser.addRecipe({id: 171, data: 5}, "CARPET", [["glycine", 1], ["limePigment", 1]]);
Synthesiser.addRecipe({id: 171, data: 6}, "CARPET", [["glycine", 1], ["redPigment", 1], ["whitePigment", 1]]);
Synthesiser.addRecipe({id: 171, data: 7}, "CARPET", [["glycine", 1], ["whitePigment", 1], ["blackPigment", 2]]);
Synthesiser.addRecipe({id: 171, data: 8}, "CARPET", [["glycine", 1], ["whitePigment", 1], ["blackPigment", 1]]);
Synthesiser.addRecipe({id: 171, data: 9}, "CARPET", [["glycine", 1], ["lightbluePigment", 1], ["whitePigment", 1]]);
Synthesiser.addRecipe({id: 171, data: 10}, "CARPET", [["glycine", 1], ["purplePigment", 1]]);
Synthesiser.addRecipe({id: 171, data: 11}, "CARPET", [["glycine", 1], ["lazurite", 1]]);
Synthesiser.addRecipe({id: 171, data: 12}, "CARPET", [["glycine", 1], ["tannicacid", 1]]);
Synthesiser.addRecipe({id: 171, data: 13}, "CARPET", [["glycine", 1], ["greenPigment", 1]]);
Synthesiser.addRecipe({id: 171, data: 14}, "CARPET", [["glycine", 1], ["redPigment", 1]]);
Synthesiser.addRecipe({id: 171, data: 15}, "CARPET", [["glycine", 1], ["blackPigment", 1]]);
Synthesiser.addRecipe({id: 41}, "METALBLOCK", [["Au", 16], ["Au", 16], ["Au", 16], ["Au", 16], ["Au", 16], ["Au", 16], ["Au", 16], ["Au", 16], ["Au", 16]], true);
Synthesiser.addRecipe({id: 42}, "METALBLOCK", [["Fe", 16], ["Fe", 16], ["Fe", 16], ["Fe", 16], ["Fe", 16], ["Fe", 16], ["Fe", 16], ["Fe", 16], ["Fe", 16]], true);
Synthesiser.addRecipe({id: 46}, "OBSIDIAN", [["tnt", 1]]);
Synthesiser.addRecipe({id: 49}, "OBSIDIAN", [["siliconDioxide", 4], ["siliconDioxide", 4], ["siliconDioxide", 4], ["magnesiumOxide", 2], null, ["siliconDioxide", 4], ["magnesiumOxide", 2], ["magnesiumOxide", 2], ["magnesiumOxide", 2]], true);
Synthesiser.addRecipe({id: 57}, "GEMBLOCK", [["fullrene", 3], ["fullrene", 3], ["fullrene", 3], ["fullrene", 3], ["fullrene", 3], ["fullrene", 3], ["fullrene", 3], ["fullrene", 3], ["fullrene", 3]], true);
Synthesiser.addRecipe({id: 81}, "PLANT", [["water", 5], null, ["water", 5], null, ["mescaline", 1], null, ["water", 5], null, ["water", 5]], true);
Synthesiser.addRecipe({id: 86}, "PLANT", [["cucurbitacin", 1]]);
Synthesiser.addRecipe({id: 405}, "SMOOTH", [["Si", 2], ["Si", 2], null, ["Zn", 2], ["W", 1], null, ["Be", 2], ["Be", 2]], true);
Synthesiser.addRecipe({id: 373}, "ITEM", [null, ["siliconDioxide", 4], null, ["siliconDioxide", 4], ["water", 5], ["siliconDioxide", 4], null, ["siliconDioxide", 4]], true);
Synthesiser.addRecipe({id: 89}, "GLOWBLOCK", [["P", 1], null, ["P", 1], ["P", 1], null, ["P", 1]], true);
Synthesiser.addRecipe({id: 110, count: 16}, "GRASS", [["fingolimod", 1]]);
Synthesiser.addRecipe({id: 133}, "GEMBLOCK", [["Cr", 3], ["Cr", 3], ["Cr", 3], ["V", 9], ["beryl", 18], ["V", 9], ["Cr", 3], ["Cr", 3], ["Cr", 3]], true);
Synthesiser.addRecipe({id: 260}, "FOOD", [["malicAcid", 1], ["water", 2]]);
Synthesiser.addRecipe({id: 263, data: 1}, "ITEM", [["C", 4], ["C", 4]]);
Synthesiser.addRecipe({id: 264}, "GEM", [null, ["fullrene", 1], null, ["fullrene", 1], null, ["fullrene", 1], null, ["fullrene", 1]], true);
//Synthesiser.addRecipe({id: ItemID.polytool}, "STAR", [null, ["fullrene", 64], null, ["fullrene", 64], null, ["fullrene", 64], null, ["fullrene", 64]], true);
Synthesiser.addRecipe({id: 265}, "INGOT", [["Fe", 16]]);
Synthesiser.addRecipe({id: 266}, "INGOT", [["Au", 16]]);
Synthesiser.addRecipe({id: 287}, "ITEM", [["serine", 1], ["glycine", 1], ["alinine", 1]], true);
Synthesiser.addRecipe({id: 288}, "ITEM", [["N", 1], ["water", 2], ["N", 1], ["N", 1], ["water", 1], ["N", 1], ["N", 1], ["water", 5], ["N", 1]], true);
Synthesiser.addRecipe({id: 289}, "ITEM", [["potassiumNitrate", 1], ["C", 1], null, ["S", 2]], true);
Synthesiser.addRecipe({id: 318}, "ITEM", [null, ["siliconDioxide", 4], null, ["siliconDioxide", 4], ["siliconDioxide", 4], ["siliconDioxide", 4]], true);
Synthesiser.addRecipe({id: 325, data: 0}, "FOOD", [null, null, null, ["Fe", 16], null, ["Fe", 16], null, ["Fe", 16]], true);
Synthesiser.addRecipe({id: 325, data: 8}, "FOOD", [null, null, null, ["Fe", 16], ["water", 16], ["Fe", 16], null, ["Fe", 16]], true);
Synthesiser.addRecipe({id: 331}, "LAPIS", [null, null, ["iron3oxide", 1], null, ["Cu", 1]], true);
Synthesiser.addRecipe({id: 152}, "LAPISBLOCK", [null, null, ["iron3oxide", 9], null, ["Cu", 9]], true);
Synthesiser.addRecipe({id: 332, count: 5}, "ITEM", [["water", 1], null, ["water", 1], null, ["water", 1], null, ["water", 1], null, ["water", 1]], true);
Synthesiser.addRecipe({id: 334, count: 5}, "ITEM", [null, null, null, null, ["keratin", 1]], true);
Synthesiser.addRecipe({id: 336, count: 8}, "ITEM", [["kaolinite", 1], ["kaolinite", 1], null, ["kaolinite", 1], ["kaolinite", 1]], true);
Synthesiser.addRecipe({id: 337, count: 2}, "ITEM", [["kaolinite", 1]]);
Synthesiser.addRecipe({id: 106}, "GRASS", [["cellulose", 1], null, ["cellulose", 1], ["cellulose", 1], null, ["cellulose", 1], ["cellulose", 1], null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 339, count: 8}, "ITEM", [null, ["cellulose", 1], null, null, ["cellulose", 1], null, null, ["cellulose", 1]], true);
Synthesiser.addRecipe({id: 352}, "ITEM", [["hydroxylapatite", 1]]);
Synthesiser.addRecipe({id: 353}, "SUGAR", [["sucrose", 1]]);
Synthesiser.addRecipe({id: 360}, "FOOD", [["cucurbitacin", 1], ["asparticAcid", 1], ["water", 1]]);
Synthesiser.addRecipe({id: 103}, "FOOD", [["cucurbitacin", 1], ["asparticAcid", 1], ["water", 16]]);
Synthesiser.addRecipe({id: 366}, "FOOD", [["K", 16], ["Na", 16], ["C", 16]], true);
Synthesiser.addRecipe({id: 368}, "TEAR", [["calciumCarbonate", 1], ["calciumCarbonate", 1], ["calciumCarbonate", 1], ["calciumCarbonate", 1], ["Es", 1], ["calciumCarbonate", 1], ["calciumCarbonate", 1], ["calciumCarbonate", 1], ["calciumCarbonate", 1]], true);
Synthesiser.addRecipe({id: 122}, "SMOOTH", [["calciumCarbonate", 18], ["hydroxylapatite", 8], ["Pu", 22], ["Fm", 12]], true);
Synthesiser.addRecipe({id: 369}, "TEAR", [["Pu", 2], null, null, ["Pu", 2], null, null, ["Pu", 2]], true);
Synthesiser.addRecipe({id: 370}, "TEAR", [["Yb", 1], ["Yb", 1], ["No", 1], null, ["Yb", 2], ["No", 2], null, ["No", 1]], true);
Synthesiser.addRecipe({id: 375}, "ITEM", [["C", 1], null, null, null, ["tetrodotoxin", 1], null, null, null, ["C", 1]], true);
Synthesiser.addRecipe({id: 378}, "TEAR", [null, ["Pu", 1], null, ["pmma", 1], ["Hg", 1], ["pmma", 1], null, ["pmma", 1]], true);
Synthesiser.addRecipe({id: 399}, "STAR", [["He", 64], ["He", 64], ["He", 64], ["C", 64], ["Cn", 16], ["He", 64], ["H", 64], ["H", 64], ["H", 64]], true);
Synthesiser.addRecipe({id: 101}, "BLOCK", [["Fe", 6]]);