Callback.addCallback("GenerateChunk", function (chunkX, chunkZ) {

    let coords = GenerationUtils.randomCoords(chunkX, chunkZ, 64, 128);
    if(Math.random() < 0.004){
    coords = GenerationUtils.findSurface(coords.x, coords.y, coords.z);

if(World.getBlock(coords.x,coords.y+1,coords.z).id === 0 && GenerationUtils.canSeeSky(coords.x, coords.y + 1, coords.z)) { 
       World.setBlock(coords.x,coords.y+1, coords.z, 158, 5);
World.setBlock(coords.x+1,coords.y+1,  coords.z, 17, 0);  
World.setBlock(coords.x+1,coords.y+2,  coords.z, 17, 0);  
World.setBlock(coords.x+1,coords.y+3,  coords.z, 17, 0);  
World.setBlock(coords.x+1,coords.y+4,  coords.z, 85, 0);  
World.setBlock(coords.x+1,coords.y+5,  coords.z, 35, 14);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+1, 35, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+1, 158, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+2, 158, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+3, 158, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+4, 158, 5);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+1, 158, 8);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+2, 158, 8);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+3, 158, 8);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+4, 17, 0);  
World.setBlock(coords.x+1,coords.y+2,  coords.z+4, 17, 0);  
World.setBlock(coords.x+1,coords.y+3,  coords.z+4, 17, 0);  
World.setBlock(coords.x+1,coords.y+4,  coords.z+4, 85, 0);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+4, 35, 14);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+2, 35, 14);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+3, 35, 0);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+4, 35, 14);  
World.setBlock(coords.x+2,coords.y+1,  coords.z, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z, 17, 0);
World.setBlock(coords.x+2,coords.y+2,  coords.z, 158, 13);
World.setBlock(coords.x+3,coords.y+2,  coords.z, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z, 17, 0);
World.setBlock(coords.x+2,coords.y+3,  coords.z, 158, 8);
World.setBlock(coords.x+3,coords.y+3,  coords.z, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z, 17, 0);
World.setBlock(coords.x+2,coords.y+4,  coords.z, 158, 5);
World.setBlock(coords.x+4,coords.y+4,  coords.z, 158, 5);
World.setBlock(coords.x+2,coords.y+1,  coords.z+1, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+1, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+1, 158, 8);
World.setBlock(coords.x+2,coords.y+1,  coords.z+2, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+2, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+2, 158, 8);
World.setBlock(coords.x+2,coords.y+1,  coords.z+3, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+3, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+3, 158, 8);
World.setBlock(coords.x+2,coords.y+1,  coords.z+4, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+4, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+4, 17, 0);
World.setBlock(coords.x+2,coords.y+2,  coords.z+4, 158, 13);
World.setBlock(coords.x+3,coords.y+2,  coords.z+4, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z+4, 17, 0);
World.setBlock(coords.x+2,coords.y+3,  coords.z+4, 158, 8);
World.setBlock(coords.x+3,coords.y+3,  coords.z+4, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z+4, 17, 0);
World.setBlock(coords.x+2,coords.y+4,  coords.z+4, 158, 5);
World.setBlock(coords.x+4,coords.y+4,  coords.z+4, 158, 5);
World.setBlock(coords.x+4,coords.y+3,  coords.z+1, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z+2, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z+3, 158, 8);
World.setBlock(coords.x+4,coords.y+4,  coords.z+2, 158, 5);
World.setBlock(coords.x+4,coords.y+2,  coords.z+1, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z+2, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z+3, 158, 13);
World.setBlock(coords.x+3,coords.y+2,  coords.z+3, VanillaBlockID.barrel, 0);
World.setBlock(coords.x+2,coords.y+2,  coords.z+2, BlockID.TradeRED, 0);
}}});

Callback.addCallback("GenerateChunk", function (chunkX, chunkZ) {

    let coords = GenerationUtils.randomCoords(chunkX, chunkZ, 64, 128);
    if(Math.random() < 0.004){
    coords = GenerationUtils.findSurface(coords.x, coords.y, coords.z);

if(World.getBlock(coords.x,coords.y+1,coords.z).id === 0 && GenerationUtils.canSeeSky(coords.x, coords.y + 1, coords.z)) { 
       World.setBlock(coords.x,coords.y+1, coords.z, 158, 5);
World.setBlock(coords.x+1,coords.y+1,  coords.z, 17, 0);  
World.setBlock(coords.x+1,coords.y+2,  coords.z, 17, 0);  
World.setBlock(coords.x+1,coords.y+3,  coords.z, 17, 0);  
World.setBlock(coords.x+1,coords.y+4,  coords.z, 85, 0);  
World.setBlock(coords.x+1,coords.y+5,  coords.z, 35, 5);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+1, 35, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+1, 158, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+2, 158, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+3, 158, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+4, 158, 5);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+1, 158, 8);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+2, 158, 8);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+3, 158, 8);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+4, 17, 0);  
World.setBlock(coords.x+1,coords.y+2,  coords.z+4, 17, 0);  
World.setBlock(coords.x+1,coords.y+3,  coords.z+4, 17, 0);  
World.setBlock(coords.x+1,coords.y+4,  coords.z+4, 85, 0);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+4, 35, 5);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+2, 35, 5);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+3, 35, 0);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+4, 35, 5);  
World.setBlock(coords.x+2,coords.y+1,  coords.z, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z, 17, 0);
World.setBlock(coords.x+2,coords.y+2,  coords.z, 158, 13);
World.setBlock(coords.x+3,coords.y+2,  coords.z, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z, 17, 0);
World.setBlock(coords.x+2,coords.y+3,  coords.z, 158, 8);
World.setBlock(coords.x+3,coords.y+3,  coords.z, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z, 17, 0);
World.setBlock(coords.x+2,coords.y+4,  coords.z, 158, 5);
World.setBlock(coords.x+4,coords.y+4,  coords.z, 158, 5);
World.setBlock(coords.x+2,coords.y+1,  coords.z+1, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+1, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+1, 158, 8);
World.setBlock(coords.x+2,coords.y+1,  coords.z+2, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+2, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+2, 158, 8);
World.setBlock(coords.x+2,coords.y+1,  coords.z+3, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+3, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+3, 158, 8);
World.setBlock(coords.x+2,coords.y+1,  coords.z+4, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+4, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+4, 17, 0);
World.setBlock(coords.x+2,coords.y+2,  coords.z+4, 158, 13);
World.setBlock(coords.x+3,coords.y+2,  coords.z+4, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z+4, 17, 0);
World.setBlock(coords.x+2,coords.y+3,  coords.z+4, 158, 8);
World.setBlock(coords.x+3,coords.y+3,  coords.z+4, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z+4, 17, 0);
World.setBlock(coords.x+2,coords.y+4,  coords.z+4, 158, 5);
World.setBlock(coords.x+4,coords.y+4,  coords.z+4, 158, 5);
World.setBlock(coords.x+4,coords.y+3,  coords.z+1, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z+2, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z+3, 158, 8);
World.setBlock(coords.x+4,coords.y+4,  coords.z+2, 158, 5);
World.setBlock(coords.x+4,coords.y+2,  coords.z+1, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z+2, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z+3, 158, 13);
World.setBlock(coords.x+3,coords.y+2,  coords.z+3, VanillaBlockID.barrel, 0);
World.setBlock(coords.x+2,coords.y+2,  coords.z+2, BlockID.TradeGREEN, 0);
}}});

Callback.addCallback("GenerateChunk", function (chunkX, chunkZ) {

    let coords = GenerationUtils.randomCoords(chunkX, chunkZ, 64, 128);
    if(Math.random() < 0.004){
    coords = GenerationUtils.findSurface(coords.x, coords.y, coords.z);

if(World.getBlock(coords.x,coords.y+1,coords.z).id === 0 && GenerationUtils.canSeeSky(coords.x, coords.y + 1, coords.z)) { 
       World.setBlock(coords.x,coords.y+1, coords.z, 158, 5);
World.setBlock(coords.x+1,coords.y+1,  coords.z, 17, 0);  
World.setBlock(coords.x+1,coords.y+2,  coords.z, 17, 0);  
World.setBlock(coords.x+1,coords.y+3,  coords.z, 17, 0);  
World.setBlock(coords.x+1,coords.y+4,  coords.z, 85, 0);  
World.setBlock(coords.x+1,coords.y+5,  coords.z, 35, 11);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+1, 35, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+1, 158, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+2, 158, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+3, 158, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+4, 158, 5);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+1, 158, 8);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+2, 158, 8);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+3, 158, 8);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+4, 17, 0);  
World.setBlock(coords.x+1,coords.y+2,  coords.z+4, 17, 0);  
World.setBlock(coords.x+1,coords.y+3,  coords.z+4, 17, 0);  
World.setBlock(coords.x+1,coords.y+4,  coords.z+4, 85, 0);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+4, 35, 11);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+2, 35, 11);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+3, 35, 0);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+4, 35, 11);  
World.setBlock(coords.x+2,coords.y+1,  coords.z, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z, 17, 0);
World.setBlock(coords.x+2,coords.y+2,  coords.z, 158, 13);
World.setBlock(coords.x+3,coords.y+2,  coords.z, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z, 17, 0);
World.setBlock(coords.x+2,coords.y+3,  coords.z, 158, 8);
World.setBlock(coords.x+3,coords.y+3,  coords.z, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z, 17, 0);
World.setBlock(coords.x+2,coords.y+4,  coords.z, 158, 5);
World.setBlock(coords.x+4,coords.y+4,  coords.z, 158, 5);
World.setBlock(coords.x+2,coords.y+1,  coords.z+1, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+1, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+1, 158, 8);
World.setBlock(coords.x+2,coords.y+1,  coords.z+2, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+2, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+2, 158, 8);
World.setBlock(coords.x+2,coords.y+1,  coords.z+3, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+3, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+3, 158, 8);
World.setBlock(coords.x+2,coords.y+1,  coords.z+4, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+4, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+4, 17, 0);
World.setBlock(coords.x+2,coords.y+2,  coords.z+4, 158, 13);
World.setBlock(coords.x+3,coords.y+2,  coords.z+4, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z+4, 17, 0);
World.setBlock(coords.x+2,coords.y+3,  coords.z+4, 158, 8);
World.setBlock(coords.x+3,coords.y+3,  coords.z+4, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z+4, 17, 0);
World.setBlock(coords.x+2,coords.y+4,  coords.z+4, 158, 5);
World.setBlock(coords.x+4,coords.y+4,  coords.z+4, 158, 5);
World.setBlock(coords.x+4,coords.y+3,  coords.z+1, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z+2, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z+3, 158, 8);
World.setBlock(coords.x+4,coords.y+4,  coords.z+2, 158, 5);
World.setBlock(coords.x+4,coords.y+2,  coords.z+1, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z+2, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z+3, 158, 13);
World.setBlock(coords.x+3,coords.y+2,  coords.z+3, VanillaBlockID.barrel, 0);
World.setBlock(coords.x+2,coords.y+2,  coords.z+2, BlockID.TradeBLUE, 0);
}}});

Callback.addCallback("GenerateChunk", function (chunkX, chunkZ) {

    let coords = GenerationUtils.randomCoords(chunkX, chunkZ, 64, 128);
    if(Math.random() < 0.004){
    coords = GenerationUtils.findSurface(coords.x, coords.y, coords.z);

if(World.getBlock(coords.x,coords.y+1,coords.z).id === 0 && GenerationUtils.canSeeSky(coords.x, coords.y + 1, coords.z)) { 
       World.setBlock(coords.x,coords.y+1, coords.z, 158, 5);
World.setBlock(coords.x+1,coords.y+1,  coords.z, 17, 0);  
World.setBlock(coords.x+1,coords.y+2,  coords.z, 17, 0);  
World.setBlock(coords.x+1,coords.y+3,  coords.z, 17, 0);  
World.setBlock(coords.x+1,coords.y+4,  coords.z, 85, 0);  
World.setBlock(coords.x+1,coords.y+5,  coords.z, 35, 4);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+1, 35, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+1, 158, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+2, 158, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+3, 158, 0);  
World.setBlock(coords.x,coords.y+1,  coords.z+4, 158, 5);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+1, 158, 8);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+2, 158, 8);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+3, 158, 8);  
World.setBlock(coords.x+1,coords.y+1,  coords.z+4, 17, 0);  
World.setBlock(coords.x+1,coords.y+2,  coords.z+4, 17, 0);  
World.setBlock(coords.x+1,coords.y+3,  coords.z+4, 17, 0);  
World.setBlock(coords.x+1,coords.y+4,  coords.z+4, 85, 0);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+4, 35, 4);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+2, 35, 4);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+3, 35, 0);  
World.setBlock(coords.x+1,coords.y+5,  coords.z+4, 35, 4);  
World.setBlock(coords.x+2,coords.y+1,  coords.z, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z, 17, 0);
World.setBlock(coords.x+2,coords.y+2,  coords.z, 158, 13);
World.setBlock(coords.x+3,coords.y+2,  coords.z, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z, 17, 0);
World.setBlock(coords.x+2,coords.y+3,  coords.z, 158, 8);
World.setBlock(coords.x+3,coords.y+3,  coords.z, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z, 17, 0);
World.setBlock(coords.x+2,coords.y+4,  coords.z, 158, 5);
World.setBlock(coords.x+4,coords.y+4,  coords.z, 158, 5);
World.setBlock(coords.x+2,coords.y+1,  coords.z+1, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+1, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+1, 158, 8);
World.setBlock(coords.x+2,coords.y+1,  coords.z+2, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+2, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+2, 158, 8);
World.setBlock(coords.x+2,coords.y+1,  coords.z+3, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+3, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+3, 158, 8);
World.setBlock(coords.x+2,coords.y+1,  coords.z+4, 158, 8);
World.setBlock(coords.x+3,coords.y+1,  coords.z+4, 158, 8);
World.setBlock(coords.x+4,coords.y+1,  coords.z+4, 17, 0);
World.setBlock(coords.x+2,coords.y+2,  coords.z+4, 158, 13);
World.setBlock(coords.x+3,coords.y+2,  coords.z+4, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z+4, 17, 0);
World.setBlock(coords.x+2,coords.y+3,  coords.z+4, 158, 8);
World.setBlock(coords.x+3,coords.y+3,  coords.z+4, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z+4, 17, 0);
World.setBlock(coords.x+2,coords.y+4,  coords.z+4, 158, 5);
World.setBlock(coords.x+4,coords.y+4,  coords.z+4, 158, 5);
World.setBlock(coords.x+4,coords.y+3,  coords.z+1, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z+2, 158, 8);
World.setBlock(coords.x+4,coords.y+3,  coords.z+3, 158, 8);
World.setBlock(coords.x+4,coords.y+4,  coords.z+2, 158, 5);
World.setBlock(coords.x+4,coords.y+2,  coords.z+1, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z+2, 158, 13);
World.setBlock(coords.x+4,coords.y+2,  coords.z+3, 158, 13);
World.setBlock(coords.x+3,coords.y+2,  coords.z+3, VanillaBlockID.barrel, 0);
World.setBlock(coords.x+2,coords.y+2,  coords.z+2, BlockID.TradeYELLOW, 0);
}}});