IDRegistry.genItemID("goldencoins");
Item.createItem("goldencoins", "Golden coins", {name: "goldencoins", meta: 0}, {stack: 64});
IDRegistry.genItemID("daedraHeart");
Item.createItem("daedraHeart", "Daedra heart", {name: "daedraHeart", meta: 0}, {stack: 64});
IDRegistry.genItemID("minorHealing");
Item.createItem("minorHealing", "Minor healing", {name: "minorHealing", meta: 0}, {stack: 64});
IDRegistry.genItemID("minorMagicka");
Item.createItem("minorMagicka", "Minor magicka", {name: "minorMagicka", meta: 0}, {stack: 64});
IDRegistry.genItemID("leatherStrips");
Item.createItem("leatherStrips", "Leather strips", {name: "leatherStrips", meta: 0}, {stack: 64});
IDRegistry.genItemID("cup");
Item.createItem("cup", "Cup", {name: "cup", meta: 0}, {stack: 1});
IDRegistry.genItemID("cup1");
Item.createItem("cup1", "Cup", {name: "cup1", meta: 0}, {stack: 1});
IDRegistry.genItemID("cup2");
Item.createItem("cup2", "Cup", {name: "cup2", meta: 0}, {stack: 1});
IDRegistry.genItemID("plate");
Item.createItem("plate", "Plate", {name: "plate", meta: 0}, {stack: 1});
IDRegistry.genItemID("plate1");
Item.createItem("plate1", "Plate", {name: "plate1", meta: 0}, {stack: 1});
IDRegistry.genItemID("plate2");
Item.createItem("plate2", "Plate", {name: "plate2", meta: 0}, {stack: 1});
IDRegistry.genItemID("barrel");
Item.createItem("barrel", "barrel", {name: "barrel", meta: 0}, {stack: 1});
IDRegistry.genItemID("candle");
Item.createItem("candle", "Candle", {name: "candle", meta: 0}, {stack: 1});
IDRegistry.genItemID("lampa");
Item.createItem("lampa", "Lamp", {name: "lampa", meta: 0}, {stack: 1});
IDRegistry.genItemID("urn");
Item.createItem("urn", "Urn", {name: "urn", meta: 0}, {stack: 1});
IDRegistry.genItemID("tanning");
Item.createItem("tanning", "Tanning machine", {name: "tanning", meta: 0}, {stack: 1});
IDRegistry.genItemID("grindstone");
Item.createItem("grindstone", "Grindstone", {name: "grindstone", meta: 0}, {stack: 1});
IDRegistry.genItemID("cheese");
Item.createItem("cheese", "\xa7eCheese", {name: "cheese", meta: 0}, {stack: 16});
IDRegistry.genItemID("chandelier");
Item.createItem("chandelier", "Chandelier", {name: "chandelier", meta: 0}, {stack: 1});
IDRegistry.genItemID("scarecrow");
Item.createItem("scarecrow", "Scarecrow", {name: "scarecrow", meta: 0}, {stack: 1});
IDRegistry.genItemID("scarecrow1");
Item.createItem("scarecrow1", "Scarecrow", {name: "scarecrow1", meta: 0}, {stack: 1});
IDRegistry.genItemID("secateurs");
Item.createItem("secateurs", "secateurs", {name: "secateurs", meta: 0}, {stack: 1});
Item.setMaxDamage(ItemID.secateurs, 150);

