CropRegistry.registerWithID("airCrop", "airCrop", "airCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.airCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.airCrop, drop: ItemID.airEssence, seed: ItemID.airSeeds});
CropRegistry.registerWithID("coalCrop", "coalCrop", "coalCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.coalCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.coalCrop, drop: ItemID.coalEssence, seed: ItemID.coalSeeds});
CropRegistry.registerWithID("diamondCrop", "diamondCrop", "diamondCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.diamondCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.diamondCrop, drop: ItemID.diamondEssence, seed: ItemID.diamondSeeds});
CropRegistry.registerWithID("dyeCrop", "dyeCrop", "dyeCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.dyeCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.dyeCrop, drop: ItemID.dyeEssence, seed: ItemID.dyeSeeds});
CropRegistry.registerWithID("earthCrop", "earthCrop", "earthCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.earthCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.earthCrop, drop: ItemID.earthEssence, seed: ItemID.earthSeeds});
CropRegistry.registerWithID("emeraldCrop", "emeraldCrop", "emeraldCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.emeraldCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.emeraldCrop, drop: ItemID.emeraldEssence, seed: ItemID.emeraldSeeds});
CropRegistry.registerWithID("experienceCrop", "experienceCrop", "experienceCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.experienceCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.experienceCrop, drop: ItemID.experienceEssence, seed: ItemID.experienceSeeds});
CropRegistry.registerWithID("fireCrop", "fireCrop", "fireCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.fireCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.fireCrop, drop: ItemID.fireEssence, seed: ItemID.fireSeeds});
CropRegistry.registerWithID("glowstoneCrop", "glowstoneCrop", "glowstoneCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.glowstoneCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.glowstoneCrop, drop: ItemID.glowstoneEssence, seed: ItemID.glowstoneSeeds});
CropRegistry.registerWithID("goldCrop", "goldCrop", "goldCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.goldCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.goldCrop, drop: ItemID.goldEssence, seed: ItemID.goldSeeds});
CropRegistry.registerWithID("ironCrop", "ironCrop", "ironCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.ironCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.ironCrop, drop: ItemID.ironEssence, seed: ItemID.ironSeeds});
CropRegistry.registerWithID("lapisCrop", "lapisCrop", "lapisCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.lapisCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.lapisCrop, drop: ItemID.lapisEssence, seed: ItemID.lapisSeeds});
CropRegistry.registerWithID("minicioCrop", "minicioCrop", "minicioCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.minicioCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.minicioCrop, drop: ItemID.minicioEssence, seed: ItemID.minicioSeeds});
CropRegistry.registerWithID("natureCrop", "natureCrop", "natureCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.natureCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.natureCrop, drop: ItemID.natureEssence, seed: ItemID.natureSeeds});
CropRegistry.registerWithID("netherCrop", "netherCrop", "netherCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.netherCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.netherCrop, drop: ItemID.netherEssence, seed: ItemID.netherSeeds});
CropRegistry.registerWithID("obsidianCrop", "obsidianCrop", "obsidianCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.obsidianCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.obsidianCrop, drop: ItemID.obsidianEssence, seed: ItemID.obsidianSeeds});
CropRegistry.registerWithID("quartzCrop", "quartzCrop", "quartzCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.quartzCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.quartzCrop, drop: ItemID.quartzEssence, seed: ItemID.quartzSeeds});
CropRegistry.registerWithID("redstoneCrop", "redstoneCrop", "redstoneCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.redstoneCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.redstoneCrop, drop: ItemID.redstoneEssence, seed: ItemID.redstoneSeeds});
CropRegistry.registerWithID("waterCrop", "waterCrop", "waterCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.waterCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.waterCrop, drop: ItemID.waterEssence, seed: ItemID.waterSeeds});
CropRegistry.registerWithID("blazeCrop", "blazeCrop", "blazeCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.blazeCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.blazeCrop, drop: ItemID.blazeEssence, seed: ItemID.blazeSeeds});
CropRegistry.registerWithID("chickenCrop", "chickenCrop", "chickenCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.chickenCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.chickenCrop, drop: ItemID.chickenEssence, seed: ItemID.chickenSeeds});
CropRegistry.registerWithID("cowCrop", "cowCrop", "cowCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.cowCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.cowCrop, drop: ItemID.cowEssence, seed: ItemID.cowSeeds});
CropRegistry.registerWithID("creeperCrop", "creeperCrop", "creeperCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.creeperCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.creeperCrop, drop: ItemID.creeperEssence, seed: ItemID.creeperSeeds});
CropRegistry.registerWithID("enderCrop", "enderCrop", "enderCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.enderCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.enderCrop, drop: ItemID.enderEssence, seed: ItemID.enderSeeds});
CropRegistry.registerWithID("ghastCrop", "ghastCrop", "ghastCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.ghastCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.ghastCrop, drop: ItemID.ghastEssence, seed: ItemID.ghastSeeds});
CropRegistry.registerWithID("pigCrop", "pigCrop", "pigCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.pigCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.pigCrop, drop: ItemID.pigEssence, seed: ItemID.pigSeeds});
CropRegistry.registerWithID("sheepCrop", "sheepCrop", "sheepCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.sheepCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.sheepCrop, drop: ItemID.sheepEssence, seed: ItemID.sheepSeeds});
CropRegistry.registerWithID("skeletonCrop", "skeletonCrop", "skeletonCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.skeletonCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.skeletonCrop, drop: ItemID.skeletonEssence, seed: ItemID.skeletonSeeds});
CropRegistry.registerWithID("slimeCrop", "slimeCrop", "slimeCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.slimeCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.slimeCrop, drop: ItemID.slimeEssence, seed: ItemID.slimeSeeds});
CropRegistry.registerWithID("spiderCrop", "spiderCrop", "spiderCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.spiderCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.spiderCrop, drop: ItemID.spiderEssence, seed: ItemID.spiderSeeds});
CropRegistry.registerWithID("witherCrop", "witherCrop", "witherCrop", BLOCK_TYPE_CROP);
PlantModel.tree(BlockID.witherCrop, 0);
CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.witherCrop, drop: ItemID.witherEssence, seed: ItemID.witherSeeds});
ModAPI.addAPICallback("ICore", function (api) {
    CropRegistry.registerWithID("copperCrop", "copperCrop", "copperCrop", BLOCK_TYPE_CROP);
    PlantModel.tree(BlockID.copperCrop, 0);
    CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.copperCrop, drop: ItemID.copperEssence, seed: ItemID.copperSeeds});
    CropRegistry.registerWithID("iridiumCrop", "iridiumCrop", "iridiumCrop", BLOCK_TYPE_CROP);
    PlantModel.tree(BlockID.iridiumCrop, 0);
    CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.iridiumCrop, drop: ItemID.iridiumEssence, seed: ItemID.iridiumSeeds});
    CropRegistry.registerWithID("leadCrop", "leadCrop", "leadCrop", BLOCK_TYPE_CROP);
    PlantModel.tree(BlockID.leadCrop, 0);
    CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.leadCrop, drop: ItemID.leadEssence, seed: ItemID.leadSeeds});
    CropRegistry.registerWithID("rubberCrop", "rubberCrop", "rubberCrop", BLOCK_TYPE_CROP);
    PlantModel.tree(BlockID.rubberCrop, 0);
    CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.rubberCrop, drop: ItemID.rubberEssence, seed: ItemID.rubberSeeds});
    CropRegistry.registerWithID("silverCrop", "silverCrop", "silverCrop", BLOCK_TYPE_CROP);
    PlantModel.tree(BlockID.silverCrop, 0);
    CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.silverCrop, drop: ItemID.silverEssence, seed: ItemID.silverSeeds});
    CropRegistry.registerWithID("steelCrop", "steelCrop", "steelCrop", BLOCK_TYPE_CROP);
    PlantModel.tree(BlockID.steelCrop, 0);
    CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.steelCrop, drop: ItemID.steelEssence, seed: ItemID.steelSeeds});
    CropRegistry.registerWithID("tinCrop", "tinCrop", "tinCrop", BLOCK_TYPE_CROP);
    PlantModel.tree(BlockID.tinCrop, 0);
    CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.tinCrop, drop: ItemID.tinEssence, seed: ItemID.tinSeeds});
    CropRegistry.registerWithID("uraniumCrop", "uraniumCrop", "uraniumCrop", BLOCK_TYPE_CROP);
    PlantModel.tree(BlockID.uraniumCrop, 0);
    CropRegistry.deriveCropAsClass("magical_crops", {id: BlockID.uraniumCrop, drop: ItemID.uraniumEssence, seed: ItemID.uraniumSeeds});
});

