IDRegistry.genItemID("minicioEssence");
Item.createItem("minicioEssence", "Minicio Essence", {name: "minicioEssence", meta: 0});
IDRegistry.genItemID("accioEssence");
Item.createItem("accioEssence", "Accio Essence", {name: "accioEssence", meta: 0});
IDRegistry.genItemID("crucioEssence");
Item.createItem("crucioEssence", "Crucio Essence", {name: "crucioEssence", meta: 0});
IDRegistry.genItemID("imperioEssence");
Item.createItem("imperioEssence", "Imperio Essence", {name: "imperioEssence", meta: 0});
IDRegistry.genItemID("zivicioEssence");
Item.createItem("zivicioEssence", "Zivicio Essence", {name: "zivicioEssence", meta: 0});
IDRegistry.genItemID("airEssence");
Item.createItem("airEssence", "Air Essence", {name: "airEssence", meta: 0});
IDRegistry.genItemID("airShardEssence");
Item.createItem("airShardEssence", "Air Shard Essence", {name: "airShardEssence", meta: 0});
IDRegistry.genItemID("coalEssence");
Item.createItem("coalEssence", "Coal Essence", {name: "coalEssence", meta: 0});
IDRegistry.genItemID("diamondEssence");
Item.createItem("diamondEssence", "Diamond Essence", {name: "diamondEssence", meta: 0});
IDRegistry.genItemID("dyeEssence");
Item.createItem("dyeEssence", "Technicolor Essence", {name: "dyeEssence", meta: 0});
IDRegistry.genItemID("earthEssence");
Item.createItem("earthEssence", "Earth Essence", {name: "earthEssence", meta: 0});
IDRegistry.genItemID("earthShardEssence");
Item.createItem("earthShardEssence", "Earth Shard Essence", {name: "earthShardEssence", meta: 0});
IDRegistry.genItemID("emeraldEssence");
Item.createItem("emeraldEssence", "Emerald Essence", {name: "emeraldEssence", meta: 0});
IDRegistry.genItemID("experienceEssence");
Item.createItem("experienceEssence", "ExperienceEssence", {name: "experienceEssence", meta: 0});
IDRegistry.genItemID("fireEssence");
Item.createItem("fireEssence", "Fire Essence", {name: "fireEssence", meta: 0});
IDRegistry.genItemID("fireShardEssence");
Item.createItem("fireShardEssence", "Fire Shard Essence", {name: "fireShardEssence", meta: 0});
IDRegistry.genItemID("glowstoneEssence");
Item.createItem("glowstoneEssence", "Glowstone Essence", {name: "glowstoneEssence", meta: 0});
IDRegistry.genItemID("goldEssence");
Item.createItem("goldEssence", "Gold Essence", {name: "goldEssence", meta: 0});
IDRegistry.genItemID("ironEssence");
Item.createItem("ironEssence", "Iron Essence", {name: "ironEssence", meta: 0});
IDRegistry.genItemID("lapisEssence");
Item.createItem("lapisEssence", "Lapis Essence", {name: "lapisEssence", meta: 0});
IDRegistry.genItemID("natureEssence");
Item.createItem("natureEssence", "Nature Essence", {name: "natureEssence", meta: 0});
IDRegistry.genItemID("netherEssence");
Item.createItem("netherEssence", "Nether Essence", {name: "netherEssence", meta: 0});
IDRegistry.genItemID("obsidianEssence");
Item.createItem("obsidianEssence", "Obsidian Essence", {name: "obsidianEssence", meta: 0});
IDRegistry.genItemID("quartzEssence");
Item.createItem("quartzEssence", "Quartz Essence", {name: "quartzEssence", meta: 0});
IDRegistry.genItemID("redstoneEssence");
Item.createItem("redstoneEssence", "Redstone Essence", {name: "redstoneEssence", meta: 0});
IDRegistry.genItemID("waterEssence");
Item.createItem("waterEssence", "Water Essence", {name: "waterEssence", meta: 0});
IDRegistry.genItemID("waterShardEssence");
Item.createItem("waterShardEssence", "Water Shard Essence", {name: "waterShardEssence", meta: 0});
IDRegistry.genItemID("blazeEssence");
Item.createItem("blazeEssence", "Blaze Essence", {name: "blazeEssence", meta: 0});
IDRegistry.genItemID("chickenEssence");
Item.createItem("chickenEssence", "Chicken Essence", {name: "chickenEssence", meta: 0});
IDRegistry.genItemID("cowEssence");
Item.createItem("cowEssence", "Cow Essence", {name: "cowEssence", meta: 0});
IDRegistry.genItemID("creeperEssence");
Item.createItem("creeperEssence", "Creeper Essence", {name: "creeperEssence", meta: 0});
IDRegistry.genItemID("enderEssence");
Item.createItem("enderEssence", "Ender Essence", {name: "enderEssence", meta: 0});
IDRegistry.genItemID("ghastEssence");
Item.createItem("ghastEssence", "Ghast Essence", {name: "ghastEssence", meta: 0});
IDRegistry.genItemID("pigEssence");
Item.createItem("pigEssence", "Pig Essence", {name: "pigEssence", meta: 0});
IDRegistry.genItemID("sheepEssence");
Item.createItem("sheepEssence", "Sheep Essence", {name: "sheepEssence", meta: 0});
IDRegistry.genItemID("skeletonEssence");
Item.createItem("skeletonEssence", "Skeleton Essence", {name: "skeletonEssence", meta: 0});
IDRegistry.genItemID("slimeEssence");
Item.createItem("slimeEssence", "Slime Essence", {name: "slimeEssence", meta: 0});
IDRegistry.genItemID("spiderEssence");
Item.createItem("spiderEssence", "Spider Essence", {name: "spiderEssence", meta: 0});
IDRegistry.genItemID("witherEssence");
Item.createItem("witherEssence", "Wither Essence", {name: "witherEssence", meta: 0});
ModAPI.addAPICallback("ICore", function (api) {
    IDRegistry.genItemID("copperEssence");
    Item.createItem("copperEssence", "Copper Essence", {name: "copperEssence", meta: 0});
    IDRegistry.genItemID("iridiumEssence");
    Item.createItem("iridiumEssence", "Iridium Essence", {name: "iridiumEssence", meta: 0});
    IDRegistry.genItemID("leadEssence");
    Item.createItem("leadEssence", "Lead Essence", {name: "leadEssence", meta: 0});
    IDRegistry.genItemID("rubberEssence");
    Item.createItem("rubberEssence", "Rubber Essence", {name: "rubberEssence", meta: 0});
    IDRegistry.genItemID("silverEssence");
    Item.createItem("silverEssence", "Silver Essence", {name: "silverEssence", meta: 0});
    IDRegistry.genItemID("steelEssence");
    Item.createItem("steelEssence", "Steel Essence", {name: "steelEssence", meta: 0});
    IDRegistry.genItemID("tinEssence");
    Item.createItem("tinEssence", "Tin Essence", {name: "tinEssence", meta: 0});
    IDRegistry.genItemID("uraniumEssence");
    Item.createItem("uraniumEssence", "Uraniun Essence", {name: "uraniumEssence", meta: 0});
});

