Callback.addCallback("PostLoaded", function () {
    Recipes.addShaped({id: ItemID.minicioSeeds, count: 1, data: 0}, ["xxx", "x#x", "xxx"], ["x", ItemID.minicioEssence, 0, "#", 295, 0]);
    Recipes.addShaped({id: ItemID.airSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.accioEssence, 0, "b", 374, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.waterSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.accioEssence, 0, "b", 325, 8, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.earthSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.accioEssence, 0, "b", 3, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.fireSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.accioEssence, 0, "b", 325, 10, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.coalSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.accioEssence, 0, "b", 263, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.dyeSeeds, count: 1, data: 0}, ["sxl", "x#x", "pxd"], ["x", ItemID.accioEssence, 0, "s", 351, 0, "l", 351, 4, "p", 351, 9, "d", 351, 12, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.natureSeeds, count: 1, data: 0}, ["sxl", "x#x", "pxd"], ["x", ItemID.accioEssence, 0, "s", 37, 0, "l", 38, 0, "p", 81, 0, "d", 86, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.redstoneSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.crucioEssence, 0, "b", 331, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.glowstoneSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.crucioEssence, 0, "b", 348, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.obsidianSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.crucioEssence, 0, "b", 49, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.netherSeeds, count: 1, data: 0}, ["bxz", "x#x", "sxb"], ["x", ItemID.crucioEssence, 0, "b", 87, 0, "s", 112, 0, "z", 88, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.cowSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.crucioEssence, 0, "b", 334, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.pigSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.crucioEssence, 0, "b", 319, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.chickenSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.crucioEssence, 0, "b", 344, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.sheepSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.crucioEssence, 0, "b", 35, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.ironSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", 265, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.goldSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", 266, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.lapisSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", 351, 4, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.experienceSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", 403, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.quartzSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", 406, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.creeperSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", 289, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.blazeSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", 369, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.enderSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", 368, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.skeletonSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", 352, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.slimeSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", 341, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.spiderSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", 375, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.ghastSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", 370, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.diamondSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.zivicioEssence, 0, "b", 264, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.emeraldSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.zivicioEssence, 0, "b", 388, 0, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: ItemID.witherSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.zivicioEssence, 0, "b", 397, 1, "#", ItemID.minicioSeeds, 0]);
    Recipes.addShaped({id: 332, count: 32, data: 0}, ["x# ", "#x ", ""], ["x", ItemID.airEssence, 0, "#", ItemID.waterEssence, 0]);
    Recipes.addShaped({id: 325, count: 1, data: 0}, [" x ", "x#x", " x "], ["x", ItemID.waterEssence, 0, "#", 325, 10]);
    Recipes.addShaped({id: 17, count: 8, data: 0}, ["x# ", "## ", ""], ["x", ItemID.waterEssence, 0, "#", ItemID.natureEssence, 0]);
    Recipes.addShaped({id: 17, count: 8, data: 1}, ["#x ", "## ", ""], ["x", ItemID.waterEssence, 0, "#", ItemID.natureEssence, 0]);
    Recipes.addShaped({id: 17, count: 8, data: 2}, ["## ", "x# ", ""], ["x", ItemID.waterEssence, 0, "#", ItemID.natureEssence, 0]);
    Recipes.addShaped({id: 17, count: 8, data: 3}, ["## ", "#x ", ""], ["x", ItemID.waterEssence, 0, "#", ItemID.natureEssence, 0]);
    Recipes.addShaped({id: 3, count: 48, data: 0}, ["xxx", "x x", "xxx"], ["x", ItemID.earthEssence, 0]);
    Recipes.addShaped({id: 337, count: 32, data: 0}, ["x# ", "#x ", ""], ["x", ItemID.waterEssence, 0, "#", ItemID.earthEssence, 0]);
    Recipes.addShaped({id: 4, count: 64, data: 0}, ["x# ", "#x ", ""], ["x", ItemID.fireEssence, 0, "#", ItemID.earthEssence, 0]);
    Recipes.addShaped({id: 12, count: 16, data: 0}, ["#x ", "x# ", ""], ["x", ItemID.fireEssence, 0, "#", ItemID.earthEssence, 0]);
    Recipes.addShaped({id: 13, count: 16, data: 0}, ["xx ", "## ", ""], ["x", ItemID.fireEssence, 0, "#", ItemID.earthEssence, 0]);
    Recipes.addShaped({id: 325, count: 1, data: 10}, [" x ", "x#x", " x "], ["x", ItemID.fireEssence, 0, "#", 325, 0]);
    Recipes.addShaped({id: 263, count: 12, data: 0}, ["xxx", "x x", "xxx"], ["x", ItemID.coalEssence, 0]);
    Recipes.addShaped({id: 351, count: 6, data: 0}, ["xxx", "", ""], ["x", ItemID.dyeEssence, 0]);
    Recipes.addShaped({id: 351, count: 6, data: 1}, ["", "xxx", ""], ["x", ItemID.dyeEssence, 0]);
    Recipes.addShaped({id: 351, count: 6, data: 2}, ["", "", "xxx"], ["x", ItemID.dyeEssence, 0]);
    Recipes.addShaped({id: 351, count: 6, data: 6}, ["x", "x", "x"], ["x", ItemID.dyeEssence, 0]);
    Recipes.addShaped({id: 351, count: 6, data: 5}, [" x ", " x ", " x "], ["x", ItemID.dyeEssence, 0]);
    Recipes.addShaped({id: 351, count: 6, data: 7}, ["x", " x ", "  x"], ["x", ItemID.dyeEssence, 0]);
    Recipes.addShaped({id: 351, count: 6, data: 8}, [" x ", " x ", "x"], ["x", ItemID.dyeEssence, 0]);
    Recipes.addShaped({id: 351, count: 6, data: 9}, ["xx ", "x", ""], ["x", ItemID.dyeEssence, 0]);
    Recipes.addShaped({id: 351, count: 6, data: 10}, [" xx", "x", ""], ["x", ItemID.dyeEssence, 0]);
    Recipes.addShaped({id: 351, count: 6, data: 11}, ["", "x", "x x"], ["x", ItemID.dyeEssence, 0]);
    Recipes.addShaped({id: 351, count: 6, data: 12}, ["xx ", " x ", ""], ["x", ItemID.dyeEssence, 0]);
    Recipes.addShaped({id: 351, count: 6, data: 13}, [" xx", "x", ""], ["x", ItemID.dyeEssence, 0]);
    Recipes.addShaped({id: 351, count: 6, data: 14}, [" x ", "x", " x "], ["x", ItemID.dyeEssence, 0]);
    Recipes.addShaped({id: 48, count: 1, data: 0}, ["###", "#x#", "###"], ["x", ItemID.natureEssence, 0, "#", 4, 0]);
    Recipes.addShaped({id: 98, count: 8, data: 1}, ["xx#", "xn#", "##x"], ["x", 98, 0, "#", 98, 2, "n", ItemID.natureEssence, 0]);
    Recipes.addShaped({id: 106, count: 16, data: 0}, ["x x", "xxx", "x x"], ["x", ItemID.natureEssence, 0]);
    Recipes.addShaped({id: 111, count: 8, data: 0}, [" x ", "xxx", "x x"], ["x", ItemID.natureEssence, 0]);
    Recipes.addShaped({id: 110, count: 8, data: 0}, ["xnx", "nmn", "xnx"], ["x", 3, 0, "m", 39, 2, "n", ItemID.natureEssence, 0]);
    Recipes.addShaped({id: 81, count: 8, data: 0}, ["x", "x", "x"], ["x", ItemID.natureEssence, 0]);
    Recipes.addShaped({id: 331, count: 24, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.redstoneEssence, 0]);
    Recipes.addShaped({id: 348, count: 12, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.glowstoneEssence, 0]);
    Recipes.addShaped({id: 49, count: 8, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.obsidianEssence, 0]);
    Recipes.addShaped({id: 88, count: 8, data: 0}, ["xxx", "x x", "xxx"], ["x", ItemID.netherEssence, 0]);
    Recipes.addShaped({id: 87, count: 16, data: 0}, ["xxx", "x", ""], ["x", ItemID.netherEssence, 0]);
    Recipes.addShaped({id: 112, count: 4, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.netherEssence, 0]);
    Recipes.addShaped({id: 334, count: 8, data: 0}, ["xxx", "x x", "xxx"], ["x", ItemID.cowEssence, 0]);
    Recipes.addShaped({id: 325, count: 1, data: 1}, [" x ", "x#x", " x "], ["x", ItemID.cowEssence, 0, "#", 325, 0]);
    Recipes.addShaped({id: 363, count: 4, data: 0}, ["xxx", "x", ""], ["x", ItemID.cowEssence, 0]);
    Recipes.addShaped({id: 319, count: 4, data: 0}, ["xxx", "x", ""], ["x", ItemID.pigEssence, 0]);
    Recipes.addShaped({id: 288, count: 8, data: 0}, ["xxx", "x x", "xxx"], ["x", ItemID.chickenEssence, 0]);
    Recipes.addShaped({id: 344, count: 4, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.chickenEssence, 0]);
    Recipes.addShaped({id: 365, count: 4, data: 0}, ["xxx", "x", ""], ["x", ItemID.chickenEssence, 0]);
    Recipes.addShaped({id: 35, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.sheepEssence, 0]);
    Recipes.addShaped({id: 15, count: 8, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.ironEssence, 0]);
    Recipes.addShaped({id: 14, count: 5, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.goldEssence, 0]);
    Recipes.addShaped({id: 351, count: 12, data: 4}, ["xxx", "xxx", "xxx"], ["x", ItemID.lapisEssence, 0]);
    Recipes.addShaped({id: 384, count: 4, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.experienceEssence, 0]);
    Recipes.addShaped({id: 406, count: 8, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.quartzEssence, 0]);
    Recipes.addShaped({id: 397, count: 1, data: 4}, ["xxx", "xxx", "xxx"], ["x", ItemID.creeperEssence, 0]);
    Recipes.addShaped({id: 289, count: 8, data: 0}, ["xxx", "x x", "xxx"], ["x", ItemID.creeperEssence, 0]);
    Recipes.addShaped({id: 500, count: 1, data: 0}, ["x#x", "#s#", "x#x"], ["x", ItemID.skeletonEssence, 0, "#", ItemID.creeperEssence, 0, "s", 351, 11]);
    Recipes.addShaped({id: 369, count: 4, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.blazeEssence, 0]);
    Recipes.addShaped({id: 368, count: 4, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.enderEssence, 0]);
    Recipes.addShaped({id: 121, count: 8, data: 0}, ["xxx", "x#x", "xxx"], ["x", 1, 0, "#", ItemID.enderEssence, 0]);
    Recipes.addShaped({id: 144, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.skeletonEssence, 0]);
    Recipes.addShaped({id: 352, count: 8, data: 0}, ["xxx", "x x", "xxx"], ["x", ItemID.skeletonEssence, 0]);
    Recipes.addShaped({id: 341, count: 8, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.slimeEssence, 0]);
    Recipes.addShaped({id: 287, count: 8, data: 0}, ["xxx", "x x", "xxx"], ["x", ItemID.spiderEssence, 0]);
    Recipes.addShaped({id: 375, count: 8, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.spiderEssence, 0]);
    Recipes.addShaped({id: 370, count: 2, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.ghastEssence, 0]);
    Recipes.addShaped({id: 264, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.diamondEssence, 0]);
    Recipes.addShaped({id: 388, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.emeraldEssence, 0]);
    Recipes.addShaped({id: 397, count: 1, data: 1}, ["xxx", "xxx", "xxx"], ["x", ItemID.witherEssence, 0]);
    Recipes.addShaped({id: ItemID.magicalFertilizer, count: 4, data: 0}, ["xzx", "z#z", "xzx"], ["x", 351, 15, "#", 264, 0, "z", ItemID.minicioEssence, 0]);
    Recipes.addShapeless({id: ItemID.minicioEssence, count: 4, data: 0}, [{id: ItemID.accioEssence, data: 0}]);
    Recipes.addShapeless({id: ItemID.accioEssence, count: 4, data: 0}, [{id: ItemID.crucioEssence, data: 0}]);
    Recipes.addShapeless({id: ItemID.crucioEssence, count: 4, data: 0}, [{id: ItemID.imperioEssence, data: 0}]);
    Recipes.addShapeless({id: ItemID.imperioEssence, count: 4, data: 0}, [{id: ItemID.zivicioEssence, data: 0}]);
    Recipes.addShaped({id: BlockID.dustMinicio, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.minicioEssence, 0]);
    Recipes.addShaped({id: BlockID.dustAccio, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.accioEssence, 0]);
    Recipes.addShaped({id: BlockID.dustCrucio, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.crucioEssence, 0]);
    Recipes.addShaped({id: BlockID.dustImperio, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.imperioEssence, 0]);
    Recipes.addShaped({id: BlockID.dustZivicio, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.zivicioEssence, 0]);
    Recipes.addShaped({id: BlockID.dustUltimate, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", BlockID.dustZivicio, 0]);
    Recipes.addShaped({id: ItemID.minicioEssence, count: 9, data: 0}, ["x", "", ""], ["x", BlockID.dustMinicio, 0]);
    Recipes.addShaped({id: ItemID.accioEssence, count: 9, data: 0}, ["x", "", ""], ["x", BlockID.dustAccio, 0]);
    Recipes.addShaped({id: ItemID.crucioEssence, count: 9, data: 0}, ["x", "", ""], ["x", BlockID.dustCrucio, 0]);
    Recipes.addShaped({id: ItemID.imperioEssence, count: 9, data: 0}, ["x", "", ""], ["x", BlockID.dustImperio, 0]);
    Recipes.addShaped({id: ItemID.zivicioEssence, count: 9, data: 0}, ["x", "", ""], ["x", BlockID.dustZivicio, 0]);
    Recipes.addShaped({id: BlockID.dustZivicio, count: 9, data: 0}, ["x", "", ""], ["x", BlockID.dustUltimate, 0]);
    Recipes.addShaped({id: ItemID.accioFurnace, count: 1, data: 0}, [" x ", "x#x", " x "], ["x", ItemID.accioEssence, 0, "#", 61, 0]);
    Recipes.addShaped({id: ItemID.crucioFurnace, count: 1, data: 0}, [" x ", "x#x", " x "], ["x", ItemID.crucioEssence, 0, "#", ItemID.accioFurnace, 0]);
    Recipes.addShaped({id: ItemID.imperioFurnace, count: 1, data: 0}, [" x ", "x#x", " x "], ["x", ItemID.imperioEssence, 0, "#", ItemID.crucioFurnace, 0]);
    Recipes.addShaped({id: ItemID.zivicioFurnace, count: 1, data: 0}, [" x ", "x#x", " x "], ["x", ItemID.zivicioEssence, 0, "#", ItemID.imperioFurnace, 0]);
    Recipes.addShaped({id: ItemID.ultimateFurnace, count: 1, data: 0}, [" x ", "x#x", " x "], ["x", BlockID.dustZivicio, 0, "#", ItemID.zivicioFurnace, 0]);
});
ModAPI.addAPICallback("ICore", function (api) {
    Callback.addCallback("PostLoaded", function () {
        Recipes.addShaped({id: ItemID.copperSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", ItemID.ingotCopper, 0, "#", ItemID.minicioSeeds, 0]);
        Recipes.addShaped({id: ItemID.leadSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", ItemID.ingotLead, 0, "#", ItemID.minicioSeeds, 0]);
        Recipes.addShaped({id: ItemID.rubberSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.accioEssence, 0, "b", ItemID.latex, 0, "#", ItemID.minicioSeeds, 0]);
        Recipes.addShaped({id: ItemID.silverSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", ItemID.ingotSilver, 0, "#", ItemID.minicioSeeds, 0]);
        Recipes.addShaped({id: ItemID.steelSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", ItemID.ingotSteel, 0, "#", ItemID.minicioSeeds, 0]);
        Recipes.addShaped({id: ItemID.tinSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.imperioEssence, 0, "b", ItemID.ingotTin, 0, "#", ItemID.minicioSeeds, 0]);
        Recipes.addShaped({id: ItemID.iridiumSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.zivicioEssence, 0, "b", ItemID.iridiumChunk, 0, "#", ItemID.minicioSeeds, 0]);
        Recipes.addShaped({id: ItemID.uraniumSeeds, count: 1, data: 0}, ["bxb", "x#x", "bxb"], ["x", ItemID.zivicioEssence, 0, "b", ItemID.uranium, 0, "#", ItemID.minicioSeeds, 0]);
        Recipes.addShaped({id: ItemID.ingotCopper, count: 4, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.copperEssence, 0]);
        Recipes.addShaped({id: ItemID.ingotLead, count: 4, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.leadEssence, 0]);
        Recipes.addShaped({id: ItemID.ingotSilver, count: 4, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.silverEssence, 0]);
        Recipes.addShaped({id: ItemID.ingotSteel, count: 4, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.steelEssence, 0]);
        Recipes.addShaped({id: ItemID.ingotTin, count: 4, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.tinEssence, 0]);
        Recipes.addShaped({id: ItemID.latex, count: 8, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.rubberEssence, 0]);
        Recipes.addShaped({id: BlockID.oreUranium, count: 4, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.uraniumEssence, 0]);
        Recipes.addShaped({id: ItemID.iridiumChunk, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.iridiumEssence, 0]);
    });
});

