IDRegistry.genItemID("airSeeds");
Item.createItem("airSeeds", "Air Seeds", {name: "airSeeds", meta: 0});
IDRegistry.genItemID("coalSeeds");
Item.createItem("coalSeeds", "Coal Seeds", {name: "coalSeeds", meta: 0});
IDRegistry.genItemID("diamondSeeds");
Item.createItem("diamondSeeds", "Diamond Seeds", {name: "diamondSeeds", meta: 0});
IDRegistry.genItemID("dyeSeeds");
Item.createItem("dyeSeeds", "Dye Seeds", {name: "dyeSeeds", meta: 0});
IDRegistry.genItemID("earthSeeds");
Item.createItem("earthSeeds", "Earth Seeds", {name: "earthSeeds", meta: 0});
IDRegistry.genItemID("emeraldSeeds");
Item.createItem("emeraldSeeds", "Emerald Seeds", {name: "emeraldSeeds", meta: 0});
IDRegistry.genItemID("experienceSeeds");
Item.createItem("experienceSeeds", "Experience Seeds", {name: "experienceSeeds", meta: 0});
IDRegistry.genItemID("fireSeeds");
Item.createItem("fireSeeds", "Fire Seeds", {name: "fireSeeds", meta: 0});
IDRegistry.genItemID("glowstoneSeeds");
Item.createItem("glowstoneSeeds", "Glowstone Seeds", {name: "glowstoneSeeds", meta: 0});
IDRegistry.genItemID("goldSeeds");
Item.createItem("goldSeeds", "Gold Seeds", {name: "goldSeeds", meta: 0});
IDRegistry.genItemID("ironSeeds");
Item.createItem("ironSeeds", "Iron Seeds", {name: "ironSeeds", meta: 0});
IDRegistry.genItemID("lapisSeeds");
Item.createItem("lapisSeeds", "Lapis Seeds", {name: "lapisSeeds", meta: 0});
IDRegistry.genItemID("minicioSeeds");
Item.createItem("minicioSeeds", "Minicio Seeds", {name: "minicioSeeds", meta: 0});
IDRegistry.genItemID("natureSeeds");
Item.createItem("natureSeeds", "Nature Seeds", {name: "natureSeeds", meta: 0});
IDRegistry.genItemID("netherSeeds");
Item.createItem("netherSeeds", "Nether Seeds", {name: "netherSeeds", meta: 0});
IDRegistry.genItemID("obsidianSeeds");
Item.createItem("obsidianSeeds", "Obsidian Seeds", {name: "obsidianSeeds", meta: 0});
IDRegistry.genItemID("quartzSeeds");
Item.createItem("quartzSeeds", "Quartz Seeds", {name: "quartzSeeds", meta: 0});
IDRegistry.genItemID("redstoneSeeds");
Item.createItem("redstoneSeeds", "Redstone Seeds", {name: "redstoneSeeds", meta: 0});
IDRegistry.genItemID("waterSeeds");
Item.createItem("waterSeeds", "Water Seeds", {name: "waterSeeds", meta: 0});
IDRegistry.genItemID("blazeSeeds");
Item.createItem("blazeSeeds", "Blaze Seeds", {name: "blazeSeeds", meta: 0});
IDRegistry.genItemID("chickenSeeds");
Item.createItem("chickenSeeds", "Chicken Seeds", {name: "chickenSeeds", meta: 0});
IDRegistry.genItemID("cowSeeds");
Item.createItem("cowSeeds", "Cow Seeds", {name: "cowSeeds", meta: 0});
IDRegistry.genItemID("creeperSeeds");
Item.createItem("creeperSeeds", "Creeper Seeds", {name: "creeperSeeds", meta: 0});
IDRegistry.genItemID("enderSeeds");
Item.createItem("enderSeeds", "Ender Seeds", {name: "enderSeeds", meta: 0});
IDRegistry.genItemID("ghastSeeds");
Item.createItem("ghastSeeds", "Ghast Seeds", {name: "ghastSeeds", meta: 0});
IDRegistry.genItemID("pigSeeds");
Item.createItem("pigSeeds", "Pig Seeds", {name: "pigSeeds", meta: 0});
IDRegistry.genItemID("sheepSeeds");
Item.createItem("sheepSeeds", "Sheep Seeds", {name: "sheepSeeds", meta: 0});
IDRegistry.genItemID("skeletonSeeds");
Item.createItem("skeletonSeeds", "Skeleton Seeds", {name: "skeletonSeeds", meta: 0});
IDRegistry.genItemID("slimeSeeds");
Item.createItem("slimeSeeds", "Slime Seeds", {name: "slimeSeeds", meta: 0});
IDRegistry.genItemID("spiderSeeds");
Item.createItem("spiderSeeds", "Spider Seeds", {name: "spiderSeeds", meta: 0});
IDRegistry.genItemID("witherSeeds");
Item.createItem("witherSeeds", "Wither Seeds", {name: "witherSeeds", meta: 0});
IDRegistry.genItemID("magicalFertilizer");
Item.createItem("magicalFertilizer", "Magical Fertilizer", {name: "magicalFertilizer", meta: 0});
ModAPI.addAPICallback("ICore", function (api) {
    IDRegistry.genItemID("copperSeeds");
    Item.createItem("copperSeeds", "Copper Seeds", {name: "copperSeeds", meta: 0});
    IDRegistry.genItemID("iridiumSeeds");
    Item.createItem("iridiumSeeds", "Iridium Seeds", {name: "iridiumSeeds", meta: 0});
    IDRegistry.genItemID("leadSeeds");
    Item.createItem("leadSeeds", "Lead Seeds", {name: "leadSeeds", meta: 0});
    IDRegistry.genItemID("rubberSeeds");
    Item.createItem("rubberSeeds", "Rubber Seeds", {name: "rubberSeeds", meta: 0});
    IDRegistry.genItemID("silverSeeds");
    Item.createItem("silverSeeds", "Silver Seeds", {name: "silverSeeds", meta: 0});
    IDRegistry.genItemID("steelSeeds");
    Item.createItem("steelSeeds", "Steel Seeds", {name: "steelSeeds", meta: 0});
    IDRegistry.genItemID("tinSeeds");
    Item.createItem("tinSeeds", "Tin Seeds", {name: "tinSeeds", meta: 0});
    IDRegistry.genItemID("uraniumSeeds");
    Item.createItem("uraniumSeeds", "Uraniun Seeds", {name: "uraniumSeeds", meta: 0});
});

