this.text = `align:
title:
lang:
translate:true
dir:
hidden:false
accessKey:
draggable:false
spellcheck:false
autocapitalize:
contentEditable:inherit
isContentEditable:false
inputMode:
offsetParent:null
offsetTop:0
offsetLeft:0
offsetWidth:0
offsetHeight:0
style:CSSStyleDeclaration
innerText:
outerText:
onabort:null
onblur:null
oncancel:null
oncanplay:null
oncanplaythrough:null
onchange:null
onclick:null
onclose:null
oncontextmenu:null
oncuechange:null
ondblclick:null
ondrag:null
ondragend:null
ondragenter:null
ondragleave:null
ondragover:null
ondragstart:null
ondrop:null
ondurationchange:null
onemptied:null
onended:null
onerror:null
onfocus:null
onformdata:null
oninput:null
oninvalid:null
onkeydown:null
onkeypress:null
onkeyup:null
onload:null
onloadeddata:null
onloadedmetadata:null
onloadstart:null
onmousedown:null
onmouseenter:null
onmouseleave:null
onmousemove:null
onmouseout:null
onmouseover:null
onmouseup:null
onmousewheel:null
onpause:null
onplay:null
onplaying:null
onprogress:null
onratechange:null
onreset:null
onresize:null
onscroll:null
onseeked:null
onseeking:null
onselect:null
onstalled:null
onsubmit:null
onsuspend:null
ontimeupdate:null
ontoggle:null
onvolumechange:null
onwaiting:null
onwebkitanimationend:null
onwebkitanimationiteration:null
onwebkitanimationstart:null
onwebkittransitionend:null
onwheel:null
onauxclick:null
ongotpointercapture:null
onlostpointercapture:null
onpointerdown:null
onpointermove:null
onpointerup:null
onpointercancel:null
onpointerover:null
onpointerout:null
onpointerenter:null
onpointerleave:null
onselectstart:null
onselectionchange:null
onanimationend:null
onanimationiteration:null
onanimationstart:null
ontransitionrun:null
ontransitionstart:null
ontransitionend:null
ontransitioncancel:null
oncopy:null
oncut:null
onpaste:null
dataset:DOMStringMap
nonce:
autofocus:false
tabIndex:-1
attachInternals:(){...}
blur:(){...}
click:(){...}
focus:(){...}
onpointerrawupdate:null
enterKeyHint:
ontouchcancel:null
ontouchend:null
ontouchmove:null
ontouchstart:null
getParent:(t){...}
namespaceURI:http://www.w3.org/1999/xhtml
prefix:null
localName:div
tagName:DIV
id:
className:
classList:DOMTokenList
slot:
attributes:NamedNodeMap
shadowRoot:null
part:DOMTokenList
assignedSlot:null
innerHTML:
outerHTML:&lt;div&gt;&lt;/div&gt;
scrollTop:0
scrollLeft:0
scrollWidth:0
scrollHeight:0
clientTop:0
clientLeft:0
clientWidth:0
clientHeight:0
attributeStyleMap:StylePropertyMap
onbeforecopy:null
onbeforecut:null
onbeforepaste:null
onsearch:null
elementTiming:
onfullscreenchange:null
onfullscreenerror:null
onwebkitfullscreenchange:null
onwebkitfullscreenerror:null
onbeforexrselect:null
children:HTMLCollection
firstElementChild:null
lastElementChild:null
childElementCount:0
previousElementSibling:null
nextElementSibling:null
after:(){...}
animate:(){...}
append:(){...}
attachShadow:(){...}
before:(){...}
closest:(){...}
computedStyleMap:(){...}
getAttribute:(){...}
getAttributeNS:(){...}
getAttributeNames:(){...}
getAttributeNode:(){...}
getAttributeNodeNS:(){...}
getBoundingClientRect:(){...}
getClientRects:(){...}
getElementsByClassName:(){...}
getElementsByTagName:(){...}
getElementsByTagNameNS:(){...}
hasAttribute:(){...}
hasAttributeNS:(){...}
hasAttributes:(){...}
hasPointerCapture:(){...}
insertAdjacentElement:(){...}
insertAdjacentHTML:(){...}
insertAdjacentText:(){...}
matches:(){...}
prepend:(){...}
querySelector:(){...}
querySelectorAll:(){...}
releasePointerCapture:(){...}
remove:(){...}
removeAttribute:(){...}
removeAttributeNS:(){...}
removeAttributeNode:(){...}
replaceWith:(){...}
requestFullscreen:(){...}
requestPointerLock:(){...}
scroll:(){...}
scrollBy:(){...}
scrollIntoView:(){...}
scrollIntoViewIfNeeded:(){...}
scrollTo:(){...}
setAttribute:(){...}
setAttributeNS:(){...}
setAttributeNode:(){...}
setAttributeNodeNS:(){...}
setPointerCapture:(){...}
toggleAttribute:(){...}
webkitMatchesSelector:(){...}
webkitRequestFullScreen:(){...}
webkitRequestFullscreen:(){...}
ariaAtomic:null
ariaAutoComplete:null
ariaBusy:null
ariaChecked:null
ariaColCount:null
ariaColIndex:null
ariaColSpan:null
ariaCurrent:null
ariaDescription:null
ariaDisabled:null
ariaExpanded:null
ariaHasPopup:null
ariaHidden:null
ariaKeyShortcuts:null
ariaLabel:null
ariaLevel:null
ariaLive:null
ariaModal:null
ariaMultiLine:null
ariaMultiSelectable:null
ariaOrientation:null
ariaPlaceholder:null
ariaPosInSet:null
ariaPressed:null
ariaReadOnly:null
ariaRelevant:null
ariaRequired:null
ariaRoleDescription:null
ariaRowCount:null
ariaRowIndex:null
ariaRowSpan:null
ariaSelected:null
ariaSetSize:null
ariaSort:null
ariaValueMax:null
ariaValueMin:null
ariaValueNow:null
ariaValueText:null
getAnimations:(){...}
replaceChildren:(){...}
nodeType:1
nodeName:DIV
baseURI:http://localhost:8159/console.html
isConnected:false
ownerDocument:HTMLDocument
parentNode:null
parentElement:null
childNodes:NodeList
firstChild:null
lastChild:null
previousSibling:null
nextSibling:null
nodeValue:null
textContent:
ELEMENT_NODE:1
ATTRIBUTE_NODE:2
TEXT_NODE:3
CDATA_SECTION_NODE:4
ENTITY_REFERENCE_NODE:5
ENTITY_NODE:6
PROCESSING_INSTRUCTION_NODE:7
COMMENT_NODE:8
DOCUMENT_NODE:9
DOCUMENT_TYPE_NODE:10
DOCUMENT_FRAGMENT_NODE:11
NOTATION_NODE:12
DOCUMENT_POSITION_DISCONNECTED:1
DOCUMENT_POSITION_PRECEDING:2
DOCUMENT_POSITION_FOLLOWING:4
DOCUMENT_POSITION_CONTAINS:8
DOCUMENT_POSITION_CONTAINED_BY:16
DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC:32
appendChild:(){...}
cloneNode:(){...}
compareDocumentPosition:(){...}
contains:(){...}
getRootNode:(){...}
hasChildNodes:(){...}
insertBefore:(){...}
isDefaultNamespace:(){...}
isEqualNode:(){...}
isSameNode:(){...}
lookupNamespaceURI:(){...}
lookupPrefix:(){...}
normalize:(){...}
removeChild:(){...}
replaceChild:(){...}
addEventListener:(){...}
dispatchEvent:(){...}
removeEventListener:(){...}
__proto__:`

text = text.split('\n')

console.log(text)