Translation.addTranslation("String Bag", {ru: "Авоська"});
Translation.addTranslation("Strap", {ru: "Ремень"});
Translation.addTranslation("Accumulator", {ru: "Аккумулятор"});
Translation.addTranslation("Lead Plate", {ru: "Свинцовая Пластина"});
Translation.addTranslation("Battery: Planet-2", {ru: "Батарейка: Планета-2"});
Translation.addTranslation("Low Block Of The Unit", {ru: "Нижний Блок Аппарата ГазВоды"});
Translation.addTranslation("High Block Of The Unit", {ru: "Верхний Блок Аппарата ГазВоды"});
Translation.addTranslation("Game", {ru: "Игровая Приставка"});
Translation.addTranslation("SGS", {ru: "ППШ"});
Translation.addTranslation("AK Bullets", {ru: "Патроны к АК"});
Translation.addTranslation("SGS Bullets", {ru: "Патроны к ППШ"});
Translation.addTranslation("Sickle", {ru: "Серп"});
Translation.addTranslation("Hammer", {ru: "Молот"});
Translation.addTranslation("Bar Mars", {ru: "Батончик Марс"});
Translation.addTranslation("Galss Of Coca-Cola", {ru: "Стакан Кока-Колы"});
Translation.addTranslation("Glass Of Water", {ru: "Стакан Газированной Воды"});
Translation.addTranslation("Burning Machine", {ru: "Выжигатель"});
Translation.addTranslation("Plank", {ru: "Доска"});
Translation.addTranslation("Plank With Sickle And Hammer", {ru: "Доска С Серпом И Молотом"});
Translation.addTranslation("Plank With Star", {ru: "Доска Со Звездой"});
Translation.addTranslation("Plank With Tank", {ru: "Доска С Танком"});
Translation.addTranslation("Glass", {ru: "Стакан"});
Translation.addTranslation("Pin", {ru: "Значок"});
Translation.addTranslation("Low Block Of The Sneck Apparatus", {ru: "Нижний Блок Снекового Аппарата"});
Translation.addTranslation("High Block Of The Sneck Apparatus", {ru: "Верхний Блок Снекового Аппарата"});
Translation.addTranslation("50 Kopeks", {ru: "50 Копеек"});