//BLOCK
Translation.addTranslation("Rock Salt", {ja: "岩塩", ru: "Каменная соль", zh: "矿盐"});
Translation.addTranslation("Vanilla Flower", {ja: "バニラの花", ru: "Ванильный цветок", zh: "香草花"});
Translation.addTranslation("Chocolate Cake", {ja: "チョコケーキ", ru: "Шоколадный торт", zh: "巧克力蛋糕"});
Translation.addTranslation("Chocolate Cookie Cake", {ja: "チョコレートクッキーケーキ", ru: "Торт из шоколадного печенья", zh: "巧克力曲奇蛋糕"});
Translation.addTranslation("Cheese Cake", {ja: "チーズケーキ", ru: "Сырный торт", zh: "奶酪蛋糕"});
Translation.addTranslation("Nether Cake", {ja: "ネザーケーキ", ru: "Адский торт", zh: "下界蛋糕"});
Translation.addTranslation("Strawberry Cake", {ja: "ストロベリーケーキ", ru: "Клубничный торт", zh: "草莓蛋糕"});
Translation.addTranslation("Pumpkin Cake", {ja: "パンプキンケーキ", ru: "Тыквенный торт", zh: "南瓜蛋糕"});
Translation.addTranslation("Pizza", {ja: "ピザ", ru: "Пицца", zh: "披萨"});

//ITEM
Translation.addTranslation("Rice", {ja: "米", ru: "Рис", zh: "稻米"});
Translation.addTranslation("Butter Rice", {ja: "バターライス", ru: "Масляный рис", zh: "黄油拌饭"});
Translation.addTranslation("Fried Rice", {ja: "チャーハン", ru: "Жареный рис", zh: "炒饭"});
Translation.addTranslation("Pepper Seeds", {ja: "コショウの種", ru: "Перцовые семена", zh: "胡椒籽"});
Translation.addTranslation("Pepper", {ja: "コショウ", ru: "Перец", zh: "胡椒"});
Translation.addTranslation("Corn Seeds", {ja: "トウモロコシの種", ru: "Семена кукурузы", zh: "玉米种子"});
Translation.addTranslation("Raw Corn", {ja: "生のトウモロコシ", ru: "Сырая кукуруза", zh: "生玉米"});
Translation.addTranslation("Corn", {ja: "トウモロコシ", ru: "Кукуруза", zh: "熟玉米"});
Translation.addTranslation("Cucumber Seeds", {ja: "キュウリの種", ru: "Семена огурцов", zh: "黄瓜种子"});
Translation.addTranslation("Cucumber", {ja: "キュウリ", ru: "Огурец", zh: "黄瓜"});
Translation.addTranslation("Lettuce Seeds", {ja: "レタスの種", ru: "Семена салата", zh: "生菜种子"});
Translation.addTranslation("Lettuce", {ja: "レタス", ru: "Салат", zh: "生菜"});
Translation.addTranslation("Onion", {ja: "タマネギ", ru: "Лук", zh: "洋葱"});
Translation.addTranslation("Tomato Seeds", {ja: "トマトの種", ru: "Семена томатов", zh: "番茄种子"});
Translation.addTranslation("Tomato", {ja: "トマト", ru: "Томат", zh: "番茄"});
Translation.addTranslation("Strawberry Seeds", {ja: "イチゴの種", ru: "Клубничные семена", zh: "草莓种子"});
Translation.addTranslation("Strawberry", {ja: "イチゴ", ru: "Клубника", zh: "草莓"});
Translation.addTranslation("Lemon Seeds", {ja: "レモンの種", ru: "Семена лимона", zh: "柠檬籽"});
Translation.addTranslation("Lemon", {ja: "レモン", ru: "Лимон", zh: "柠檬"});
Translation.addTranslation("Pineapple Seeds", {ja: "パイナップルの種", ru: "Семена ананаса", zh: "菠萝种子"});
Translation.addTranslation("Pineapple", {ja: "パイナップル", ru: "Ананас", zh: "菠萝"});
Translation.addTranslation("Salt", {ja: "塩", ru: "Соль", zh: "盐"});
Translation.addTranslation("Dough", {ja: "生地", ru: "Тесто", zh: "生面团"});
Translation.addTranslation("Cooked Dough", {ja: "焼いた生地", ru: "Приготовленное тесто", zh: "熟面团"});
Translation.addTranslation("Crouton", {ja: "クルトン", ru: "Сухарик", zh: "油炸面包丁"});

Translation.addTranslation("Butter", {ja: "バター", ru: "Масло", zh: "黄油"});
Translation.addTranslation("Cheese", {ja: "チーズ", ru: "Сыр", zh: "奶酪"});
Translation.addTranslation("Cheese Puff", {ja: "チーズパフ", ru: "Сырный шарик", zh: "奶酪泡芙"});
Translation.addTranslation("Chips", {ja: "チップス", ru: "Чипсы", zh: "薯片"});
Translation.addTranslation("Salty Chips", {ja: "塩辛いチップス", ru: "Соленые чипсы", zh: "咸薯片"});
Translation.addTranslation("Spicy Chips", {ja: "辛いチップス", ru: "Пряные чипсы", zh: "香辣薯片"});
Translation.addTranslation("Onion Rings", {ja: "オニオンリング", ru: "Луковые кольца", zh: "洋葱圈"});
Translation.addTranslation("Cheesy Bread", {ja: "チーズパン", ru: "Сырный хлеб", zh: "奶酪面包"});
Translation.addTranslation("Potato Bread", {ja: "ジャガイモパン", ru: "Картофельный хлеб", zh: "土豆面包"});
Translation.addTranslation("Corn Bread", {ja: "トウモロコシパン", ru: "Кукурузный хлеб", zh: "玉米面包"});
Translation.addTranslation("Rice Bread", {ja: "米粉パン", ru: "Рисовый хлеб", zh: "大米面包"});
Translation.addTranslation("Baguette", {ja: "バゲット", ru: "Багет", zh: "法棍面包"});
Translation.addTranslation("Fried Egg", {ja: "目玉焼き", ru: "Яичница", zh: "煎鸡蛋"});
Translation.addTranslation("Pancake", {ja: "パンケーキ", ru: "Блин", zh: "煎饼"});
Translation.addTranslation("Waffle", {ja: "ワッフル", ru: "Вафля", zh: "华夫饼"});
Translation.addTranslation("Macaroni and Cheese", {ja: "マカロニとチーズ", ru: "Макароны с сыром", zh: "奶酪通心粉"});
Translation.addTranslation("Spaghetti", {ja: "スパゲッティ", ru: "Спагетти", zh: "意大利面"});
Translation.addTranslation("Enchilada", {ja: "エンチラーダ", ru: "Энчилада", zh: "香辣玉米卷饼"});
Translation.addTranslation("Lasagne", {ja: "ラザニア", ru: "Лазанья", zh: "千层面"});
Translation.addTranslation("Jambon-Beurre", {ja: "ジャンボン-ブゥール", ru: "Сэндвич с ветчиной из багета", zh: "黄油火腿"});
Translation.addTranslation("Flesh", {ja: "肉", ru: "Приготовленная плоть", zh: "肉"});

Translation.addTranslation("Ham", {ja: "ハム", ru: "Окорок", zh: "火腿"});
Translation.addTranslation("Sausage", {ja: "ソーセージ", ru: "Сосиска", zh: "香肠"});
Translation.addTranslation("Bacon", {ja: "ベーコン", ru: "Бекон", zh: "培根"});
Translation.addTranslation("Beef Jerky", {ja: "ビーフジャーキー", ru: "Вяленая говядина", zh: "牛肉干"});
Translation.addTranslation("Ground Beef", {ja: "牛のひき肉", ru: "Говяжий фарш", zh: "牛肉馅"});
Translation.addTranslation("Raw Chicken Wing", {ja: "生の手羽先", ru: "Сырое куриное крылышко", zh: "生鸡翅"});
Translation.addTranslation("Cooked Chicken Wing", {ja: "焼き手羽先", ru: "Приготовленное куриное крылышко", zh: "熟鸡翅"});
Translation.addTranslation("Spicy Chicken Wing", {ja: "辛い手羽先", ru: "Пряное куриное крылышко", zh: "香辣鸡翅"});
Translation.addTranslation("Bucket of Fried Chicken", {ja: "フライドチキン入りバケツ", ru: "Ведро жареной курицы", zh: "炸鸡桶"});
Translation.addTranslation("Top Bun", {ja: "上のバンズパン", ru: "Верх булки для гамбургера", zh: "顶部的汉堡面包"});
Translation.addTranslation("Bottom Bun", {ja: "底のバンズパン", ru: "Низ булки для гамбургера", zh: "底部的汉堡面包"});
Translation.addTranslation("Hamburger", {ja: "ハンバーガー", ru: "Гамбургер", zh: "牛肉汉堡"});
Translation.addTranslation("Chicken Burger", {ja: "チキンバーガー", ru: "Чикенбургер", zh: "鸡肉汉堡"});
Translation.addTranslation("Cheeseburger", {ja: "チーズバーガー", ru: "Чизбургер", zh: "奶酪汉堡"});
Translation.addTranslation("Hot Dog", {ja: "ホットドッグ", ru: "Хот-дог", zh: "热狗"});
Translation.addTranslation("Sausage Roll", {ja: "ソーセージロール", ru: "Сосиска в тесте", zh: "香肠卷"});
Translation.addTranslation("Slice of Pizza", {ja: "切り分けたピザ", ru: "Кусочек пиццы", zh: "披萨切片"});
Translation.addTranslation("Tortilla", {ja: "トルティーヤ", ru: "Тортилья", zh: "玉米饼"});
Translation.addTranslation("Taco", {ja: "タコス", ru: "Тако", zh: "塔可"});
Translation.addTranslation("Burrito", {ja: "ブリート", ru: "Буррито", zh: "墨西哥卷饼"});
Translation.addTranslation("Kebab", {ja: "ケバブ", ru: "Кебаб", zh: "牛肉卷饼"});

Translation.addTranslation("Chicken Sandwich", {ja: "チキンサンド", ru: "Куриный сендвич", zh: "鸡肉三明治"});
Translation.addTranslation("BLT Sandwich", {ja: "BLTサンドイッチ", ru: "Сэндвич с беконом, салатом и томатами", zh: "英式传统三明治"});
Translation.addTranslation("Breakfast Sandwich", {ja: "朝食のサンドイッチ", ru: "Сэндвич на завтрак", zh: "早餐三明治"});
Translation.addTranslation("Grilled Cheese Sandwich", {ja: "グリルチーズサンドイッチ", ru: "Сырный сэндвич", zh: "烤奶酪三明治"});
Translation.addTranslation("Ice Cream Sandwich", {ja: "アイスクリームサンドイッチ", ru: "Сэндвич с мороженым", zh: "冰淇淋三明治"});
Translation.addTranslation("Seaweed", {ja: "海藻", ru: "Водоросли", zh: "熟海草"});
Translation.addTranslation("Futomaki", {ja: "太巻き", ru: "Футомаки", zh: "大太卷寿司"});
Translation.addTranslation("Uramaki", {ja: "裏巻", ru: "Урамаки", zh: "反卷寿司"});
Translation.addTranslation("Oshizushi", {ja: "押し寿司", ru: "Оши-суши", zh: "押寿司"});
Translation.addTranslation("Bowl", {ja: "ボウル", ru: "Миска", zh: "碗"});
Translation.addTranslation("Garden Salad", {ja: "グリーンサラダ", ru: "Садовый салат", zh: "田园沙拉"});
Translation.addTranslation("Chicken Salad", {ja: "チキンサラダ", ru: "Куриный салат", zh: "鸡肉沙拉"});
Translation.addTranslation("Caesar Salad", {ja: "シーザーサラダ", ru: "Салат Цезарь", zh: "凯撒沙拉"});
Translation.addTranslation("Onion Salad", {ja: "オニオンサラダ", ru: "Луковый салат", zh: "洋葱沙拉"});
Translation.addTranslation("Taco Salad", {ja: "タコサラダ", ru: "Тако салат", zh: "玉米饼沙拉"});
Translation.addTranslation("Cucumber Soup", {ja: "キュウリのスープ", ru: "Огуречный суп", zh: "黄瓜汤"});
Translation.addTranslation("Tomato Soup", {ja: "トマトスープ", ru: "Томатный суп", zh: "番茄汤"});
Translation.addTranslation("Vegetable Soup", {ja: "野菜スープ", ru: "Овощной суп", zh: "蔬菜汤"});
Translation.addTranslation("Chicken Soup", {ja: "チキンスープ", ru: "Куриный суп", zh: "鸡汤"});
Translation.addTranslation("Beef Stew", {ja: "ビーフシチュー", ru: "Тушеная говядина", zh: "炖牛肉"});
Translation.addTranslation("Pumpkin Stew", {ja: "カボチャのシチュー", ru: "Тушеная тыква", zh: "南瓜盅"});

Translation.addTranslation("Caramel Apple", {ja: "キャラメルアップル", ru: "Карамельное яблоко", zh: "焦糖苹果"});
Translation.addTranslation("Marshmallow", {ja: "マシュマロ", ru: "Зефир", zh: "棉花糖"});
Translation.addTranslation("Roasted Marshmallow", {ja: "ローストマシュマロ", ru: "Жареный зефир", zh: "烤棉花糖"});
Translation.addTranslation("Chocolate Cookie", {ja: "チョコレートクッキー", ru: "Шоколадное печенье", zh: "巧克力饼干"});
Translation.addTranslation("Vanilla Cookie", {ja: "バニラクッキー", ru: "Ванильное печенье", zh: "香草奶油夹心饼干"});
Translation.addTranslation("Brownie", {ja: "ブラウニー", ru: "Брауни", zh: "布朗巧克力饼干"});
Translation.addTranslation("Bourbon Biscuit", {ja: "バーボンビスケット", ru: "Бурбонское печенье", zh: "巧克力夹心饼干"});
Translation.addTranslation("Chocolate", {ja: "チョコレート", ru: "Шоколад", zh: "巧克力"});
Translation.addTranslation("Chocolate Ice Cream Ball", {ja: "チョコレートアイスクリームボール", ru: "Шоколадный мороженый шарик", zh: "巧克力冰淇淋球"});
Translation.addTranslation("Vanilla Ice Cream Ball", {ja: "バニラアイスクリームボール", ru: "Ванильный мороженый шарик", zh: "香草冰淇淋球"});
Translation.addTranslation("Strawberry Ice Cream Ball", {ja: "ストロベリーアイスクリームボール", ru: "Клубничный мороженый шарик", zh: "草莓冰淇淋球"});
Translation.addTranslation("Ice Cream Cone", {ja: "アイスクリームコーン", ru: "Рожок мороженого", zh: "冰淇淋蛋卷"});
Translation.addTranslation("Chocolate Ice Cream", {ja: "チョコレートアイスクリーム", ru: "Шоколадное мороженое", zh: "巧克力冰淇淋"});
Translation.addTranslation("Vanilla Ice Cream", {ja: "バニラアイスクリーム", ru: "Ванильное мороженое", zh: "香草冰淇淋"});
Translation.addTranslation("Strawberry Ice Cream", {ja: "ストロベリーアイスクリーム", ru: "Клубничное мороженое", zh: "草莓冰淇淋"});
Translation.addTranslation("Crescent Roll", {ja: "クレセントロール", ru: "Рогалик", zh: "牛角面包"});
Translation.addTranslation("Donut", {ja: "ドーナツ", ru: "Пончик", zh: "甜甜圈"});
Translation.addTranslation("Sugar Donut", {ja: "シュガードーナツ", ru: "Сахарный пончик", zh: "糖霜甜甜圈"});
Translation.addTranslation("Chocolate Donut", {ja: "チョコレートドーナツ", ru: "Шоколадный пончик", zh: "巧克力甜甜圈"});
Translation.addTranslation("Vanilla Donut", {ja: "バニラドーナツ", ru: "Ванильный пончик", zh: "香草甜甜圈"});
Translation.addTranslation("Paper Cup", {ja: "紙コップ", ru: "Бумажный стакан", zh: "纸杯"});

Translation.addTranslation("Vanilla Cupcake", {ja: "バニラカップケーキ", ru: "Ванильный кекс", zh: "香草纸杯蛋糕"});
Translation.addTranslation("Chocolate Cupcake", {ja: "チョコレートカップケーキ", ru: "Шоколадный кекс", zh: "巧克力纸杯蛋糕"});
Translation.addTranslation("Chocolate Cookie Cupcake", {ja: "チョコレートクッキーカップケーキ", ru: "Кекс из шоколаного печенья", zh: "巧克力饼干纸杯蛋糕"});
Translation.addTranslation("Strawberry Cupcake", {ja: "ストロベリーカップケーキ", ru: "Клубничный кекс", zh: "草莓纸杯蛋糕"});
Translation.addTranslation("Pie Shell", {ja: "パイシェル", ru: "Корж пирога", zh: "馅饼皮"});
Translation.addTranslation("Apple Pie", {ja: "アップルパイ", ru: "Яблочный пирог", zh: "苹果派"});
Translation.addTranslation("Golden Apple Pie", {ja: "金のアップルパイ", ru: "Золотой яблочный пирог", zh: "金苹果派"});
Translation.addTranslation("Cheese Pie", {ja: "チーズパイ", ru: "Сырный пирог", zh: "奶酪派"});
Translation.addTranslation("Chicken Pot Pie", {ja: "チキンポットパイ", ru: "Горшечный куриный пирог", zh: "鸡肉派"});
Translation.addTranslation("Chocolate Pie", {ja: "チョコレートパイ", ru: "Шоколадный пирог", zh: "巧克力派"});
Translation.addTranslation("Bacon Pie", {ja: "ベーコンパイ", ru: "Пирог с беконом", zh: "培根派"});
Translation.addTranslation("Fish Pie", {ja: "フィッシュパイ", ru: "Рыбный пирог", zh: "仰望星空派"});
Translation.addTranslation("Strawberry Pie", {ja: "ストロベリーパイ", ru: "Клубничный пирог", zh: "草莓派"});
Translation.addTranslation("Tomato Sauce", {ja: "トマトソース", ru: "Томатный соус", zh: "番茄酱"});
Translation.addTranslation("Hot Sauce", {ja: "ホットソース", ru: "Острый соус", zh: "辣酱"});
Translation.addTranslation("Chocolate Syrup", {ja: "チョコレートシロップ", ru: "Шоколадный сироп", zh: "巧克力酱"});
Translation.addTranslation("Vanilla Extract", {ja: "バニラの抽出物", ru: "Экстракт ванили", zh: "香草精"});
Translation.addTranslation("Vanilla Cream", {ja: "バニラクリーム", ru: "Ванильный крем", zh: "香草奶油"});
Translation.addTranslation("Empty Can", {ja: "空の缶", ru: "Пустая банка", zh: "空罐"});
Translation.addTranslation("Speedy Energy Drink", {ja: "スピーディエナジードリンク", ru: "Скоростной энергетический напиток", zh: "极速能量饮料"});
Translation.addTranslation("Healthy Energy Drink", {ja: "健康的なエネルギードリンク", ru: "Здоровый энергетический напиток", zh: "健康能量饮料"});

Translation.addTranslation("Stealthy Energy Drink", {ja: "ステルスエネルギードリンク", ru: "Скрытый энергетический напиток", zh: "隐身能量饮料"});
Translation.addTranslation("Strong Energy Drink", {ja: "強いエネルギードリンク", ru: "Сильный энергетический напиток", zh: "强壮能量饮料"});
Translation.addTranslation("Deadly Energy Drink", {ja: "命にかかわるエネルギードリンク", ru: "Смертельный энергетический напиток", zh: "致命能量饮料"});
Translation.addTranslation("Super Energy Drink", {ja: "スーパーエナジードリンク", ru: "Супер энергетический напиток", zh: "超级能量饮料"});
Translation.addTranslation("Glass Mug", {ja: "ガラスのマグカップ", ru: "Стеклянная кружка", zh: "玻璃杯"});
Translation.addTranslation("Beer", {ja: "ビール", ru: "Пиво", zh: "啤酒"});
Translation.addTranslation("Coffee Cup", {ja: "コーヒーカップ", ru: "Кофейная чашка", zh: "咖啡杯"});
Translation.addTranslation("Coffee", {ja: "コーヒー", ru: "Кофе", zh: "咖啡"});
Translation.addTranslation("Cappuccino", {ja: "カプチーノ", ru: "Капучино", zh: "卡布奇诺"});
Translation.addTranslation("Lemonade", {ja: "レモネード", ru: "Лимонад", zh: "柠檬水"});
Translation.addTranslation("Strawberry Juice", {ja: "イチゴジュース", ru: "Клубничный сок", zh: "草莓汁"});
Translation.addTranslation("Pineapple Juice", {ja: "パイナップルジュース", ru: "Ананасовый сок", zh: "菠萝汁"});
Translation.addTranslation("Lemon Syrup", {ja: "レモンシロップ", ru: "Лимонный сироп", zh: "柠檬糖浆"});
Translation.addTranslation("Strawberry Syrup", {ja: "イチゴシロップ", ru: "Клубничный сироп", zh: "草莓糖浆"});
Translation.addTranslation("Pineapple Syrup", {ja: "パイナップルシロップ", ru: "Ананасовый сироп", zh: "菠萝糖浆"});
Translation.addTranslation("Lemonade Slushie", {ja: "レモンスラッシー", ru: "Лимонная слякоть", zh: "柠檬泥"});
Translation.addTranslation("Strawberry Slushie", {ja: "イチゴスラッシー", ru: "Клубничная слякоть", zh: "草莓泥"});
Translation.addTranslation("Pineapple Slushie", {ja: "パイナップルスラッシー", ru: "Ананасовый сладкий", zh: "凤梨酥"});

//CATEGORY
Translation.addTranslation("XL-Items", {ja: "XL-アイテム", ru: "XL-Предметы", zh: "XL-项目"});
Translation.addTranslation("XL-Foods", {ja: "XL-食べ物", ru: "XL-Еда", zh: "XL-食品"});
Translation.addTranslation("XL-Seeds", {ja: "XL-種", ru: "XL-Семена", zh: "XL-种子"});