ShootLib.addGun({
    id:"pm",
    name:"PM",
    ammo:"ammohandgun",
    accuracy:6,
    recoil:4,
    rate:10,
    texture:{
        name:"pm",
        meta:0
    },
    shotType:ShotType.NORMAL,
    buttonType:ButtonType.CLICK,
    bullet:{
        speed:10,
        count:8,
        damage:5
    },
    fov:{
        level:2
    },
    sounds:{
        shot:"pm/shot.ogg",
        empty:"EmptyGun.mp3",
        reload:"pm/reload.ogg"
    }
});
Callback.addCallback("GunsDefined", function(){
    RecipeTE.addGridRecipe("guns_workbench", "pm", ["ip"], {i:{id:265}, "p":{id:ItemID["pistol_base"]}}, GUN_PRODUCTION_TIME);
})