IMPORT("ToolType");
Ace3.addItem("emerald_sword", "Emerald Sword", {name: "EmeraldSword", meta: 0}, {stack: 1});
Ace3.addItem("emerald_pickaxe", "Emerald Pickaxe", {name: "EmeraldPickaxe", meta: 0}, {stack: 1});
Ace3.addItem("emerald_axe", "Emerald Axe", {name: "EmeraldAxe", meta: 0}, {stack: 1});
Ace3.addItem("emerald_shovel", "Emerald Shovel", {name: "EmeraldShovel", meta: 0}, {stack: 1});
Ace3.addItem("emerald_hoe", "Emerald Hoe", {name: "EmeraldHoe", meta: 0}, {stack: 1});
Ace3.addItem("emerald_katana", "Emerald Katana", {name: "EmeraldKatana", meta: 0}, {stack: 1});
Ace3.addItem("big_emerald_sword", "Big Emerald Sword", {name: "BigEmeraldSword", meta: 0}, {stack: 1});
Ace3.addItem("emerald_khopesh", "Emerald Khopesh", {name: "EmeraldKhopesh", meta: 0}, {stack: 1});
Ace3.addItem("emerald_battleaxe", "Emerald Battleaxe", {name: "EmeraldBattleaxe", meta: 0}, {stack: 1});
ToolAPI.addToolMaterial("emerald", {durability: 2345, level: 3, efficiency: 6, damage: 8.5, enchantability: 14});
var MBig_emerald_sword = {durability: 2345, level: 3, efficiency: 6, damage: 15, enchantability: 14};
var MEmerald_katana = {durability: 2345, level: 3, efficiency: 6, damage: 12, enchantability: 14};
var MEmerald_khopesh = {durability: 2345, level: 3, efficiency: 6, damage: 13, enchantability: 14};
var MEmerald_battleaxe = {durability: 2345, level: 3, efficiency: 6, damage: 11, enchantability: 14};
ToolAPI.setTool(ItemID.emerald_sword, "emerald", ToolType.sword);
ToolAPI.setTool(ItemID.emerald_pickaxe, "emerald", ToolType.pickaxe);
ToolAPI.setTool(ItemID.emerald_axe, "emerald", ToolType.axe);
ToolAPI.setTool(ItemID.emerald_shovel, "emerald", ToolType.shovel);
ToolAPI.setTool(ItemID.emerald_hoe, "emerald", ToolType.hoe);
ToolAPI.setTool(ItemID.big_emerald_sword, MBig_emerald_sword, ToolType.sword);
ToolAPI.setTool(ItemID.emerald_katana, MEmerald_katana, ToolType.sword);
ToolAPI.setTool(ItemID.emerald_khopesh, MEmerald_khopesh, ToolType.sword);
ToolAPI.setTool(ItemID.emerald_battleaxe, MEmerald_battleaxe, ToolType.sword);

