IDRegistry.genItemID("drawingATmega2560");
Item.createItem("drawingATmega2560", "ATmega2560 Chip Drawing", {name: "drawing_atmega_2560"});
IDRegistry.genItemID("drawingATmega328");
Item.createItem("drawingATmega328", "ATmega328 Chip Drawing", {name: "drawing_atmega_328"});
IDRegistry.genItemID("drawingChipRaspberry");
Item.createItem("drawingChipRaspberry", "Raspberry PI Central Chip Drawing", {name: "drawing_chip_raspberry"});
IDRegistry.genItemID("drawingChipset");
Item.createItem("drawingChipset", "Chipset Drawing", {name: "drawing_chipset"});
IDRegistry.genItemID("drawingCpu");
Item.createItem("drawingCpu", "CPU Drawing", {name: "drawing_cpu"});
IDRegistry.genItemID("drawingChipRam");
Item.createItem("drawingChipRam", "RAM Chip Drawing", {name: "drawing_chip_ram"});
IDRegistry.genItemID("drawingChipVideo");
Item.createItem("drawingChipVideo", "Video Chip Drawing", {name: "drawing_chip_video"});
IDRegistry.genItemID("drawingChipGeneratorSpaceTime");
Item.createItem("drawingChipGeneratorSpaceTime", "Space-Time Frequency Generator Chip Drawing", {name: "drawing_chip_generator_space_time"});
IDRegistry.genItemID("drawingPcbArduinoMega");
Item.createItem("drawingPcbArduinoMega", "Arduino Mega PCB Drawing", {name: "drawing_pcb_arduino_mega"});
IDRegistry.genItemID("drawingPcbArduinoUno");
Item.createItem("drawingPcbArduinoUno", "Arduino Uno PCB Drawing", {name: "drawing_pcb_arduino_uno"});
IDRegistry.genItemID("drawingPcbRaspberry3");
Item.createItem("drawingPcbRaspberry3", "Raspberry PI 3 PCB Drawing", {name: "drawing_pcb_raspberry"});
IDRegistry.genItemID("drawingPcbMotherboard");
Item.createItem("drawingPcbMotherboard", "Motherboard PCB Drawing", {name: "drawing_pcb_motherboard"});
IDRegistry.genItemID("drawingPcbPowerSupply");
Item.createItem("drawingPcbPowerSupply", "Power Supply PCB Drawing", {name: "drawing_pcb_power_supply"});
IDRegistry.genItemID("drawingPcbRam");
Item.createItem("drawingPcbRam", "RAM PCB Drawing", {name: "drawing_pcb_ram"});
IDRegistry.genItemID("drawingPcbCardVideo");
Item.createItem("drawingPcbCardVideo", "Video Card PCB Drawing", {name: "drawing_pcb_card_video"});
IDRegistry.genItemID("drawingPcbControllerHdd");
Item.createItem("drawingPcbControllerHdd", "HDD Controller PCB Drawing", {name: "drawing_pcb_controller_hdd"});
IDRegistry.genItemID("pressFormPlate");
Item.createItem("pressFormPlate", "Plate Press Form", {name: "press_form", meta: 0}, {});
IDRegistry.genItemID("pressFormBlade");
Item.createItem("pressFormBlade", "Blade Press Form", {name: "press_form_blade", meta: 0}, {});
IDRegistry.genItemID("pressFormRadiator");
Item.createItem("pressFormRadiator", "Radiator Press Form", {name: "press_form_radiator", meta: 0}, {});
IDRegistry.genItemID("pressFormRod");
Item.createItem("pressFormRod", "Rod Press Form", {name: "press_form_rod", meta: 0}, {});
IDRegistry.genItemID("pressFormRoller");
Item.createItem("pressFormRoller", "Roller Press Form", {name: "press_form_roller", meta: 0}, {});

