IDRegistry.genItemID("silver");
Item.createItem("silver", "Silver", {name: "silver", meta: 0}, {});
IDRegistry.genItemID("waste");
Item.createItem("waste", "Waste", {name: "waste", meta: 0}, {});
IDRegistry.genItemID("dustQuartz");
Item.createItem("dustQuartz", "Quartz Dust", {name: "dust_quartz", meta: 0}, {});
IDRegistry.genItemID("bitumen");
Item.createItem("bitumen", "Bitumen", {name: "bitumen", meta: 0}, {});
IDRegistry.genItemID("propylene");
Item.createItem("propylene", "Propylene", {name: "propylene", meta: 0}, {});
IDRegistry.genItemID("oilResin");
Item.createItem("oilResin", "Oil Resin", {name: "oil_resin", meta: 0}, {});
IDRegistry.genItemID("oilFuel");
Item.createItem("oilFuel", "Fuel Oil", {name: "oil_fuel", meta: 0}, {});
Recipes.addFurnaceFuel(ItemID.oilFuel, 0, 1000);
IDRegistry.genItemID("petrol");
Item.createItem("petrol", "Petrol", {name: "petrol", meta: 0}, {});
Recipes.addFurnaceFuel(ItemID.petrol, 0, 3000);
IDRegistry.genItemID("kerosene");
Item.createItem("kerosene", "Kerosene", {name: "kerosene", meta: 0}, {});
Recipes.addFurnaceFuel(ItemID.kerosene, 0, 3000);
IDRegistry.genItemID("tarCoal");
Item.createItem("tarCoal", "Coal Tar", {name: "tar_coal", meta: 0}, {});
IDRegistry.genItemID("coke");
Item.createItem("coke", "Coke", {name: "coke", meta: 0}, {});
Recipes.addFurnaceFuel(ItemID.coke, 0, 2000);
IDRegistry.genItemID("threadGlass");
Item.createItem("threadGlass", "Glass Thread", {name: "thread_glass", meta: 0}, {});
IDRegistry.genItemID("fiberglass");
Item.createItem("fiberglass", "Fiberglass", {name: "fiberglass", meta: 0}, {});
RecipesManager.addShaped({id: ItemID.fiberglass, count: 1, data: 0}, ["aaa", "aaa", "aaa"], ["a", ItemID.threadGlass, 0]);
IDRegistry.genItemID("textolite");
Item.createItem("textolite", "Textolite", {name: "textolite", meta: 0}, {});
RecipesManager.addShaped({id: ItemID.textolite, count: 2, data: 0}, ["aaa", "bbb", "aaa"], ["a", ItemID.fiberglass, 0, "b", ItemID.tarCoal, 0]);
RecipesManager.addShaped({id: ItemID.textolite, count: 2, data: 0}, ["aaa", "bbb", "aaa"], ["a", ItemID.fiberglass, 0, "b", ItemID.oilResin, 0]);
IDRegistry.genItemID("textoliteFoil");
Item.createItem("textoliteFoil", "Foil Textolite", {name: "textolite_foil", meta: 0}, {});
RecipesManager.addShaped({id: ItemID.textoliteFoil, count: 3, data: 0}, ["aaa", "bbb", "aaa"], ["a", ItemID.plateCopper, 0, "b", ItemID.textolite, 0]);
IDRegistry.genItemID("granulesPolypropylene");
Item.createItem("granulesPolypropylene", "Granules of Polypropylene", {name: "granules_polypropylene", meta: 0}, {});
IDRegistry.genItemID("platePolypropylene");
Item.createItem("platePolypropylene", "Polypropylene Plate", {name: "plate_polypropylene", meta: 0}, {});
IDRegistry.genItemID("bladePolypropylene");
Item.createItem("bladePolypropylene", "Polypropylene Blade", {name: "blade_polypropylene", meta: 0}, {});
IDRegistry.genItemID("casingPolypropylene");
Item.createItem("casingPolypropylene", "Polypropylene Casing", {name: "casing_polypropylene", meta: 0}, {});
RecipesManager.addShaped({id: ItemID.casingPolypropylene, count: 3, data: 0}, ["aa", "aa", "aa"], ["a", ItemID.platePolypropylene, 0]);
IDRegistry.genItemID("lineAssembly");
Item.createItem("lineAssembly", "Assembly Line", {name: "line_assembly", meta: 0}, {});
RecipesManager.addShaped({id: ItemID.lineAssembly, count: 1, data: 0}, ["aaa", "b b"], ["a", ItemID.plateIron, 0, "b", ItemID.roller, 0]);
IDRegistry.genItemID("chopper");
Item.createItem("chopper", "Chopper", {name: "chopper", meta: 0}, {});
RecipesManager.addShaped({id: ItemID.chopper, count: 0, data: 0}, [" a ", "a a", " a "], ["a", 265, 0]);
Callback.addCallback("ICore", function (api) {
    RecipesManager.addShaped({id: ItemID.scrap, count: 1, data: 0}, ["aaa", "aaa", "aaa"], ["a", ItemID.waste, 0]);
});
IDRegistry.genItemID("silicon");
Item.createItem("silicon", "Silicon", {name: "silicon", meta: 0}, {});
RecipesManager.addShapeless({id: ItemID.silicon, count: 1, data: 0}, [{id: ItemID.magnesium, data: 0}, {id: 406, data: 0}]);
IDRegistry.genItemID("crystalSilicon");
Item.createItem("crystalSilicon", "Silicon Crystal", {name: "crystal_silicon", meta: 0}, {});

