IDRegistry.genItemID("xeonIngot");
Item.createItem("xeonIngot", "Xeon ingot", {name: "xeon"}, {});
IDRegistry.genItemID("axelIngot");
Item.createItem("axelIngot", "Axel ingot", {name: "axel"}, {});
importLib("ToolType", "*");
ToolAPI.addToolMaterial("xeon", {durability: 954, level: 4, efficiency: 10, damage: 2, enchantability: 14});
IDRegistry.genItemID("xeonSword");
Item.createItem("xeonSword", "Xeon sword", {name: "xeonSword"}, {stack: "1"});
ToolAPI.setTool(ItemID.xeonSword, "xeon", ToolType.sword);
IDRegistry.genItemID("xeonPickaxe");
Item.createItem("xeonPickaxe", "Xeon pickaxe", {name: "xeonPickaxe"}, {stack: "1"});
ToolAPI.setTool(ItemID.xeonPickaxe, "xeon", ToolType.pickaxe);
IDRegistry.genItemID("xeonAxe");
Item.createItem("xeonAxe", "Xeon axe", {name: "xeonAxe"}, {stack: "1"});
ToolAPI.setTool(ItemID.xeonAxe, "xeon", ToolType.axe);
IDRegistry.genItemID("xeonHoe");
Item.createItem("xeonHoe", "Xeon hoe", {name: "xeonHoe"}, {stack: "1"});
ToolAPI.setTool(ItemID.xeonHoe, "xeon", ToolType.hoe);
IDRegistry.genItemID("xeonShovel");
Item.createItem("xeonShovel", "Xeon shovel", {name: "xeonShovel"}, {stack: "1"});
ToolAPI.setTool(ItemID.xeonShovel, "xeon", ToolType.shovel);
ToolAPI.addToolMaterial("axel", {durability: 425, level: 3, efficiency: 10, damage: 2, enchantability: 14});
IDRegistry.genItemID("axelSword");
Item.createItem("axelSword", "Axel sword", {name: "axelSword"}, {stack: "1"});
ToolAPI.setTool(ItemID.axelSword, "axel", ToolType.sword);
IDRegistry.genItemID("axelPickaxe");
Item.createItem("axelPickaxe", "Axel pickaxe", {name: "axelPickaxe"}, {stack: "1"});
ToolAPI.setTool(ItemID.axelPickaxe, "axel", ToolType.pickaxe);
IDRegistry.genItemID("axelAxe");
Item.createItem("axelAxe", "Axel axe", {name: "axelAxe"}, {stack: "1"});
ToolAPI.setTool(ItemID.axelAxe, "axel", ToolType.axe);
IDRegistry.genItemID("axelHoe");
Item.createItem("axelHoe", "Axel hoe", {name: "axelHoe"}, {stack: "1"});
ToolAPI.setTool(ItemID.axelHoe, "axel", ToolType.hoe);
IDRegistry.genItemID("axelShovel");
Item.createItem("axelShovel", "Axel shovel", {name: "axelShovel"}, {stack: "1"});
ToolAPI.setTool(ItemID.axelShovel, "axel", ToolType.shovel);
Recipes.addShaped({id: ItemID.xeonSword, count: 1, data: 0}, ["a", "a", "x"], ["x", 280, 0, "a", ItemID.xeonIngot, 0]);
Recipes.addShaped({id: ItemID.xeonPickaxe, count: 1, data: 0}, ["aaa", " x ", " x "], ["x", 280, 0, "a", ItemID.xeonIngot, 0]);
Recipes.addShaped({id: ItemID.xeonShovel, count: 1, data: 0}, ["a", "x", "x"], ["x", 280, 0, "a", ItemID.xeonIngot, 0]);
Recipes.addShaped({id: ItemID.xeonHoe, count: 1, data: 0}, ["aa", "x", "x"], ["x", 280, 0, "a", ItemID.xeonIngot, 0]);
Recipes.addShaped({id: ItemID.xeonAxe, count: 1, data: 0}, ["aa", "ax", " x"], ["x", 280, 0, "a", ItemID.xeonIngot, 0]);
Recipes.addShaped({id: ItemID.axelSword, count: 1, data: 0}, ["a", "a", "x"], ["x", 280, 0, "a", ItemID.axelIngot, 0]);
Recipes.addShaped({id: ItemID.axelPickaxe, count: 1, data: 0}, ["aaa", " x ", " x "], ["x", 280, 0, "a", ItemID.axelIngot, 0]);
Recipes.addShaped({id: ItemID.axelShovel, count: 1, data: 0}, ["a", "x", "x"], ["x", 280, 0, "a", ItemID.axelIngot, 0]);
Recipes.addShaped({id: ItemID.axelHoe, count: 1, data: 0}, ["aa", "x", "x"], ["x", 280, 0, "a", ItemID.axelIngot, 0]);
Recipes.addShaped({id: ItemID.axelAxe, count: 1, data: 0}, ["aa", "ax", " x"], ["x", 280, 0, "a", ItemID.axelIngot, 0]);

