//перевод я делаю всегда к релизу новой беты
//инструменты
Translation.addTranslation("Шипованная дубина", {en: "Studded cudgel"});
Translation.addTranslation("Ядовитая шипованная дубина", {en: "Poisoned studded cudgel"});
Translation.addTranslation("Нож с шипом древнего стража", {en: "Knife with a thorn of an ancient guard"});
Translation.addTranslation("Нож с шипом стража", {en: "Knife with a thorn of a guard"});
Translation.addTranslation("Стальная лопата", {en: "Steel shovel"});
Translation.addTranslation("Стальная кирка", {en: "Steel pickax"});
Translation.addTranslation("Стальной меч", {en: "Steel sword"});
Translation.addTranslation("Стальной топор", {en: "Steel axe"});
Translation.addTranslation("Стальная мотыга", {en: "Steel hoe"});
Translation.addTranslation("Деревянный метательный нож", {en: "Wooden throwing knife"});
Translation.addTranslation("Каменный метательный нож", {en: "Stone throwing knife"});
Translation.addTranslation("Кремниевый метательный нож", {en: "Silicon throwing knife"});
Translation.addTranslation("Золотой метательный нож", {en: "Golden throwing knife"});
Translation.addTranslation("Алмазный метательный нож", {en: "Diamond throwing knife"});
Translation.addTranslation("Стальной метательный нож", {en: "Steel throwing knife"});
Translation.addTranslation("Железный метательный нож", {en: "Iron throwing knife"});
Translation.addTranslation("Изумрудный метательный нож", {en: "Emerald throwing knife"});
Translation.addTranslation("Обсидиановый метательный нож", {en: "Obsidian throwing knife"});
Translation.addTranslation("Костяной метательный нож", {en: "Bone throwing knife"});
//предметы
Translation.addTranslation("Шип древнего стража", {en: "Thorn of an ancient guard"});
Translation.addTranslation("Кристалл магмы:заряженность-100(мин.)", {en: "Magma crystal:charging-100(min.)"});
Translation.addTranslation("Кристалл магмы:заряженность-400", {en: "Magma crystal:charging-400"});
Translation.addTranslation("Кристалл магмы:заряженность-700", {en: "Magma crystal:charging-700"});
Translation.addTranslation("Кристалл магмы:заряженность-1000", {en: "Magma crystal:charging-1000"});
Translation.addTranslation("Кристалл магмы:заряженность-1300", {en: "Magma crystal:charging-1300"});
Translation.addTranslation("Кристалл магмы:заряженность-1600(сред.)", {en: "Magma crystal:charging-1600(med.)"});
Translation.addTranslation("Кристалл магмы:заряженность-1900", {en: "Magma crystal:charging-1900"});
Translation.addTranslation("Кристалл магмы:заряженность-2200", {en: "Magma crystal:charging-2200"});
Translation.addTranslation("Кристалл магмы:заряженность-2500", {en: "Magma crystal:charging-2500"});
Translation.addTranslation("Кристалл магмы:заряженность-2800", {en: "Magma crystal:charging-2800"});
Translation.addTranslation("Кристалл магмы:заряженность-3100(макс.)", {en: "Magma crystal:charging-3100(max.)"});
Translation.addTranslation("Шип стража", {en: "Thorn of a guard"});
Translation.addTranslation("Камень", {en: "Rock"});
Translation.addTranslation("Алмазный самородок", {en: "Diamond nugget"});
Translation.addTranslation("Адский слиток", {en: "Hellish ingot"});
Translation.addTranslation("Порванная бумага", {en: "Torn paper"});
Translation.addTranslation("Сломанная палка", {en: "Broken stick"});
Translation.addTranslation("Сломанная стрела", {en: "Broken arrow"});
Translation.addTranslation("Железный самородок", {en: "Iron nugget"});
Translation.addTranslation("Сетка от просеивателя", {en: "Mesh of sifter"});
Translation.addTranslation("Создать утку", {en: "Create a duck"});
Translation.addTranslation("Создать кабана", {en: "Create a boar"});
Translation.addTranslation("Изумрудный самородок", {en: "Emerald nugget"});
Translation.addTranslation("Игла", {en: "Needle"});
Translation.addTranslation("Сердце дракона", {en: "Dragon heart"});
Translation.addTranslation("Осколок кремния", {en: "Fragment of silicon"});
Translation.addTranslation("Железная банка", {en: "Iron capacity"});
Translation.addTranslation("Кольчужное кольцо", {en: "Chain ring"});
Translation.addTranslation("Горсть песка", {en: "Handful of sand"});
Translation.addTranslation("Горсть гравия", {en: "Handful of gravel"});
Translation.addTranslation("Горсть земли", {en: "Handful of earth"});
Translation.addTranslation("Гнилая нить", {en: "Rotten thread"});
Translation.addTranslation("Старая ткань", {en: "Old cloth"});
Translation.addTranslation("Водяной фильтр", {en: "Water filter"});
Translation.addTranslation("Трава", {en: "Grass"});
Translation.addTranslation("Алмазный самородок", {en: "Diamond nugget"});
Translation.addTranslation("Катушка с нитями", {en: "Coil with threads"});
Translation.addTranslation("Обыкновенная веревка", {en: "Common rope"});
Translation.addTranslation("Травяная веревка", {en: "Grass rope"});
Translation.addTranslation("Зуб паука", {en: "Spider's teeth"});
Translation.addTranslation("Ядовитый зуб паука", {en: "Poisonous spider's teeth"});
Translation.addTranslation("Прочная ткань", {en: "Durable fabric"});
Translation.addTranslation("Гнилая кость", {en: "Rotten bone"});
Translation.addTranslation("Гнилая нить", {en: "Rotten thread"});
Translation.addTranslation("Травяная нить", {en: "Grass thread"});
Translation.addTranslation("Частица угля", {en: "Coal particle"});
Translation.addTranslation("Лоза", {en: "Vine"});
Translation.addTranslation("Медвежья шкура", {en: "Bear skin"});
Translation.addTranslation("Баллон с воздухом", {en: "Balloon with air"});
Translation.addTranslation("Кнопка ютуб", {en: "Button youtube"});
Translation.addTranslation("Сера", {en: "Sulfur"});
Translation.addTranslation("Зола", {en: "Ash"});
Translation.addTranslation("Просеиватель из дуба", {en: "Oak sifter"});
Translation.addTranslation("Просеиватель из березы", {en: "Birch sifter"});
Translation.addTranslation("Просеиватель из сосны", {en: "Pine sifter"});
Translation.addTranslation("Просеиватель из акации", {en: "Acacia sifter"});
Translation.addTranslation("Просеиватель из темного дуба", {en: "Dark oak sifter"});
Translation.addTranslation("Просеиватель из тропического дерева", {en: "Tropical tree sifter"});
Translation.addTranslation("Решётка для термоустойчивой печи", {en: "Grate for heat-resistant furnace"});
Translation.addTranslation("Стальной самородок", {en: "Steel nugget"});
Translation.addTranslation("Катушка с травяными нитями", {en: "Coil with herbal threads"});
Translation.addTranslation("Калиевая селитра", {en: "Potassium nitre"});
Translation.addTranslation("Антрацитовый уголь", {en: "Anthracite coal"});
Translation.addTranslation("Стальной слиток", {en: "Steel ingot"});
Translation.addTranslation("Rock", {ru: "Камень"});
Translation.addTranslation("Саженец вишни", {en: "Cherry sapling"});
Translation.addTranslation("Рубин", {en: "Ruby"});
Translation.addTranslation("Пепел", {en: "Ash"});
Translation.addTranslation("Метеоритовый слиток", {en: "Meteorite bar"});
Translation.addTranslation("Металлалом", {en: "Scrap metal"});
Translation.addTranslation("Стальной металлалом", {en: "Steel scrap metal"});
Translation.addTranslation("Адский металлалом", {en: "Hellish scrap metal"});
Translation.addTranslation("Цветной металлалом", {en: "Non-ferrous scrap metal"});
Translation.addTranslation("Метеоритовый самородок", {en: "Meteorite nugget"});
Translation.addTranslation("Адский самородок", {en: "Hellish nugget"});
Translation.addTranslation("Осколок рубина", {en: "Ruby shard"});
Translation.addTranslation("Межгалактическая валюта", {en: "Intergalactic currency"});
Translation.addTranslation("Набор для создания микрочипов", {en: "Set for creating microarrays"});
Translation.addTranslation("Микрочип", {en: "Microchip"});
Translation.addTranslation("Микрочип ускорения", {en: "Microchip acceleration"});
Translation.addTranslation("Продвинутый микрочип ускорения", {en: "Advanced acceleration microchip"});
Translation.addTranslation("Ракушка", {en: "Shell"});
Translation.addTranslation("Кокос", {en: "Coconut"});
Translation.addTranslation("Чешуя дракона края", {en: "Scale of dragon of edge"});
Translation.addTranslation("Спальный набор", {en: "Bedroom set"});
Translation.addTranslation("Создать краба", {en: "Create crab"});
Translation.addTranslation("Создать мумию", {en: "Create mummy"});
Translation.addTranslation("Создать зараженного монстра", {en: "Create infected mob"});
Translation.addTranslation("Ткацкий станок из дуба", {en: "Oak loom"});
Translation.addTranslation("Ткацкий станок из березы", {en: "Birch loom"});
Translation.addTranslation("Ткацкий станок из сосны", {en: "Pine loom"});
Translation.addTranslation("Ткацкий станок из акации", {en: "Acacia loom"});
Translation.addTranslation("Ткацкий станок из темного дуба", {en: "Dark oak loom"});
Translation.addTranslation("Ткацкий станок из тропического дерева", {en: "Tropical tree loom"});
Translation.addTranslation("Фабрика чипов", {en: "Factory of chips"});
Translation.addTranslation("Мини пресс", {en: "Mini press"});
Translation.addTranslation("Мини кактус", {en: "Mini cactus"});
Translation.addTranslation("Саженец пальмы", {en: "Palm sapling"});
//еда
Translation.addTranslation("Сыр", {en: "Cheese"});
Translation.addTranslation("Вишенка", {en: "Cherry"});
Translation.addTranslation("Колбаса", {en: "Sausage"});
Translation.addTranslation("Сырой яблочный пирог", {en: "Raw apple pie"});
Translation.addTranslation("Сырой вишневый пирог", {en: "Raw cherry pie"});
Translation.addTranslation("Роллы", {en: "Rolls"});
Translation.addTranslation("Приготовленный яблочный пирог", {en: "Cooked apple pie"});
Translation.addTranslation("Приготовленный вишневый пирог", {en: "Cooked cherry pie"});
Translation.addTranslation("Пузырек с молоком", {en: "Bubble with milk"});
Translation.addTranslation("Мука", {en: "Flour"});
Translation.addTranslation("Семечки", {en: "Sunflower seeds"});
Translation.addTranslation("Тесто", {en: "Dough"});
Translation.addTranslation("Очищенная приготовленная рыба", {en: "Peeled cooked fish"});
Translation.addTranslation("Очищенный приготовленный лосось", {en: "Peeled cooked salmon"});
Translation.addTranslation("Шоколадная плитка", {en: "Chocolate bar"});
Translation.addTranslation("Сырая пицца", {en: "Raw pizza"});
Translation.addTranslation("Приготовленная пицца", {en: "Cooked pizza"});
Translation.addTranslation("Яичница", {en: "Omelette"});
Translation.addTranslation("Мясо рыбы фугу", {en: "Meat fugu fish"});
Translation.addTranslation("Безопасное мясо рыбы фугу", {en: "Safe meat fugu fish"});
Translation.addTranslation("Приготовленное мясо рыбы фугу", {en: "Cooked meat fugu fish"});
Translation.addTranslation("Бутерброд", {en: "Sandwich"});
Translation.addTranslation("Сырое мясо края", {en: "Raw edge meat"});
Translation.addTranslation("Приготовленное мясо края", {en: "Cooked edge meat"});
Translation.addTranslation("Пузырек с расплавленным сыром", {en: "Bubble with melted cheese"});
Translation.addTranslation("Очищенный сырой лосось", {en: "Peeled raw salmon"});
Translation.addTranslation("Очищенная сырая рыба", {en: "Peeled raw fish"});
Translation.addTranslation("Сырое мясо рыбы", {en: "Raw fish meat"});
Translation.addTranslation("Приготовленное мясо рыбы", {en: "Cooked fish meat"});
Translation.addTranslation("Сырое мясо лосося", {en: "Raw salmon meat"});
Translation.addTranslation("Приготовленное мясо лосося", {en: "Cooked salmon meat"});
Translation.addTranslation("Очищенный кокос", {en: "Peeled coconut"});
Translation.addTranslation("Сырое мясо краба", {en: "Raw crab meat"});
Translation.addTranslation("Приготовленное мясо краба", {en: "Cooked crab ceat"});
Translation.addTranslation("Миска с кокосовым молоком", {en: "Bowl of coconut milk"});
Translation.addTranslation("Энергетический напиток", {en: "Energy drink"});
//броня
Translation.addTranslation("Меховой капюшон", {en: "Fur hood"});
Translation.addTranslation("Меховая куртка", {en: "Fur jacket"});
Translation.addTranslation("Меховые поножи", {en: "Fur leggings"});
Translation.addTranslation("Меховые ботинки", {en: "Fur boots"});
Translation.addTranslation("Прочный тканевый шлем", {en: "Durable fabric helmet"});
Translation.addTranslation("Прочная тканевая куртка", {en: "Durable fabric jacket"});
Translation.addTranslation("Прочные тканевые поножи", {en: "Durable fabric leggings"});
Translation.addTranslation("Прочные тканевые ботинки", {en: "Durable fabric boots"});
Translation.addTranslation("Ветхий шлем", {en: "Disrepair helmet"});
Translation.addTranslation("Ветхая куртка", {en: "Disrepair jacket"});
Translation.addTranslation("Ветхие поножи", {en: "Disrepair leggings"});
Translation.addTranslation("Ветхие ботинки", {en: "Disrepair boots"});
Translation.addTranslation("Адский шлем", {en: "Hellish helmet"});
Translation.addTranslation("Адская кираса", {en: "Hellish chestplate"});
Translation.addTranslation("Адские поножи", {en: "Hellish leggings"});
Translation.addTranslation("Адские ботинки", {en: "Hellish boots"});
Translation.addTranslation("Шахтерская каска", {en: "Miner's helmet"});
Translation.addTranslation("Водолазный шлем", {en: "Diving helmet"});
Translation.addTranslation("Баллоны с воздухом", {en: "Balloons with air"});
Translation.addTranslation("Стальной шлем", {en: "Steel helmet"});
Translation.addTranslation("Стальная кираса", {en: "Steel chestplate"});
Translation.addTranslation("Стальные поножи", {en: "Steel leggings"});
Translation.addTranslation("Стальные ботинки", {en: "Steel boots"});
Translation.addTranslation("капюшон дракона края", {en: "Dragon's hood"});
Translation.addTranslation("Кираса дракона края", {en: "Dragon's chestplate"});
Translation.addTranslation("Поножи дракона края", {en: "Dragon's leggings"});
Translation.addTranslation("Ботинки дракона края", {en: "Dragon's boots"});
//блоки
Translation.addTranslation("Сито", {en: "Sieve"});
Translation.addTranslation("Листва пальмы", {en: "Palm leaves"});
Translation.addTranslation("Древесина вишни", {en: "Cherry wood"});
Translation.addTranslation("Антрацитовая руда", {en: "Anthracite ore"});
Translation.addTranslation("Руда кристалла магмы", {en: "Magma crystal ore"});
Translation.addTranslation("Серная руда", {en: "Sulfuric ore"});
Translation.addTranslation("Стальной блок", {en: "Steel block"});
Translation.addTranslation("Древесина пальмы", {en: "Palm wood"});
Translation.addTranslation("Листва вишни", {en: "Cherry leaves"});
Translation.addTranslation("Рубиновая руда", {en: "Ruby ore"});
Translation.addTranslation("Блок пепла", {en: "Ash block"});
Translation.addTranslation("Рубиновый блок", {en: "Ruby block"});
Translation.addTranslation("Метеоритовая руда", {en: "Meteorite ore"});
Translation.addTranslation("Метеоритовый блок", {en: "Meteorite block"});
Translation.addTranslation("Стальной провод", {en: "Steel wire"});
Translation.addTranslation("Водяной генератор", {en: "Water generator"});
Translation.addTranslation("Ветхая накидка", {en: "Disrepair mantle"});
Translation.addTranslation("Ветхий капюшон", {en: "Disrepair hood"});
Translation.addTranslation("Углеродное волокно", {en: "Carbon fiber"});
Translation.addTranslation("Стальные ласты", {en: "Steel flippers"});
Translation.addTranslation("Алмазные ласты", {en: "Diamond flippers"});
Translation.addTranslation("Дайверский шлем", {en: "Diving helmet"});
Translation.addTranslation("Дайверская куртка", {en: "Diving jacket"});
Translation.addTranslation("Дайверские поножи", {en: "Diving leggings"});