IDRegistry.genBlockID("respherite_ore");
Block.createBlock("respherite_ore", [{name: "Руда респерита", texture: [["respherite_ore", 0], ["respherite_ore", 0], ["respherite_ore", 0], ["respherite_ore", 0], ["respherite_ore", 0], ["respherite_ore", 0]], inCreative: true}]);
ToolAPI.registerBlockMaterial(BlockID.respherite_ore, "stone"); 
Block.setDestroyTime(BlockID.respherite_ore, 4.3); 
Block.setDestroyLevel("respherite_ore", 3);
IDRegistry.genBlockID("Hellite_ore");
Block.createBlock("Hellite_ore", [{name: "Руда хеллита", texture: [["hellite_ore", 0], ["hellite_ore", 0], ["hellite_ore", 0], ["hellite_ore", 0], ["hellite_ore", 0], ["hellite_ore", 0]], inCreative: true}]);
ToolAPI.registerBlockMaterial(BlockID.Hellite_ore, "stone"); 
Block.setDestroyTime(BlockID.Hellite_ore, 4.3); 
Block.setDestroyLevel("Hellite_ore", 3);
IDRegistry.genBlockID("ruby_ore");
Block.createBlock("ruby_ore", [{name: "Рубиновая руда", texture: [["ruby_ore", 0], ["ruby_ore", 0], ["ruby_ore", 0], ["ruby_ore", 0], ["ruby_ore", 0], ["ruby_ore", 0]], inCreative: true}]);
ToolAPI.registerBlockMaterial(BlockID.ruby_ore, "stone"); 
Block.setDestroyTime(BlockID.ruby_ore, 4.3); 
Block.setDestroyLevel("ruby_ore", 3);
IDRegistry.genBlockID("mishril_ore");
Block.createBlock("mishril_ore", [{name: "Мишриловая руда", texture: [["mishril_ore", 0], ["mishril_ore", 0], ["mishril_ore", 0], ["mishril_ore", 0], ["mishril_ore", 0], ["mishril_ore", 0]], inCreative: true}]);
ToolAPI.registerBlockMaterial(BlockID.mishril_ore, "stone"); 
Block.setDestroyTime(BlockID.mishril_ore, 4.4); 