IDRegistry.genItemID("RobeOfTheAzureWizard");
Item.createArmorItem("RobeOfTheAzureWizard", "aw.item.RobeOfTheAzureWizard", {name: "RobeOfTheAzureWizard", meta: 0}, {type: "chestplate", armor: 6, durability: 2220, texture: "armor/noy.png"});
MagicCore.setArmor(ItemID.RobeOfTheAzureWizard, "magic", 60, {scrutiny: "RobeOfTheAzureWizard", tab: "riches"});
MagicCore.setArmorMagic(ItemID.RobeOfTheAzureWizard, "magic", 10);
IDRegistry.genItemID("fire_king");
Item.createArmorItem("fire_king", "aw.item.fire_king", {name: "aw_fire_king", meta: 0}, {type: "helmet", armor: 4, durability: 2775, texture: "armor/noy.png"});
MagicCore.setArmor(ItemID.fire_king, "magic", 55, {scrutiny: "fire", tab: "riches"});
MagicCore.setArmorMagic(ItemID.fire_king, "dead", 12);
IDRegistry.genItemID("fire_king_chestplate");
Item.createArmorItem("fire_king_chestplate", "aw.item.fire_chestplate", {name: "aw_fire_king", meta: 1}, {type: "chestplate", armor: 8, durability: 4102, texture: "armor/noy.png"});
MagicCore.setArmor(ItemID.fire_king_chestplate, "magic", 60, {scrutiny: "fire", tab: "riches"});
MagicCore.setArmorMagic(ItemID.fire_king_chestplate, "magic", 8);
IDRegistry.genItemID("fire_king_leggings");
Item.createArmorItem("fire_king_leggings", "aw.item.fire_leggings", {name: "aw_fire_king", meta: 2}, {type: "leggings", armor: 6, durability: 3805, texture: "armor/noy.png"});
MagicCore.setArmor(ItemID.fire_king_leggings, "magic", 58, {scrutiny: "fire", tab: "riches"});
MagicCore.setArmorMagic(ItemID.fire_king_leggings, "magic", 6);
IDRegistry.genItemID("fire_king_boots");
Item.createArmorItem("fire_king_boots", "aw.item.fire_boots", {name: "aw_fire_king", meta: 3}, {type: "boots", armor: 4, durability: 2438, texture: "armor/noy.png"});
MagicCore.setArmor(ItemID.fire_king_boots, "magic", 55, {scrutiny: "fire", tab: "riches"});
MagicCore.setArmorMagic(ItemID.fire_king_boots, "dead", 12);
IDRegistry.genItemID("bandit_helmet");
Item.createArmorItem("bandit_helmet", "aw.item.bandit_helmet", {name: "bandit", meta: 0}, {type: "helmet", armor: 4, durability: 1775, texture: "armor/noy.png"});
MagicCore.setArmor(ItemID.bandit_helmet, "protection", 55, {scrutiny: "bandit", tab: "riches"});
MagicCore.setArmorMagic(ItemID.bandit_helmet, "dead", 12);
IDRegistry.genItemID("bandit_chestplate");
Item.createArmorItem("bandit_chestplate", "aw.item.bandit_chestplate", {name: "bandit", meta: 1}, {type: "chestplate", armor: 8, durability: 3102, texture: "armor/noy.png"});
MagicCore.setArmor(ItemID.bandit_chestplate, "protection", 60, {scrutiny: "bandit", tab: "riches"});
MagicCore.setArmorMagic(ItemID.bandit_chestplate, "magic", 7);
IDRegistry.genItemID("bandit_leggings");
Item.createArmorItem("bandit_leggings", "aw.item.bandit_leggings", {name: "bandit", meta: 2}, {type: "leggings", armor: 6, durability: 2805, texture: "armor/noy.png"});
MagicCore.setArmor(ItemID.bandit_leggings, "protection", 58, {scrutiny: "bandit", tab: "riches"});
MagicCore.setArmorMagic(ItemID.bandit_leggings, "magic", 5);
IDRegistry.genItemID("bandit_boots");
Item.createArmorItem("bandit_boots", "aw.item.bandit_boots", {name: "bandit", meta: 3}, {type: "boots", armor: 4, durability: 1438, texture: "armor/noy.png"});
MagicCore.setArmor(ItemID.bandit_boots, "protection", 55, {scrutiny: "bandit", tab: "riches"});
MagicCore.setArmorMagic(ItemID.bandit_boots, "dead", 12);
IDRegistry.genItemID("necromancer_helmet");
Item.createArmorItem("necromancer_helmet", "aw.item.necromancer_helmet", {name: "necromancer", meta: 0}, {type: "helmet", armor: 4, durability: 1775, texture: "armor/noy.png"});
MagicCore.setArmor(ItemID.necromancer_helmet, "necromancer", 15, {scrutiny: "necromancer", tab: "riches"});
MagicCore.setArmorMagic(ItemID.necromancer_helmet, "magic", 3);
IDRegistry.genItemID("necromancer_chestplate");
Item.createArmorItem("necromancer_chestplate", "aw.item.necromancer_chestplate", {name: "necromancer", meta: 1}, {type: "chestplate", armor: 8, durability: 3102, texture: "armor/noy.png"});
MagicCore.setArmor(ItemID.necromancer_chestplate, "necromancer", 20, {scrutiny: "necromancer", tab: "riches"});
MagicCore.setArmorMagic(ItemID.necromancer_chestplate, "dead", 12);
IDRegistry.genItemID("necromancer_leggings");
Item.createArmorItem("necromancer_leggings", "aw.item.bandit_leggings", {name: "necromancer", meta: 2}, {type: "leggings", armor: 6, durability: 2805, texture: "armor/noy.png"});
MagicCore.setArmor(ItemID.necromancer_leggings, "necromancer", 20, {scrutiny: "necromancer", tab: "riches"});
MagicCore.setArmorMagic(ItemID.necromancer_leggings, "dead", 8);
IDRegistry.genItemID("necromancer_boots");
Item.createArmorItem("necromancer_boots", "aw.item.bandit_boots", {name: "necromancer", meta: 3}, {type: "boots", armor: 4, durability: 1438, texture: "armor/noy.png"});
MagicCore.setArmor(ItemID.necromancer_boots, "necromancer", 15, {scrutiny: "necromancer", tab: "riches"});
MagicCore.setArmorMagic(ItemID.necromancer_boots, "magic", 4);
Item.addCreativeGroup("armor", Translation.translate("aw.creative_group.armor"), [ItemID.RobeOfTheAzureWizard, ItemID.fire_king, ItemID.fire_king_chestplate, ItemID.fire_king_leggings, ItemID.fire_king_boots, ItemID.bandit_helmet, ItemID.bandit_chestplate, ItemID.bandit_leggings, ItemID.bandit_boots, ItemID.necromancer_helmet, ItemID.necromancer_chestplate, ItemID.necromancer_leggings, ItemID.necromancer_boots]);
Item.setEnchantType(ItemID.RobeOfTheAzureWizard, Native.EnchantType.chestplate, 14);
Item.setEnchantType(ItemID.fire_king, Native.EnchantType.helmet, 14);
Item.setEnchantType(ItemID.fire_king_chestplate, Native.EnchantType.chestplate, 14);
Item.setEnchantType(ItemID.fire_king_leggings, Native.EnchantType.leggings, 14);
Item.setEnchantType(ItemID.fire_king_boots, Native.EnchantType.boots, 14);
Item.setEnchantType(ItemID.bandit_helmet, Native.EnchantType.helmet, 14);
Item.setEnchantType(ItemID.bandit_chestplate, Native.EnchantType.chestplate, 14);
Item.setEnchantType(ItemID.bandit_leggings, Native.EnchantType.leggings, 14);
Item.setEnchantType(ItemID.bandit_boots, Native.EnchantType.boots, 14);
Item.setEnchantType(ItemID.necromancer_helmet, Native.EnchantType.helmet, 14);
Item.setEnchantType(ItemID.necromancer_chestplate, Native.EnchantType.chestplate, 14);
Item.setEnchantType(ItemID.necromancer_leggings, Native.EnchantType.leggings, 14);
Item.setEnchantType(ItemID.necromancer_boots, Native.EnchantType.boots, 14);

