function buildCrater(x, y, z) {
    World.setBlock(x, y, z, 0, 0);
    World.setBlock(x, y + 1, z, 0, 0);
    World.setBlock(x, y + 2, z, 0, 0);
    World.setBlock(x + 1, y + 2, z, 0, 0);
    World.setBlock(x + 2, y + 2, z, 0, 0);
    World.setBlock(x + 3, y + 2, z, 0, 0);
    World.setBlock(x + 4, y + 2, z, 0, 0);
    World.setBlock(x + 5, y + 2, z, 0, 0);
    World.setBlock(x + 1, y + 2, z + 1, 0, 0);
    World.setBlock(x + 2, y + 2, z + 1, 0, 0);
    World.setBlock(x + 3, y + 2, z + 1, 0, 0);
    World.setBlock(x + 4, y + 2, z + 1, 0, 0);
    World.setBlock(x + 5, y + 2, z + 1, 0, 0);
    World.setBlock(x + 1, y + 2, z + 2, 0, 0);
    World.setBlock(x + 2, y + 2, z + 2, 0, 0);
    World.setBlock(x + 3, y + 2, z + 2, 0, 0);
    World.setBlock(x + 4, y + 2, z + 2, 0, 0);
    World.setBlock(x + 5, y + 2, z + 2, 0, 0);
    World.setBlock(x + 1, y + 2, z - 1, 0, 0);
    World.setBlock(x + 2, y + 2, z - 1, 0, 0);
    World.setBlock(x + 3, y + 2, z - 1, 0, 0);
    World.setBlock(x + 4, y + 2, z - 1, 0, 0);
    World.setBlock(x + 5, y + 2, z - 1, 0, 0);
    World.setBlock(x + 1, y + 2, z - 2, 0, 0);
    World.setBlock(x + 2, y + 2, z - 2, 0, 0);
    World.setBlock(x + 3, y + 2, z - 2, 0, 0);
    World.setBlock(x + 4, y + 2, z - 2, 0, 0);
    World.setBlock(x + 5, y + 2, z - 2, 0, 0);
    World.setBlock(x - 1, y + 2, z, 0, 0);
    World.setBlock(x - 2, y + 2, z, 0, 0);
    World.setBlock(x - 3, y + 2, z, 0, 0);
    World.setBlock(x - 4, y + 2, z, 0, 0);
    World.setBlock(x - 5, y + 2, z, 0, 0);
    World.setBlock(x - 1, y + 2, z + 1, 0, 0);
    World.setBlock(x - 2, y + 2, z + 1, 0, 0);
    World.setBlock(x - 3, y + 2, z + 1, 0, 0);
    World.setBlock(x - 4, y + 2, z + 1, 0, 0);
    World.setBlock(x - 5, y + 2, z + 1, 0, 0);
    World.setBlock(x - 1, y + 2, z + 2, 0, 0);
    World.setBlock(x - 2, y + 2, z + 2, 0, 0);
    World.setBlock(x - 3, y + 2, z + 2, 0, 0);
    World.setBlock(x - 4, y + 2, z + 2, 0, 0);
    World.setBlock(x - 5, y + 2, z + 2, 0, 0);
    World.setBlock(x - 1, y + 2, z - 1, 0, 0);
    World.setBlock(x - 2, y + 2, z - 1, 0, 0);
    World.setBlock(x - 3, y + 2, z - 1, 0, 0);
    World.setBlock(x - 4, y + 2, z - 1, 0, 0);
    World.setBlock(x - 5, y + 2, z - 1, 0, 0);
    World.setBlock(x - 1, y + 2, z - 2, 0, 0);
    World.setBlock(x - 2, y + 2, z - 2, 0, 0);
    World.setBlock(x - 3, y + 2, z - 2, 0, 0);
    World.setBlock(x - 4, y + 2, z - 2, 0, 0);
    World.setBlock(x - 5, y + 2, z - 2, 0, 0);
    World.setBlock(x, y + 2, z - 1, 0, 0);
    World.setBlock(x, y + 2, z - 2, 0, 0);
    World.setBlock(x, y + 2, z - 3, 0, 0);
    World.setBlock(x, y + 2, z - 4, 0, 0);
    World.setBlock(x, y + 2, z - 5, 0, 0);
    World.setBlock(x, y + 2, z + 1, 0, 0);
    World.setBlock(x, y + 2, z + 2, 0, 0);
    World.setBlock(x, y + 2, z + 3, 0, 0);
    World.setBlock(x, y + 2, z + 4, 0, 0);
    World.setBlock(x, y + 2, z + 5, 0, 0);
    World.setBlock(x + 1, y + 2, z + 5, 0, 0);
    World.setBlock(x + 2, y + 2, z + 5, 0, 0);
    World.setBlock(x - 1, y + 2, z + 5, 0, 0);
    World.setBlock(x - 2, y + 2, z + 5, 0, 0);
    World.setBlock(x + 1, y + 2, z - 5, 0, 0);
    World.setBlock(x + 2, y + 2, z - 5, 0, 0);
    World.setBlock(x - 1, y + 2, z - 5, 0, 0);
    World.setBlock(x - 2, y + 2, z - 5, 0, 0);
    World.setBlock(x + 1, y + 2, z - 3, 0, 0);
    World.setBlock(x + 1, y + 2, z - 4, 0, 0);
    World.setBlock(x + 2, y + 2, z - 3, 0, 0);
    World.setBlock(x + 2, y + 2, z - 4, 0, 0);
    World.setBlock(x + 3, y + 2, z - 3, 0, 0);
    World.setBlock(x + 3, y + 2, z - 4, 0, 0);
    World.setBlock(x + 4, y + 2, z - 3, 0, 0);
    World.setBlock(x + 4, y + 2, z - 4, 0, 0);
    World.setBlock(x - 1, y + 2, z - 3, 0, 0);
    World.setBlock(x - 1, y + 2, z - 4, 0, 0);
    World.setBlock(x - 2, y + 2, z - 3, 0, 0);
    World.setBlock(x - 2, y + 2, z - 4, 0, 0);
    World.setBlock(x - 3, y + 2, z - 3, 0, 0);
    World.setBlock(x - 3, y + 2, z - 4, 0, 0);
    World.setBlock(x - 4, y + 2, z - 3, 0, 0);
    World.setBlock(x - 4, y + 2, z - 4, 0, 0);
    World.setBlock(x + 1, y + 2, z + 3, 0, 0);
    World.setBlock(x + 1, y + 2, z + 4, 0, 0);
    World.setBlock(x + 2, y + 2, z + 3, 0, 0);
    World.setBlock(x + 2, y + 2, z + 4, 0, 0);
    World.setBlock(x + 3, y + 2, z + 3, 0, 0);
    World.setBlock(x + 3, y + 2, z + 4, 0, 0);
    World.setBlock(x + 4, y + 2, z + 3, 0, 0);
    World.setBlock(x + 4, y + 2, z + 4, 0, 0);
    World.setBlock(x - 1, y + 2, z + 3, 0, 0);
    World.setBlock(x - 1, y + 2, z + 4, 0, 0);
    World.setBlock(x - 2, y + 2, z + 3, 0, 0);
    World.setBlock(x - 2, y + 2, z + 4, 0, 0);
    World.setBlock(x - 3, y + 2, z + 3, 0, 0);
    World.setBlock(x - 3, y + 2, z + 4, 0, 0);
    World.setBlock(x - 4, y + 2, z + 3, 0, 0);
    World.setBlock(x - 4, y + 2, z + 4, 0, 0);
    World.setBlock(x + 1, y + 1, z, 0, 0);
    World.setBlock(x + 2, y + 1, z, 0, 0);
    World.setBlock(x + 3, y + 1, z, 0, 0);
    World.setBlock(x + 4, y + 1, z, 0, 0);
    World.setBlock(x + 5, y + 1, z, 0, 0);
    World.setBlock(x + 1, y + 1, z + 1, 0, 0);
    World.setBlock(x + 2, y + 1, z + 1, 0, 0);
    World.setBlock(x + 3, y + 1, z + 1, 0, 0);
    World.setBlock(x + 4, y + 1, z + 1, 0, 0);
    World.setBlock(x + 5, y + 1, z + 1, 0, 0);
    World.setBlock(x + 1, y + 1, z + 2, 0, 0);
    World.setBlock(x + 2, y + 1, z + 2, 0, 0);
    World.setBlock(x + 3, y + 1, z + 2, 0, 0);
    World.setBlock(x + 4, y + 1, z + 2, 0, 0);
    World.setBlock(x + 5, y + 1, z + 2, 0, 0);
    World.setBlock(x + 1, y + 1, z - 1, 0, 0);
    World.setBlock(x + 2, y + 1, z - 1, 0, 0);
    World.setBlock(x + 3, y + 1, z - 1, 0, 0);
    World.setBlock(x + 4, y + 1, z - 1, 0, 0);
    World.setBlock(x + 5, y + 1, z - 1, 0, 0);
    World.setBlock(x + 1, y + 1, z - 2, 0, 0);
    World.setBlock(x + 2, y + 1, z - 2, 0, 0);
    World.setBlock(x + 3, y + 1, z - 2, 0, 0);
    World.setBlock(x + 4, y + 1, z - 2, 0, 0);
    World.setBlock(x + 5, y + 1, z - 2, 0, 0);
    World.setBlock(x - 1, y + 1, z, 0, 0);
    World.setBlock(x - 2, y + 1, z, 0, 0);
    World.setBlock(x - 3, y + 1, z, 0, 0);
    World.setBlock(x - 4, y + 1, z, 0, 0);
    World.setBlock(x - 5, y + 1, z, 0, 0);
    World.setBlock(x - 1, y + 1, z + 1, 0, 0);
    World.setBlock(x - 2, y + 1, z + 1, 0, 0);
    World.setBlock(x - 3, y + 1, z + 1, 0, 0);
    World.setBlock(x - 4, y + 1, z + 1, 0, 0);
    World.setBlock(x - 5, y + 1, z + 1, 0, 0);
    World.setBlock(x - 1, y + 1, z + 2, 0, 0);
    World.setBlock(x - 2, y + 1, z + 2, 0, 0);
    World.setBlock(x - 3, y + 1, z + 2, 0, 0);
    World.setBlock(x - 4, y + 1, z + 2, 0, 0);
    World.setBlock(x - 5, y + 1, z + 2, 0, 0);
    World.setBlock(x - 1, y + 1, z - 1, 0, 0);
    World.setBlock(x - 2, y + 1, z - 1, 0, 0);
    World.setBlock(x - 3, y + 1, z - 1, 0, 0);
    World.setBlock(x - 4, y + 1, z - 1, 0, 0);
    World.setBlock(x - 5, y + 1, z - 1, 0, 0);
    World.setBlock(x - 1, y + 1, z - 2, 0, 0);
    World.setBlock(x - 2, y + 1, z - 2, 0, 0);
    World.setBlock(x - 3, y + 1, z - 2, 0, 0);
    World.setBlock(x - 4, y + 1, z - 2, 0, 0);
    World.setBlock(x - 5, y + 1, z - 2, 0, 0);
    World.setBlock(x, y + 1, z - 1, 0, 0);
    World.setBlock(x, y + 1, z - 2, 0, 0);
    World.setBlock(x, y + 1, z - 3, 0, 0);
    World.setBlock(x, y + 1, z - 4, 0, 0);
    World.setBlock(x, y + 1, z - 5, 0, 0);
    World.setBlock(x, y + 1, z + 1, 0, 0);
    World.setBlock(x, y + 1, z + 2, 0, 0);
    World.setBlock(x, y + 1, z + 3, 0, 0);
    World.setBlock(x, y + 1, z + 4, 0, 0);
    World.setBlock(x, y + 1, z + 5, 0, 0);
    World.setBlock(x + 1, y + 1, z + 5, 0, 0);
    World.setBlock(x + 2, y + 1, z + 5, 0, 0);
    World.setBlock(x - 1, y + 1, z + 5, 0, 0);
    World.setBlock(x - 2, y + 1, z + 5, 0, 0);
    World.setBlock(x + 1, y + 1, z - 5, 0, 0);
    World.setBlock(x + 2, y + 1, z - 5, 0, 0);
    World.setBlock(x - 1, y + 1, z - 5, 0, 0);
    World.setBlock(x - 2, y + 1, z - 5, 0, 0);
    World.setBlock(x + 1, y + 1, z - 3, 0, 0);
    World.setBlock(x + 1, y + 1, z - 4, 0, 0);
    World.setBlock(x + 2, y + 1, z - 3, 0, 0);
    World.setBlock(x + 2, y + 1, z - 4, 0, 0);
    World.setBlock(x + 3, y + 1, z - 3, 0, 0);
    World.setBlock(x + 3, y + 1, z - 4, 0, 0);
    World.setBlock(x + 4, y + 1, z - 3, 0, 0);
    World.setBlock(x + 4, y + 1, z - 4, 0, 0);
    World.setBlock(x - 1, y + 1, z - 3, 0, 0);
    World.setBlock(x - 1, y + 1, z - 4, 0, 0);
    World.setBlock(x - 2, y + 1, z - 3, 0, 0);
    World.setBlock(x - 2, y + 1, z - 4, 0, 0);
    World.setBlock(x - 3, y + 1, z - 3, 0, 0);
    World.setBlock(x - 3, y + 1, z - 4, 0, 0);
    World.setBlock(x - 4, y + 1, z - 3, 0, 0);
    World.setBlock(x - 4, y + 1, z - 4, 0, 0);
    World.setBlock(x + 1, y + 1, z + 3, 0, 0);
    World.setBlock(x + 1, y + 1, z + 4, 0, 0);
    World.setBlock(x + 2, y + 1, z + 3, 0, 0);
    World.setBlock(x + 2, y + 1, z + 4, 0, 0);
    World.setBlock(x + 3, y + 1, z + 3, 0, 0);
    World.setBlock(x + 3, y + 1, z + 4, 0, 0);
    World.setBlock(x + 4, y + 1, z + 3, 0, 0);
    World.setBlock(x + 4, y + 1, z + 4, 0, 0);
    World.setBlock(x - 1, y + 1, z + 3, 0, 0);
    World.setBlock(x - 1, y + 1, z + 4, 0, 0);
    World.setBlock(x - 2, y + 1, z + 3, 0, 0);
    World.setBlock(x - 2, y + 1, z + 4, 0, 0);
    World.setBlock(x - 3, y + 1, z + 3, 0, 0);
    World.setBlock(x - 3, y + 1, z + 4, 0, 0);
    World.setBlock(x - 4, y + 1, z + 3, 0, 0);
    World.setBlock(x - 4, y + 1, z + 4, 0, 0);
    World.setBlock(x, y, z, 0, 0);
    World.setBlock(x + 1, y, z, 0, 0);
    World.setBlock(x + 2, y, z, 0, 0);
    World.setBlock(x + 3, y, z, 0, 0);
    World.setBlock(x + 4, y, z, 0, 0);
    World.setBlock(x + 5, y, z, 0, 0);
    World.setBlock(x + 1, y, z + 1, 0, 0);
    World.setBlock(x + 2, y, z + 1, 0, 0);
    World.setBlock(x + 3, y, z + 1, 0, 0);
    World.setBlock(x + 4, y, z + 1, 0, 0);
    World.setBlock(x + 5, y, z + 1, 0, 0);
    World.setBlock(x + 1, y, z + 2, 0, 0);
    World.setBlock(x + 2, y, z + 2, 0, 0);
    World.setBlock(x + 3, y, z + 2, 0, 0);
    World.setBlock(x + 4, y, z + 2, 0, 0);
    World.setBlock(x + 5, y, z + 2, 0, 0);
    World.setBlock(x + 1, y, z - 1, 0, 0);
    World.setBlock(x + 2, y, z - 1, 0, 0);
    World.setBlock(x + 3, y, z - 1, 0, 0);
    World.setBlock(x + 4, y, z - 1, 0, 0);
    World.setBlock(x + 5, y, z - 1, 0, 0);
    World.setBlock(x + 1, y, z - 2, 0, 0);
    World.setBlock(x + 2, y, z - 2, 0, 0);
    World.setBlock(x + 3, y, z - 2, 0, 0);
    World.setBlock(x + 4, y, z - 2, 0, 0);
    World.setBlock(x + 5, y, z - 2, 0, 0);
    World.setBlock(x - 1, y, z, 0, 0);
    World.setBlock(x - 2, y, z, 0, 0);
    World.setBlock(x - 3, y, z, 0, 0);
    World.setBlock(x - 4, y, z, 0, 0);
    World.setBlock(x - 5, y, z, 0, 0);
    World.setBlock(x - 1, y, z + 1, 0, 0);
    World.setBlock(x - 2, y, z + 1, 0, 0);
    World.setBlock(x - 3, y, z + 1, 0, 0);
    World.setBlock(x - 4, y, z + 1, 0, 0);
    World.setBlock(x - 5, y, z + 1, 0, 0);
    World.setBlock(x - 1, y, z + 2, 0, 0);
    World.setBlock(x - 2, y, z + 2, 0, 0);
    World.setBlock(x - 3, y, z + 2, 0, 0);
    World.setBlock(x - 4, y, z + 2, 0, 0);
    World.setBlock(x - 5, y, z + 2, 0, 0);
    World.setBlock(x - 1, y, z - 1, 0, 0);
    World.setBlock(x - 2, y, z - 1, 0, 0);
    World.setBlock(x - 3, y, z - 1, 0, 0);
    World.setBlock(x - 4, y, z - 1, 0, 0);
    World.setBlock(x - 5, y, z - 1, 0, 0);
    World.setBlock(x - 1, y, z - 2, 0, 0);
    World.setBlock(x - 2, y, z - 2, 0, 0);
    World.setBlock(x - 3, y, z - 2, 0, 0);
    World.setBlock(x - 4, y, z - 2, 0, 0);
    World.setBlock(x - 5, y, z - 2, 0, 0);
    World.setBlock(x, y, z - 1, 0, 0);
    World.setBlock(x, y, z - 2, 0, 0);
    World.setBlock(x, y, z - 3, 0, 0);
    World.setBlock(x, y, z - 4, 0, 0);
    World.setBlock(x, y, z - 5, 0, 0);
    World.setBlock(x, y, z + 1, 0, 0);
    World.setBlock(x, y, z + 2, 0, 0);
    World.setBlock(x, y, z + 3, 0, 0);
    World.setBlock(x, y, z + 4, 0, 0);
    World.setBlock(x, y, z + 5, 0, 0);
    World.setBlock(x + 1, y, z + 5, 0, 0);
    World.setBlock(x + 2, y, z + 5, 0, 0);
    World.setBlock(x - 1, y, z + 5, 0, 0);
    World.setBlock(x - 2, y, z + 5, 0, 0);
    World.setBlock(x + 1, y, z - 5, 0, 0);
    World.setBlock(x + 2, y, z - 5, 0, 0);
    World.setBlock(x - 1, y, z - 5, 0, 0);
    World.setBlock(x - 2, y, z - 5, 0, 0);
    World.setBlock(x + 1, y, z - 3, 0, 0);
    World.setBlock(x + 1, y, z - 4, 0, 0);
    World.setBlock(x + 2, y, z - 3, 0, 0);
    World.setBlock(x + 2, y, z - 4, 0, 0);
    World.setBlock(x + 3, y, z - 3, 0, 0);
    World.setBlock(x + 3, y, z - 4, 0, 0);
    World.setBlock(x + 4, y, z - 3, 0, 0);
    World.setBlock(x + 4, y, z - 4, 0, 0);
    World.setBlock(x - 1, y, z - 3, 0, 0);
    World.setBlock(x - 1, y, z - 4, 0, 0);
    World.setBlock(x - 2, y, z - 3, 0, 0);
    World.setBlock(x - 2, y, z - 4, 0, 0);
    World.setBlock(x - 3, y, z - 3, 0, 0);
    World.setBlock(x - 3, y, z - 4, 0, 0);
    World.setBlock(x - 4, y, z - 3, 0, 0);
    World.setBlock(x - 4, y, z - 4, 0, 0);
    World.setBlock(x + 1, y, z + 3, 0, 0);
    World.setBlock(x + 1, y, z + 4, 0, 0);
    World.setBlock(x + 2, y, z + 3, 0, 0);
    World.setBlock(x + 2, y, z + 4, 0, 0);
    World.setBlock(x + 3, y, z + 3, 0, 0);
    World.setBlock(x + 3, y, z + 4, 0, 0);
    World.setBlock(x + 4, y, z + 3, 0, 0);
    World.setBlock(x + 4, y, z + 4, 0, 0);
    World.setBlock(x - 1, y, z + 3, 0, 0);
    World.setBlock(x - 1, y, z + 4, 0, 0);
    World.setBlock(x - 2, y, z + 3, 0, 0);
    World.setBlock(x - 2, y, z + 4, 0, 0);
    World.setBlock(x - 3, y, z + 3, 0, 0);
    World.setBlock(x - 3, y, z + 4, 0, 0);
    World.setBlock(x - 4, y, z + 3, 0, 0);
    World.setBlock(x - 4, y, z + 4, 0, 0);
    World.setBlock(x, y - 1, z, 0, 0);
    World.setBlock(x - 1, y - 1, z, 0, 0);
    World.setBlock(x - 2, y - 1, z, 0, 0);
    World.setBlock(x - 3, y - 1, z, 0, 0);
    World.setBlock(x - 4, y - 1, z, 0, 0);
    World.setBlock(x + 1, y - 1, z, 0, 0);
    World.setBlock(x + 2, y - 1, z, 0, 0);
    World.setBlock(x + 3, y - 1, z, 0, 0);
    World.setBlock(x + 4, y - 1, z, 0, 0);
    World.setBlock(x - 1, y - 1, z - 1, 0, 0);
    World.setBlock(x - 2, y - 1, z - 1, 0, 0);
    World.setBlock(x - 3, y - 1, z - 1, 0, 0);
    World.setBlock(x - 4, y - 1, z - 1, 0, 0);
    World.setBlock(x - 1, y - 1, z - 2, 0, 0);
    World.setBlock(x - 2, y - 1, z - 2, 0, 0);
    World.setBlock(x - 3, y - 1, z - 2, 0, 0);
    World.setBlock(x - 4, y - 1, z - 2, 0, 0);
    World.setBlock(x - 1, y - 1, z + 1, 0, 0);
    World.setBlock(x - 2, y - 1, z + 1, 0, 0);
    World.setBlock(x - 3, y - 1, z + 1, 0, 0);
    World.setBlock(x - 4, y - 1, z + 1, 0, 0);
    World.setBlock(x - 1, y - 1, z + 2, 0, 0);
    World.setBlock(x - 2, y - 1, z + 2, 0, 0);
    World.setBlock(x - 3, y - 1, z + 2, 0, 0);
    World.setBlock(x - 4, y - 1, z + 2, 0, 0);
    World.setBlock(x + 1, y - 1, z - 1, 0, 0);
    World.setBlock(x + 2, y - 1, z - 1, 0, 0);
    World.setBlock(x + 3, y - 1, z - 1, 0, 0);
    World.setBlock(x + 4, y - 1, z - 1, 0, 0);
    World.setBlock(x + 1, y - 1, z - 2, 0, 0);
    World.setBlock(x + 2, y - 1, z - 2, 0, 0);
    World.setBlock(x + 3, y - 1, z - 2, 0, 0);
    World.setBlock(x + 4, y - 1, z - 2, 0, 0);
    World.setBlock(x + 1, y - 1, z + 1, 0, 0);
    World.setBlock(x + 2, y - 1, z + 1, 0, 0);
    World.setBlock(x + 3, y - 1, z + 1, 0, 0);
    World.setBlock(x + 4, y - 1, z + 1, 0, 0);
    World.setBlock(x + 1, y - 1, z + 2, 0, 0);
    World.setBlock(x + 2, y - 1, z + 2, 0, 0);
    World.setBlock(x + 3, y - 1, z + 2, 0, 0);
    World.setBlock(x + 4, y - 1, z + 2, 0, 0);
    World.setBlock(x, y - 1, z + 1, 0, 0);
    World.setBlock(x, y - 1, z + 2, 0, 0);
    World.setBlock(x, y - 1, z + 3, 0, 0);
    World.setBlock(x, y - 1, z + 4, 0, 0);
    World.setBlock(x, y - 1, z - 1, 0, 0);
    World.setBlock(x, y - 1, z - 2, 0, 0);
    World.setBlock(x, y - 1, z - 3, 0, 0);
    World.setBlock(x, y - 1, z - 4, 0, 0);
    World.setBlock(x - 1, y - 1, z + 3, 0, 0);
    World.setBlock(x - 1, y - 1, z + 4, 0, 0);
    World.setBlock(x - 2, y - 1, z + 3, 0, 0);
    World.setBlock(x - 2, y - 1, z + 4, 0, 0);
    World.setBlock(x - 3, y - 1, z + 3, 0, 0);
    World.setBlock(x + 1, y - 1, z + 3, 0, 0);
    World.setBlock(x + 1, y - 1, z + 4, 0, 0);
    World.setBlock(x + 2, y - 1, z + 3, 0, 0);
    World.setBlock(x + 2, y - 1, z + 4, 0, 0);
    World.setBlock(x + 3, y - 1, z + 3, 0, 0);
    World.setBlock(x - 1, y - 1, z - 3, 0, 0);
    World.setBlock(x - 1, y - 1, z - 4, 0, 0);
    World.setBlock(x - 2, y - 1, z - 3, 0, 0);
    World.setBlock(x - 2, y - 1, z - 4, 0, 0);
    World.setBlock(x - 3, y - 1, z - 3, 0, 0);
    World.setBlock(x + 1, y - 1, z - 3, 0, 0);
    World.setBlock(x + 1, y - 1, z - 4, 0, 0);
    World.setBlock(x + 2, y - 1, z - 3, 0, 0);
    World.setBlock(x + 2, y - 1, z - 4, 0, 0);
    World.setBlock(x + 3, y - 1, z - 3, 0, 0);
    World.setBlock(x, y - 2, z, 0, 0);
    World.setBlock(x - 1, y - 2, z, 0, 0);
    World.setBlock(x - 2, y - 2, z, 0, 0);
    World.setBlock(x - 1, y - 2, z - 1, 0, 0);
    World.setBlock(x - 2, y - 2, z - 1, 0, 0);
    World.setBlock(x - 1, y - 2, z + 1, 0, 0);
    World.setBlock(x - 2, y - 2, z + 1, 0, 0);
    World.setBlock(x + 1, y - 2, z, 0, 0);
    World.setBlock(x + 2, y - 2, z, 0, 0);
    World.setBlock(x + 1, y - 2, z - 1, 0, 0);
    World.setBlock(x + 2, y - 2, z - 1, 0, 0);
    World.setBlock(x + 1, y - 2, z + 1, 0, 0);
    World.setBlock(x + 2, y - 2, z + 1, 0, 0);
    World.setBlock(x, y - 2, z + 1, 0, 0);
    World.setBlock(x, y - 2, z + 2, 0, 0);
    World.setBlock(x - 1, y - 2, z + 2, 0, 0);
    World.setBlock(x + 1, y - 2, z + 2, 0, 0);
    World.setBlock(x, y - 2, z - 1, 0, 0);
    World.setBlock(x, y - 2, z - 2, 0, 0);
    World.setBlock(x - 1, y - 2, z - 2, 0, 0);
    World.setBlock(x + 1, y - 2, z - 2, 0, 0);
    let rand_num = custom_random(1, METEORITE_MAX_CHANCE);
    if (rand_num == 1) {
        World.setBlock(x, y - 2, z, BlockID.meteorite, 0);
    }
}

