var LANPADAS_DECORATIVO = Block.createSpecialType({base: 5, lightlevel: 15});
IDRegistry.genItemID("sofaItembranco");
Item.createItem("sofaItembranco", "Sof\xe1 Branco", {name: "sofa_t_color_w", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItemazul");
Item.createItem("sofaItemazul", "Sof\xe1 Azul", {name: "sofa_t_color_b", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItemazulclaro");
Item.createItem("sofaItemazulclaro", "Sof\xe1 azul claro", {name: "sofa_t_color_lb", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItemverde");
Item.createItem("sofaItemverde", "Sof\xe1 verde", {name: "sofa_t_color_g", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItemverdeclaro");
Item.createItem("sofaItemverdeclaro", "Sof\xe1 verde claro", {name: "sofa_t_color_lg", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItemamarelo");
Item.createItem("sofaItemamarelo", "Sof\xe1 amarelo", {name: "sofa_t_color_y", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItemlaranja");
Item.createItem("sofaItemlaranja", "Sof\xe1 laranja", {name: "sofa_t_color_o", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItemvermelho");
Item.createItem("sofaItemvermelho", "Sof\xe1 Vermelho", {name: "sofa_t_color_r", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItemmarrom");
Item.createItem("sofaItemmarrom", "Sof\xe1 Marrom", {name: "sofa_t_color_br", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItempreto");
Item.createItem("sofaItempreto", "Sof\xe1 Preto", {name: "sofa_t_color_bl", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItemcinza");
Item.createItem("sofaItemcinza", "Sof\xe1 cinza", {name: "sofa_t_color_lgr", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItemcinzaescuro");
Item.createItem("sofaItemcinzaescuro", "Sof\xe1 cinza escuro", {name: "sofa_t_color_gr", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItemciano");
Item.createItem("sofaItemciano", "Sof\xe1 ciano", {name: "sofa_t_color_c", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItemrosa");
Item.createItem("sofaItemrosa", "Sof\xe1 rosa", {name: "sofa_t_color_pi", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItemmagenta");
Item.createItem("sofaItemmagenta", "Sof\xe1 Magenta", {name: "sofa_t_color_m", meta: 0}, {stack: 64});
IDRegistry.genItemID("sofaItemroxo");
Item.createItem("sofaItemroxo", "Sof\xe1 Roxo", {name: "sofa_t_color_p", meta: 0}, {stack: 64});
IDRegistry.genBlockID("sof\xe1branco");
Block.createBlock("sof\xe1branco", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofábranco, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1azul");
Block.createBlock("sof\xe1azul", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofáazul, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1azulclaro");
Block.createBlock("sof\xe1azulclaro", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofáazulclaro, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1verde");
Block.createBlock("sof\xe1verde", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofáverde, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1verdeclaro");
Block.createBlock("sof\xe1verdeclaro", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofáverdeclaro, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1amarelo");
Block.createBlock("sof\xe1amarelo", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofáamarelo, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1laranja");
Block.createBlock("sof\xe1laranja", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofálaranja, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1vermelho");
Block.createBlock("sof\xe1vermelho", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofávermelho, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1marrom");
Block.createBlock("sof\xe1marrom", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofámarrom, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1preto");
Block.createBlock("sof\xe1preto", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofápreto, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1cinza");
Block.createBlock("sof\xe1cinza", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofácinza, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1cinzaescuro");
Block.createBlock("sof\xe1cinzaescuro", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofácinzaescuro, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1ciano");
Block.createBlock("sof\xe1ciano", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofáciano, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1rosa");
Block.createBlock("sof\xe1rosa", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofárosa, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1magenta");
Block.createBlock("sof\xe1magenta", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofámagenta, "stone", 2, true);
IDRegistry.genBlockID("sof\xe1roxo");
Block.createBlock("sof\xe1roxo", [{name: "Sof\xe1 de l\xe3 branca", texture: [["wool", 0], ["wool", 0], ["wool", 1], ["wool", 2], ["wool", 1], ["wool", 1]], inCreative: false}]);
ToolAPI.registerBlockMaterial(BlockID.sofároxo, "stone", 2, true);
IDRegistry.genBlockID("lanpadabranca");
Block.createBlock("lanpadabranca", [{name: "L\xe2mpada Branca", texture: [["lbranco", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.lanpadabranca, "stone", 2, true);
IDRegistry.genBlockID("lanpadaazulclaro");
Block.createBlock("lanpadaazulclaro", [{name: "L\xe2mpada Azul Claro", texture: [["lazul_claro", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.lanpadaazulclaro, "stone", 2, true);
IDRegistry.genBlockID("lanpadaazul");
Block.createBlock("lanpadaazul", [{name: "L\xe2mpada Azul", texture: [["lblue", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.lanpadaazul, "stone", 2, true);
IDRegistry.genBlockID("lanpadaverdec");
Block.createBlock("lanpadaverdec", [{name: "L\xe2mpada Azul", texture: [["lverdec", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.lanpadaverdec, "stone", 2, true);
IDRegistry.genBlockID("lanpadaamarela");
Block.createBlock("lanpadaamarela", [{name: "L\xe2mpada Azul", texture: [["lamarelo", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.lanpadaamarela, "stone", 2, true);
IDRegistry.genBlockID("lanpadaVermelha");
Block.createBlock("lanpadaVermelha", [{name: "L\xe2mpada Vermelha", texture: [["lred", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.lanpadaVermelha, "stone", 2, true);
IDRegistry.genBlockID("lanpadaLaranja");
Block.createBlock("lanpadaLaranja", [{name: "L\xe2mpada Laranja", texture: [["llaranja", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.lanpadaLaranja, "stone", 2, true);
IDRegistry.genBlockID("Lanpadaciano");
Block.createBlock("Lanpadaciano", [{name: "L\xe2mpada Ciano", texture: [["lciano", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.Lanpadaciano, "stone", 2, true);
IDRegistry.genBlockID("LanpadaRosa");
Block.createBlock("LanpadaRosa", [{name: "L\xe2mpada Rosa", texture: [["lrosa", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.LanpadaRosa, "stone", 2, true);
IDRegistry.genBlockID("lanpadaPreta");
Block.createBlock("lanpadaPreta", [{name: "L\xe2mpada Preta", texture: [["lblack", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.lanpadaPreta, "stone", 2, true);
IDRegistry.genBlockID("LanpadaRoxa");
Block.createBlock("LanpadaRoxa", [{name: "L\xe2mpada roxa", texture: [["lpurple", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.LanpadaRoxa, "stone", 2, true);
IDRegistry.genBlockID("LanpadaSinza");
Block.createBlock("LanpadaSinza", [{name: "L\xe2mpada sinza", texture: [["lgray", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.LanpadaSinza, "stone", 2, true);
IDRegistry.genBlockID("LanpadaSinzaEscuro");
Block.createBlock("LanpadaSinzaEscuro", [{name: "L\xe2mpada Cinza escuro", texture: [["lgray_dark", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.LanpadaSinzaEscuro, "stone", 2, true);
IDRegistry.genBlockID("LanpadaVerdeEscuro");
Block.createBlock("LanpadaVerdeEscuro", [{name: "L\xe2mpada Verde escuro", texture: [["lverdees", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.LanpadaVerdeEscuro, "stone", 2, true);
IDRegistry.genBlockID("LanpadaMarron");
Block.createBlock("LanpadaMarron", [{name: "L\xe2mpada Marron", texture: [["lmarrom", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.LanpadaMarron, "stone", 2, true);
IDRegistry.genBlockID("LanpadaMagenta");
Block.createBlock("LanpadaMagenta", [{name: "L\xe2mpada Magenta", texture: [["lmagenta", 0]], inCreative: true}], LANPADAS_DECORATIVO);
ToolAPI.registerBlockMaterial(BlockID.LanpadaMagenta, "stone", 2, true);
Callback.addCallback("PreLoaded", function () {
    const sofábrancorender = new ICRender.Model();
    const sofábrancomodel = BlockRenderer.createModel();
    sofábrancomodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofábrancomodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.cwhite, 0);
    sofábrancomodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.cwhite, 0);
    sofábrancomodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.cwhite, 0);
    sofábrancomodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.cwhite, 0);
    sofábrancorender.addEntry(sofábrancomodel);
    BlockRenderer.setStaticICRender(BlockID.sofábranco, 0, sofábrancorender);
    Block.registerDropFunction("sof\xe1branco", function () {
        return [[ItemID.sofábranco, 1, 0]];
    });
    Item.registerUseFunction("sofaItembranco", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofábranco);
        Player.decreaseCarriedItem(1);
    });
    const sofáazulrender = new ICRender.Model();
    const sofáazulmodel = BlockRenderer.createModel();
    sofáazulmodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofáazulmodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.cblue, 0);
    sofáazulmodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.cblue, 0);
    sofáazulmodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.cblue, 0);
    sofáazulmodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.cblue, 0);
    sofáazulrender.addEntry(sofáazulmodel);
    BlockRenderer.setStaticICRender(BlockID.sofáazul, 0, sofáazulrender);
    Block.registerDropFunction("sof\xe1azul", function () {
        return [[ItemID.sofáazul, 1, 0]];
    });
    Item.registerUseFunction("sofaItemazul", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofáazul);
        Player.decreaseCarriedItem(1);
    });
    const sofáazulclarorender = new ICRender.Model();
    const sofáazulclaromodel = BlockRenderer.createModel();
    sofáazulclaromodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofáazulclaromodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.cbluec, 0);
    sofáazulclaromodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.cbluec, 0);
    sofáazulclaromodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.cbluec, 0);
    sofáazulclaromodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.cbluec, 0);
    sofáazulclarorender.addEntry(sofáazulclaromodel);
    BlockRenderer.setStaticICRender(BlockID.sofáazulclaro, 0, sofáazulclarorender);
    Block.registerDropFunction("sof\xe1azulclaro", function () {
        return [[ItemID.sofáazulclaro, 1, 0]];
    });
    Item.registerUseFunction("sofaItemazulclaro", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofáazulclaro);
        Player.decreaseCarriedItem(1);
    });
    const sofáverderender = new ICRender.Model();
    const sofáverdemodel = BlockRenderer.createModel();
    sofáverdemodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofáverdemodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.cgreen, 0);
    sofáverdemodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.cgreen, 0);
    sofáverdemodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.cgreen, 0);
    sofáverdemodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.cgreen, 0);
    sofáverderender.addEntry(sofáverdemodel);
    BlockRenderer.setStaticICRender(BlockID.sofáverde, 0, sofáverderender);
    Block.registerDropFunction("sof\xe1verde", function () {
        return [[ItemID.sofáverde, 1, 0]];
    });
    Item.registerUseFunction("sofaItemverde", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofáverde);
        Player.decreaseCarriedItem(1);
    });
    const sofáverdeclarorender = new ICRender.Model();
    const sofáverdeclaromodel = BlockRenderer.createModel();
    sofáverdeclaromodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofáverdeclaromodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.cgreenclaro, 0);
    sofáverdeclaromodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.cgreenclaro, 0);
    sofáverdeclaromodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.cgreenclaro, 0);
    sofáverdeclaromodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.cgreenclaro, 0);
    sofáverdeclarorender.addEntry(sofáverdeclaromodel);
    BlockRenderer.setStaticICRender(BlockID.sofáverdeclaro, 0, sofáverdeclarorender);
    Block.registerDropFunction("sof\xe1verdeclaro", function () {
        return [[ItemID.sofáverdeclaro, 1, 0]];
    });
    Item.registerUseFunction("sofaItemverdeclaro", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofáverdeclaro);
        Player.decreaseCarriedItem(1);
    });
    const sofáamarelorender = new ICRender.Model();
    const sofáamarelomodel = BlockRenderer.createModel();
    sofáamarelomodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofáamarelomodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.camarelo, 0);
    sofáamarelomodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.camarelo, 0);
    sofáamarelomodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.camarelo, 0);
    sofáamarelomodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.camarelo, 0);
    sofáamarelorender.addEntry(sofáamarelomodel);
    BlockRenderer.setStaticICRender(BlockID.sofáamarelo, 0, sofáamarelorender);
    Block.registerDropFunction("sof\xe1amarelo", function () {
        return [[ItemID.sofáamarelo, 1, 0]];
    });
    Item.registerUseFunction("sofaItemamarelo", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofáamarelo);
        Player.decreaseCarriedItem(1);
    });
    const sofálaranjarender = new ICRender.Model();
    const sofálaranjamodel = BlockRenderer.createModel();
    sofálaranjamodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofálaranjamodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.claranja, 0);
    sofálaranjamodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.claranja, 0);
    sofálaranjamodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.claranja, 0);
    sofálaranjamodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.claranja, 0);
    sofálaranjarender.addEntry(sofálaranjamodel);
    BlockRenderer.setStaticICRender(BlockID.sofálaranja, 0, sofálaranjarender);
    Block.registerDropFunction("sof\xe1laranja", function () {
        return [[ItemID.sofálaranja, 1, 0]];
    });
    Item.registerUseFunction("sofaItemlaranja", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofálaranja);
        Player.decreaseCarriedItem(1);
    });
    const sofávermelhorender = new ICRender.Model();
    const sofávermelhomodel = BlockRenderer.createModel();
    sofávermelhomodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofávermelhomodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.cred, 0);
    sofávermelhomodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.cred, 0);
    sofávermelhomodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.cred, 0);
    sofávermelhomodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.cred, 0);
    sofávermelhorender.addEntry(sofávermelhomodel);
    BlockRenderer.setStaticICRender(BlockID.sofávermelho, 0, sofávermelhorender);
    Block.registerDropFunction("sof\xe1vermelho", function () {
        return [[ItemID.sofávermelho, 1, 0]];
    });
    Item.registerUseFunction("sofaItemvermelho", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofávermelho);
        Player.decreaseCarriedItem(1);
    });
    const sofámarromrender = new ICRender.Model();
    const sofámarrommodel = BlockRenderer.createModel();
    sofámarrommodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofámarrommodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.cmarron, 0);
    sofámarrommodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.cmarron, 0);
    sofámarrommodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.cmarron, 0);
    sofámarrommodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.cmarron, 0);
    sofámarromrender.addEntry(sofámarrommodel);
    BlockRenderer.setStaticICRender(BlockID.sofámarrom, 0, sofámarromrender);
    Block.registerDropFunction("sof\xe1marrom", function () {
        return [[ItemID.sofámarrom, 1, 0]];
    });
    Item.registerUseFunction("sofaItemmarrom", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofámarrom);
        Player.decreaseCarriedItem(1);
    });
    const sofápretorender = new ICRender.Model();
    const sofápretomodel = BlockRenderer.createModel();
    sofápretomodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofápretomodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.cpreto, 0);
    sofápretomodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.cpreto, 0);
    sofápretomodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.cpreto, 0);
    sofápretomodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.cpreto, 0);
    sofápretorender.addEntry(sofápretomodel);
    BlockRenderer.setStaticICRender(BlockID.sofápreto, 0, sofápretorender);
    Block.registerDropFunction("sof\xe1preto", function () {
        return [[ItemID.sofápreto, 1, 0]];
    });
    Item.registerUseFunction("sofaItempreto", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofápreto);
        Player.decreaseCarriedItem(1);
    });
    const sofácinzarender = new ICRender.Model();
    const sofácinzamodel = BlockRenderer.createModel();
    sofácinzamodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofácinzamodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.ccinza, 0);
    sofácinzamodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.ccinza, 0);
    sofácinzamodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.ccinza, 0);
    sofácinzamodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.ccinza, 0);
    sofácinzarender.addEntry(sofácinzamodel);
    BlockRenderer.setStaticICRender(BlockID.sofácinza, 0, sofácinzarender);
    Block.registerDropFunction("sof\xe1cinza", function () {
        return [[ItemID.sofácinza, 1, 0]];
    });
    Item.registerUseFunction("sofaItemcinza", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofácinza);
        Player.decreaseCarriedItem(1);
    });
    const sofácinzaescurorender = new ICRender.Model();
    const sofácinzaescuromodel = BlockRenderer.createModel();
    sofácinzaescuromodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofácinzaescuromodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.ccinzaescuro, 0);
    sofácinzaescuromodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.ccinzaescuro, 0);
    sofácinzaescuromodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.ccinzaescuro, 0);
    sofácinzaescuromodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.ccinzaescuro, 0);
    sofácinzaescurorender.addEntry(sofácinzaescuromodel);
    BlockRenderer.setStaticICRender(BlockID.sofácinzaescuro, 0, sofácinzaescurorender);
    Block.registerDropFunction("sof\xe1cinzaescuro", function () {
        return [[ItemID.sofácinzaescuro, 1, 0]];
    });
    Item.registerUseFunction("sofaItemcinzaescuro", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofácinzaescuro);
        Player.decreaseCarriedItem(1);
    });
    const sofácianorender = new ICRender.Model();
    const sofácianomodel = BlockRenderer.createModel();
    sofácianomodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofácianomodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.cciano, 0);
    sofácianomodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.cciano, 0);
    sofácianomodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.cciano, 0);
    sofácianomodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.cciano, 0);
    sofácianorender.addEntry(sofácianomodel);
    BlockRenderer.setStaticICRender(BlockID.sofáciano, 0, sofácianorender);
    Block.registerDropFunction("sof\xe1ciano", function () {
        return [[ItemID.sofáciano, 1, 0]];
    });
    Item.registerUseFunction("sofaItemciano", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofáciano);
        Player.decreaseCarriedItem(1);
    });
    const sofárosarender = new ICRender.Model();
    const sofárosamodel = BlockRenderer.createModel();
    sofárosamodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofárosamodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.cpink, 0);
    sofárosamodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.cpink, 0);
    sofárosamodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.cpink, 0);
    sofárosamodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.cpink, 0);
    sofárosarender.addEntry(sofárosamodel);
    BlockRenderer.setStaticICRender(BlockID.sofárosa, 0, sofárosarender);
    Block.registerDropFunction("sof\xe1rosa", function () {
        return [[ItemID.sofárosa, 1, 0]];
    });
    Item.registerUseFunction("sofaItemrosa", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofárosa);
        Player.decreaseCarriedItem(1);
    });
    const sofámagentarender = new ICRender.Model();
    const sofámagentamodel = BlockRenderer.createModel();
    sofámagentamodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofámagentamodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.cmangeta, 0);
    sofámagentamodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.cmangeta, 0);
    sofámagentamodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.cmangeta, 0);
    sofámagentamodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.cmangeta, 0);
    sofámagentarender.addEntry(sofámagentamodel);
    BlockRenderer.setStaticICRender(BlockID.sofámagenta, 0, sofámagentarender);
    Block.registerDropFunction("sof\xe1magenta", function () {
        return [[ItemID.sofámagenta, 1, 0]];
    });
    Item.registerUseFunction("sofaItemmagenta", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofámagenta);
        Player.decreaseCarriedItem(1);
    });
    const sofároxorender = new ICRender.Model();
    const sofároxomodel = BlockRenderer.createModel();
    sofároxomodel.addBox(0 / 16, 0, 0 / 16, 16 / 16, 1 / 16, 15 / 16, 5, 0);
    sofároxomodel.addBox(0 / 16, 1 / 16, 0 / 16, 16 / 16, 16 / 16, 1 / 16, BlockID.croxo, 0);
    sofároxomodel.addBox(15 / 16, 1 / 16, 1 / 16, 16 / 16, 8 / 16, 15 / 16, BlockID.croxo, 0);
    sofároxomodel.addBox(0 / 16, 1 / 16, 1 / 16, 1 / 16, 8 / 16, 15 / 16, BlockID.croxo, 0);
    sofároxomodel.addBox(1 / 16, 1 / 16, 1 / 16, 15 / 16, 4 / 16, 15 / 16, BlockID.croxo, 0);
    sofároxorender.addEntry(sofároxomodel);
    BlockRenderer.setStaticICRender(BlockID.sofároxo, 0, sofároxorender);
    Block.registerDropFunction("sof\xe1roxo", function () {
        return [[ItemID.sofároxo, 1, 0]];
    });
    Item.registerUseFunction("sofaItemroxo", function (coords, item, block) {
        World.setBlock(coords.relative.x, coords.relative.y, coords.relative.z, BlockID.sofároxo);
        Player.decreaseCarriedItem(1);
    });
});
Callback.addCallback("PostLoaded", function () {
    Recipes.addShaped({id: ItemID.sofaItembranco, count: 5, data: 0}, ["aoa", " aaa", "bbb"], ["a", BlockID.cwhite, 0, "b", 5, 0]);
    Recipes.addShaped({id: ItemID.sofaItemazul, count: 1, data: 0}, ["ab"], ["a", ItemID.sofaItembranco, 0, "b", 351, 4]);
    Recipes.addShaped({id: ItemID.sofaItemazulclaro, count: 1, data: 0}, ["ab"], ["a", ItemID.sofaItembranco, 0, "b", 351, 12]);
    Recipes.addShaped({id: ItemID.sofaItemverde, count: 1, data: 0}, ["ab"], ["a", ItemID.sofaItembranco, 0, "b", 351, 2]);
    Recipes.addShaped({id: ItemID.sofaItemverdeclaro, count: 1, data: 0}, ["ab"], ["a", ItemID.sofaItembranco, 0, "b", 351, 10]);
    Recipes.addShaped({id: ItemID.sofaItemamarelo, count: 1, data: 0}, ["ab"], ["a", ItemID.sofaItembranco, 0, "b", 351, 11]);
    Recipes.addShaped({id: ItemID.sofaItemlaranja, count: 1, data: 0}, ["ab"], ["a", ItemID.sofaItembranco, 0, "b", 351, 14]);
    Recipes.addShaped({id: ItemID.sofaItemvermelho, count: 1, data: 0}, ["ab"], ["a", ItemID.sofaItembranco, 0, "b", 351, 1]);
    Recipes.addShaped({id: ItemID.sofaItemmarrom, count: 1, data: 0}, ["ab"], ["a", ItemID.sofaItembranco, 0, "b", 351, 3]);
    Recipes.addShaped({id: ItemID.sofaItempreto, count: 1, data: 0}, ["ab"], ["a", ItemID.sofaItembranco, 0, "b", 351, 0]);
    Recipes.addShaped({id: ItemID.sofaItemcinza, count: 1, data: 0}, ["ab"], ["a", ItemID.sofaItembranco, 0, "b", 351, 7]);
    Recipes.addShaped({id: ItemID.sofaItemciano, count: 1, data: 0}, ["ab"], ["a", ItemID.sofaItembranco, 0, "b", 351, 6]);
    Recipes.addShaped({id: ItemID.sofaItemrosa, count: 1, data: 0}, ["ab"], ["a", ItemID.sofaItembranco, 0, "b", 351, 9]);
    Recipes.addShaped({id: ItemID.sofaItemmagenta, count: 1, data: 0}, ["ab"], ["a", ItemID.sofaItembranco, 0, "b", 351, 13]);
    Recipes.addShaped({id: ItemID.sofaItemroxo, count: 1, data: 0}, ["ab"], ["a", ItemID.sofaItembranco, 0, "b", 351, 5]);
    Recipes.addShaped({id: BlockID.lanpadabranca, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 15]);
    Recipes.addShaped({id: BlockID.lanpadaazulclaro, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 12]);
    Recipes.addShaped({id: BlockID.lanpadaazul, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 4]);
    Recipes.addShaped({id: BlockID.lanpadaverdec, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 10]);
    Recipes.addShaped({id: BlockID.lanpadaamarela, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 11]);
    Recipes.addShaped({id: BlockID.lanpadaVermelha, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 1]);
    Recipes.addShaped({id: BlockID.lanpadaLaranja, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 14]);
    Recipes.addShaped({id: BlockID.Lanpadaciano, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 6]);
    Recipes.addShaped({id: BlockID.LanpadaRosa, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 9]);
    Recipes.addShaped({id: BlockID.lanpadaPreta, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 0]);
    Recipes.addShaped({id: BlockID.LanpadaRoxa, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 5]);
    Recipes.addShaped({id: BlockID.LanpadaSinza, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 7]);
    Recipes.addShaped({id: BlockID.LanpadaSinzaEscuro, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 8]);
    Recipes.addShaped({id: BlockID.LanpadaVerdeEscuro, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 2]);
    Recipes.addShaped({id: BlockID.LanpadaMarron, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 3]);
    Recipes.addShaped({id: BlockID.LanpadaMagenta, count: 8, data: 0}, ["aaa", "aba", "aaa"], ["a", 89, 0, "b", 351, 13]);
});

