Translation.addTranslation("Leadstone Sоlar Panel", {ru:"Свинцовая Солнечная Панель"});
Translation.addTranslation("Hardent Sоlar Panel", {ru:"Закалённая Солнечная Панель"});
Translation.addTranslation("Redstone Sоlar Panel", {ru:"Краснокаменная Солнечная Панель"});
Translation.addTranslation("Resonant Sоlar Panel", {ru:"Резонирующая Солнечная Панель"});
Translation.addTranslation("Advanced Sоlar Panel", {ru:"Улучшенная Солнечная Панель"});
Translation.addTranslation("Ultimate Sоlar Panel", {ru:"Окончательная Солнечная Панель"});
Translation.addTranslation("Power tier", {ru: "Энергоуровень"});
Translation.addTranslation("§5Maksim Kievsky: §2detected a problem with a block drop. §114.02.2018 §9version 2.0.1", {ru: "§5Максим Киевский: §2обнаружил проблему с дропом блоков. §114.02.2018 §9версии 2.0.1"});
Translation.addTranslation("§5miron27khv: §4created 90% of texture mod. §9Was taken to the development team since version 2.2.3", {ru: "§5miron27khv: §создал 90% текстур мода. §9состоит в команде разработчиков с версии 2.2.3"});
Translation.addTranslation("§4ripemc: §6 noticed a bug with integration with IC². §214.04.2019 §9version 2.4.5.3", {ru: "§4ripemc: §6 заметил баг с интеграцией с IC². §214.04.2019 §9версии 2.4.5.3"});
Translation.addTranslation("§5BrassyFaNToM: §7 reported an error with most of the mechanisms. §C08.06.2019 §9 Versions §b3§f.§70", {ru: "§5BrassyFaNToM: §7 сообщил о баге с большинством механизмов. §C08.06.2019 §9версии §b3§f.§80"});
Translation.addTranslation("This message can be disabled by disabling the show_helpers_message parameter in the config (games/com.mojang/mods/ores/config.json)", {ru: "это сообщение можно отключить, отключив параметр show_helpers_message в конфиге (games/com.mojang/mods/ores/config.json)"});
Translation.addTranslation("Do not open the workbench items from mods - it will lead to the crash!", {ru: "Не открывать верстак предметами из модов - это приведёт к крашу!"});
Translation.addTranslation("All about Ores Mod", {ru: "Все о моде Ores Mod"});
Translation.addTranslation("About ores", {ru: "О рудах"});
Translation.addTranslation("About mechanical blocks", {ru: "О механических блоках"});
Translation.addTranslation("About other items", {ru: "О прочих предметах"});
Translation.addTranslation("To main", {ru: "На главную"});
Translation.addTranslation("Used in crafts.", {ru: "Используется в крафтах."});
Translation.addTranslation("Advantage", {ru: "Преимущество"});
Translation.addTranslation("Disadvantage", {ru: "Недостаток"});
Translation.addTranslation("not rare", {ru: "не редкий"});
Translation.addTranslation("no strengths", {ru: "нет сильных сторон"});
Translation.addTranslation("Adamantite", {ru: "Адамантит"});
Translation.addTranslation("Lead", {ru: "Свинец"});
Translation.addTranslation("Malachite", {ru: "Малахит"});
Translation.addTranslation("Muthril", {ru: "Мифрил"});
Translation.addTranslation("Uranium", {ru: "Ураниум"});
Translation.addTranslation("Sapphire", {ru: "Сапфир"});
Translation.addTranslation("very fast", {ru: "Очень быстрый"});
Translation.addTranslation("not durable", {ru: "Не долговечен"});
Translation.addTranslation("strength", {ru: "сильный"});
Translation.addTranslation("not rare, relatively durable and efficient", {ru: "не редкий, сравнительно прочный и эффективный"});
Translation.addTranslation("lower speed than malachite", {ru: "менее низкая скорость, чем у малахита"});
Translation.addTranslation("the most effective material", {ru: "самый эффективный материал"});
Translation.addTranslation("rate", {ru: "редкий"});
Translation.addTranslation("effective, has the highest damage", {ru: "эффективный, имеет самый высокий урон"});
Translation.addTranslation("rarely comes across", {ru: "редко попадается"});
Translation.addTranslation("Turns reconstructed matter into objects.", {ru: "Превращает реконструированную материю в предметы."});
Translation.addTranslation("Using molecular converters", {ru: "Использование молекулярного конвертатора"});
Translation.addTranslation("The information panel in the mechanism window displays the current state of the mechanism and helps to understand how the mechanism works.", {ru: "Информационная панель в окне механизма отображает текущее состояние механизма и помогает понять, как работает механизм."});
Translation.addTranslation("As a result, you will receive an item that was as a result of the reconstruction of matter.", {ru: "В результате вы получите предмет, который был в результате реконструкции материи."});
Translation.addTranslation("At the exit you will receive the item that was recorded in the reconstructed matter.", {ru: "На выходе вы получите предмет, который был записан в реконструированной материи."});
Translation.addTranslation("The only source of chips", {ru: "Единственный источник получения чипов"});
Translation.addTranslation("For the mechanism to work, you need to: keep the mechanism charged with energy and place the research chips in the upper slot.", {ru: "Чтобы механизм работал, вам необходимо: держать механизм заряженным энергией и поместить исследовательские чипы в верхнюю щель."});
Translation.addTranslation("Generator, for generating a new type of energy QE (Quantum Energy)", {ru: "Генератор, для генерации нового типа энергии QE(Quantum Energy)"});
Translation.addTranslation("Using a molecular generator", {ru: "Использование молекулярного генератора"});
Translation.addTranslation("Working with this mechanism is the easiest.", {ru: "Работа с этим механизмом самая простая."});
Translation.addTranslation("In the interface of the mechanism there are many slots, in these slots are placed any items that the mechanism will turn into energy.", {ru: "В интерфейсе механизма находится множество слотов, в эти слоты помещаются любые предметы, которые механизм превратит в энергию."});
Translation.addTranslation("The mechanism does not consume Eu-energy.", {ru: "Механизм не потребляет Eu-энергии."});
Translation.addTranslation("The removal of energy is carried out by attaching a special conductor to the upper side of the mechanism.", {ru: "Вывод энергии осуществляется, путем присоединения специального проводника к верхней стороне механизма."});
Translation.addTranslation("He accepts ordinary matter and any object, the data of which he will transmit to matter and will issue reconstructed matter.", {ru: "Принимает обычную материю и какой-либо предмет, данные которого он передаст в материю и выдаст реконструированную материю."});
Translation.addTranslation("Reconstructed matter is used in a molecular transducer.", {ru: "Реконструированная материя применяется в молекулярном преобразователе."});
Translation.addTranslation("Use of matter re-constructor", {ru: "Использование реконструктора материи"});
Translation.addTranslation("To understand the mechanism - just open it and look at the panel below.", {ru: "Чтобы понять, как работает механизм - посмотрите на панель снизу, в окне механизма."});
Translation.addTranslation("The red and yellow text indicates that the mechanism is lacking for work.", {ru: "Красный и желтый текст показывают, что нехватает механизму для работы."});
Translation.addTranslation("Molecular compactor compresses QE energy, turning it into matter.", {ru: "Молекулярный уплотнитель сжимает QE энергию, превращая её в материю."});
Translation.addTranslation("The use of molecular sealer.", {ru: "Использование молекулярного уплотнителя."});
Translation.addTranslation("The operation of this mechanism is fully automatic, you just need to maintain working conditions.", {ru: "Работа этого механизма полностью автоматическая, вам лишь нужно поддерживать условия работы"});
Translation.addTranslation("This is the only mechanism that consumes QE-energy.", {ru: "Это единственный механизм, который потребляет QE-энергию."});
Translation.addTranslation("In order for the mechanism to accept QE-energy, you need to connect a wire to it to the upper side.", {ru: "Чтобы механизм принимал QE-энергию - нужно подключить к нему провод к верхней стороне."});
Translation.addTranslation("The mechanism itself begins to work when the energy inside it is greater than 0.", {ru: "Механизм сам начинает работать, когда энергия внутри него больше чем 0."});
Translation.addTranslation("The redstone signal stops the operation of the mechanism, but at the same time it will still be able to absorb energy.", {ru: "Редстоун-сигнал останавливает работу механизма, но при этом он по прежнему сможет принимать в себя энергию."});
Translation.addTranslation("Generation", {ru: "Генерация"});
Translation.addTranslation("night", {ru: "ночью"});
Translation.addTranslation("Leadstone", {ru: "Свинцовая"});
Translation.addTranslation("Hardent", {ru: "Закалённая"});
Translation.addTranslation("Redstone", {ru: "Краснокаменная"});
Translation.addTranslation("Resonant", {ru: "Резонирующая"});
Translation.addTranslation("Advanced", {ru: "Улучшенная"});
Translation.addTranslation("Ultimate", {ru: "Окончательная"});
Translation.addTranslation("This mechanism will grow the tree anywhere.", {ru: "Этот механизм вырастит дерево где угодно."});
Translation.addTranslation("Use of a wood incubator", {ru: "Использование древесного инкубатора"});
Translation.addTranslation("To use a wood incubator you will need: seedling, energy and catalyst.", {ru: "Для использования древесного инкубатора понадобится: саженец, энергия и катализатор."});
Translation.addTranslation("List of supported seedlings and catalysts on the right page.", {ru: "Список поддерживаемых саженцев и катализаторов на правой странице."});
Translation.addTranslation("Before using the mechanism, you need to place a block of earth or dirt next to it.", {ru: "Перед использованием механизма вам нужно поставить рядом с ним блок земли или грязи."});
Translation.addTranslation("In the window of the mechanism, approximately in the middle, there is a red rectangle.", {ru: "В окне механизма, примерно по середине, находится красный прямоугольник."});
Translation.addTranslation("You need to work only with slots from the left of this rectangle.", {ru: "Вам нужно работать только со слотами с лева от этого прямоугольника."});
Translation.addTranslation("A sapling is placed in the top slot; in the right - the catalyst", {ru: "В верхний слот помещается саженец; в правый - катализатор"});
Translation.addTranslation("If you did everything correctly, then a sapling will appear on the dirt block, and the red rectangle will turn green.", {ru: "Если вы все сделали правильно - то на блоке грязи появится саженец, а красный прямоугольник будет становиться зелёным."});
Translation.addTranslation("I remind you that the mechanism consumes energy, nothing will work without it.", {ru: "Напоминаю, что механизм потребляет энергию, без неё ничего работать не будет."});
Translation.addTranslation("The red box is the growth progress bar. When progress is completed - you will receive a tree, seedlings and a special drop, if there is one.", {ru: "Красный прямоугольник - шкала прогресса роста. Когда прогресс завершится - вы получите дерево, саженцы и особый дроп, если таков есть."});
Translation.addTranslation("Saplings:", {ru: "Saplings:"});
Translation.addTranslation("Currently only saplings from minecraft are supported.", {ru: "В настоящий момент поддерживаются только саженцы из minecraft."});
Translation.addTranslation("Catalysts:", {ru: "Катализаторы:"});
Translation.addTranslation("Bone flour.", {ru: "Костная мука."});
Translation.addTranslation("The catalyst is used to accelerate the growth of the tree, its use is not necessary", {ru: "Катализатор используется для ускорения роста дерева, его использование не обязательно"});
Translation.addTranslation("Solar Panels", {ru: "Солнечная панель"});
Translation.addTranslation("Chips", {ru: "Чипы"});
Translation.addTranslation("Receiving:", {ru: "Получение:"});
Translation.addTranslation("Application:", {ru: "Применение:"});
Translation.addTranslation("Creating mechanisms", {ru: "Создание механизмов"});
Translation.addTranslation("Used in the creation of solar panels", {ru: "Используются в создании солнечных панелей"});
Translation.addTranslation("To find out the recipe for higher level kernels, put the core one level less in inventory and open the inventory.", {ru: "Чтобы узнать рецепт ядер более высокого уровня - положите в инвентарь ядро на один уровень меньше и откройте инвентарь."});
Translation.addTranslation("For example, to find out the recipe for the core of a hardened solar panel - take the lead core and open the workbench.", {ru: "Например, чтобы узнать рецепт для ядра закаленной солнечной панели - возьмите ядро свинцовой и откройте верстак."});
Translation.addTranslation("Cores", {ru: "Ядра"});
Translation.addTranslation("Nuggets", {ru: "Самородки"});
Translation.addTranslation("Production Station", {ru: "Производственная Станция"});
Translation.addTranslation("Nanite Collector", {ru: "Сборщик Нанитов"});
Translation.addTranslation("Nanite Training Node", {ru: "Узел Обучения Нанитов"});
Translation.addTranslation("Input", {ru: "Выход"})