CropRegistry.registerWithID("appleBlock", "appleBlock", "appleBlock", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.appleBlock, drop: 260});
CropRegistry.registerWithID("apricot", "apricot", "apricot", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.apricot, drop: ItemID.apricot});
CropRegistry.registerWithID("cherry", "cherry", "cherry", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.cherry, drop: ItemID.cherry});
CropRegistry.registerWithID("avocado", "avocado", "avocado", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.avocado, drop: ItemID.avocado});
CropRegistry.registerWithID("banana", "banana", "banana", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.banana, drop: ItemID.banana});
CropRegistry.registerWithID("date", "date", "date", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.date, drop: ItemID.date});
CropRegistry.registerWithID("dragonfruit", "dragonfruit", "dragonfruit", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.dragonfruit, drop: ItemID.dragonfruit});
CropRegistry.registerWithID("fig", "fig", "fig", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.fig, drop: ItemID.fig});
CropRegistry.registerWithID("grapefruit", "grapefruit", "grapefruit", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.grapefruit, drop: ItemID.grapefruit});
CropRegistry.registerWithID("gooseberry", "gooseberry", "gooseberry", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.gooseberry, drop: ItemID.gooseberry});
CropRegistry.registerWithID("lemon", "lemon", "lemon", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.lemon, drop: ItemID.lemon});
CropRegistry.registerWithID("lime", "lime", "lime", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.lime, drop: ItemID.lime});
CropRegistry.registerWithID("mango", "mango", "mango", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.mango, drop: ItemID.mango});
CropRegistry.registerWithID("olive", "olive", "olive", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.olive, drop: ItemID.olive});
CropRegistry.registerWithID("orange", "orange", "orange", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.orange, drop: ItemID.orange});
CropRegistry.registerWithID("papaya", "papaya", "papaya", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.papaya, drop: ItemID.papaya});
CropRegistry.registerWithID("peach", "peach", "peach", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.peach, drop: ItemID.peach});
CropRegistry.registerWithID("pear", "pear", "pear", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.pear, drop: ItemID.pear});
CropRegistry.registerWithID("persimmon", "persimmon", "persimmon", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.persimmon, drop: ItemID.persimmon});
CropRegistry.registerWithID("plum", "plum", "plum", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.plum, drop: ItemID.plum});
CropRegistry.registerWithID("pomegranate", "pomegranate", "pomegranate", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.pomegranate, drop: ItemID.pomegranate});
CropRegistry.registerWithID("starfruit", "starfruit", "starfruit", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.starfruit, drop: ItemID.starfruit});
CropRegistry.registerWithID("almond", "almond", "almond", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.almond, drop: ItemID.almond});
CropRegistry.registerWithID("peppercornfruit", "peppercornfruit", "peppercornfruit", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.peppercornfruit, drop: ItemID.peppercornfruit});
CropRegistry.registerWithID("cashew", "cashew", "cashew", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.cashew, drop: ItemID.cashew});
CropRegistry.registerWithID("coconut", "coconut", "coconut", BLOCK_TYPE_CROP);
CropRegistry.deriveCropAsClass("Harvestcraft_fruit", {id: BlockID.coconut, drop: ItemID.coconut});

