IDRegistry.genItemID("appleSapling");
Item.createItem("appleSapling", "Apple Tree Sapling", {name: "appleSapling", data: 0});
IDRegistry.genItemID("apricotSapling");
Item.createItem("apricotSapling", "Apricot Tree Sapling", {name: "apricotSapling", data: 0});
IDRegistry.genItemID("cherrySapling");
Item.createItem("cherrySapling", "Cherry Tree Sapling", {name: "cherrySapling", data: 0});
IDRegistry.genItemID("avocadoSapling");
Item.createItem("avocadoSapling", "Avocado Tree Sapling", {name: "avocadoSapling", data: 0});
IDRegistry.genItemID("bananaSapling");
Item.createItem("bananaSapling", "Banana Tree Sapling", {name: "bananaSapling", data: 0});
IDRegistry.genItemID("dateSapling");
Item.createItem("dateSapling", "Date Tree Sapling", {name: "dateSapling", data: 0});
IDRegistry.genItemID("dragonfruitSapling");
Item.createItem("dragonfruitSapling", "Dragonfruit Tree Sapling", {name: "dragonfruitSapling", data: 0});
IDRegistry.genItemID("figSapling");
Item.createItem("figSapling", "Fig Tree Sapling", {name: "figSapling", data: 0});
IDRegistry.genItemID("grapefruitSapling");
Item.createItem("grapefruitSapling", "Grapefruit Tree Sapling", {name: "grapefruitSapling", data: 0});
IDRegistry.genItemID("gooseberrySapling");
Item.createItem("gooseberrySapling", "Gooseberry Tree Sapling", {name: "gooseberrySapling", data: 0});
IDRegistry.genItemID("lemonSapling");
Item.createItem("lemonSapling", "Lemon Tree Sapling", {name: "lemonSapling", data: 0});
IDRegistry.genItemID("limeSapling");
Item.createItem("limeSapling", "Lime Tree Sapling", {name: "limeSapling", data: 0});
IDRegistry.genItemID("mangoSapling");
Item.createItem("mangoSapling", "Mango Tree Sapling", {name: "mangoSapling", data: 0});
IDRegistry.genItemID("oliveSapling");
Item.createItem("oliveSapling", "Olive Tree Sapling", {name: "oliveSapling", data: 0});
IDRegistry.genItemID("orangeSapling");
Item.createItem("orangeSapling", "Orange Tree Sapling", {name: "orangeSapling", data: 0});
IDRegistry.genItemID("papayaSapling");
Item.createItem("papayaSapling", "Papaya Tree Sapling", {name: "papayaSapling", data: 0});
IDRegistry.genItemID("peachSapling");
Item.createItem("peachSapling", "Peach Tree Sapling", {name: "peachSapling", data: 0});
IDRegistry.genItemID("pearSapling");
Item.createItem("pearSapling", "Pear Tree Sapling", {name: "pearSapling", data: 0});
IDRegistry.genItemID("persimmonSapling");
Item.createItem("persimmonSapling", "Persimmon Tree Sapling", {name: "persimmonSapling", data: 0});
IDRegistry.genItemID("plumSapling");
Item.createItem("plumSapling", "Plum Tree Sapling", {name: "plumSapling", data: 0});
IDRegistry.genItemID("pomegranateSapling");
Item.createItem("pomegranateSapling", "Pomegranate Tree Sapling", {name: "pomegranateSapling", data: 0});
IDRegistry.genItemID("starfruitSapling");
Item.createItem("starfruitSapling", "Starfruit Tree Sapling", {name: "starfruitSapling", data: 0});
IDRegistry.genItemID("almondSapling");
Item.createItem("almondSapling", "Almond Tree Sapling", {name: "almondSapling", data: 0});
IDRegistry.genItemID("peppercornSapling");
Item.createItem("peppercornSapling", "Peppercorn Tree Sapling", {name: "peppercornSapling", data: 0});
IDRegistry.genItemID("cashewSapling");
Item.createItem("cashewSapling", "Cashew Tree Sapling", {name: "cashewSapling", data: 0});
IDRegistry.genItemID("coconutSapling");
Item.createItem("coconutSapling", "Coconut Tree Sapling", {name: "coconutSapling", data: 0});

