var appleTreesCount = {min: __config__.access("generation.group.trees.apple.min"), max: __config__.access("generation.group.trees.apple.max"), enabled: true};
TreeRegistry.addTreeGeneration("apple", middleBiomes, appleTreesCount, __config__.access("generation.numbers.trees.apple"));
var apricotTreesCount = {min: __config__.access("generation.group.trees.apricot.min"), max: __config__.access("generation.group.trees.apricot.max"), enabled: true};
TreeRegistry.addTreeGeneration("apricot", savannaBiomes, apricotTreesCount, __config__.access("generation.numbers.trees.apricot"));
var cherryTreesCount = {min: __config__.access("generation.group.trees.cherry.min"), max: __config__.access("generation.group.trees.cherry.max"), enabled: true};
TreeRegistry.addTreeGeneration("cherry", middleBiomes, cherryTreesCount, __config__.access("generation.numbers.trees.cherry"));
var avocadoTreesCount = {min: __config__.access("generation.group.trees.avocado.min"), max: __config__.access("generation.group.trees.avocado.max"), enabled: true};
TreeRegistry.addTreeGeneration("avocado", middleBiomes, avocadoTreesCount, __config__.access("generation.numbers.trees.avocado"));
var bananaTreesCount = {min: __config__.access("generation.group.trees.banana.min"), max: __config__.access("generation.group.trees.banana.max"), enabled: true};
TreeRegistry.addTreeGeneration("banana", savannaBiomes, bananaTreesCount, __config__.access("generation.numbers.trees.banana"));
var dateTreesCount = {min: __config__.access("generation.group.trees.date.min"), max: __config__.access("generation.group.trees.date.max"), enabled: true};
TreeRegistry.addTreeGeneration("date", savannaBiomes, dateTreesCount, __config__.access("generation.numbers.trees.date"));
var dragonfruitTreesCount = {min: __config__.access("generation.group.trees.dragonfruit.min"), max: __config__.access("generation.group.trees.dragonfruit.max"), enabled: true};
TreeRegistry.addTreeGeneration("dragonfruit", savannaBiomes, dragonfruitTreesCount, __config__.access("generation.numbers.trees.dragonfruit"));
var figTreesCount = {min: __config__.access("generation.group.trees.fig.min"), max: __config__.access("generation.group.trees.fig.max"), enabled: true};
TreeRegistry.addTreeGeneration("fig", savannaBiomes, figTreesCount, __config__.access("generation.numbers.trees.fig"));
var grapefruitTreesCount = {min: __config__.access("generation.group.trees.grapefruit.min"), max: __config__.access("generation.group.trees.grapefruit.max"), enabled: true};
TreeRegistry.addTreeGeneration("grapefruit", savannaBiomes, grapefruitTreesCount, __config__.access("generation.numbers.trees.grapefruit"));
var gooseberryTreesCount = {min: __config__.access("generation.group.trees.gooseberry.min"), max: __config__.access("generation.group.trees.gooseberry.max"), enabled: true};
TreeRegistry.addTreeGeneration("gooseberry", savannaBiomes, gooseberryTreesCount, __config__.access("generation.numbers.trees.gooseberry"));
var lemonTreesCount = {min: __config__.access("generation.group.trees.lemon.min"), max: __config__.access("generation.group.trees.lemon.max"), enabled: true};
TreeRegistry.addTreeGeneration("lemon", savannaBiomes, lemonTreesCount, __config__.access("generation.numbers.trees.lemon"));
var limeTreesCount = {min: __config__.access("generation.group.trees.lime.min"), max: __config__.access("generation.group.trees.lime.max"), enabled: true};
TreeRegistry.addTreeGeneration("lime", savannaBiomes, limeTreesCount, __config__.access("generation.numbers.trees.lime"));
var mangoTreesCount = {min: __config__.access("generation.group.trees.mango.min"), max: __config__.access("generation.group.trees.mango.max"), enabled: true};
TreeRegistry.addTreeGeneration("mango", savannaBiomes, mangoTreesCount, __config__.access("generation.numbers.trees.mango"));
var oliveTreesCount = {min: __config__.access("generation.group.trees.olive.min"), max: __config__.access("generation.group.trees.olive.max"), enabled: true};
TreeRegistry.addTreeGeneration("olive", savannaBiomes, oliveTreesCount, __config__.access("generation.numbers.trees.olive"));
var orangeTreesCount = {min: __config__.access("generation.group.trees.orange.min"), max: __config__.access("generation.group.trees.orange.max"), enabled: true};
TreeRegistry.addTreeGeneration("orange", savannaBiomes, orangeTreesCount, __config__.access("generation.numbers.trees.orange"));
var papayaTreesCount = {min: __config__.access("generation.group.trees.papaya.min"), max: __config__.access("generation.group.trees.papaya.max"), enabled: true};
TreeRegistry.addTreeGeneration("papaya", savannaBiomes, papayaTreesCount, __config__.access("generation.numbers.trees.papaya"));
var peachTreesCount = {min: __config__.access("generation.group.trees.peach.min"), max: __config__.access("generation.group.trees.peach.max"), enabled: true};
TreeRegistry.addTreeGeneration("peach", savannaBiomes, peachTreesCount, __config__.access("generation.numbers.trees.peach"));
var pearTreesCount = {min: __config__.access("generation.group.trees.pear.min"), max: __config__.access("generation.group.trees.pear.max"), enabled: true};
TreeRegistry.addTreeGeneration("pear", taigaBiomes, pearTreesCount, __config__.access("generation.numbers.trees.pear"));
var persimmonTreesCount = {min: __config__.access("generation.group.trees.persimmon.min"), max: __config__.access("generation.group.trees.persimmon.max"), enabled: true};
TreeRegistry.addTreeGeneration("persimmon", savannaBiomes, persimmonTreesCount, __config__.access("generation.numbers.trees.persimmon"));
var plumTreesCount = {min: __config__.access("generation.group.trees.plum.min"), max: __config__.access("generation.group.trees.plum.max"), enabled: true};
TreeRegistry.addTreeGeneration("plum", savannaBiomes, plumTreesCount, __config__.access("generation.numbers.trees.plum"));
var pomegranateTreesCount = {min: __config__.access("generation.group.trees.pomegranate.min"), max: __config__.access("generation.group.trees.pomegranate.max"), enabled: true};
TreeRegistry.addTreeGeneration("pomegranate", savannaBiomes, pomegranateTreesCount, __config__.access("generation.numbers.trees.pomegranate"));
var starfruitTreesCount = {min: __config__.access("generation.group.trees.starfruit.min"), max: __config__.access("generation.group.trees.starfruit.max"), enabled: true};
TreeRegistry.addTreeGeneration("starfruit", savannaBiomes, starfruitTreesCount, __config__.access("generation.numbers.trees.starfruit"));
var almondTreesCount = {min: __config__.access("generation.group.trees.almond.min"), max: __config__.access("generation.group.trees.almond.max"), enabled: true};
TreeRegistry.addTreeGeneration("almond", savannaBiomes, almondTreesCount, __config__.access("generation.numbers.trees.almond"));
var peppercornTreesCount = {min: __config__.access("generation.group.trees.peppercorn.min"), max: __config__.access("generation.group.trees.peppercorn.max"), enabled: true};
TreeRegistry.addTreeGeneration("peppercorn", savannaBiomes, peppercornTreesCount, __config__.access("generation.numbers.trees.peppercorn"));
var cashewTreesCount = {min: __config__.access("generation.group.trees.cashew.min"), max: __config__.access("generation.group.trees.cashew.max"), enabled: true};
TreeRegistry.addTreeGeneration("cashew", savannaBiomes, cashewTreesCount, __config__.access("generation.numbers.trees.cashew"));
var coconutTreesCount = {min: __config__.access("generation.group.trees.coconut.min"), max: __config__.access("generation.group.trees.coconut.max"), enabled: true};
TreeRegistry.addTreeGeneration("coconut", savannaBiomes, coconutTreesCount, __config__.access("generation.numbers.trees.coconut"));

