Translation.addTranslation("Copper Ore", {zh:"铜矿" });
Translation.addTranslation("Magnet Ore", {zh:"磁铁矿" });
Translation.addTranslation("Battery Box", {zh:"储电箱" });
Translation.addTranslation("Generator", {zh:"发电机" });
Translation.addTranslation("Stator", {zh:"发电机定子" });
Translation.addTranslation("Rotor", {zh:"发电机转子" });
Translation.addTranslation("Steel Plate", {zh:"钢板" });
Translation.addTranslation("Copper Plate", {zh:"铜板" });
Translation.addTranslation("Screw", {zh:"螺丝" });
Translation.addTranslation("Coil", {zh:"电磁铁" });
Translation.addTranslation("Generator Core", {zh:"发电机核心" });
Translation.addTranslation("Steel Stick", {zh:"钢棒" });
Translation.addTranslation("Electric Machinery", {zh:"电动机" });
Translation.addTranslation("Electric Brush", {zh:"电刷" });
Translation.addTranslation("Hoof Magnet", {zh:"蹄型磁铁" });
Translation.addTranslation("Steel Mill", {zh:"钢磨盘" });
Translation.addTranslation("Gold Mill", {zh:"金磨盘" });
Translation.addTranslation("Diamond Mill", {zh:"钻石磨盘" });
Translation.addTranslation("Copper Wire", {zh:"铜丝" });
Translation.addTranslation("Steel Wire", {zh:"钢丝" });
Translation.addTranslation("Resistor", {zh:"电阻器" });
Translation.addTranslation("Storage Battery", {zh:"蓄电池" });
Translation.addTranslation("Coke", {zh:"焦炭" });
Translation.addTranslation("Tool", {zh:"摇柄" });
Translation.addTranslation("Wrench", {zh:"扳手" });
Translation.addTranslation("Screwdriver", {zh:"螺丝刀" });
Translation.addTranslation("Fire-Tongs", {zh:"火钳" });
Translation.addTranslation("Iron Forging Hammer", {zh:"铁锤" });
Translation.addTranslation("Iron Pliers", {zh:"铁钳子" });
Translation.addTranslation("Iron Knife", {zh:"铁小刀" });
Translation.addTranslation("Steel Forging Hammer", {zh:"钢锤" });
Translation.addTranslation("Steel Pliers", {zh:"钢钳子" });
Translation.addTranslation("Steel Knife", {zh:"钢小刀" });
Translation.addTranslation("Gold Forging Hammer", {zh:"金锤" });
Translation.addTranslation("Gold Pliers", {zh:"金钳子" });
Translation.addTranslation("Gold Knife", {zh:"金小刀" });
Translation.addTranslation("Diamond Forging Hammer", {zh:"钻石锤" });
Translation.addTranslation("Diamond Pliers", {zh:"钻石钳子" });
Translation.addTranslation("Diamond Knife", {zh:"钻石小刀" });
Translation.addTranslation("Iron Gravel", {zh:"铁矿砂" });
Translation.addTranslation("Gold Gravel", {zh:"金矿砂" });
Translation.addTranslation("Copper Gravel", {zh:"铜矿砂" });
Translation.addTranslation("Steel Ingot", {zh:"钢锭" });
Translation.addTranslation("Magnet Ingot", {zh:"磁铁锭" });
Translation.addTranslation("Copper Ingot", {zh:"铜锭" });
Translation.addTranslation("Steel Ingot(h)", {zh:"炽热的钢锭" });
Translation.addTranslation("Copper Ingot(h)", {zh:"炽热的铜锭" });
Translation.addTranslation("Mill", {zh:"研磨机" });
Translation.addTranslation("Plate Compressors", {zh:"压板机" });
Translation.addTranslation("Ore Washer", {zh:"基础洗矿机" });
Translation.addTranslation("Steel Workbench", {zh:"钢制工作台" });
Translation.addTranslation("Water Pump", {zh:"水泵" });
Translation.addTranslation("Oven", {zh:"烤箱" });
Translation.addTranslation("Machine Tool<", {zh:"机床" });
Translation.addTranslation("Forging Furnace", {zh:"锻造炉"});
Translation.addTranslation("Cake Machine", {zh:"蛋糕机" });
Translation.addTranslation("Magnetizer", {zh:"磁化机" });
Translation.addTranslation("Liquid Fuel Generator", {zh:"液体燃料发电机" });
Translation.addTranslation("God's Generators", {zh:"上帝的发电机(创造模式)" });
Translation.addTranslation("Coal-fired Generators", {zh:"燃煤发电机" });
Translation.addTranslation("Water Pipe", {zh:"管道" });
Translation.addTranslation("FuE Wire", {zh:"FuE导线" });
Translation.addTranslation("Machine Shell", {zh:"机器外壳" });
Translation.addTranslation("Large Machine Shell", {zh:"大型机器外壳" });
Translation.addTranslation("Boiler", {zh:"储罐" });
Translation.addTranslation("Coke Oven", {zh:"焦炉" });
Translation.addTranslation("Industrial Furnaces", {zh:"工业炉" });
Translation.addTranslation("Grinder", {zh:"粉碎机" });
Translation.addTranslation("Large Ore Washer", {zh:"大型洗矿机" });
Translation.addTranslation("Chimney", {zh:"烟囱" });
Translation.addTranslation("Blast Furnace", {zh:"高炉" });
Translation.addTranslation("ft_exhaust Pipe", {zh:"废气管" });