IDRegistry.genItemID("copperHelmet");
IDRegistry.genItemID("copperChestplate");
IDRegistry.genItemID("copperLeggings");
IDRegistry.genItemID("copperBoots");
IDRegistry.genItemID("bronzeHelmet");
IDRegistry.genItemID("bronzeChestplate");
IDRegistry.genItemID("bronzeLeggings");
IDRegistry.genItemID("bronzeBoots");
IDRegistry.genItemID("hepatizonHelmet");
IDRegistry.genItemID("hepatizonChestplate");
IDRegistry.genItemID("hepatizonLeggings");
IDRegistry.genItemID("hepatizonBoots");
IDRegistry.genItemID("damascus_steelHelmet");
IDRegistry.genItemID("damascus_steelChestplate");
IDRegistry.genItemID("damascus_steelLeggings");
IDRegistry.genItemID("damascus_steelBoots");
IDRegistry.genItemID("angmallenHelmet");
IDRegistry.genItemID("angmallenChestplate");
IDRegistry.genItemID("angmallenLeggings");
IDRegistry.genItemID("angmallenBoots");
IDRegistry.genItemID("steelHelmet");
IDRegistry.genItemID("steelChestplate");
IDRegistry.genItemID("steelLeggings");
IDRegistry.genItemID("steelBoots");
IDRegistry.genItemID("brassHelmet");
IDRegistry.genItemID("brassChestplate");
IDRegistry.genItemID("brassLeggings");
IDRegistry.genItemID("brassBoots");
IDRegistry.genItemID("silverHelmet");
IDRegistry.genItemID("silverChestplate");
IDRegistry.genItemID("silverLeggings");
IDRegistry.genItemID("silverBoots");
IDRegistry.genItemID("electrumHelmet");
IDRegistry.genItemID("electrumChestplate");
IDRegistry.genItemID("electrumLeggings");
IDRegistry.genItemID("electrumBoots");
IDRegistry.genItemID("platinumHelmet");
IDRegistry.genItemID("platinumChestplate");
IDRegistry.genItemID("platinumLeggings");
IDRegistry.genItemID("platinumBoots");
IDRegistry.genItemID("ignatiusHelmet");
IDRegistry.genItemID("ignatiusChestplate");
IDRegistry.genItemID("ignatiusLeggings");
IDRegistry.genItemID("ignatiusBoots");
IDRegistry.genItemID("shadow_ironHelmet");
IDRegistry.genItemID("shadow_ironChestplate");
IDRegistry.genItemID("shadow_ironLeggings");
IDRegistry.genItemID("shadow_ironBoots");
IDRegistry.genItemID("shadow_steelHelmet");
IDRegistry.genItemID("shadow_steelChestplate");
IDRegistry.genItemID("shadow_steelLeggings");
IDRegistry.genItemID("shadow_steelBoots");
IDRegistry.genItemID("midasiumHelmet");
IDRegistry.genItemID("midasiumChestplate");
IDRegistry.genItemID("midasiumLeggings");
IDRegistry.genItemID("midasiumBoots");
IDRegistry.genItemID("vyroxeresHelmet");
IDRegistry.genItemID("vyroxeresChestplate");
IDRegistry.genItemID("vyroxeresLeggings");
IDRegistry.genItemID("vyroxeresBoots");
IDRegistry.genItemID("ceruclaseHelmet");
IDRegistry.genItemID("ceruclaseChestplate");
IDRegistry.genItemID("ceruclaseLeggings");
IDRegistry.genItemID("ceruclaseBoots");
IDRegistry.genItemID("inolashiteHelmet");
IDRegistry.genItemID("inolashiteChestplate");
IDRegistry.genItemID("inolashiteLeggings");
IDRegistry.genItemID("inolashiteBoots");
IDRegistry.genItemID("kalendriteHelmet");
IDRegistry.genItemID("kalendriteChestplate");
IDRegistry.genItemID("kalendriteLeggings");
IDRegistry.genItemID("kalendriteBoots");
IDRegistry.genItemID("amordrineHelmet");
IDRegistry.genItemID("amordrineChestplate");
IDRegistry.genItemID("amordrineLeggings");
IDRegistry.genItemID("amordrineBoots");
IDRegistry.genItemID("vulcaniteHelmet");
IDRegistry.genItemID("vulcaniteChestplate");
IDRegistry.genItemID("vulcaniteLeggings");
IDRegistry.genItemID("vulcaniteBoots");
IDRegistry.genItemID("sanguiniteHelmet");
IDRegistry.genItemID("sanguiniteChestplate");
IDRegistry.genItemID("sanguiniteLeggings");
IDRegistry.genItemID("sanguiniteBoots");
IDRegistry.genItemID("prometheumHelmet");
IDRegistry.genItemID("prometheumChestplate");
IDRegistry.genItemID("prometheumLeggings");
IDRegistry.genItemID("prometheumBoots");
IDRegistry.genItemID("deep_ironHelmet");
IDRegistry.genItemID("deep_ironChestplate");
IDRegistry.genItemID("deep_ironLeggings");
IDRegistry.genItemID("deep_ironBoots");
IDRegistry.genItemID("black_steelHelmet");
IDRegistry.genItemID("black_steelChestplate");
IDRegistry.genItemID("black_steelLeggings");
IDRegistry.genItemID("black_steelBoots");
IDRegistry.genItemID("oureclaseHelmet");
IDRegistry.genItemID("oureclaseChestplate");
IDRegistry.genItemID("oureclaseLeggings");
IDRegistry.genItemID("oureclaseBoots");
IDRegistry.genItemID("astral_silverHelmet");
IDRegistry.genItemID("astral_silverChestplate");
IDRegistry.genItemID("astral_silverLeggings");
IDRegistry.genItemID("astral_silverBoots");
IDRegistry.genItemID("carmotHelmet");
IDRegistry.genItemID("carmotChestplate");
IDRegistry.genItemID("carmotLeggings");
IDRegistry.genItemID("carmotBoots");
IDRegistry.genItemID("mithrilHelmet");
IDRegistry.genItemID("mithrilChestplate");
IDRegistry.genItemID("mithrilLeggings");
IDRegistry.genItemID("mithrilBoots");
IDRegistry.genItemID("quicksilverHelmet");
IDRegistry.genItemID("quicksilverChestplate");
IDRegistry.genItemID("quicksilverLeggings");
IDRegistry.genItemID("quicksilverBoots");
IDRegistry.genItemID("haderothHelmet");
IDRegistry.genItemID("haderothChestplate");
IDRegistry.genItemID("haderothLeggings");
IDRegistry.genItemID("haderothBoots");
IDRegistry.genItemID("orichalcumHelmet");
IDRegistry.genItemID("orichalcumChestplate");
IDRegistry.genItemID("orichalcumLeggings");
IDRegistry.genItemID("orichalcumBoots");
IDRegistry.genItemID("celenegilHelmet");
IDRegistry.genItemID("celenegilChestplate");
IDRegistry.genItemID("celenegilLeggings");
IDRegistry.genItemID("celenegilBoots");
IDRegistry.genItemID("adamantineHelmet");
IDRegistry.genItemID("adamantineChestplate");
IDRegistry.genItemID("adamantineLeggings");
IDRegistry.genItemID("adamantineBoots");
IDRegistry.genItemID("atlarusHelmet");
IDRegistry.genItemID("atlarusChestplate");
IDRegistry.genItemID("atlarusLeggings");
IDRegistry.genItemID("atlarusBoots");
IDRegistry.genItemID("tartariteHelmet");
IDRegistry.genItemID("tartariteChestplate");
IDRegistry.genItemID("tartariteLeggings");
IDRegistry.genItemID("tartariteBoots");
IDRegistry.genItemID("eximiteHelmet");
IDRegistry.genItemID("eximiteChestplate");
IDRegistry.genItemID("eximiteLeggings");
IDRegistry.genItemID("eximiteBoots");
IDRegistry.genItemID("desichalkosHelmet");
IDRegistry.genItemID("desichalkosChestplate");
IDRegistry.genItemID("desichalkosLeggings");
IDRegistry.genItemID("desichalkosBoots");
Item.createArmorItem("copperHelmet", "Copper Helmet", {name: "copper_helmet"}, {type: "helmet", armor: 2, durability: 110, texture: "armor/copper_layer_1.png"});
Item.createArmorItem("copperChestplate", "Copper Chestplate", {name: "copper_chestplate"}, {type: "chestplate", armor: 3, durability: 160, texture: "armor/copper_layer_1.png"});
Item.createArmorItem("copperLeggings", "Copper Leggings", {name: "copper_leggings"}, {type: "leggings", armor: 2, durability: 150, texture: "armor/copper_layer_2.png"});
Item.createArmorItem("copperBoots", "Copper Boots", {name: "copper_boots"}, {type: "boots", armor: 1, durability: 130, texture: "armor/copper_layer_1.png"});
Item.createArmorItem("bronzeHelmet", "Bronze Helmet", {name: "bronze_helmet"}, {type: "helmet", armor: 2, durability: 143, texture: "armor/bronze_layer_1.png"});
Item.createArmorItem("bronzeChestplate", "Bronze Chestplate", {name: "bronze_chestplate"}, {type: "chestplate", armor: 4, durability: 208, texture: "armor/bronze_layer_1.png"});
Item.createArmorItem("bronzeLeggings", "Bronze Leggings", {name: "bronze_leggings"}, {type: "leggings", armor: 3, durability: 195, texture: "armor/bronze_layer_2.png"});
Item.createArmorItem("bronzeBoots", "Bronze Boots", {name: "bronze_boots"}, {type: "boots", armor: 3, durability: 169, texture: "armor/bronze_layer_1.png"});
Item.createArmorItem("hepatizonHelmet", "Hepatizon Helmet", {name: "hepatizon_helmet"}, {type: "helmet", armor: 2, durability: 154, texture: "armor/hepatizon_layer_1.png"});
Item.createArmorItem("hepatizonChestplate", "Hepatizon Chestplate", {name: "hepatizon_chestplate"}, {type: "chestplate", armor: 4, durability: 224, texture: "armor/hepatizon_layer_1.png"});
Item.createArmorItem("hepatizonLeggings", "Hepatizon Leggings", {name: "hepatizon_leggings"}, {type: "leggings", armor: 3, durability: 210, texture: "armor/hepatizon_layer_2.png"});
Item.createArmorItem("hepatizonBoots", "Hepatizon Boots", {name: "hepatizon_boots"}, {type: "boots", armor: 3, durability: 182, texture: "armor/hepatizon_layer_1.png"});
Item.createArmorItem("damascus_steelHelmet", "Damascus_steel Helmet", {name: "damascus_steel_helmet"}, {type: "helmet", armor: 3, durability: 220, texture: "armor/damascus_steel_layer_1.png"});
Item.createArmorItem("damascus_steelChestplate", "Damascus_steel Chestplate", {name: "damascus_steel_chestplate"}, {type: "chestplate", armor: 6, durability: 320, texture: "armor/damascus_steel_layer_1.png"});
Item.createArmorItem("damascus_steelLeggings", "Damascus_steel Leggings", {name: "damascus_steel_leggings"}, {type: "leggings", armor: 5, durability: 300, texture: "armor/damascus_steel_layer_2.png"});
Item.createArmorItem("damascus_steelBoots", "Damascus_steel Boots", {name: "damascus_steel_boots"}, {type: "boots", armor: 3, durability: 260, texture: "armor/damascus_steel_layer_1.png"});
Item.createArmorItem("angmallenHelmet", "Angmallen Helmet", {name: "angmallen_helmet"}, {type: "helmet", armor: 3, durability: 198, texture: "armor/angmallen_layer_1.png"});
Item.createArmorItem("angmallenChestplate", "Angmallen Chestplate", {name: "angmallen_chestplate"}, {type: "chestplate", armor: 6, durability: 288, texture: "armor/angmallen_layer_1.png"});
Item.createArmorItem("angmallenLeggings", "Angmallen Leggings", {name: "angmallen_leggings"}, {type: "leggings", armor: 5, durability: 270, texture: "armor/angmallen_layer_2.png"});
Item.createArmorItem("angmallenBoots", "Angmallen Boots", {name: "angmallen_boots"}, {type: "boots", armor: 3, durability: 234, texture: "armor/angmallen_layer_1.png"});
Item.createArmorItem("steelHelmet", "Steel Helmet", {name: "steel_helmet"}, {type: "helmet", armor: 3, durability: 242, texture: "armor/steel_layer_1.png"});
Item.createArmorItem("steelChestplate", "Steel Chestplate", {name: "steel_chestplate"}, {type: "chestplate", armor: 6, durability: 352, texture: "armor/steel_layer_1.png"});
Item.createArmorItem("steelLeggings", "Steel Leggings", {name: "steel_leggings"}, {type: "leggings", armor: 5, durability: 330, texture: "armor/steel_layer_2.png"});
Item.createArmorItem("steelBoots", "Steel Boots", {name: "steel_boots"}, {type: "boots", armor: 3, durability: 286, texture: "armor/steel_layer_1.png"});
Item.createArmorItem("brassHelmet", "Brass Helmet", {name: "brass_helmet"}, {type: "helmet", armor: 2, durability: 33, texture: "armor/brass_layer_1.png"});
Item.createArmorItem("brassChestplate", "Brass Chestplate", {name: "brass_chestplate"}, {type: "chestplate", armor: 3, durability: 48, texture: "armor/brass_layer_1.png"});
Item.createArmorItem("brassLeggings", "Brass Leggings", {name: "brass_leggings"}, {type: "leggings", armor: 2, durability: 45, texture: "armor/brass_layer_2.png"});
Item.createArmorItem("brassBoots", "Brass Boots", {name: "brass_boots"}, {type: "boots", armor: 1, durability: 39, texture: "armor/brass_layer_1.png"});
Item.createArmorItem("silverHelmet", "Silver Helmet", {name: "silver_helmet"}, {type: "helmet", armor: 2, durability: 55, texture: "armor/silver_layer_1.png"});
Item.createArmorItem("silverChestplate", "Silver Chestplate", {name: "silver_chestplate"}, {type: "chestplate", armor: 4, durability: 80, texture: "armor/silver_layer_1.png"});
Item.createArmorItem("silverLeggings", "Silver Leggings", {name: "silver_leggings"}, {type: "leggings", armor: 3, durability: 75, texture: "armor/silver_layer_2.png"});
Item.createArmorItem("silverBoots", "Silver Boots", {name: "silver_boots"}, {type: "boots", armor: 2, durability: 65, texture: "armor/silver_layer_1.png"});
Item.createArmorItem("electrumHelmet", "Electrum Helmet", {name: "electrum_helmet"}, {type: "helmet", armor: 2, durability: 99, texture: "armor/electrum_layer_1.png"});
Item.createArmorItem("electrumChestplate", "Electrum Chestplate", {name: "electrum_chestplate"}, {type: "chestplate", armor: 6, durability: 144, texture: "armor/electrum_layer_1.png"});
Item.createArmorItem("electrumLeggings", "Electrum Leggings", {name: "electrum_leggings"}, {type: "leggings", armor: 5, durability: 135, texture: "armor/electrum_layer_2.png"});
Item.createArmorItem("electrumBoots", "Electrum Boots", {name: "electrum_boots"}, {type: "boots", armor: 2, durability: 117, texture: "armor/electrum_layer_1.png"});
Item.createArmorItem("platinumHelmet", "Platinum Helmet", {name: "platinum_helmet"}, {type: "helmet", armor: 3, durability: 121, texture: "armor/platinum_layer_1.png"});
Item.createArmorItem("platinumChestplate", "Platinum Chestplate", {name: "platinum_chestplate"}, {type: "chestplate", armor: 6, durability: 176, texture: "armor/platinum_layer_1.png"});
Item.createArmorItem("platinumLeggings", "Platinum Leggings", {name: "platinum_leggings"}, {type: "leggings", armor: 5, durability: 165, texture: "armor/platinum_layer_2.png"});
Item.createArmorItem("platinumBoots", "Platinum Boots", {name: "platinum_boots"}, {type: "boots", armor: 3, durability: 143, texture: "armor/platinum_layer_1.png"});
Item.createArmorItem("ignatiusHelmet", "Ignatius Helmet", {name: "ignatius_helmet"}, {type: "helmet", armor: 2, durability: 165, texture: "armor/ignatius_layer_1.png"});
Item.createArmorItem("ignatiusChestplate", "Ignatius Chestplate", {name: "ignatius_chestplate"}, {type: "chestplate", armor: 6, durability: 240, texture: "armor/ignatius_layer_1.png"});
Item.createArmorItem("ignatiusLeggings", "Ignatius Leggings", {name: "ignatius_leggings"}, {type: "leggings", armor: 5, durability: 225, texture: "armor/ignatius_layer_2.png"});
Item.createArmorItem("ignatiusBoots", "Ignatius Boots", {name: "ignatius_boots"}, {type: "boots", armor: 2, durability: 195, texture: "armor/ignatius_layer_1.png"});
Item.createArmorItem("shadow_ironHelmet", "Shadow_iron Helmet", {name: "shadow_iron_helmet"}, {type: "helmet", armor: 3, durability: 176, texture: "armor/shadow_iron_layer_1.png"});
Item.createArmorItem("shadow_ironChestplate", "Shadow_iron Chestplate", {name: "shadow_iron_chestplate"}, {type: "chestplate", armor: 6, durability: 256, texture: "armor/shadow_iron_layer_1.png"});
Item.createArmorItem("shadow_ironLeggings", "Shadow_iron Leggings", {name: "shadow_iron_leggings"}, {type: "leggings", armor: 5, durability: 240, texture: "armor/shadow_iron_layer_2.png"});
Item.createArmorItem("shadow_ironBoots", "Shadow_iron Boots", {name: "shadow_iron_boots"}, {type: "boots", armor: 2, durability: 208, texture: "armor/shadow_iron_layer_1.png"});
Item.createArmorItem("shadow_steelHelmet", "Shadow_steel Helmet", {name: "shadow_steel_helmet"}, {type: "helmet", armor: 3, durability: 220, texture: "armor/shadow_steel_layer_1.png"});
Item.createArmorItem("shadow_steelChestplate", "Shadow_steel Chestplate", {name: "shadow_steel_chestplate"}, {type: "chestplate", armor: 6, durability: 320, texture: "armor/shadow_steel_layer_1.png"});
Item.createArmorItem("shadow_steelLeggings", "Shadow_steel Leggings", {name: "shadow_steel_leggings"}, {type: "leggings", armor: 5, durability: 300, texture: "armor/shadow_steel_layer_2.png"});
Item.createArmorItem("shadow_steelBoots", "Shadow_steel Boots", {name: "shadow_steel_boots"}, {type: "boots", armor: 4, durability: 260, texture: "armor/shadow_steel_layer_1.png"});
Item.createArmorItem("midasiumHelmet", "Midasium Helmet", {name: "midasium_helmet"}, {type: "helmet", armor: 2, durability: 88, texture: "armor/midasium_layer_1.png"});
Item.createArmorItem("midasiumChestplate", "Midasium Chestplate", {name: "midasium_chestplate"}, {type: "chestplate", armor: 5, durability: 128, texture: "armor/midasium_layer_1.png"});
Item.createArmorItem("midasiumLeggings", "Midasium Leggings", {name: "midasium_leggings"}, {type: "leggings", armor: 3, durability: 120, texture: "armor/midasium_layer_2.png"});
Item.createArmorItem("midasiumBoots", "Midasium Boots", {name: "midasium_boots"}, {type: "boots", armor: 3, durability: 104, texture: "armor/midasium_layer_1.png"});
Item.createArmorItem("vyroxeresHelmet", "Vyroxeres Helmet", {name: "vyroxeres_helmet"}, {type: "helmet", armor: 3, durability: 253, texture: "armor/vyroxeres_layer_1.png"});
Item.createArmorItem("vyroxeresChestplate", "Vyroxeres Chestplate", {name: "vyroxeres_chestplate"}, {type: "chestplate", armor: 6, durability: 368, texture: "armor/vyroxeres_layer_1.png"});
Item.createArmorItem("vyroxeresLeggings", "Vyroxeres Leggings", {name: "vyroxeres_leggings"}, {type: "leggings", armor: 5, durability: 345, texture: "armor/vyroxeres_layer_2.png"});
Item.createArmorItem("vyroxeresBoots", "Vyroxeres Boots", {name: "vyroxeres_boots"}, {type: "boots", armor: 4, durability: 299, texture: "armor/vyroxeres_layer_1.png"});
Item.createArmorItem("ceruclaseHelmet", "Ceruclase Helmet", {name: "ceruclase_helmet"}, {type: "helmet", armor: 3, durability: 275, texture: "armor/ceruclase_layer_1.png"});
Item.createArmorItem("ceruclaseChestplate", "Ceruclase Chestplate", {name: "ceruclase_chestplate"}, {type: "chestplate", armor: 6, durability: 400, texture: "armor/ceruclase_layer_1.png"});
Item.createArmorItem("ceruclaseLeggings", "Ceruclase Leggings", {name: "ceruclase_leggings"}, {type: "leggings", armor: 5, durability: 375, texture: "armor/ceruclase_layer_2.png"});
Item.createArmorItem("ceruclaseBoots", "Ceruclase Boots", {name: "ceruclase_boots"}, {type: "boots", armor: 4, durability: 325, texture: "armor/ceruclase_layer_1.png"});
Item.createArmorItem("inolashiteHelmet", "Inolashite Helmet", {name: "inolashite_helmet"}, {type: "helmet", armor: 4, durability: 330, texture: "armor/inolashite_layer_1.png"});
Item.createArmorItem("inolashiteChestplate", "Inolashite Chestplate", {name: "inolashite_chestplate"}, {type: "chestplate", armor: 7, durability: 480, texture: "armor/inolashite_layer_1.png"});
Item.createArmorItem("inolashiteLeggings", "Inolashite Leggings", {name: "inolashite_leggings"}, {type: "leggings", armor: 5, durability: 450, texture: "armor/inolashite_layer_2.png"});
Item.createArmorItem("inolashiteBoots", "Inolashite Boots", {name: "inolashite_boots"}, {type: "boots", armor: 4, durability: 390, texture: "armor/inolashite_layer_1.png"});
Item.createArmorItem("kalendriteHelmet", "Kalendrite Helmet", {name: "kalendrite_helmet"}, {type: "helmet", armor: 4, durability: 308, texture: "armor/kalendrite_layer_1.png"});
Item.createArmorItem("kalendriteChestplate", "Kalendrite Chestplate", {name: "kalendrite_chestplate"}, {type: "chestplate", armor: 6, durability: 448, texture: "armor/kalendrite_layer_1.png"});
Item.createArmorItem("kalendriteLeggings", "Kalendrite Leggings", {name: "kalendrite_leggings"}, {type: "leggings", armor: 5, durability: 420, texture: "armor/kalendrite_layer_2.png"});
Item.createArmorItem("kalendriteBoots", "Kalendrite Boots", {name: "kalendrite_boots"}, {type: "boots", armor: 4, durability: 364, texture: "armor/kalendrite_layer_1.png"});
Item.createArmorItem("amordrineHelmet", "Amordrine Helmet", {name: "amordrine_helmet"}, {type: "helmet", armor: 4, durability: 352, texture: "armor/amordrine_layer_1.png"});
Item.createArmorItem("amordrineChestplate", "Amordrine Chestplate", {name: "amordrine_chestplate"}, {type: "chestplate", armor: 7, durability: 512, texture: "armor/amordrine_layer_1.png"});
Item.createArmorItem("amordrineLeggings", "Amordrine Leggings", {name: "amordrine_leggings"}, {type: "leggings", armor: 5, durability: 480, texture: "armor/amordrine_layer_2.png"});
Item.createArmorItem("amordrineBoots", "Amordrine Boots", {name: "amordrine_boots"}, {type: "boots", armor: 4, durability: 416, texture: "armor/amordrine_layer_1.png"});
Item.createArmorItem("vulcaniteHelmet", "Vulcanite Helmet", {name: "vulcanite_helmet"}, {type: "helmet", armor: 4, durability: 374, texture: "armor/vulcanite_layer_1.png"});
Item.createArmorItem("vulcaniteChestplate", "Vulcanite Chestplate", {name: "vulcanite_chestplate"}, {type: "chestplate", armor: 7, durability: 544, texture: "armor/vulcanite_layer_1.png"});
Item.createArmorItem("vulcaniteLeggings", "Vulcanite Leggings", {name: "vulcanite_leggings"}, {type: "leggings", armor: 6, durability: 510, texture: "armor/vulcanite_layer_2.png"});
Item.createArmorItem("vulcaniteBoots", "Vulcanite Boots", {name: "vulcanite_boots"}, {type: "boots", armor: 4, durability: 442, texture: "armor/vulcanite_layer_1.png"});
Item.createArmorItem("sanguiniteHelmet", "Sanguinite Helmet", {name: "sanguinite_helmet"}, {type: "helmet", armor: 5, durability: 396, texture: "armor/sanguinite_layer_1.png"});
Item.createArmorItem("sanguiniteChestplate", "Sanguinite Chestplate", {name: "sanguinite_chestplate"}, {type: "chestplate", armor: 7, durability: 576, texture: "armor/sanguinite_layer_1.png"});
Item.createArmorItem("sanguiniteLeggings", "Sanguinite Leggings", {name: "sanguinite_leggings"}, {type: "leggings", armor: 6, durability: 540, texture: "armor/sanguinite_layer_2.png"});
Item.createArmorItem("sanguiniteBoots", "Sanguinite Boots", {name: "sanguinite_boots"}, {type: "boots", armor: 4, durability: 468, texture: "armor/sanguinite_layer_1.png"});
Item.createArmorItem("prometheumHelmet", "Prometheum Helmet", {name: "prometheum_helmet"}, {type: "helmet", armor: 2, durability: 99, texture: "armor/prometheum_layer_1.png"});
Item.createArmorItem("prometheumChestplate", "Prometheum Chestplate", {name: "prometheum_chestplate"}, {type: "chestplate", armor: 3, durability: 144, texture: "armor/prometheum_layer_1.png"});
Item.createArmorItem("prometheumLeggings", "Prometheum Leggings", {name: "prometheum_leggings"}, {type: "leggings", armor: 2, durability: 135, texture: "armor/prometheum_layer_2.png"});
Item.createArmorItem("prometheumBoots", "Prometheum Boots", {name: "prometheum_boots"}, {type: "boots", armor: 1, durability: 117, texture: "armor/prometheum_layer_1.png"});
Item.createArmorItem("deep_ironHelmet", "Deep_iron Helmet", {name: "deep_iron_helmet"}, {type: "helmet", armor: 2, durability: 154, texture: "armor/deep_iron_layer_1.png"});
Item.createArmorItem("deep_ironChestplate", "Deep_iron Chestplate", {name: "deep_iron_chestplate"}, {type: "chestplate", armor: 6, durability: 224, texture: "armor/deep_iron_layer_1.png"});
Item.createArmorItem("deep_ironLeggings", "Deep_iron Leggings", {name: "deep_iron_leggings"}, {type: "leggings", armor: 5, durability: 210, texture: "armor/deep_iron_layer_2.png"});
Item.createArmorItem("deep_ironBoots", "Deep_iron Boots", {name: "deep_iron_boots"}, {type: "boots", armor: 2, durability: 182, texture: "armor/deep_iron_layer_1.png"});
Item.createArmorItem("black_steelHelmet", "Black_steel Helmet", {name: "black_steel_helmet"}, {type: "helmet", armor: 3, durability: 242, texture: "armor/black_steel_layer_1.png"});
Item.createArmorItem("black_steelChestplate", "Black_steel Chestplate", {name: "black_steel_chestplate"}, {type: "chestplate", armor: 6, durability: 352, texture: "armor/black_steel_layer_1.png"});
Item.createArmorItem("black_steelLeggings", "Black_steel Leggings", {name: "black_steel_leggings"}, {type: "leggings", armor: 5, durability: 330, texture: "armor/black_steel_layer_2.png"});
Item.createArmorItem("black_steelBoots", "Black_steel Boots", {name: "black_steel_boots"}, {type: "boots", armor: 3, durability: 286, texture: "armor/black_steel_layer_1.png"});
Item.createArmorItem("oureclaseHelmet", "Oureclase Helmet", {name: "oureclase_helmet"}, {type: "helmet", armor: 3, durability: 220, texture: "armor/oureclase_layer_1.png"});
Item.createArmorItem("oureclaseChestplate", "Oureclase Chestplate", {name: "oureclase_chestplate"}, {type: "chestplate", armor: 6, durability: 320, texture: "armor/oureclase_layer_1.png"});
Item.createArmorItem("oureclaseLeggings", "Oureclase Leggings", {name: "oureclase_leggings"}, {type: "leggings", armor: 5, durability: 300, texture: "armor/oureclase_layer_2.png"});
Item.createArmorItem("oureclaseBoots", "Oureclase Boots", {name: "oureclase_boots"}, {type: "boots", armor: 4, durability: 260, texture: "armor/oureclase_layer_1.png"});
Item.createArmorItem("astral_silverHelmet", "Astral_silver Helmet", {name: "astral_silver_helmet"}, {type: "helmet", armor: 2, durability: 110, texture: "armor/astral_silver_layer_1.png"});
Item.createArmorItem("astral_silverChestplate", "Astral_silver Chestplate", {name: "astral_silver_chestplate"}, {type: "chestplate", armor: 6, durability: 160, texture: "armor/astral_silver_layer_1.png"});
Item.createArmorItem("astral_silverLeggings", "Astral_silver Leggings", {name: "astral_silver_leggings"}, {type: "leggings", armor: 5, durability: 150, texture: "armor/astral_silver_layer_2.png"});
Item.createArmorItem("astral_silverBoots", "Astral_silver Boots", {name: "astral_silver_boots"}, {type: "boots", armor: 2, durability: 130, texture: "armor/astral_silver_layer_1.png"});
Item.createArmorItem("carmotHelmet", "Carmot Helmet", {name: "carmot_helmet"}, {type: "helmet", armor: 3, durability: 132, texture: "armor/carmot_layer_1.png"});
Item.createArmorItem("carmotChestplate", "Carmot Chestplate", {name: "carmot_chestplate"}, {type: "chestplate", armor: 6, durability: 192, texture: "armor/carmot_layer_1.png"});
Item.createArmorItem("carmotLeggings", "Carmot Leggings", {name: "carmot_leggings"}, {type: "leggings", armor: 5, durability: 180, texture: "armor/carmot_layer_2.png"});
Item.createArmorItem("carmotBoots", "Carmot Boots", {name: "carmot_boots"}, {type: "boots", armor: 3, durability: 156, texture: "armor/carmot_layer_1.png"});
Item.createArmorItem("mithrilHelmet", "Mithril Helmet", {name: "mithril_helmet"}, {type: "helmet", armor: 4, durability: 308, texture: "armor/mithril_layer_1.png"});
Item.createArmorItem("mithrilChestplate", "Mithril Chestplate", {name: "mithril_chestplate"}, {type: "chestplate", armor: 6, durability: 448, texture: "armor/mithril_layer_1.png"});
Item.createArmorItem("mithrilLeggings", "Mithril Leggings", {name: "mithril_leggings"}, {type: "leggings", armor: 5, durability: 420, texture: "armor/mithril_layer_2.png"});
Item.createArmorItem("mithrilBoots", "Mithril Boots", {name: "mithril_boots"}, {type: "boots", armor: 4, durability: 364, texture: "armor/mithril_layer_1.png"});
Item.createArmorItem("quicksilverHelmet", "Quicksilver Helmet", {name: "quicksilver_helmet"}, {type: "helmet", armor: 4, durability: 330, texture: "armor/quicksilver_layer_1.png"});
Item.createArmorItem("quicksilverChestplate", "Quicksilver Chestplate", {name: "quicksilver_chestplate"}, {type: "chestplate", armor: 7, durability: 480, texture: "armor/quicksilver_layer_1.png"});
Item.createArmorItem("quicksilverLeggings", "Quicksilver Leggings", {name: "quicksilver_leggings"}, {type: "leggings", armor: 5, durability: 450, texture: "armor/quicksilver_layer_2.png"});
Item.createArmorItem("quicksilverBoots", "Quicksilver Boots", {name: "quicksilver_boots"}, {type: "boots", armor: 4, durability: 390, texture: "armor/quicksilver_layer_1.png"});
Item.createArmorItem("haderothHelmet", "Haderoth Helmet", {name: "haderoth_helmet"}, {type: "helmet", armor: 4, durability: 352, texture: "armor/haderoth_layer_1.png"});
Item.createArmorItem("haderothChestplate", "Haderoth Chestplate", {name: "haderoth_chestplate"}, {type: "chestplate", armor: 7, durability: 512, texture: "armor/haderoth_layer_1.png"});
Item.createArmorItem("haderothLeggings", "Haderoth Leggings", {name: "haderoth_leggings"}, {type: "leggings", armor: 5, durability: 480, texture: "armor/haderoth_layer_2.png"});
Item.createArmorItem("haderothBoots", "Haderoth Boots", {name: "haderoth_boots"}, {type: "boots", armor: 4, durability: 416, texture: "armor/haderoth_layer_1.png"});
Item.createArmorItem("orichalcumHelmet", "Orichalcum Helmet", {name: "orichalcum_helmet"}, {type: "helmet", armor: 4, durability: 374, texture: "armor/orichalcum_layer_1.png"});
Item.createArmorItem("orichalcumChestplate", "Orichalcum Chestplate", {name: "orichalcum_chestplate"}, {type: "chestplate", armor: 7, durability: 544, texture: "armor/orichalcum_layer_1.png"});
Item.createArmorItem("orichalcumLeggings", "Orichalcum Leggings", {name: "orichalcum_leggings"}, {type: "leggings", armor: 6, durability: 510, texture: "armor/orichalcum_layer_2.png"});
Item.createArmorItem("orichalcumBoots", "Orichalcum Boots", {name: "orichalcum_boots"}, {type: "boots", armor: 4, durability: 442, texture: "armor/orichalcum_layer_1.png"});
Item.createArmorItem("celenegilHelmet", "Celenegil Helmet", {name: "celenegil_helmet"}, {type: "helmet", armor: 5, durability: 396, texture: "armor/celenegil_layer_1.png"});
Item.createArmorItem("celenegilChestplate", "Celenegil Chestplate", {name: "celenegil_chestplate"}, {type: "chestplate", armor: 7, durability: 576, texture: "armor/celenegil_layer_1.png"});
Item.createArmorItem("celenegilLeggings", "Celenegil Leggings", {name: "celenegil_leggings"}, {type: "leggings", armor: 6, durability: 540, texture: "armor/celenegil_layer_2.png"});
Item.createArmorItem("celenegilBoots", "Celenegil Boots", {name: "celenegil_boots"}, {type: "boots", armor: 4, durability: 468, texture: "armor/celenegil_layer_1.png"});
Item.createArmorItem("adamantineHelmet", "Adamantine Helmet", {name: "adamantine_helmet"}, {type: "helmet", armor: 5, durability: 418, texture: "armor/adamantine_layer_1.png"});
Item.createArmorItem("adamantineChestplate", "Adamantine Chestplate", {name: "adamantine_chestplate"}, {type: "chestplate", armor: 7, durability: 608, texture: "armor/adamantine_layer_1.png"});
Item.createArmorItem("adamantineLeggings", "Adamantine Leggings", {name: "adamantine_leggings"}, {type: "leggings", armor: 6, durability: 570, texture: "armor/adamantine_layer_2.png"});
Item.createArmorItem("adamantineBoots", "Adamantine Boots", {name: "adamantine_boots"}, {type: "boots", armor: 4, durability: 494, texture: "armor/adamantine_layer_1.png"});
Item.createArmorItem("atlarusHelmet", "Atlarus Helmet", {name: "atlarus_helmet"}, {type: "helmet", armor: 5, durability: 440, texture: "armor/atlarus_layer_1.png"});
Item.createArmorItem("atlarusChestplate", "Atlarus Chestplate", {name: "atlarus_chestplate"}, {type: "chestplate", armor: 7, durability: 640, texture: "armor/atlarus_layer_1.png"});
Item.createArmorItem("atlarusLeggings", "Atlarus Leggings", {name: "atlarus_leggings"}, {type: "leggings", armor: 6, durability: 600, texture: "armor/atlarus_layer_2.png"});
Item.createArmorItem("atlarusBoots", "Atlarus Boots", {name: "atlarus_boots"}, {type: "boots", armor: 4, durability: 520, texture: "armor/atlarus_layer_1.png"});
Item.createArmorItem("tartariteHelmet", "Tartarite Helmet", {name: "tartarite_helmet"}, {type: "helmet", armor: 5, durability: 462, texture: "armor/tartarite_layer_1.png"});
Item.createArmorItem("tartariteChestplate", "Tartarite Chestplate", {name: "tartarite_chestplate"}, {type: "chestplate", armor: 7, durability: 672, texture: "armor/tartarite_layer_1.png"});
Item.createArmorItem("tartariteLeggings", "Tartarite Leggings", {name: "tartarite_leggings"}, {type: "leggings", armor: 6, durability: 630, texture: "armor/tartarite_layer_2.png"});
Item.createArmorItem("tartariteBoots", "Tartarite Boots", {name: "tartarite_boots"}, {type: "boots", armor: 5, durability: 546, texture: "armor/tartarite_layer_1.png"});
Item.createArmorItem("eximiteHelmet", "Eximite Helmet", {name: "eximite_helmet"}, {type: "helmet", armor: 4, durability: 264, texture: "armor/eximite_layer_1.png"});
Item.createArmorItem("eximiteChestplate", "Eximite Chestplate", {name: "eximite_chestplate"}, {type: "chestplate", armor: 6, durability: 384, texture: "armor/eximite_layer_1.png"});
Item.createArmorItem("eximiteLeggings", "Eximite Leggings", {name: "eximite_leggings"}, {type: "leggings", armor: 5, durability: 360, texture: "armor/eximite_layer_2.png"});
Item.createArmorItem("eximiteBoots", "Eximite Boots", {name: "eximite_boots"}, {type: "boots", armor: 4, durability: 312, texture: "armor/eximite_layer_1.png"});
Item.createArmorItem("desichalkosHelmet", "Desichalkos Helmet", {name: "desichalkos_helmet"}, {type: "helmet", armor: 4, durability: 330, texture: "armor/desichalkos_layer_1.png"});
Item.createArmorItem("desichalkosChestplate", "Desichalkos Chestplate", {name: "desichalkos_chestplate"}, {type: "chestplate", armor: 7, durability: 480, texture: "armor/desichalkos_layer_1.png"});
Item.createArmorItem("desichalkosLeggings", "Desichalkos Leggings", {name: "desichalkos_leggings"}, {type: "leggings", armor: 5, durability: 450, texture: "armor/desichalkos_layer_2.png"});
Item.createArmorItem("desichalkosBoots", "Desichalkos Boots", {name: "desichalkos_boots"}, {type: "boots", armor: 4, durability: 390, texture: "armor/desichalkos_layer_1.png"});

