IMPORT("MTL");
IDRegistry.genBlockID("copper_ore");
Block.createBlock("copper_ore", [{name: "Copper Ore", texture: [["copper_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.copper_ore, "stone", 2, true);
Block.setDestroyLevel("copper_ore", 2);
IDRegistry.genBlockID("tin_ore");
Block.createBlock("tin_ore", [{name: "Tin Ore", texture: [["tin_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.tin_ore, "stone", 2, true);
Block.setDestroyLevel("tin_ore", 2);
IDRegistry.genBlockID("manganese_ore");
Block.createBlock("manganese_ore", [{name: "Manganese Ore", texture: [["manganese_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.manganese_ore, "stone", 3, true);
Block.setDestroyLevel("manganese_ore", 3);
IDRegistry.genBlockID("zinc_ore");
Block.createBlock("zinc_ore", [{name: "Zinc Ore", texture: [["zinc_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.zinc_ore, "stone", 1, true);
Block.setDestroyLevel("zinc_ore", 1);
IDRegistry.genBlockID("silver_ore");
Block.createBlock("silver_ore", [{name: "Silver Ore", texture: [["silver_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.silver_ore, "stone", 2, true);
Block.setDestroyLevel("silver_ore", 2);
IDRegistry.genBlockID("platinum_ore");
Block.createBlock("platinum_ore", [{name: "Platinum Ore", texture: [["platinum_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.platinum_ore, "stone", 3, true);
Block.setDestroyLevel("platinum_ore", 3);
IDRegistry.genBlockID("prometheum_ore");
Block.createBlock("prometheum_ore", [{name: "Prometheum Ore", texture: [["prometheum_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.prometheum_ore, "stone", 2, true);
Block.setDestroyLevel("prometheum_ore", 2);
IDRegistry.genBlockID("deep_iron_ore");
Block.createBlock("deep_iron_ore", [{name: "Deep Iron Ore", texture: [["deep_iron_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.deep_iron_ore, "stone", 2, true);
Block.setDestroyLevel("deep_iron_ore", 2);
IDRegistry.genBlockID("infuscolium_ore");
Block.createBlock("infuscolium_ore", [{name: "Infuscolium Ore", texture: [["infuscolium_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.infuscolium_ore, "stone", 2, true);
Block.setDestroyLevel("infuscolium_ore", 2);
IDRegistry.genBlockID("oureclase_ore");
Block.createBlock("oureclase_ore", [{name: "Oureclase Ore", texture: [["oureclase_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.oureclase_ore, "stone", 3, true);
Block.setDestroyLevel("oureclase_ore", 3);
IDRegistry.genBlockID("astral_silver_ore");
Block.createBlock("astral_silver_ore", [{name: "Astral Silver Ore", texture: [["astral_silver_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.astral_silver_ore, "stone", 4, true);
Block.setDestroyLevel("astral_silver_ore", 4);
IDRegistry.genBlockID("carmot_ore");
Block.createBlock("carmot_ore", [{name: "Carmot Ore", texture: [["carmot_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.carmot_ore, "stone", 4, true);
Block.setDestroyLevel("carmot_ore", 4);
IDRegistry.genBlockID("mithril_ore");
Block.createBlock("mithril_ore", [{name: "Mithril Ore", texture: [["mithril_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.mithril_ore, "stone", 4, true);
Block.setDestroyLevel("mithril_ore", 4);
IDRegistry.genBlockID("rubracium_ore");
Block.createBlock("rubracium_ore", [{name: "Rubracium Ore", texture: [["rubracium_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.rubracium_ore, "stone", 4, true);
Block.setDestroyLevel("rubracium_ore", 4);
IDRegistry.genBlockID("orichalcum_ore");
Block.createBlock("orichalcum_ore", [{name: "Orichalcum Ore", texture: [["orichalcum_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.orichalcum_ore, "stone", 5, true);
Block.setDestroyLevel("orichalcum_ore", 5);
IDRegistry.genBlockID("adamantine_ore");
Block.createBlock("adamantine_ore", [{name: "Adamantine Ore", texture: [["adamantine_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.adamantine_ore, "stone", 6, true);
Block.setDestroyLevel("adamantine_ore", 6);
IDRegistry.genBlockID("atlarus_ore");
Block.createBlock("atlarus_ore", [{name: "Atlarus Ore", texture: [["atlarus_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.atlarus_ore, "stone", 6, true);
Block.setDestroyLevel("atlarus_ore", 6);
IDRegistry.genBlockID("ignatius_ore");
Block.createBlock("ignatius_ore", [{name: "Ignatius Ore", texture: [["ignatius_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.ignatius_ore, "stone", 2, true);
Block.setDestroyLevel("ignatius_ore", 2);
IDRegistry.genBlockID("shadow_iron_ore");
Block.createBlock("shadow_iron_ore", [{name: "Shadow Iron Ore", texture: [["shadow_iron_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.shadow_iron_ore, "stone", 2, true);
Block.setDestroyLevel("shadow_iron_ore", 2);
IDRegistry.genBlockID("lemurite_ore");
Block.createBlock("lemurite_ore", [{name: "Lemurite Ore", texture: [["lemurite_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.lemurite_ore, "stone", 2, true);
Block.setDestroyLevel("lemurite_ore", 2);
IDRegistry.genBlockID("midasium_ore");
Block.createBlock("midasium_ore", [{name: "Midasium Ore", texture: [["midasium_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.midasium_ore, "stone", 3, true);
Block.setDestroyLevel("midasium_ore", 3);
IDRegistry.genBlockID("vyroxeres_ore");
Block.createBlock("vyroxeres_ore", [{name: "Vyroxeres Ore", texture: [["vyroxeres_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.vyroxeres_ore, "stone", 3, true);
Block.setDestroyLevel("vyroxeres_ore", 3);
IDRegistry.genBlockID("ceruclase_ore");
Block.createBlock("ceruclase_ore", [{name: "Ceruclase Ore", texture: [["ceruclase_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.ceruclase_ore, "stone", 3, true);
Block.setDestroyLevel("ceruclase_ore", 3);
IDRegistry.genBlockID("alduorite_ore");
Block.createBlock("alduorite_ore", [{name: "Alduorite Ore", texture: [["alduorite_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.alduorite_ore, "stone", 3, true);
Block.setDestroyLevel("alduorite_ore", 3);
IDRegistry.genBlockID("kalendrite_ore");
Block.createBlock("kalendrite_ore", [{name: "Kalendrite Ore", texture: [["kalendrite_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.kalendrite_ore, "stone", 4, true);
Block.setDestroyLevel("kalendrite_ore", 4);
IDRegistry.genBlockID("vulcanite_ore");
Block.createBlock("vulcanite_ore", [{name: "Vulcanite Ore", texture: [["vulcanite_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.vulcanite_ore, "stone", 5, true);
Block.setDestroyLevel("vulcanite_ore", 5);
IDRegistry.genBlockID("sanguinite_ore");
Block.createBlock("sanguinite_ore", [{name: "Sanguinite Ore", texture: [["sanguinite_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.sanguinite_ore, "stone", 6, true);
Block.setDestroyLevel("sanguinite_ore", 6);
IDRegistry.genBlockID("eximite_ore");
Block.createBlock("eximite_ore", [{name: "Eximite Ore", texture: [["eximite_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.eximite_ore, "stone", 4, true);
Block.setDestroyLevel("eximite_ore", 4);
IDRegistry.genBlockID("meutoite_ore");
Block.createBlock("meutoite_ore", [{name: "Meutoite Ore", texture: [["meutoite_ore", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.meutoite_ore, "stone", 4, true);
Block.setDestroyLevel("meutoite_ore", 4);

