IDRegistry.genItemID("copper_nugget");
Item.createItem("copper_nugget", "Copper Nugget", {name: "copper_nugget", meta: 0}, {});
IDRegistry.genItemID("copper_dust");
Item.createItem("copper_dust", "Copper Dust", {name: "copper_dust", meta: 0}, {});
IDRegistry.genItemID("copper_ingot");
Item.createItem("copper_ingot", "Copper Ingot", {name: "copper_ingot", meta: 0}, {});
IDRegistry.genItemID("manganese_nugget");
Item.createItem("manganese_nugget", "Manganese Nugget", {name: "manganese_nugget", meta: 0}, {});
IDRegistry.genItemID("manganese_dust");
Item.createItem("manganese_dust", "Manganese Dust", {name: "manganese_dust", meta: 0}, {});
IDRegistry.genItemID("manganese_ingot");
Item.createItem("manganese_ingot", "Manganese Ingot", {name: "manganese_ingot", meta: 0}, {});
IDRegistry.genItemID("tin_nugget");
Item.createItem("tin_nugget", "Tin Nugget", {name: "tin_nugget", meta: 0}, {});
IDRegistry.genItemID("tin_dust");
Item.createItem("tin_dust", "Tin Dust", {name: "tin_dust", meta: 0}, {});
IDRegistry.genItemID("tin_ingot");
Item.createItem("tin_ingot", "Tin Ingot", {name: "tin_ingot", meta: 0}, {});
IDRegistry.genItemID("zinc_nugget");
Item.createItem("zinc_nugget", "Zinc Nugget", {name: "zinc_nugget", meta: 0}, {});
IDRegistry.genItemID("zinc_dust");
Item.createItem("zinc_dust", "Zinc Dust", {name: "zinc_dust", meta: 0}, {});
IDRegistry.genItemID("zinc_ingot");
Item.createItem("zinc_ingot", "Zinc Ingot", {name: "zinc_ingot", meta: 0}, {});
IDRegistry.genItemID("prometheum_nugget");
Item.createItem("prometheum_nugget", "Prometheum Nugget", {name: "prometheum_nugget", meta: 0}, {});
IDRegistry.genItemID("prometheum_dust");
Item.createItem("prometheum_dust", "Prometheum Dust", {name: "prometheum_dust", meta: 0}, {});
IDRegistry.genItemID("prometheum_ingot");
Item.createItem("prometheum_ingot", "Prometheum Ingot", {name: "prometheum_ingot", meta: 0}, {});
IDRegistry.genItemID("deep_iron_nugget");
Item.createItem("deep_iron_nugget", "Deep Iron Nugget", {name: "deep_iron_nugget", meta: 0}, {});
IDRegistry.genItemID("deep_iron_dust");
Item.createItem("deep_iron_dust", "Deep Iron Dust", {name: "deep_iron_dust", meta: 0}, {});
IDRegistry.genItemID("deep_iron_ingot");
Item.createItem("deep_iron_ingot", "Deep Iron Ingot", {name: "deep_iron_ingot", meta: 0}, {});
IDRegistry.genItemID("infuscolium_nugget");
Item.createItem("infuscolium_nugget", "Infuscolium Nugget", {name: "infuscolium_nugget", meta: 0}, {});
IDRegistry.genItemID("infuscolium_dust");
Item.createItem("infuscolium_dust", "Infuscolium Dust", {name: "infuscolium_dust", meta: 0}, {});
IDRegistry.genItemID("infuscolium_ingot");
Item.createItem("infuscolium_ingot", "Infuscolium Ingot", {name: "infuscolium_ingot", meta: 0}, {});
IDRegistry.genItemID("oureclase_nugget");
Item.createItem("oureclase_nugget", "Oureclase Nugget", {name: "oureclase_nugget", meta: 0}, {});
IDRegistry.genItemID("oureclase_dust");
Item.createItem("oureclase_dust", "Oureclase Dust", {name: "oureclase_dust", meta: 0}, {});
IDRegistry.genItemID("oureclase_ingot");
Item.createItem("oureclase_ingot", "Oureclase Ingot", {name: "oureclase_ingot", meta: 0}, {});
IDRegistry.genItemID("rubracium_nugget");
Item.createItem("rubracium_nugget", "Rubracium Nugget", {name: "rubracium_nugget", meta: 0}, {});
IDRegistry.genItemID("rubracium_dust");
Item.createItem("rubracium_dust", "Rubracium Dust", {name: "rubracium_dust", meta: 0}, {});
IDRegistry.genItemID("rubracium_ingot");
Item.createItem("rubracium_ingot", "Rubracium Ingot", {name: "rubracium_ingot", meta: 0}, {});
IDRegistry.genItemID("carmot_nugget");
Item.createItem("carmot_nugget", "Carmot Nugget", {name: "carmot_nugget", meta: 0}, {});
IDRegistry.genItemID("carmot_dust");
Item.createItem("carmot_dust", "Carmot Dust", {name: "carmot_dust", meta: 0}, {});
IDRegistry.genItemID("carmot_ingot");
Item.createItem("carmot_ingot", "Carmot Ingot", {name: "carmot_ingot", meta: 0}, {});
IDRegistry.genItemID("orichalcum_nugget");
Item.createItem("orichalcum_nugget", "Orichalcum Nugget", {name: "orichalcum_nugget", meta: 0}, {});
IDRegistry.genItemID("orichalcum_dust");
Item.createItem("orichalcum_dust", "Orichalcum Dust", {name: "orichalcum_dust", meta: 0}, {});
IDRegistry.genItemID("orichalcum_ingot");
Item.createItem("orichalcum_ingot", "Orichalcum Ingot", {name: "orichalcum_ingot", meta: 0}, {});
IDRegistry.genItemID("silver_nugget");
Item.createItem("silver_nugget", "Silver Nugget", {name: "silver_nugget", meta: 0}, {});
IDRegistry.genItemID("silver_dust");
Item.createItem("silver_dust", "Silver Dust", {name: "silver_dust", meta: 0}, {});
IDRegistry.genItemID("silver_ingot");
Item.createItem("silver_ingot", "Silver Ingot", {name: "silver_ingot", meta: 0}, {});
IDRegistry.genItemID("adamantine_nugget");
Item.createItem("adamantine_nugget", "Adamantine Nugget", {name: "adamantine_nugget", meta: 0}, {});
IDRegistry.genItemID("adamantine_dust");
Item.createItem("adamantine_dust", "Adamantine Dust", {name: "adamantine_dust", meta: 0}, {});
IDRegistry.genItemID("adamantine_ingot");
Item.createItem("adamantine_ingot", "Adamantine Ingot", {name: "adamantine_ingot", meta: 0}, {});
IDRegistry.genItemID("atlarus_nugget");
Item.createItem("atlarus_nugget", "Atlarus Nugget", {name: "atlarus_nugget", meta: 0}, {});
IDRegistry.genItemID("atlarus_dust");
Item.createItem("atlarus_dust", "Atlarus Dust", {name: "atlarus_dust", meta: 0}, {});
IDRegistry.genItemID("atlarus_ingot");
Item.createItem("atlarus_ingot", "Atlarus Ingot", {name: "atlarus_ingot", meta: 0}, {});
IDRegistry.genItemID("astral_silver_nugget");
Item.createItem("astral_silver_nugget", "Astral Silver Nugget", {name: "astral_silver_nugget", meta: 0}, {});
IDRegistry.genItemID("astral_silver_dust");
Item.createItem("astral_silver_dust", "Astral Silver Dust", {name: "astral_silver_dust", meta: 0}, {});
IDRegistry.genItemID("astral_silver_ingot");
Item.createItem("astral_silver_ingot", "Astral Silver Ingot", {name: "astral_silver_ingot", meta: 0}, {});
IDRegistry.genItemID("platinum_nugget");
Item.createItem("platinum_nugget", "Platinum Nugget", {name: "platinum_nugget", meta: 0}, {});
IDRegistry.genItemID("platinum_dust");
Item.createItem("platinum_dust", "Platinum Dust", {name: "platinum_dust", meta: 0}, {});
IDRegistry.genItemID("platinum_ingot");
Item.createItem("platinum_ingot", "Platinum Ingot", {name: "platinum_ingot", meta: 0}, {});
IDRegistry.genItemID("mithril_nugget");
Item.createItem("mithril_nugget", "Mithril Nugget", {name: "mithril_nugget", meta: 0}, {});
IDRegistry.genItemID("mithril_dust");
Item.createItem("mithril_dust", "Mithril Dust", {name: "mithril_dust", meta: 0}, {});
IDRegistry.genItemID("mithril_ingot");
Item.createItem("mithril_ingot", "Mithril Ingot", {name: "mithril_ingot", meta: 0}, {});
IDRegistry.genItemID("ignatius_nugget");
Item.createItem("ignatius_nugget", "Ignatius Nugget", {name: "ignatius_nugget", meta: 0}, {});
IDRegistry.genItemID("ignatius_dust");
Item.createItem("ignatius_dust", "Ignatius Dust", {name: "ignatius_dust", meta: 0}, {});
IDRegistry.genItemID("ignatius_ingot");
Item.createItem("ignatius_ingot", "Ignatius Ingot", {name: "ignatius_ingot", meta: 0}, {});
IDRegistry.genItemID("shadow_iron_nugget");
Item.createItem("shadow_iron_nugget", "Shadow Iron Nugget", {name: "shadow_iron_nugget", meta: 0}, {});
IDRegistry.genItemID("shadow_iron_dust");
Item.createItem("shadow_iron_dust", "Shadow Iron Dust", {name: "shadow_iron_dust", meta: 0}, {});
IDRegistry.genItemID("shadow_iron_ingot");
Item.createItem("shadow_iron_ingot", "Shadow Iron Ingot", {name: "shadow_iron_ingot", meta: 0}, {});
IDRegistry.genItemID("lemurite_nugget");
Item.createItem("lemurite_nugget", "Lemurite Nugget", {name: "lemurite_nugget", meta: 0}, {});
IDRegistry.genItemID("lemurite_dust");
Item.createItem("lemurite_dust", "Lemurite Dust", {name: "lemurite_dust", meta: 0}, {});
IDRegistry.genItemID("lemurite_ingot");
Item.createItem("lemurite_ingot", "Lemurite Ingot", {name: "lemurite_ingot", meta: 0}, {});
IDRegistry.genItemID("midasium_nugget");
Item.createItem("midasium_nugget", "Midasium Nugget", {name: "midasium_nugget", meta: 0}, {});
IDRegistry.genItemID("midasium_dust");
Item.createItem("midasium_dust", "Midasium Dust", {name: "midasium_dust", meta: 0}, {});
IDRegistry.genItemID("midasium_ingot");
Item.createItem("midasium_ingot", "Midasium Ingot", {name: "midasium_ingot", meta: 0}, {});
IDRegistry.genItemID("vyroxeres_nugget");
Item.createItem("vyroxeres_nugget", "Vyroxeres Nugget", {name: "vyroxeres_nugget", meta: 0}, {});
IDRegistry.genItemID("vyroxeres_dust");
Item.createItem("vyroxeres_dust", "Vyroxeres Dust", {name: "vyroxeres_dust", meta: 0}, {});
IDRegistry.genItemID("vyroxeres_ingot");
Item.createItem("vyroxeres_ingot", "Vyroxeres Ingot", {name: "vyroxeres_ingot", meta: 0}, {});
IDRegistry.genItemID("alduorite_nugget");
Item.createItem("alduorite_nugget", "Alduorite Nugget", {name: "alduorite_nugget", meta: 0}, {});
IDRegistry.genItemID("alduorite_dust");
Item.createItem("alduorite_dust", "Alduorite Dust", {name: "alduorite_dust", meta: 0}, {});
IDRegistry.genItemID("alduorite_ingot");
Item.createItem("alduorite_ingot", "Alduorite Ingot", {name: "alduorite_ingot", meta: 0}, {});
IDRegistry.genItemID("ignatius_nugget");
Item.createItem("ignatius_nugget", "Ignatius Nugget", {name: "ignatius_nugget", meta: 0}, {});
IDRegistry.genItemID("ignatius_dust");
Item.createItem("ignatius_dust", "Ignatius Dust", {name: "ignatius_dust", meta: 0}, {});
IDRegistry.genItemID("ignatius_ingot");
Item.createItem("ignatius_ingot", "Ignatius Ingot", {name: "ignatius_ingot", meta: 0}, {});
IDRegistry.genItemID("kalendrite_nugget");
Item.createItem("kalendrite_nugget", "Kalendrite Nugget", {name: "kalendrite_nugget", meta: 0}, {});
IDRegistry.genItemID("kalendrite_dust");
Item.createItem("kalendrite_dust", "Kalendrite Dust", {name: "kalendrite_dust", meta: 0}, {});
IDRegistry.genItemID("kalendrite_ingot");
Item.createItem("kalendrite_ingot", "Kalendrite Ingot", {name: "kalendrite_ingot", meta: 0}, {});
IDRegistry.genItemID("vulcanite_nugget");
Item.createItem("vulcanite_nugget", "Vulcanite Nugget", {name: "vulcanite_nugget", meta: 0}, {});
IDRegistry.genItemID("vulcanite_dust");
Item.createItem("vulcanite_dust", "Vulcanite Dust", {name: "vulcanite_dust", meta: 0}, {});
IDRegistry.genItemID("vulcanite_ingot");
Item.createItem("vulcanite_ingot", "Vulcanite Ingot", {name: "vulcanite_ingot", meta: 0}, {});
IDRegistry.genItemID("ceruclase_nugget");
Item.createItem("ceruclase_nugget", "Ceruclase Nugget", {name: "ceruclase_nugget", meta: 0}, {});
IDRegistry.genItemID("ceruclase_dust");
Item.createItem("ceruclase_dust", "Ceruclase Dust", {name: "ceruclase_dust", meta: 0}, {});
IDRegistry.genItemID("ceruclase_ingot");
Item.createItem("ceruclase_ingot", "Ceruclase Ingot", {name: "ceruclase_ingot", meta: 0}, {});
IDRegistry.genItemID("sanguinite_nugget");
Item.createItem("sanguinite_nugget", "Sanguinite Nugget", {name: "sanguinite_nugget", meta: 0}, {});
IDRegistry.genItemID("sanguinite_dust");
Item.createItem("sanguinite_dust", "Sanguinite Dust", {name: "sanguinite_dust", meta: 0}, {});
IDRegistry.genItemID("sanguinite_ingot");
Item.createItem("sanguinite_ingot", "Sanguinite Ingot", {name: "sanguinite_ingot", meta: 0}, {});
IDRegistry.genItemID("eximite_nugget");
Item.createItem("eximite_nugget", "Eximite Nugget", {name: "eximite_nugget", meta: 0}, {});
IDRegistry.genItemID("eximite_dust");
Item.createItem("eximite_dust", "Eximite Dust", {name: "eximite_dust", meta: 0}, {});
IDRegistry.genItemID("eximite_ingot");
Item.createItem("eximite_ingot", "Eximite Ingot", {name: "eximite_ingot", meta: 0}, {});
IDRegistry.genItemID("meutoite_nugget");
Item.createItem("meutoite_nugget", "Meutoite Nugget", {name: "meutoite_nugget", meta: 0}, {});
IDRegistry.genItemID("meutoite_dust");
Item.createItem("meutoite_dust", "Meutoite Dust", {name: "meutoite_dust", meta: 0}, {});
IDRegistry.genItemID("meutoite_ingot");
Item.createItem("meutoite_ingot", "Meutoite Ingot", {name: "meutoite_ingot", meta: 0}, {});
IDRegistry.genItemID("bronze_nugget");
Item.createItem("bronze_nugget", "Bronze Nugget", {name: "bronze_nugget", meta: 0}, {});
IDRegistry.genItemID("bronze_dust");
Item.createItem("bronze_dust", "Bronze Dust", {name: "bronze_dust", meta: 0}, {});
IDRegistry.genItemID("bronze_ingot");
Item.createItem("bronze_ingot", "Bronze Ingot", {name: "bronze_ingot", meta: 0}, {});
IDRegistry.genItemID("inolashite_nugget");
Item.createItem("inolashite_nugget", "Inolashite Nugget", {name: "inolashite_nugget", meta: 0}, {});
IDRegistry.genItemID("inolashite_dust");
Item.createItem("inolashite_dust", "Inolashite Dust", {name: "inolashite_dust", meta: 0}, {});
IDRegistry.genItemID("inolashite_ingot");
Item.createItem("inolashite_ingot", "Inolashite Ingot", {name: "inolashite_ingot", meta: 0}, {});
IDRegistry.genItemID("brass_nugget");
Item.createItem("brass_nugget", "Brass Nugget", {name: "brass_nugget", meta: 0}, {});
IDRegistry.genItemID("brass_dust");
Item.createItem("brass_dust", "Brass Dust", {name: "brass_dust", meta: 0}, {});
IDRegistry.genItemID("brass_ingot");
Item.createItem("brass_ingot", "Brass Ingot", {name: "brass_ingot", meta: 0}, {});
IDRegistry.genItemID("steel_nugget");
Item.createItem("steel_nugget", "Steel Nugget", {name: "steel_nugget", meta: 0}, {});
IDRegistry.genItemID("steel_dust");
Item.createItem("steel_dust", "Steel Dust", {name: "steel_dust", meta: 0}, {});
IDRegistry.genItemID("steel_ingot");
Item.createItem("steel_ingot", "Steel Ingot", {name: "steel_ingot", meta: 0}, {});
IDRegistry.genItemID("shadow_steel_nugget");
Item.createItem("shadow_steel_nugget", "Shadow Steel Nugget", {name: "shadow_steel_nugget", meta: 0}, {});
IDRegistry.genItemID("shadow_steel_dust");
Item.createItem("shadow_steel_dust", "Shadow Steel Dust", {name: "shadow_steel_dust", meta: 0}, {});
IDRegistry.genItemID("shadow_steel_ingot");
Item.createItem("shadow_steel_ingot", "Shadow Steel Ingot", {name: "shadow_steel_ingot", meta: 0}, {});
IDRegistry.genItemID("black_steel_nugget");
Item.createItem("black_steel_nugget", "Black Steel Nugget", {name: "black_steel_nugget", meta: 0}, {});
IDRegistry.genItemID("black_steel_dust");
Item.createItem("black_steel_dust", "Black Steel Dust", {name: "black_steel_dust", meta: 0}, {});
IDRegistry.genItemID("black_steel_ingot");
Item.createItem("black_steel_ingot", "Black Steel Ingot", {name: "black_steel_ingot", meta: 0}, {});
IDRegistry.genItemID("damascus_steel_nugget");
Item.createItem("damascus_steel_nugget", "Damascus Steel Nugget", {name: "damascus_steel_nugget", meta: 0}, {});
IDRegistry.genItemID("damascus_steel_dust");
Item.createItem("damascus_steel_dust", "Damascus Steel Dust", {name: "damascus_steel_dust", meta: 0}, {});
IDRegistry.genItemID("damascus_steel_ingot");
Item.createItem("damascus_steel_ingot", "Damascus Steel Ingot", {name: "damascus_steel_ingot", meta: 0}, {});
IDRegistry.genItemID("electrum_nugget");
Item.createItem("electrum_nugget", "Electrum Nugget", {name: "electrum_nugget", meta: 0}, {});
IDRegistry.genItemID("electrum_dust");
Item.createItem("electrum_dust", "Electrum Dust", {name: "electrum_dust", meta: 0}, {});
IDRegistry.genItemID("electrum_ingot");
Item.createItem("electrum_ingot", "Electrum Ingot", {name: "electrum_ingot", meta: 0}, {});
IDRegistry.genItemID("celenegil_nugget");
Item.createItem("celenegil_nugget", "Celenegil Nugget", {name: "celenegil_nugget", meta: 0}, {});
IDRegistry.genItemID("celenegil_dust");
Item.createItem("celenegil_dust", "Celenegil Dust", {name: "celenegil_dust", meta: 0}, {});
IDRegistry.genItemID("celenegil_ingot");
Item.createItem("celenegil_ingot", "Celenegil Ingot", {name: "celenegil_ingot", meta: 0}, {});
IDRegistry.genItemID("amordrine_nugget");
Item.createItem("amordrine_nugget", "Amordrine Nugget", {name: "amordrine_nugget", meta: 0}, {});
IDRegistry.genItemID("amordrine_dust");
Item.createItem("amordrine_dust", "Amordrine Dust", {name: "amordrine_dust", meta: 0}, {});
IDRegistry.genItemID("amordrine_ingot");
Item.createItem("amordrine_ingot", "Amordrine Ingot", {name: "amordrine_ingot", meta: 0}, {});
IDRegistry.genItemID("haderoth_nugget");
Item.createItem("haderoth_nugget", "Haderoth Nugget", {name: "haderoth_nugget", meta: 0}, {});
IDRegistry.genItemID("haderoth_dust");
Item.createItem("haderoth_dust", "Haderoth Dust", {name: "haderoth_dust", meta: 0}, {});
IDRegistry.genItemID("haderoth_ingot");
Item.createItem("haderoth_ingot", "Haderoth Ingot", {name: "haderoth_ingot", meta: 0}, {});
IDRegistry.genItemID("tartarite_nugget");
Item.createItem("tartarite_nugget", "Tartarite Nugget", {name: "tartarite_nugget", meta: 0}, {});
IDRegistry.genItemID("tartarite_dust");
Item.createItem("tartarite_dust", "Tartarite Dust", {name: "tartarite_dust", meta: 0}, {});
IDRegistry.genItemID("tartarite_ingot");
Item.createItem("tartarite_ingot", "Tartarite Ingot", {name: "tartarite_ingot", meta: 0}, {});
IDRegistry.genItemID("desichalkos_nugget");
Item.createItem("desichalkos_nugget", "Desichalkos Nugget", {name: "desichalkos_nugget", meta: 0}, {});
IDRegistry.genItemID("desichalkos_dust");
Item.createItem("desichalkos_dust", "Desichalkos Dust", {name: "desichalkos_dust", meta: 0}, {});
IDRegistry.genItemID("desichalkos_ingot");
Item.createItem("desichalkos_ingot", "Desichalkos Ingot", {name: "desichalkos_ingot", meta: 0}, {});
IDRegistry.genItemID("angmallen_nugget");
Item.createItem("angmallen_nugget", "Angmallen Nugget", {name: "angmallen_nugget", meta: 0}, {});
IDRegistry.genItemID("angmallen_dust");
Item.createItem("angmallen_dust", "Angmallen Dust", {name: "angmallen_dust", meta: 0}, {});
IDRegistry.genItemID("angmallen_ingot");
Item.createItem("angmallen_ingot", "Angmallen Ingot", {name: "angmallen_ingot", meta: 0}, {});
IDRegistry.genItemID("hepatizon_nugget");
Item.createItem("hepatizon_nugget", "Hepatizon Nugget", {name: "hepatizon_nugget", meta: 0}, {});
IDRegistry.genItemID("hepatizon_dust");
Item.createItem("hepatizon_dust", "Hepatizon Dust", {name: "hepatizon_dust", meta: 0}, {});
IDRegistry.genItemID("hepatizon_ingot");
Item.createItem("hepatizon_ingot", "Hepatizon Ingot", {name: "hepatizon_ingot", meta: 0}, {});
IDRegistry.genItemID("quicksilver_nugget");
Item.createItem("quicksilver_nugget", "Quicksilver Nugget", {name: "quicksilver_nugget", meta: 0}, {});
IDRegistry.genItemID("quicksilver_dust");
Item.createItem("quicksilver_dust", "Quicksilver Dust", {name: "quicksilver_dust", meta: 0}, {});
IDRegistry.genItemID("quicksilver_ingot");
Item.createItem("quicksilver_ingot", "Quicksilver Ingot", {name: "quicksilver_ingot", meta: 0}, {});
IDRegistry.genItemID("iron_dust");
Item.createItem("iron_dust", "Iron Dust", {name: "iron_dust", meta: 0}, {});
IDRegistry.genItemID("gold_dust");
Item.createItem("gold_dust", "Gold Dust", {name: "gold_dust", meta: 0}, {});

