IDRegistry.genBlockID("copper_brick");
Block.createBlock("copper_brick", [{name: "Copper Brick", texture: [["copper_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.copper_brick, "stone", 2, true);
Block.setDestroyLevel("copper_brick", 2);
IDRegistry.genBlockID("tin_brick");
Block.createBlock("tin_brick", [{name: "Tin Brick", texture: [["tin_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.tin_brick, "stone", 2, true);
Block.setDestroyLevel("tin_brick", 2);
IDRegistry.genBlockID("bronze_brick");
Block.createBlock("bronze_brick", [{name: "Bronze Brick", texture: [["bronze_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.bronze_brick, "stone", 3, true);
Block.setDestroyLevel("bronze_brick", 3);
IDRegistry.genBlockID("hepatizon_brick");
Block.createBlock("hepatizon_brick", [{name: "Hepatizon Brick", texture: [["hepatizon_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.hepatizon_brick, "stone", 3, true);
Block.setDestroyLevel("hepatizon_brick", 3);
IDRegistry.genBlockID("damascus_steel_brick");
Block.createBlock("damascus_steel_brick", [{name: "Damascus Steel Brick", texture: [["damascus_steel_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.damascus_steel_brick, "stone", 4, true);
Block.setDestroyLevel("damascus_steel_brick", 4);
IDRegistry.genBlockID("angmallen_brick");
Block.createBlock("angmallen_brick", [{name: "Angmallen Brick", texture: [["angmallen_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.angmallen_brick, "stone", 3, true);
Block.setDestroyLevel("angmallen_brick", 3);
IDRegistry.genBlockID("manganese_brick");
Block.createBlock("manganese_brick", [{name: "Manganese Brick", texture: [["manganese_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.manganese_brick, "stone", 3, true);
Block.setDestroyLevel("manganese_brick", 3);
IDRegistry.genBlockID("steel_brick");
Block.createBlock("steel_brick", [{name: "Steel Brick", texture: [["steel_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.steel_brick, "stone", 4, true);
Block.setDestroyLevel("steel_brick", 4);
IDRegistry.genBlockID("zinc_brick");
Block.createBlock("zinc_brick", [{name: "Zinc Brick", texture: [["zinc_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.zinc_brick, "stone", 1, true);
Block.setDestroyLevel("zinc_brick", 1);
IDRegistry.genBlockID("brass_brick");
Block.createBlock("brass_brick", [{name: "Brass Brick", texture: [["brass_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.brass_brick, "stone", 1, true);
Block.setDestroyLevel("brass_brick", 1);
IDRegistry.genBlockID("silver_brick");
Block.createBlock("silver_brick", [{name: "Silver Brick", texture: [["silver_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.silver_brick, "stone", 1, true);
Block.setDestroyLevel("silver_brick", 1);
IDRegistry.genBlockID("electrum_brick");
Block.createBlock("electrum_brick", [{name: "Electrum Brick", texture: [["electrum_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.electrum_brick, "stone", 2, true);
Block.setDestroyLevel("electrum_brick", 2);
IDRegistry.genBlockID("platinum_brick");
Block.createBlock("platinum_brick", [{name: "Platinum Brick", texture: [["platinum_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.platinum_brick, "stone", 3, true);
Block.setDestroyLevel("platinum_brick", 3);
IDRegistry.genBlockID("ignatius_brick");
Block.createBlock("ignatius_brick", [{name: "Ignatius Brick", texture: [["ignatius_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.ignatius_brick, "stone", 2, true);
Block.setDestroyLevel("ignatius_brick", 2);
IDRegistry.genBlockID("shadow_iron_brick");
Block.createBlock("shadow_iron_brick", [{name: "Shadow Iron Brick", texture: [["shadow_iron_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.shadow_iron_brick, "stone", 2, true);
Block.setDestroyLevel("shadow_iron_brick", 2);
IDRegistry.genBlockID("lemurite_brick");
Block.createBlock("lemurite_brick", [{name: "Lemurite Brick", texture: [["lemurite_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.lemurite_brick, "stone", 2, true);
Block.setDestroyLevel("lemurite_brick", 2);
IDRegistry.genBlockID("shadow_steel_brick");
Block.createBlock("shadow_steel_brick", [{name: "Shadow Steel Brick", texture: [["shadow_steel_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.shadow_steel_brick, "stone", 3, true);
Block.setDestroyLevel("shadow_steel_brick", 3);
IDRegistry.genBlockID("midasium_brick");
Block.createBlock("midasium_brick", [{name: "Midasium Brick", texture: [["midasium_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.midasium_brick, "stone", 4, true);
Block.setDestroyLevel("midasium_brick", 4);
IDRegistry.genBlockID("vyroxeres_brick");
Block.createBlock("vyroxeres_brick", [{name: "Vyroxeres Brick", texture: [["vyroxeres_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.vyroxeres_brick, "stone", 4, true);
Block.setDestroyLevel("vyroxeres_brick", 4);
IDRegistry.genBlockID("ceruclase_brick");
Block.createBlock("ceruclase_brick", [{name: "Ceruclase Brick", texture: [["ceruclase_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.ceruclase_brick, "stone", 4, true);
Block.setDestroyLevel("ceruclase_brick", 4);
IDRegistry.genBlockID("alduorite_brick");
Block.createBlock("alduorite_brick", [{name: "Adluorite Brick", texture: [["alduorite_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.alduorite_brick, "stone", 3, true);
Block.setDestroyLevel("alduorite_brick", 3);
IDRegistry.genBlockID("inolashite_brick");
Block.createBlock("inolashite_brick", [{name: "Inolashite Brick", texture: [["inolashite_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.inolashite_brick, "stone", 5, true);
Block.setDestroyLevel("inolashite_brick", 5);
IDRegistry.genBlockID("kalendrite_brick");
Block.createBlock("kalendrite_brick", [{name: "Kalendrite Brick", texture: [["kalendrite_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.kalendrite_brick, "stone", 5, true);
Block.setDestroyLevel("kalendrite_brick", 5);
IDRegistry.genBlockID("amordrine_brick");
Block.createBlock("amordrine_brick", [{name: "Amordrine Brick", texture: [["amordrine_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.amordrine_brick, "stone", 5, true);
Block.setDestroyLevel("amordrine_brick", 5);
IDRegistry.genBlockID("vulcanite_brick");
Block.createBlock("vulcanite_brick", [{name: "Vulcanite Brick", texture: [["vulcanite_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.vulcanite_brick, "stone", 6, true);
Block.setDestroyLevel("vulcanite_brick", 6);
IDRegistry.genBlockID("sanguinite_brick");
Block.createBlock("sanguinite_brick", [{name: "Sanguinite Brick", texture: [["sanguinite_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.sanguinite_brick, "stone", 7, true);
Block.setDestroyLevel("sanguinite_brick", 7);
IDRegistry.genBlockID("prometheum_brick");
Block.createBlock("prometheum_brick", [{name: "Prometheum Brick", texture: [["prometheum_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.prometheum_brick, "stone", 2, true);
Block.setDestroyLevel("prometheum_brick", 2);
IDRegistry.genBlockID("deep_iron_brick");
Block.createBlock("deep_iron_brick", [{name: "Deep Iron Brick", texture: [["deep_iron_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.deep_iron_brick, "stone", 3, true);
Block.setDestroyLevel("deep_iron_brick", 3);
IDRegistry.genBlockID("infuscolium_brick");
Block.createBlock("infuscolium_brick", [{name: "Infuscolium Brick", texture: [["infuscolium_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.infuscolium_brick, "stone", 2, true);
Block.setDestroyLevel("infuscolium_brick", 2);
IDRegistry.genBlockID("black_steel_brick");
Block.createBlock("black_steel_brick", [{name: "Black Steel Brick", texture: [["black_steel_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.black_steel_brick, "stone", 3, true);
Block.setDestroyLevel("black_steel_brick", 3);
IDRegistry.genBlockID("oureclase_brick");
Block.createBlock("oureclase_brick", [{name: "Oureclase Brick", texture: [["oureclase_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.oureclase_brick, "stone", 4, true);
Block.setDestroyLevel("oureclase_brick", 4);
IDRegistry.genBlockID("astral_silver_brick");
Block.createBlock("astral_silver_brick", [{name: "Astral Silver Brick", texture: [["astral_silver_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.astral_silver_brick, "stone", 5, true);
Block.setDestroyLevel("astral_silver_brick", 5);
IDRegistry.genBlockID("carmot_brick");
Block.createBlock("carmot_brick", [{name: "Carmot Brick", texture: [["carmot_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.carmot_brick, "stone", 5, true);
Block.setDestroyLevel("carmot_brick", 5);
IDRegistry.genBlockID("mithril_brick");
Block.createBlock("mithril_brick", [{name: "Mithril Brick", texture: [["mithril_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.mithril_brick, "stone", 5, true);
Block.setDestroyLevel("mithril_brick", 5);
IDRegistry.genBlockID("rubracium_brick");
Block.createBlock("rubracium_brick", [{name: "Rubracium Brick", texture: [["rubracium_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.rubracium_brick, "stone", 4, true);
Block.setDestroyLevel("rubracium_brick", 4);
IDRegistry.genBlockID("quicksilver_brick");
Block.createBlock("quicksilver_brick", [{name: "Quicksilver Brick", texture: [["quicksilver_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.quicksilver_brick, "stone", 5, true);
Block.setDestroyLevel("quicksilver_brick", 5);
IDRegistry.genBlockID("haderoth_brick");
Block.createBlock("haderoth_brick", [{name: "Haderoth Brick", texture: [["haderoth_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.haderoth_brick, "stone", 5, true);
Block.setDestroyLevel("haderoth_brick", 5);
IDRegistry.genBlockID("orichalcum_brick");
Block.createBlock("orichalcum_brick", [{name: "Orichalcum Brick", texture: [["orichalcum_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.orichalcum_brick, "stone", 6, true);
Block.setDestroyLevel("orichalcum_brick", 6);
IDRegistry.genBlockID("celenegil_brick");
Block.createBlock("celenegil_brick", [{name: "Celenegil Brick", texture: [["celenegil_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.celenegil_brick, "stone", 6, true);
Block.setDestroyLevel("celenegil_brick", 6);
IDRegistry.genBlockID("adamantine_brick");
Block.createBlock("adamantine_brick", [{name: "Adamantine Brick", texture: [["adamantine_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.adamantine_brick, "stone", 7, true);
Block.setDestroyLevel("adamantine_brick", 7);
IDRegistry.genBlockID("atlarus_brick");
Block.createBlock("atlarus_brick", [{name: "Atlarus Brick", texture: [["atlarus_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.atlarus_brick, "stone", 7, true);
Block.setDestroyLevel("atlarus_brick", 7);
IDRegistry.genBlockID("tartarite_brick");
Block.createBlock("tartarite_brick", [{name: "Tartarite Brick", texture: [["tartarite_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.tartarite_brick, "stone", 8, true);
Block.setDestroyLevel("tartarite_brick", 8);
IDRegistry.genBlockID("eximite_brick");
Block.createBlock("eximite_brick", [{name: "Eximite Brick", texture: [["eximite_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.eximite_brick, "stone", 4, true);
Block.setDestroyLevel("eximite_brick", 4);
IDRegistry.genBlockID("meutoite_brick");
Block.createBlock("meutoite_brick", [{name: "Meutoite Brick", texture: [["meutoite_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.meutoite_brick, "stone", 4, true);
Block.setDestroyLevel("meutoite_brick", 4);
IDRegistry.genBlockID("desichalkos_brick");
Block.createBlock("desichalkos_brick", [{name: "Desichalkos Brick", texture: [["desichalkos_brick", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.desichalkos_brick, "stone", 5, true);
Block.setDestroyLevel("desichalkos_brick", 5);

