IDRegistry.genBlockID("copper_block");
Block.createBlock("copper_block", [{name: "Copper Block", texture: [["copper_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.copper_block, "stone", 2, true);
Block.setDestroyLevel("copper_block", 2);
IDRegistry.genBlockID("tin_block");
Block.createBlock("tin_block", [{name: "Tin Block", texture: [["tin_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.tin_block, "stone", 2, true);
Block.setDestroyLevel("tin_block", 2);
IDRegistry.genBlockID("bronze_block");
Block.createBlock("bronze_block", [{name: "Bronze Block", texture: [["bronze_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.bronze_block, "stone", 3, true);
Block.setDestroyLevel("bronze_block", 3);
IDRegistry.genBlockID("hepatizon_block");
Block.createBlock("hepatizon_block", [{name: "Hepatizon Block", texture: [["hepatizon_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.hepatizon_block, "stone", 3, true);
Block.setDestroyLevel("hepatizon_block", 3);
IDRegistry.genBlockID("damascus_steel_block");
Block.createBlock("damascus_steel_block", [{name: "Damascus Steel Block", texture: [["damascus_steel_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.damascus_steel_block, "stone", 4, true);
Block.setDestroyLevel("damascus_steel_block", 4);
IDRegistry.genBlockID("angmallen_block");
Block.createBlock("angmallen_block", [{name: "Angmallen Block", texture: [["angmallen_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.angmallen_block, "stone", 3, true);
Block.setDestroyLevel("angmallen_block", 3);
IDRegistry.genBlockID("manganese_block");
Block.createBlock("manganese_block", [{name: "Manganese Block", texture: [["manganese_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.manganese_block, "stone", 3, true);
Block.setDestroyLevel("manganese_block", 3);
IDRegistry.genBlockID("steel_block");
Block.createBlock("steel_block", [{name: "Steel Block", texture: [["steel_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.steel_block, "stone", 4, true);
Block.setDestroyLevel("steel_block", 4);
IDRegistry.genBlockID("zinc_block");
Block.createBlock("zinc_block", [{name: "Zinc Block", texture: [["zinc_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.zinc_block, "stone", 1, true);
Block.setDestroyLevel("zinc_block", 1);
IDRegistry.genBlockID("brass_block");
Block.createBlock("brass_block", [{name: "Brass Block", texture: [["brass_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.brass_block, "stone", 1, true);
Block.setDestroyLevel("brass_block", 1);
IDRegistry.genBlockID("silver_block");
Block.createBlock("silver_block", [{name: "Silver Block", texture: [["silver_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.silver_block, "stone", 1, true);
Block.setDestroyLevel("silver_block", 1);
IDRegistry.genBlockID("electrum_block");
Block.createBlock("electrum_block", [{name: "Electrum Block", texture: [["electrum_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.electrum_block, "stone", 2, true);
Block.setDestroyLevel("electrum_block", 2);
IDRegistry.genBlockID("platinum_block");
Block.createBlock("platinum_block", [{name: "Platinum Block", texture: [["platinum_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.platinum_block, "stone", 3, true);
Block.setDestroyLevel("platinum_block", 3);
IDRegistry.genBlockID("ignatius_block");
Block.createBlock("ignatius_block", [{name: "Ignatius Block", texture: [["ignatius_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.ignatius_block, "stone", 2, true);
Block.setDestroyLevel("ignatius_block", 2);
IDRegistry.genBlockID("shadow_iron_block");
Block.createBlock("shadow_iron_block", [{name: "Shadow Iron Block", texture: [["shadow_iron_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.shadow_iron_block, "stone", 2, true);
Block.setDestroyLevel("shadow_iron_block", 2);
IDRegistry.genBlockID("lemurite_block");
Block.createBlock("lemurite_block", [{name: "Lemurite Block", texture: [["lemurite_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.lemurite_block, "stone", 2, true);
Block.setDestroyLevel("lemurite_block", 2);
IDRegistry.genBlockID("shadow_steel_block");
Block.createBlock("shadow_steel_block", [{name: "Shadow Steel Block", texture: [["shadow_steel_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.shadow_steel_block, "stone", 3, true);
Block.setDestroyLevel("shadow_steel_block", 3);
IDRegistry.genBlockID("midasium_block");
Block.createBlock("midasium_block", [{name: "Midasium Block", texture: [["midasium_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.midasium_block, "stone", 4, true);
Block.setDestroyLevel("midasium_block", 4);
IDRegistry.genBlockID("vyroxeres_block");
Block.createBlock("vyroxeres_block", [{name: "Vyroxeres Block", texture: [["vyroxeres_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.vyroxeres_block, "stone", 4, true);
Block.setDestroyLevel("vyroxeres_block", 4);
IDRegistry.genBlockID("ceruclase_block");
Block.createBlock("ceruclase_block", [{name: "Ceruclase Block", texture: [["ceruclase_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.ceruclase_block, "stone", 4, true);
Block.setDestroyLevel("ceruclase_block", 4);
IDRegistry.genBlockID("alduorite_block");
Block.createBlock("alduorite_block", [{name: "Adluorite Block", texture: [["alduorite_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.alduorite_block, "stone", 3, true);
Block.setDestroyLevel("alduorite_block", 3);
IDRegistry.genBlockID("inolashite_block");
Block.createBlock("inolashite_block", [{name: "Inolashite Block", texture: [["inolashite_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.inolashite_block, "stone", 5, true);
Block.setDestroyLevel("inolashite_block", 5);
IDRegistry.genBlockID("kalendrite_block");
Block.createBlock("kalendrite_block", [{name: "Kalendrite Block", texture: [["kalendrite_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.kalendrite_block, "stone", 5, true);
Block.setDestroyLevel("kalendrite_block", 5);
IDRegistry.genBlockID("amordrine_block");
Block.createBlock("amordrine_block", [{name: "Amordrine Block", texture: [["amordrine_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.amordrine_block, "stone", 5, true);
Block.setDestroyLevel("amordrine_block", 5);
IDRegistry.genBlockID("vulcanite_block");
Block.createBlock("vulcanite_block", [{name: "Vulcanite Block", texture: [["vulcanite_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.vulcanite_block, "stone", 6, true);
Block.setDestroyLevel("vulcanite_block", 6);
IDRegistry.genBlockID("sanguinite_block");
Block.createBlock("sanguinite_block", [{name: "Sanguinite Block", texture: [["sanguinite_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.sanguinite_block, "stone", 7, true);
Block.setDestroyLevel("sanguinite_block", 7);
IDRegistry.genBlockID("prometheum_block");
Block.createBlock("prometheum_block", [{name: "Prometheum Block", texture: [["prometheum_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.prometheum_block, "stone", 2, true);
Block.setDestroyLevel("prometheum_block", 2);
IDRegistry.genBlockID("deep_iron_block");
Block.createBlock("deep_iron_block", [{name: "Deep Iron Block", texture: [["deep_iron_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.deep_iron_block, "stone", 3, true);
Block.setDestroyLevel("deep_iron_block", 3);
IDRegistry.genBlockID("infuscolium_block");
Block.createBlock("infuscolium_block", [{name: "Infuscolium Block", texture: [["infuscolium_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.infuscolium_block, "stone", 2, true);
Block.setDestroyLevel("infuscolium_block", 2);
IDRegistry.genBlockID("black_steel_block");
Block.createBlock("black_steel_block", [{name: "Black Steel Block", texture: [["black_steel_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.black_steel_block, "stone", 3, true);
Block.setDestroyLevel("black_steel_block", 3);
IDRegistry.genBlockID("oureclase_block");
Block.createBlock("oureclase_block", [{name: "Oureclase Block", texture: [["oureclase_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.oureclase_block, "stone", 4, true);
Block.setDestroyLevel("oureclase_block", 4);
IDRegistry.genBlockID("astral_silver_block");
Block.createBlock("astral_silver_block", [{name: "Astral Silver Block", texture: [["astral_silver_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.astral_silver_block, "stone", 5, true);
Block.setDestroyLevel("astral_silver_block", 5);
IDRegistry.genBlockID("carmot_block");
Block.createBlock("carmot_block", [{name: "Carmot Block", texture: [["carmot_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.carmot_block, "stone", 5, true);
Block.setDestroyLevel("carmot_block", 5);
IDRegistry.genBlockID("mithril_block");
Block.createBlock("mithril_block", [{name: "Mithril Block", texture: [["mithril_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.mithril_block, "stone", 5, true);
Block.setDestroyLevel("mithril_block", 5);
IDRegistry.genBlockID("rubracium_block");
Block.createBlock("rubracium_block", [{name: "Rubracium Block", texture: [["rubracium_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.rubracium_block, "stone", 4, true);
Block.setDestroyLevel("rubracium_block", 4);
IDRegistry.genBlockID("quicksilver_block");
Block.createBlock("quicksilver_block", [{name: "Quicksilver Block", texture: [["quicksilver_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.quicksilver_block, "stone", 5, true);
Block.setDestroyLevel("quicksilver_block", 5);
IDRegistry.genBlockID("haderoth_block");
Block.createBlock("haderoth_block", [{name: "Haderoth Block", texture: [["haderoth_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.haderoth_block, "stone", 5, true);
Block.setDestroyLevel("haderoth_block", 5);
IDRegistry.genBlockID("orichalcum_block");
Block.createBlock("orichalcum_block", [{name: "Orichalcum Block", texture: [["orichalcum_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.orichalcum_block, "stone", 6, true);
Block.setDestroyLevel("orichalcum_block", 6);
IDRegistry.genBlockID("celenegil_block");
Block.createBlock("celenegil_block", [{name: "Celenegil Block", texture: [["celenegil_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.celenegil_block, "stone", 6, true);
Block.setDestroyLevel("celenegil_block", 6);
IDRegistry.genBlockID("adamantine_block");
Block.createBlock("adamantine_block", [{name: "Adamantine Block", texture: [["adamantine_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.adamantine_block, "stone", 7, true);
Block.setDestroyLevel("adamantine_block", 7);
IDRegistry.genBlockID("atlarus_block");
Block.createBlock("atlarus_block", [{name: "Atlarus Block", texture: [["atlarus_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.atlarus_block, "stone", 7, true);
Block.setDestroyLevel("atlarus_block", 7);
IDRegistry.genBlockID("tartarite_block");
Block.createBlock("tartarite_block", [{name: "Tartarite Block", texture: [["tartarite_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.tartarite_block, "stone", 8, true);
Block.setDestroyLevel("tartarite_block", 8);
IDRegistry.genBlockID("eximite_block");
Block.createBlock("eximite_block", [{name: "Eximite Block", texture: [["eximite_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.eximite_block, "stone", 4, true);
Block.setDestroyLevel("eximite_block", 4);
IDRegistry.genBlockID("meutoite_block");
Block.createBlock("meutoite_block", [{name: "Meutoite Block", texture: [["meutoite_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.meutoite_block, "stone", 4, true);
Block.setDestroyLevel("meutoite_block", 4);
IDRegistry.genBlockID("desichalkos_block");
Block.createBlock("desichalkos_block", [{name: "Desichalkos Block", texture: [["desichalkos_block", 0]], inCreative: true}], "opaque");
ToolAPI.registerBlockMaterial(BlockID.desichalkos_block, "stone", 5, true);
Block.setDestroyLevel("desichalkos_block", 5);

