Callback.addCallback("PreLoaded", function () {
    Recipes.addShaped({id: ItemID.inolashiteSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.inolashite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.inolashiteShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.inolashite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.inolashitePickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.inolashite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.inolashiteAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.inolashite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.inolashiteHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.inolashite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.kalendriteSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.kalendrite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.kalendriteShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.kalendrite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.kalendritePickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.kalendrite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.kalendriteAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.kalendrite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.kalendriteHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.kalendrite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.amordrineSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.amordrine_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.amordrineShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.amordrine_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.amordrinePickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.amordrine_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.amordrineAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.amordrine_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.amordrineHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.amordrine_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.vulcaniteSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.vulcanite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.vulcaniteShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.vulcanite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.vulcanitePickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.vulcanite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.vulcaniteAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.vulcanite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.vulcaniteHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.vulcanite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.sanguiniteSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.sanguinite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.sanguiniteShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.sanguinite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.sanguinitePickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.sanguinite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.sanguiniteAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.sanguinite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.sanguiniteHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.sanguinite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.prometheumSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.prometheum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.prometheumShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.prometheum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.prometheumPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.prometheum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.prometheumAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.prometheum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.prometheumHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.prometheum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.deep_ironSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.deep_iron_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.deep_ironShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.deep_iron_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.deep_ironPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.deep_iron_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.deep_ironAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.deep_iron_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.deep_ironHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.deep_iron_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.black_steelSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.black_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.black_steelShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.black_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.black_steelPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.black_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.black_steelAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.black_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.black_steelHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.black_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.oureclaseSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.oureclase_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.oureclaseShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.oureclase_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.oureclasePickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.oureclase_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.oureclaseAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.oureclase_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.oureclaseHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.oureclase_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.astral_silverSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.astral_silver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.astral_silverShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.astral_silver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.astral_silverPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.astral_silver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.astral_silverAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.astral_silver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.astral_silverHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.astral_silver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.carmotSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.carmot_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.carmotShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.carmot_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.carmotPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.carmot_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.carmotAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.carmot_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.carmotHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.carmot_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.mithrilSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.mithril_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.mithrilShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.mithril_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.mithrilPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.mithril_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.mithrilAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.mithril_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.mithrilHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.mithril_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.quicksilverSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.quicksilver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.quicksilverShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.quicksilver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.quicksilverPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.quicksilver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.quicksilverAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.quicksilver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.quicksilverHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.quicksilver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.haderothSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.haderoth_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.haderothShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.haderoth_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.haderothPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.haderoth_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.haderothAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.haderoth_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.haderothHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.haderoth_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.orichalcumSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.orichalcum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.orichalcumShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.orichalcum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.orichalcumPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.orichalcum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.orichalcumAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.orichalcum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.orichalcumHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.orichalcum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.celenegilSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.celenegil_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.celenegilShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.celenegil_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.celenegilPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.celenegil_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.celenegilAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.celenegil_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.celenegilHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.celenegil_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.adamantineSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.adamantine_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.adamantineShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.adamantine_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.adamantinePickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.adamantine_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.adamantineAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.adamantine_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.adamantineHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.adamantine_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.atlarusSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.atlarus_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.atlarusShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.atlarus_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.atlarusPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.atlarus_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.atlarusAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.atlarus_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.atlarusHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.atlarus_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.tartariteSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.tartarite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.tartariteShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.tartarite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.tartaritePickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.tartarite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.tartariteAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.tartarite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.tartariteHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.tartarite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.eximiteSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.eximite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.eximiteShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.eximite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.eximitePickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.eximite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.eximiteAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.eximite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.eximiteHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.eximite_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.desichalkosSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.desichalkos_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.desichalkosShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.desichalkos_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.desichalkosPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.desichalkos_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.desichalkosAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.desichalkos_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.desichalkosHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.desichalkos_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.copperHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.copper_ingot, 0]);
    Recipes.addShaped({id: ItemID.copperChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.copper_ingot, 0]);
    Recipes.addShaped({id: ItemID.copperLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.copper_ingot, 0]);
    Recipes.addShaped({id: ItemID.copperBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.copper_ingot, 0]);
    Recipes.addShaped({id: ItemID.bronzeHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.bronze_ingot, 0]);
    Recipes.addShaped({id: ItemID.bronzeChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.bronze_ingot, 0]);
    Recipes.addShaped({id: ItemID.bronzeLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.bronze_ingot, 0]);
    Recipes.addShaped({id: ItemID.bronzeBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.bronze_ingot, 0]);
    Recipes.addShaped({id: ItemID.hepatizonHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.hepatizon_ingot, 0]);
    Recipes.addShaped({id: ItemID.hepatizonChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.hepatizon_ingot, 0]);
    Recipes.addShaped({id: ItemID.hepatizonLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.hepatizon_ingot, 0]);
    Recipes.addShaped({id: ItemID.hepatizonBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.hepatizon_ingot, 0]);
    Recipes.addShaped({id: ItemID.damascus_steelHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.damascus_steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.damascus_steelChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.damascus_steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.damascus_steelLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.damascus_steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.damascus_steelBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.damascus_steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.angmallenHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.angmallen_ingot, 0]);
    Recipes.addShaped({id: ItemID.angmallenChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.angmallen_ingot, 0]);
    Recipes.addShaped({id: ItemID.angmallenLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.angmallen_ingot, 0]);
    Recipes.addShaped({id: ItemID.angmallenBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.angmallen_ingot, 0]);
    Recipes.addShaped({id: ItemID.steelHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.steelChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.steelLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.steelBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.brassHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.brass_ingot, 0]);
    Recipes.addShaped({id: ItemID.brassChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.brass_ingot, 0]);
    Recipes.addShaped({id: ItemID.brassLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.brass_ingot, 0]);
    Recipes.addShaped({id: ItemID.brassBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.brass_ingot, 0]);
    Recipes.addShaped({id: ItemID.silverHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.silver_ingot, 0]);
    Recipes.addShaped({id: ItemID.silverChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.silver_ingot, 0]);
    Recipes.addShaped({id: ItemID.silverLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.silver_ingot, 0]);
    Recipes.addShaped({id: ItemID.silverBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.silver_ingot, 0]);
    Recipes.addShaped({id: ItemID.electrumHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.electrum_ingot, 0]);
    Recipes.addShaped({id: ItemID.electrumChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.electrum_ingot, 0]);
    Recipes.addShaped({id: ItemID.electrumLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.electrum_ingot, 0]);
    Recipes.addShaped({id: ItemID.electrumBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.electrum_ingot, 0]);
    Recipes.addShaped({id: ItemID.platinumHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.platinum_ingot, 0]);
    Recipes.addShaped({id: ItemID.platinumChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.platinum_ingot, 0]);
    Recipes.addShaped({id: ItemID.platinumLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.platinum_ingot, 0]);
    Recipes.addShaped({id: ItemID.platinumBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.platinum_ingot, 0]);
    Recipes.addShaped({id: ItemID.ignatiusHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.ignatius_ingot, 0]);
    Recipes.addShaped({id: ItemID.ignatiusChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.ignatius_ingot, 0]);
    Recipes.addShaped({id: ItemID.ignatiusLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.ignatius_ingot, 0]);
    Recipes.addShaped({id: ItemID.ignatiusBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.ignatius_ingot, 0]);
    Recipes.addShaped({id: ItemID.shadow_ironHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.shadow_iron_ingot, 0]);
    Recipes.addShaped({id: ItemID.shadow_ironChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.shadow_iron_ingot, 0]);
    Recipes.addShaped({id: ItemID.shadow_ironLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.shadow_iron_ingot, 0]);
    Recipes.addShaped({id: ItemID.shadow_ironBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.shadow_iron_ingot, 0]);
    Recipes.addShaped({id: ItemID.shadow_steelHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.shadow_steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.shadow_steelChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.shadow_steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.shadow_steelLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.shadow_steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.shadow_steelBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.shadow_steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.midasiumHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.midasium_ingot, 0]);
    Recipes.addShaped({id: ItemID.midasiumChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.midasium_ingot, 0]);
    Recipes.addShaped({id: ItemID.midasiumLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.midasium_ingot, 0]);
    Recipes.addShaped({id: ItemID.midasiumBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.midasium_ingot, 0]);
    Recipes.addShaped({id: ItemID.vyroxeresHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.vyroxeres_ingot, 0]);
    Recipes.addShaped({id: ItemID.vyroxeresChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.vyroxeres_ingot, 0]);
    Recipes.addShaped({id: ItemID.vyroxeresLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.vyroxeres_ingot, 0]);
    Recipes.addShaped({id: ItemID.vyroxeresBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.vyroxeres_ingot, 0]);
    Recipes.addShaped({id: ItemID.ceruclaseHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.ceruclase_ingot, 0]);
    Recipes.addShaped({id: ItemID.ceruclaseChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.ceruclase_ingot, 0]);
    Recipes.addShaped({id: ItemID.ceruclaseLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.ceruclase_ingot, 0]);
    Recipes.addShaped({id: ItemID.ceruclaseBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.ceruclase_ingot, 0]);
    Recipes.addShaped({id: ItemID.inolashiteHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.inolashite_ingot, 0]);
    Recipes.addShaped({id: ItemID.inolashiteChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.inolashite_ingot, 0]);
    Recipes.addShaped({id: ItemID.inolashiteLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.inolashite_ingot, 0]);
    Recipes.addShaped({id: ItemID.inolashiteBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.inolashite_ingot, 0]);
    Recipes.addShaped({id: ItemID.kalendriteHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.kalendrite_ingot, 0]);
    Recipes.addShaped({id: ItemID.kalendriteChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.kalendrite_ingot, 0]);
    Recipes.addShaped({id: ItemID.kalendriteLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.kalendrite_ingot, 0]);
    Recipes.addShaped({id: ItemID.kalendriteBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.kalendrite_ingot, 0]);
    Recipes.addShaped({id: ItemID.amordrineHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.amordrine_ingot, 0]);
    Recipes.addShaped({id: ItemID.amordrineChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.amordrine_ingot, 0]);
    Recipes.addShaped({id: ItemID.amordrineLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.amordrine_ingot, 0]);
    Recipes.addShaped({id: ItemID.amordrineBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.amordrine_ingot, 0]);
    Recipes.addShaped({id: ItemID.vulcaniteHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.vulcanite_ingot, 0]);
    Recipes.addShaped({id: ItemID.vulcaniteChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.vulcanite_ingot, 0]);
    Recipes.addShaped({id: ItemID.vulcaniteLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.vulcanite_ingot, 0]);
    Recipes.addShaped({id: ItemID.vulcaniteBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.vulcanite_ingot, 0]);
    Recipes.addShaped({id: ItemID.sanguiniteHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.sanguinite_ingot, 0]);
    Recipes.addShaped({id: ItemID.sanguiniteChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.sanguinite_ingot, 0]);
    Recipes.addShaped({id: ItemID.sanguiniteLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.sanguinite_ingot, 0]);
    Recipes.addShaped({id: ItemID.sanguiniteBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.sanguinite_ingot, 0]);
    Recipes.addShaped({id: ItemID.prometheumHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.prometheum_ingot, 0]);
    Recipes.addShaped({id: ItemID.prometheumChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.prometheum_ingot, 0]);
    Recipes.addShaped({id: ItemID.prometheumLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.prometheum_ingot, 0]);
    Recipes.addShaped({id: ItemID.prometheumBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.prometheum_ingot, 0]);
    Recipes.addShaped({id: ItemID.deep_ironHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.deep_iron_ingot, 0]);
    Recipes.addShaped({id: ItemID.deep_ironChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.deep_iron_ingot, 0]);
    Recipes.addShaped({id: ItemID.deep_ironLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.deep_iron_ingot, 0]);
    Recipes.addShaped({id: ItemID.deep_ironBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.deep_iron_ingot, 0]);
    Recipes.addShaped({id: ItemID.black_steelHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.black_steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.black_steelChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.black_steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.black_steelLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.black_steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.black_steelBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.black_steel_ingot, 0]);
    Recipes.addShaped({id: ItemID.oureclaseHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.oureclase_ingot, 0]);
    Recipes.addShaped({id: ItemID.oureclaseChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.oureclase_ingot, 0]);
    Recipes.addShaped({id: ItemID.oureclaseLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.oureclase_ingot, 0]);
    Recipes.addShaped({id: ItemID.oureclaseBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.oureclase_ingot, 0]);
    Recipes.addShaped({id: ItemID.astral_silverHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.astral_silver_ingot, 0]);
    Recipes.addShaped({id: ItemID.astral_silverChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.astral_silver_ingot, 0]);
    Recipes.addShaped({id: ItemID.astral_silverLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.astral_silver_ingot, 0]);
    Recipes.addShaped({id: ItemID.astral_silverBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.astral_silver_ingot, 0]);
    Recipes.addShaped({id: ItemID.carmotHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.carmot_ingot, 0]);
    Recipes.addShaped({id: ItemID.carmotChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.carmot_ingot, 0]);
    Recipes.addShaped({id: ItemID.carmotLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.carmot_ingot, 0]);
    Recipes.addShaped({id: ItemID.carmotBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.carmot_ingot, 0]);
    Recipes.addShaped({id: ItemID.mithrilHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.mithril_ingot, 0]);
    Recipes.addShaped({id: ItemID.mithrilChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.mithril_ingot, 0]);
    Recipes.addShaped({id: ItemID.mithrilLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.mithril_ingot, 0]);
    Recipes.addShaped({id: ItemID.mithrilBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.mithril_ingot, 0]);
    Recipes.addShaped({id: ItemID.quicksilverHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.quicksilver_ingot, 0]);
    Recipes.addShaped({id: ItemID.quicksilverChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.quicksilver_ingot, 0]);
    Recipes.addShaped({id: ItemID.quicksilverLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.quicksilver_ingot, 0]);
    Recipes.addShaped({id: ItemID.quicksilverBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.quicksilver_ingot, 0]);
    Recipes.addShaped({id: ItemID.haderothHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.haderoth_ingot, 0]);
    Recipes.addShaped({id: ItemID.haderothChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.haderoth_ingot, 0]);
    Recipes.addShaped({id: ItemID.haderothLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.haderoth_ingot, 0]);
    Recipes.addShaped({id: ItemID.haderothBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.haderoth_ingot, 0]);
    Recipes.addShaped({id: ItemID.orichalcumHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.orichalcum_ingot, 0]);
    Recipes.addShaped({id: ItemID.orichalcumChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.orichalcum_ingot, 0]);
    Recipes.addShaped({id: ItemID.orichalcumLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.orichalcum_ingot, 0]);
    Recipes.addShaped({id: ItemID.orichalcumBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.orichalcum_ingot, 0]);
    Recipes.addShaped({id: ItemID.celenegilHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.celenegil_ingot, 0]);
    Recipes.addShaped({id: ItemID.celenegilChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.celenegil_ingot, 0]);
    Recipes.addShaped({id: ItemID.celenegilLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.celenegil_ingot, 0]);
    Recipes.addShaped({id: ItemID.celenegilBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.celenegil_ingot, 0]);
    Recipes.addShaped({id: ItemID.adamantineHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.adamantine_ingot, 0]);
    Recipes.addShaped({id: ItemID.adamantineChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.adamantine_ingot, 0]);
    Recipes.addShaped({id: ItemID.adamantineLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.adamantine_ingot, 0]);
    Recipes.addShaped({id: ItemID.adamantineBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.adamantine_ingot, 0]);
    Recipes.addShaped({id: ItemID.atlarusHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.atlarus_ingot, 0]);
    Recipes.addShaped({id: ItemID.atlarusChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.atlarus_ingot, 0]);
    Recipes.addShaped({id: ItemID.atlarusLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.atlarus_ingot, 0]);
    Recipes.addShaped({id: ItemID.atlarusBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.atlarus_ingot, 0]);
    Recipes.addShaped({id: ItemID.tartariteHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.tartarite_ingot, 0]);
    Recipes.addShaped({id: ItemID.tartariteChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.tartarite_ingot, 0]);
    Recipes.addShaped({id: ItemID.tartariteLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.tartarite_ingot, 0]);
    Recipes.addShaped({id: ItemID.tartariteBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.tartarite_ingot, 0]);
    Recipes.addShaped({id: ItemID.eximiteHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.eximite_ingot, 0]);
    Recipes.addShaped({id: ItemID.eximiteChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.eximite_ingot, 0]);
    Recipes.addShaped({id: ItemID.eximiteLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.eximite_ingot, 0]);
    Recipes.addShaped({id: ItemID.eximiteBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.eximite_ingot, 0]);
    Recipes.addShaped({id: ItemID.desichalkosHelmet, count: 1, data: 0}, ["xxx", "x x"], ["x", ItemID.desichalkos_ingot, 0]);
    Recipes.addShaped({id: ItemID.desichalkosChestplate, count: 1, data: 0}, ["x x", "xxx", "xxx"], ["x", ItemID.desichalkos_ingot, 0]);
    Recipes.addShaped({id: ItemID.desichalkosLeggings, count: 1, data: 0}, ["xxx", "x x", "x x"], ["x", ItemID.desichalkos_ingot, 0]);
    Recipes.addShaped({id: ItemID.desichalkosBoots, count: 1, data: 0}, ["x x", "x x"], ["x", ItemID.desichalkos_ingot, 0]);
    Recipes.addFurnace(ItemID.copper_dust, ItemID.copper_ingot, 0);
    Recipes.addFurnace(ItemID.manganese_dust, ItemID.manganese_ingot, 0);
    Recipes.addFurnace(ItemID.tin_dust, ItemID.tin_ingot, 0);
    Recipes.addFurnace(ItemID.zinc_dust, ItemID.zinc_ingot, 0);
    Recipes.addFurnace(ItemID.prometheum_dust, ItemID.prometheum_ingot, 0);
    Recipes.addFurnace(ItemID.deep_iron_dust, ItemID.deep_iron_ingot, 0);
    Recipes.addFurnace(ItemID.infuscolium_dust, ItemID.infuscolium_ingot, 0);
    Recipes.addFurnace(ItemID.oureclase_dust, ItemID.oureclase_ingot, 0);
    Recipes.addFurnace(ItemID.rubracium_dust, ItemID.rubracium_ingot, 0);
    Recipes.addFurnace(ItemID.carmot_dust, ItemID.carmot_ingot, 0);
    Recipes.addFurnace(ItemID.orichalcum_dust, ItemID.orichalcum_ingot, 0);
    Recipes.addFurnace(ItemID.silver_dust, ItemID.silver_ingot, 0);
    Recipes.addFurnace(ItemID.adamantine_dust, ItemID.adamantine_ingot, 0);
    Recipes.addFurnace(ItemID.atlarus_dust, ItemID.atlarus_ingot, 0);
    Recipes.addFurnace(ItemID.astral_silver_dust, ItemID.astral_silver_ingot, 0);
    Recipes.addFurnace(ItemID.platinum_dust, ItemID.platinum_ingot, 0);
    Recipes.addFurnace(ItemID.mithril_dust, ItemID.mithril_ingot, 0);
    Recipes.addFurnace(ItemID.ignatius_dust, ItemID.ignatius_ingot, 0);
    Recipes.addFurnace(ItemID.shadow_iron_dust, ItemID.shadow_iron_ingot, 0);
    Recipes.addFurnace(ItemID.lemurite_dust, ItemID.lemurite_ingot, 0);
    Recipes.addFurnace(ItemID.midasium_dust, ItemID.midasium_ingot, 0);
    Recipes.addFurnace(ItemID.vyroxeres_dust, ItemID.vyroxeres_ingot, 0);
    Recipes.addFurnace(ItemID.alduorite_dust, ItemID.alduorite_ingot, 0);
    Recipes.addFurnace(ItemID.ignatius_dust, ItemID.ignatius_ingot, 0);
    Recipes.addFurnace(ItemID.kalendrite_dust, ItemID.kalendrite_ingot, 0);
    Recipes.addFurnace(ItemID.vulcanite_dust, ItemID.vulcanite_ingot, 0);
    Recipes.addFurnace(ItemID.ceruclase_dust, ItemID.ceruclase_ingot, 0);
    Recipes.addFurnace(ItemID.sanguinite_dust, ItemID.sanguinite_ingot, 0);
    Recipes.addFurnace(ItemID.eximite_dust, ItemID.eximite_ingot, 0);
    Recipes.addFurnace(ItemID.meutoite_dust, ItemID.meutoite_ingot, 0);
    Recipes.addFurnace(ItemID.bronze_dust, ItemID.bronze_ingot, 0);
    Recipes.addFurnace(ItemID.inolashite_dust, ItemID.inolashite_ingot, 0);
    Recipes.addFurnace(ItemID.brass_dust, ItemID.brass_ingot, 0);
    Recipes.addFurnace(ItemID.steel_dust, ItemID.steel_ingot, 0);
    Recipes.addFurnace(ItemID.shadow_steel_dust, ItemID.shadow_steel_ingot, 0);
    Recipes.addFurnace(ItemID.black_steel_dust, ItemID.black_steel_ingot, 0);
    Recipes.addFurnace(ItemID.damascus_steel_dust, ItemID.damascus_steel_ingot, 0);
    Recipes.addFurnace(ItemID.electrum_dust, ItemID.electrum_ingot, 0);
    Recipes.addFurnace(ItemID.celenegil_dust, ItemID.celenegil_ingot, 0);
    Recipes.addFurnace(ItemID.amordrine_dust, ItemID.amordrine_ingot, 0);
    Recipes.addFurnace(ItemID.haderoth_dust, ItemID.haderoth_ingot, 0);
    Recipes.addFurnace(ItemID.tartarite_dust, ItemID.tartarite_ingot, 0);
    Recipes.addFurnace(ItemID.desichalkos_dust, ItemID.desichalkos_ingot, 0);
    Recipes.addFurnace(ItemID.angmallen_dust, ItemID.angmallen_ingot, 0);
    Recipes.addFurnace(ItemID.hepatizon_dust, ItemID.hepatizon_ingot, 0);
    Recipes.addFurnace(ItemID.quicksilver_dust, ItemID.quicksilver_ingot, 0);
    Recipes.addFurnace(ItemID.iron_dust, 265, 0);
    Recipes.addFurnace(ItemID.gold_dust, 266, 0);
    Recipes.addShapeless({id: ItemID.bronze_dust, count: 1, data: 0}, [{id: ItemID.tin_dust, data: 0}, {id: ItemID.copper_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.shadow_steel_dust, count: 1, data: 0}, [{id: ItemID.shadow_iron_dust, data: 0}, {id: ItemID.lemurite_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.inolashite_dust, count: 1, data: 0}, [{id: ItemID.alduorite_dust, data: 0}, {id: ItemID.ceruclase_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.brass_dust, count: 1, data: 0}, [{id: ItemID.copper_dust, data: 0}, {id: ItemID.zinc_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.black_steel_dust, count: 1, data: 0}, [{id: ItemID.deep_iron_dust, data: 0}, {id: ItemID.infuscolium_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.celenegil_dust, count: 1, data: 0}, [{id: ItemID.orichalcum_dust, data: 0}, {id: ItemID.platinum_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.amordrine_dust, count: 1, data: 0}, [{id: ItemID.kalendrite_dust, data: 0}, {id: ItemID.platinum_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.haderoth_dust, count: 1, data: 0}, [{id: ItemID.mithril_dust, data: 0}, {id: ItemID.rubracium_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.tartarite_dust, count: 1, data: 0}, [{id: ItemID.adamantine_dust, data: 0}, {id: ItemID.atlarus_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.desichalkos_dust, count: 1, data: 0}, [{id: ItemID.eximite_dust, data: 0}, {id: ItemID.meutoite_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.hepatizon_dust, count: 1, data: 0}, [{id: ItemID.infuscolium_dust, data: 0}, {id: ItemID.steel_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.quicksilver_dust, count: 1, data: 0}, [{id: ItemID.mithril_dust, data: 0}, {id: ItemID.silver_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.steel_dust, count: 1, data: 0}, [{id: ItemID.manganese_dust, data: 0}, {id: ItemID.iron_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.damascus_steel_dust, count: 1, data: 0}, [{id: ItemID.bronze_dust, data: 0}, {id: ItemID.iron_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.electrum_dust, count: 1, data: 0}, [{id: ItemID.silver_dust, data: 0}, {id: ItemID.gold_dust, data: 0}]);
    Recipes.addShapeless({id: ItemID.angmallen_dust, count: 1, data: 0}, [{id: ItemID.iron_dust, data: 0}, {id: ItemID.gold_dust, data: 0}]);
    Recipes.addFurnace(BlockID.copper_ore, ItemID.copper_ingot, 0);
    Recipes.addFurnace(BlockID.tin_ore, ItemID.tin_ingot, 0);
    Recipes.addFurnace(BlockID.manganese_ore, ItemID.manganese_ingot, 0);
    Recipes.addFurnace(BlockID.zinc_ore, ItemID.zinc_ingot, 0);
    Recipes.addFurnace(BlockID.silver_ore, ItemID.silver_ingot, 0);
    Recipes.addFurnace(BlockID.platinum_ore, ItemID.platinum_ingot, 0);
    Recipes.addFurnace(BlockID.prometheum_ore, ItemID.prometheum_ingot, 0);
    Recipes.addFurnace(BlockID.deep_iron_ore, ItemID.deep_iron_ingot, 0);
    Recipes.addFurnace(BlockID.infuscolium_ore, ItemID.infuscolium_ingot, 0);
    Recipes.addFurnace(BlockID.oureclase_ore, ItemID.oureclase_ingot, 0);
    Recipes.addFurnace(BlockID.astral_silver_ore, ItemID.astral_silver_ingot, 0);
    Recipes.addFurnace(BlockID.carmot_ore, ItemID.carmot_ingot, 0);
    Recipes.addFurnace(BlockID.mithril_ore, ItemID.mithril_ingot, 0);
    Recipes.addFurnace(BlockID.rubracium_ore, ItemID.rubracium_ingot, 0);
    Recipes.addFurnace(BlockID.orichalcum_ore, ItemID.orichalcum_ingot, 0);
    Recipes.addFurnace(BlockID.adamantine_ore, ItemID.adamantine_ingot, 0);
    Recipes.addFurnace(BlockID.atlarus_ore, ItemID.atlarus_ingot, 0);
    Recipes.addFurnace(BlockID.ignatius_ore, ItemID.ignatius_ingot, 0);
    Recipes.addFurnace(BlockID.shadow_iron_ore, ItemID.shadow_iron_ingot, 0);
    Recipes.addFurnace(BlockID.lemurite_ore, ItemID.lemurite_ingot, 0);
    Recipes.addFurnace(BlockID.midasium_ore, ItemID.midasium_ingot, 0);
    Recipes.addFurnace(BlockID.vyroxeres_ore, ItemID.vyroxeres_ingot, 0);
    Recipes.addFurnace(BlockID.ceruclase_ore, ItemID.ceruclase_ingot, 0);
    Recipes.addFurnace(BlockID.alduorite_ore, ItemID.alduorite_ingot, 0);
    Recipes.addFurnace(BlockID.kalendrite_ore, ItemID.kalendrite_ingot, 0);
    Recipes.addFurnace(BlockID.vulcanite_ore, ItemID.vulcanite_ingot, 0);
    Recipes.addFurnace(BlockID.sanguinite_ore, ItemID.sanguinite_ingot, 0);
    Recipes.addFurnace(BlockID.eximite_ore, ItemID.eximite_ingot, 0);
    Recipes.addFurnace(BlockID.meutoite_ore, ItemID.meutoite_ingot, 0);
    Recipes.addShaped({id: BlockID.copper_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.copper_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.tin_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.tin_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.bronze_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.bronze_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.hepatizon_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.hepatizon_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.damascus_steel_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.damascus_steel_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.angmallen_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.angmallen_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.manganese_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.manganese_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.steel_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.steel_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.zinc_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.zinc_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.brass_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.brass_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.silver_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.silver_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.electrum_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.electrum_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.platinum_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.platinum_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.ignatius_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.ignatius_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.shadow_iron_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.shadow_iron_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.lemurite_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.lemurite_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.shadow_steel_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.shadow_steel_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.midasium_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.midasium_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.vyroxeres_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.vyroxeres_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.ceruclase_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.ceruclase_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.alduorite_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.alduorite_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.inolashite_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.inolashite_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.kalendrite_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.kalendrite_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.amordrine_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.amordrine_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.vulcanite_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.vulcanite_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.sanguinite_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.sanguinite_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.prometheum_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.prometheum_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.deep_iron_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.deep_iron_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.infuscolium_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.infuscolium_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.black_steel_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.black_steel_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.oureclase_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.oureclase_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.astral_silver_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.astral_silver_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.carmot_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.carmot_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.mithril_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.mithril_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.rubracium_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.rubracium_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.quicksilver_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.quicksilver_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.haderoth_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.haderoth_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.orichalcum_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.orichalcum_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.celenegil_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.celenegil_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.adamantine_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.adamantine_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.atlarus_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.atlarus_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.tartarite_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.tartarite_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.eximite_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.eximite_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.meutoite_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.meutoite_nugget, 0, "b", 45, 0]);
    Recipes.addShaped({id: BlockID.desichalkos_brick, count: 1, data: 0}, ["xxx", "xbx", "xxx"], ["x", ItemID.desichalkos_nugget, 0, "b", 45, 0]);
    Recipes.addShapeless({id: ItemID.fai, count: 1, data: 0}, [{id: 318, data: 0}, {id: ItemID.ignatius_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.fav, count: 1, data: 0}, [{id: 318, data: 0}, {id: ItemID.vulcanite_ingot, data: 0}]);
    Recipes.addShaped({id: BlockID.alloyer, count: 1, data: 0}, ["aaa", "scs", "sfs"], ["a", ItemID.atlarus_ingot, 0, "s", ItemID.steel_ingot, 0, "c", BlockID.copper_block, 0, "f", 61, 0]);
    Recipes.addShaped({id: BlockID.crusher, count: 1, data: 0}, ["ooo", "scs", "sfs"], ["o", ItemID.oureclase_ingot, 0, "s", ItemID.silver_ingot, 0, "c", BlockID.copper_block, 0, "f", 61, 0]);
});

