Callback.addCallback("PreLoaded", function () {
    Recipes.addShaped({id: BlockID.copper_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.copper_ingot, 0]);
    Recipes.addShaped({id: BlockID.tin_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.tin_ingot, 0]);
    Recipes.addShaped({id: BlockID.bronze_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.bronze_ingot, 0]);
    Recipes.addShaped({id: BlockID.hepatizon_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.hepatizon_ingot, 0]);
    Recipes.addShaped({id: BlockID.damascus_steel_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.damascus_steel_ingot, 0]);
    Recipes.addShaped({id: BlockID.angmallen_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.angmallen_ingot, 0]);
    Recipes.addShaped({id: BlockID.manganese_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.manganese_ingot, 0]);
    Recipes.addShaped({id: BlockID.steel_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.steel_ingot, 0]);
    Recipes.addShaped({id: BlockID.zinc_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.zinc_ingot, 0]);
    Recipes.addShaped({id: BlockID.brass_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.brass_ingot, 0]);
    Recipes.addShaped({id: BlockID.silver_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.silver_ingot, 0]);
    Recipes.addShaped({id: BlockID.electrum_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.electrum_ingot, 0]);
    Recipes.addShaped({id: BlockID.platinum_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.platinum_ingot, 0]);
    Recipes.addShaped({id: BlockID.ignatius_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.ignatius_ingot, 0]);
    Recipes.addShaped({id: BlockID.shadow_iron_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.shadow_iron_ingot, 0]);
    Recipes.addShaped({id: BlockID.lemurite_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.lemurite_ingot, 0]);
    Recipes.addShaped({id: BlockID.shadow_steel_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.shadow_steel_ingot, 0]);
    Recipes.addShaped({id: BlockID.midasium_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.midasium_ingot, 0]);
    Recipes.addShaped({id: BlockID.vyroxeres_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.vyroxeres_ingot, 0]);
    Recipes.addShaped({id: BlockID.ceruclase_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.ceruclase_ingot, 0]);
    Recipes.addShaped({id: BlockID.alduorite_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.alduorite_ingot, 0]);
    Recipes.addShaped({id: BlockID.inolashite_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.inolashite_ingot, 0]);
    Recipes.addShaped({id: BlockID.kalendrite_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.kalendrite_ingot, 0]);
    Recipes.addShaped({id: BlockID.amordrine_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.amordrine_ingot, 0]);
    Recipes.addShaped({id: BlockID.vulcanite_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.vulcanite_ingot, 0]);
    Recipes.addShaped({id: BlockID.sanguinite_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.sanguinite_ingot, 0]);
    Recipes.addShaped({id: BlockID.prometheum_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.prometheum_ingot, 0]);
    Recipes.addShaped({id: BlockID.deep_iron_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.deep_iron_ingot, 0]);
    Recipes.addShaped({id: BlockID.infuscolium_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.infuscolium_ingot, 0]);
    Recipes.addShaped({id: BlockID.black_steel_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.black_steel_ingot, 0]);
    Recipes.addShaped({id: BlockID.oureclase_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.oureclase_ingot, 0]);
    Recipes.addShaped({id: BlockID.astral_silver_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.astral_silver_ingot, 0]);
    Recipes.addShaped({id: BlockID.carmot_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.carmot_ingot, 0]);
    Recipes.addShaped({id: BlockID.mithril_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.mithril_ingot, 0]);
    Recipes.addShaped({id: BlockID.rubracium_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.rubracium_ingot, 0]);
    Recipes.addShaped({id: BlockID.quicksilver_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.quicksilver_ingot, 0]);
    Recipes.addShaped({id: BlockID.haderoth_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.haderoth_ingot, 0]);
    Recipes.addShaped({id: BlockID.orichalcum_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.orichalcum_ingot, 0]);
    Recipes.addShaped({id: BlockID.celenegil_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.celenegil_ingot, 0]);
    Recipes.addShaped({id: BlockID.adamantine_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.adamantine_ingot, 0]);
    Recipes.addShaped({id: BlockID.atlarus_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.atlarus_ingot, 0]);
    Recipes.addShaped({id: BlockID.tartarite_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.tartarite_ingot, 0]);
    Recipes.addShaped({id: BlockID.eximite_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.eximite_ingot, 0]);
    Recipes.addShaped({id: BlockID.meutoite_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.meutoite_ingot, 0]);
    Recipes.addShaped({id: BlockID.desichalkos_block, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.desichalkos_ingot, 0]);
    Recipes.addShapeless({id: ItemID.copper_ingot, count: 9, data: 0}, [{id: BlockID.copper_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.tin_ingot, count: 9, data: 0}, [{id: BlockID.tin_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.bronze_ingot, count: 9, data: 0}, [{id: BlockID.bronze_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.hepatizon_ingot, count: 9, data: 0}, [{id: BlockID.hepatizon_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.damascus_steel_ingot, count: 9, data: 0}, [{id: BlockID.damascus_steel_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.angmallen_ingot, count: 9, data: 0}, [{id: BlockID.angmallen_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.manganese_ingot, count: 9, data: 0}, [{id: BlockID.manganese_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.steel_ingot, count: 9, data: 0}, [{id: BlockID.steel_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.zinc_ingot, count: 9, data: 0}, [{id: BlockID.zinc_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.brass_ingot, count: 9, data: 0}, [{id: BlockID.brass_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.silver_ingot, count: 9, data: 0}, [{id: BlockID.silver_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.electrum_ingot, count: 9, data: 0}, [{id: BlockID.electrum_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.platinum_ingot, count: 9, data: 0}, [{id: BlockID.platinum_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.ignatius_ingot, count: 9, data: 0}, [{id: BlockID.ignatius_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.shadow_iron_ingot, count: 9, data: 0}, [{id: BlockID.shadow_iron_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.lemurite_ingot, count: 9, data: 0}, [{id: BlockID.lemurite_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.shadow_steel_ingot, count: 9, data: 0}, [{id: BlockID.shadow_steel_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.midasium_ingot, count: 9, data: 0}, [{id: BlockID.midasium_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.vyroxeres_ingot, count: 9, data: 0}, [{id: BlockID.vyroxeres_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.ceruclase_ingot, count: 9, data: 0}, [{id: BlockID.ceruclase_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.alduorite_ingot, count: 9, data: 0}, [{id: BlockID.alduorite_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.inolashite_ingot, count: 9, data: 0}, [{id: BlockID.inolashite_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.kalendrite_ingot, count: 9, data: 0}, [{id: BlockID.kalendrite_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.amordrine_ingot, count: 9, data: 0}, [{id: BlockID.amordrine_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.vulcanite_ingot, count: 9, data: 0}, [{id: BlockID.vulcanite_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.sanguinite_ingot, count: 9, data: 0}, [{id: BlockID.sanguinite_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.prometheum_ingot, count: 9, data: 0}, [{id: BlockID.prometheum_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.deep_iron_ingot, count: 9, data: 0}, [{id: BlockID.deep_iron_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.infuscolium_ingot, count: 9, data: 0}, [{id: BlockID.infuscolium_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.black_steel_ingot, count: 9, data: 0}, [{id: BlockID.black_steel_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.oureclase_ingot, count: 9, data: 0}, [{id: BlockID.oureclase_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.astral_silver_ingot, count: 9, data: 0}, [{id: BlockID.astral_silver_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.carmot_ingot, count: 9, data: 0}, [{id: BlockID.carmot_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.mithril_ingot, count: 9, data: 0}, [{id: BlockID.mithril_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.rubracium_ingot, count: 9, data: 0}, [{id: BlockID.rubracium_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.quicksilver_ingot, count: 9, data: 0}, [{id: BlockID.quicksilver_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.haderoth_ingot, count: 9, data: 0}, [{id: BlockID.haderoth_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.orichalcum_ingot, count: 9, data: 0}, [{id: BlockID.orichalcum_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.celenegil_ingot, count: 9, data: 0}, [{id: BlockID.celenegil_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.adamantine_ingot, count: 9, data: 0}, [{id: BlockID.adamantine_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.atlarus_ingot, count: 9, data: 0}, [{id: BlockID.atlarus_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.tartarite_ingot, count: 9, data: 0}, [{id: BlockID.tartarite_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.eximite_ingot, count: 9, data: 0}, [{id: BlockID.eximite_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.meutoite_ingot, count: 9, data: 0}, [{id: BlockID.meutoite_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.desichalkos_ingot, count: 9, data: 0}, [{id: BlockID.desichalkos_block, data: 0}]);
    Recipes.addShapeless({id: ItemID.copper_nugget, count: 9, data: 0}, [{id: ItemID.copper_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.tin_nugget, count: 9, data: 0}, [{id: ItemID.tin_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.bronze_nugget, count: 9, data: 0}, [{id: ItemID.bronze_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.hepatizon_nugget, count: 9, data: 0}, [{id: ItemID.hepatizon_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.damascus_steel_nugget, count: 9, data: 0}, [{id: ItemID.damascus_steel_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.angmallen_nugget, count: 9, data: 0}, [{id: ItemID.angmallen_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.manganese_nugget, count: 9, data: 0}, [{id: ItemID.manganese_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.steel_nugget, count: 9, data: 0}, [{id: ItemID.steel_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.zinc_nugget, count: 9, data: 0}, [{id: ItemID.zinc_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.brass_nugget, count: 9, data: 0}, [{id: ItemID.brass_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.silver_nugget, count: 9, data: 0}, [{id: ItemID.silver_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.electrum_nugget, count: 9, data: 0}, [{id: ItemID.electrum_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.platinum_nugget, count: 9, data: 0}, [{id: ItemID.platinum_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.ignatius_nugget, count: 9, data: 0}, [{id: ItemID.ignatius_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.shadow_iron_nugget, count: 9, data: 0}, [{id: ItemID.shadow_iron_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.lemurite_nugget, count: 9, data: 0}, [{id: ItemID.lemurite_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.shadow_steel_nugget, count: 9, data: 0}, [{id: ItemID.shadow_steel_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.midasium_nugget, count: 9, data: 0}, [{id: ItemID.midasium_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.vyroxeres_nugget, count: 9, data: 0}, [{id: ItemID.vyroxeres_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.ceruclase_nugget, count: 9, data: 0}, [{id: ItemID.ceruclase_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.alduorite_nugget, count: 9, data: 0}, [{id: ItemID.alduorite_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.inolashite_nugget, count: 9, data: 0}, [{id: ItemID.inolashite_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.kalendrite_nugget, count: 9, data: 0}, [{id: ItemID.kalendrite_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.amordrine_nugget, count: 9, data: 0}, [{id: ItemID.amordrine_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.vulcanite_nugget, count: 9, data: 0}, [{id: ItemID.vulcanite_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.sanguinite_nugget, count: 9, data: 0}, [{id: ItemID.sanguinite_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.prometheum_nugget, count: 9, data: 0}, [{id: ItemID.prometheum_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.deep_iron_nugget, count: 9, data: 0}, [{id: ItemID.deep_iron_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.infuscolium_nugget, count: 9, data: 0}, [{id: ItemID.infuscolium_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.black_steel_nugget, count: 9, data: 0}, [{id: ItemID.black_steel_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.oureclase_nugget, count: 9, data: 0}, [{id: ItemID.oureclase_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.astral_silver_nugget, count: 9, data: 0}, [{id: ItemID.astral_silver_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.carmot_nugget, count: 9, data: 0}, [{id: ItemID.carmot_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.mithril_nugget, count: 9, data: 0}, [{id: ItemID.mithril_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.rubracium_nugget, count: 9, data: 0}, [{id: ItemID.rubracium_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.quicksilver_nugget, count: 9, data: 0}, [{id: ItemID.quicksilver_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.haderoth_nugget, count: 9, data: 0}, [{id: ItemID.haderoth_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.orichalcum_nugget, count: 9, data: 0}, [{id: ItemID.orichalcum_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.celenegil_nugget, count: 9, data: 0}, [{id: ItemID.celenegil_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.adamantine_nugget, count: 9, data: 0}, [{id: ItemID.adamantine_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.atlarus_nugget, count: 9, data: 0}, [{id: ItemID.atlarus_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.tartarite_nugget, count: 9, data: 0}, [{id: ItemID.tartarite_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.eximite_nugget, count: 9, data: 0}, [{id: ItemID.eximite_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.meutoite_nugget, count: 9, data: 0}, [{id: ItemID.meutoite_ingot, data: 0}]);
    Recipes.addShapeless({id: ItemID.desichalkos_nugget, count: 9, data: 0}, [{id: ItemID.desichalkos_ingot, data: 0}]);
    Recipes.addShaped({id: ItemID.copper_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.copper_nugget, 0]);
    Recipes.addShaped({id: ItemID.tin_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.tin_nugget, 0]);
    Recipes.addShaped({id: ItemID.bronze_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.bronze_nugget, 0]);
    Recipes.addShaped({id: ItemID.hepatizon_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.hepatizon_nugget, 0]);
    Recipes.addShaped({id: ItemID.damascus_steel_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.damascus_steel_nugget, 0]);
    Recipes.addShaped({id: ItemID.angmallen_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.angmallen_nugget, 0]);
    Recipes.addShaped({id: ItemID.manganese_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.manganese_nugget, 0]);
    Recipes.addShaped({id: ItemID.steel_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.steel_nugget, 0]);
    Recipes.addShaped({id: ItemID.zinc_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.zinc_nugget, 0]);
    Recipes.addShaped({id: ItemID.brass_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.brass_nugget, 0]);
    Recipes.addShaped({id: ItemID.silver_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.silver_nugget, 0]);
    Recipes.addShaped({id: ItemID.electrum_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.electrum_nugget, 0]);
    Recipes.addShaped({id: ItemID.platinum_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.platinum_nugget, 0]);
    Recipes.addShaped({id: ItemID.ignatius_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.ignatius_nugget, 0]);
    Recipes.addShaped({id: ItemID.shadow_iron_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.shadow_iron_nugget, 0]);
    Recipes.addShaped({id: ItemID.lemurite_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.lemurite_nugget, 0]);
    Recipes.addShaped({id: ItemID.shadow_steel_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.shadow_steel_nugget, 0]);
    Recipes.addShaped({id: ItemID.midasium_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.midasium_nugget, 0]);
    Recipes.addShaped({id: ItemID.vyroxeres_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.vyroxeres_nugget, 0]);
    Recipes.addShaped({id: ItemID.ceruclase_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.ceruclase_nugget, 0]);
    Recipes.addShaped({id: ItemID.alduorite_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.alduorite_nugget, 0]);
    Recipes.addShaped({id: ItemID.inolashite_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.inolashite_nugget, 0]);
    Recipes.addShaped({id: ItemID.kalendrite_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.kalendrite_nugget, 0]);
    Recipes.addShaped({id: ItemID.amordrine_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.amordrine_nugget, 0]);
    Recipes.addShaped({id: ItemID.vulcanite_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.vulcanite_nugget, 0]);
    Recipes.addShaped({id: ItemID.sanguinite_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.sanguinite_nugget, 0]);
    Recipes.addShaped({id: ItemID.prometheum_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.prometheum_nugget, 0]);
    Recipes.addShaped({id: ItemID.deep_iron_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.deep_iron_nugget, 0]);
    Recipes.addShaped({id: ItemID.infuscolium_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.infuscolium_nugget, 0]);
    Recipes.addShaped({id: ItemID.black_steel_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.black_steel_nugget, 0]);
    Recipes.addShaped({id: ItemID.oureclase_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.oureclase_nugget, 0]);
    Recipes.addShaped({id: ItemID.astral_silver_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.astral_silver_nugget, 0]);
    Recipes.addShaped({id: ItemID.carmot_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.carmot_nugget, 0]);
    Recipes.addShaped({id: ItemID.mithril_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.mithril_nugget, 0]);
    Recipes.addShaped({id: ItemID.rubracium_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.rubracium_nugget, 0]);
    Recipes.addShaped({id: ItemID.quicksilver_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.quicksilver_nugget, 0]);
    Recipes.addShaped({id: ItemID.haderoth_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.haderoth_nugget, 0]);
    Recipes.addShaped({id: ItemID.orichalcum_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.orichalcum_nugget, 0]);
    Recipes.addShaped({id: ItemID.celenegil_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.celenegil_nugget, 0]);
    Recipes.addShaped({id: ItemID.adamantine_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.adamantine_nugget, 0]);
    Recipes.addShaped({id: ItemID.atlarus_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.atlarus_nugget, 0]);
    Recipes.addShaped({id: ItemID.tartarite_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.tartarite_nugget, 0]);
    Recipes.addShaped({id: ItemID.eximite_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.eximite_nugget, 0]);
    Recipes.addShaped({id: ItemID.meutoite_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.meutoite_nugget, 0]);
    Recipes.addShaped({id: ItemID.desichalkos_ingot, count: 1, data: 0}, ["xxx", "xxx", "xxx"], ["x", ItemID.desichalkos_nugget, 0]);
    Recipes.addShaped({id: ItemID.copperSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.copper_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.copperShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.copper_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.copperPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.copper_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.copperAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.copper_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.copperHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.copper_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.bronzeSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.bronze_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.bronzeShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.bronze_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.bronzePickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.bronze_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.bronzeAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.bronze_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.bronzeHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.bronze_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.hepatizonSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.hepatizon_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.hepatizonShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.hepatizon_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.hepatizonPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.hepatizon_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.hepatizonAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.hepatizon_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.hepatizonHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.hepatizon_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.damascus_steelSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.damascus_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.damascus_steelShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.damascus_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.damascus_steelPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.damascus_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.damascus_steelAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.damascus_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.damascus_steelHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.damascus_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.angmallenSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.angmallen_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.angmallenShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.angmallen_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.angmallenPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.angmallen_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.angmallenAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.angmallen_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.angmallenHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.angmallen_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.steelSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.steelShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.steelPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.steelAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.steelHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.brassSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.brass_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.brassShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.brass_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.brassPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.brass_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.brassAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.brass_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.brassHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.brass_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.silverSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.silver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.silverShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.silver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.silverPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.silver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.silverAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.silver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.silverHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.silver_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.electrumSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.electrum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.electrumShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.electrum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.electrumPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.electrum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.electrumAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.electrum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.electrumHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.electrum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.platinumSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.platinum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.platinumShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.platinum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.platinumPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.platinum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.platinumAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.platinum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.platinumHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.platinum_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.ignatiusSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.ignatius_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.ignatiusShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.ignatius_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.ignatiusPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.ignatius_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.ignatiusAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.ignatius_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.ignatiusHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.ignatius_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.shadow_ironSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.shadow_iron_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.shadow_ironShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.shadow_iron_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.shadow_ironPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.shadow_iron_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.shadow_ironAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.shadow_iron_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.shadow_ironHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.shadow_iron_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.shadow_steelSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.shadow_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.shadow_steelShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.shadow_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.shadow_steelPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.shadow_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.shadow_steelAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.shadow_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.shadow_steelHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.shadow_steel_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.midasiumSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.midasium_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.midasiumShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.midasium_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.midasiumPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.midasium_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.midasiumAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.midasium_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.midasiumHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.midasium_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.vyroxeresSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.vyroxeres_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.vyroxeresShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.vyroxeres_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.vyroxeresPickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.vyroxeres_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.vyroxeresAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.vyroxeres_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.vyroxeresHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.vyroxeres_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.ceruclaseSword, count: 1, data: 0}, ["a", "a", "b"], ["a", ItemID.ceruclase_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.ceruclaseShovel, count: 1, data: 0}, ["a", "b", "b"], ["a", ItemID.ceruclase_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.ceruclasePickaxe, count: 1, data: 0}, ["aaa", " b ", " b "], ["a", ItemID.ceruclase_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.ceruclaseAxe, count: 1, data: 0}, ["aa", "ab", " b"], ["a", ItemID.ceruclase_ingot, 0, "b", 280, 0]);
    Recipes.addShaped({id: ItemID.ceruclaseHoe, count: 1, data: 0}, ["aa", " b", " b"], ["a", ItemID.ceruclase_ingot, 0, "b", 280, 0]);
});

