ToolAPI.addToolMaterial("copper", {durability: 180, level: 2, efficiency: 5, damage: 1, enchantability: 5});
ToolAPI.addToolMaterial("bronze", {durability: 250, level: 3, efficiency: 6, damage: 1, enchantability: 9});
ToolAPI.addToolMaterial("hepatizon", {durability: 300, level: 3, efficiency: 8, damage: 1, enchantability: 22});
ToolAPI.addToolMaterial("damascus_steel", {durability: 500, level: 4, efficiency: 6, damage: 2, enchantability: 18});
ToolAPI.addToolMaterial("angmallen", {durability: 300, level: 3, efficiency: 8, damage: 2, enchantability: 30});
ToolAPI.addToolMaterial("steel", {durability: 750, level: 4, efficiency: 8, damage: 3, enchantability: 18});
ToolAPI.addToolMaterial("brass", {durability: 15, level: 1, efficiency: 10, damage: 1, enchantability: 18});
ToolAPI.addToolMaterial("silver", {durability: 25, level: 1, efficiency: 12, damage: 1, enchantability: 20});
ToolAPI.addToolMaterial("electrum", {durability: 50, level: 2, efficiency: 14, damage: 1, enchantability: 30});
ToolAPI.addToolMaterial("platinum", {durability: 100, level: 3, efficiency: 16, damage: 1, enchantability: 50});
ToolAPI.addToolMaterial("ignatius", {durability: 200, level: 2, efficiency: 4, damage: 2, enchantability: 15});
ToolAPI.addToolMaterial("shadow_iron", {durability: 300, level: 2, efficiency: 5, damage: 2, enchantability: 3});
ToolAPI.addToolMaterial("shadow_steel", {durability: 400, level: 3, efficiency: 6, damage: 3, enchantability: 5});
ToolAPI.addToolMaterial("midasium", {durability: 100, level: 4, efficiency: 10, damage: 3, enchantability: 35});
ToolAPI.addToolMaterial("vyroxeres", {durability: 300, level: 4, efficiency: 7, damage: 3, enchantability: 16});
ToolAPI.addToolMaterial("ceruclase", {durability: 500, level: 4, efficiency: 7, damage: 3, enchantability: 18});
ToolAPI.addToolMaterial("inolashite", {durability: 900, level: 5, efficiency: 8, damage: 3, enchantability: 25});
ToolAPI.addToolMaterial("kalendrite", {durability: 1000, level: 5, efficiency: 8, damage: 3, enchantability: 20});
ToolAPI.addToolMaterial("amordrine", {durability: 500, level: 5, efficiency: 14, damage: 2, enchantability: 50});
ToolAPI.addToolMaterial("vulcanite", {durability: 1500, level: 6, efficiency: 10, damage: 3, enchantability: 20});
ToolAPI.addToolMaterial("sanguinite", {durability: 1750, level: 7, efficiency: 12, damage: 4, enchantability: 25});
ToolAPI.addToolMaterial("prometheum", {durability: 200, level: 2, efficiency: 4, damage: 1, enchantability: 16});
ToolAPI.addToolMaterial("deep_iron", {durability: 250, level: 3, efficiency: 6, damage: 2, enchantability: 14});
ToolAPI.addToolMaterial("black_steel", {durability: 500, level: 3, efficiency: 8, damage: 2, enchantability: 17});
ToolAPI.addToolMaterial("oureclase", {durability: 750, level: 4, efficiency: 8, damage: 2, enchantability: 18});
ToolAPI.addToolMaterial("astral_silver", {durability: 35, level: 5, efficiency: 12, damage: 1, enchantability: 30});
ToolAPI.addToolMaterial("carmot", {durability: 50, level: 5, efficiency: 12, damage: 1, enchantability: 40});
ToolAPI.addToolMaterial("mithril", {durability: 1000, level: 5, efficiency: 9, damage: 3, enchantability: 18});
ToolAPI.addToolMaterial("quicksilver", {durability: 1100, level: 5, efficiency: 14, damage: 3, enchantability: 20});
ToolAPI.addToolMaterial("haderoth", {durability: 1250, level: 5, efficiency: 12, damage: 3, enchantability: 19});
ToolAPI.addToolMaterial("orichalcum", {durability: 1350, level: 6, efficiency: 9, damage: 3, enchantability: 20});
ToolAPI.addToolMaterial("celenegil", {durability: 1600, level: 6, efficiency: 14, damage: 3, enchantability: 50});
ToolAPI.addToolMaterial("adamantine", {durability: 1550, level: 7, efficiency: 10, damage: 4, enchantability: 22});
ToolAPI.addToolMaterial("atlarus", {durability: 1750, level: 7, efficiency: 10, damage: 4, enchantability: 22});
ToolAPI.addToolMaterial("tartarite", {durability: 3000, level: 8, efficiency: 14, damage: 5, enchantability: 25});
ToolAPI.addToolMaterial("eximite", {durability: 1000, level: 4, efficiency: 8, damage: 3, enchantability: 25});
ToolAPI.addToolMaterial("desichalkos", {durability: 1800, level: 5, efficiency: 10, damage: 4, enchantability: 30});
IDRegistry.genItemID("copperSword");
IDRegistry.genItemID("copperShovel");
IDRegistry.genItemID("copperPickaxe");
IDRegistry.genItemID("copperAxe");
IDRegistry.genItemID("copperHoe");
IDRegistry.genItemID("bronzeSword");
IDRegistry.genItemID("bronzeShovel");
IDRegistry.genItemID("bronzePickaxe");
IDRegistry.genItemID("bronzeAxe");
IDRegistry.genItemID("bronzeHoe");
IDRegistry.genItemID("hepatizonSword");
IDRegistry.genItemID("hepatizonShovel");
IDRegistry.genItemID("hepatizonPickaxe");
IDRegistry.genItemID("hepatizonAxe");
IDRegistry.genItemID("hepatizonHoe");
IDRegistry.genItemID("damascus_steelSword");
IDRegistry.genItemID("damascus_steelShovel");
IDRegistry.genItemID("damascus_steelPickaxe");
IDRegistry.genItemID("damascus_steelAxe");
IDRegistry.genItemID("damascus_steelHoe");
IDRegistry.genItemID("angmallenSword");
IDRegistry.genItemID("angmallenShovel");
IDRegistry.genItemID("angmallenPickaxe");
IDRegistry.genItemID("angmallenAxe");
IDRegistry.genItemID("angmallenHoe");
IDRegistry.genItemID("steelSword");
IDRegistry.genItemID("steelShovel");
IDRegistry.genItemID("steelPickaxe");
IDRegistry.genItemID("steelAxe");
IDRegistry.genItemID("steelHoe");
IDRegistry.genItemID("brassSword");
IDRegistry.genItemID("brassShovel");
IDRegistry.genItemID("brassPickaxe");
IDRegistry.genItemID("brassAxe");
IDRegistry.genItemID("brassHoe");
IDRegistry.genItemID("silverSword");
IDRegistry.genItemID("silverShovel");
IDRegistry.genItemID("silverPickaxe");
IDRegistry.genItemID("silverAxe");
IDRegistry.genItemID("silverHoe");
IDRegistry.genItemID("electrumSword");
IDRegistry.genItemID("electrumShovel");
IDRegistry.genItemID("electrumPickaxe");
IDRegistry.genItemID("electrumAxe");
IDRegistry.genItemID("electrumHoe");
IDRegistry.genItemID("platinumSword");
IDRegistry.genItemID("platinumShovel");
IDRegistry.genItemID("platinumPickaxe");
IDRegistry.genItemID("platinumAxe");
IDRegistry.genItemID("platinumHoe");
IDRegistry.genItemID("ignatiusSword");
IDRegistry.genItemID("ignatiusShovel");
IDRegistry.genItemID("ignatiusPickaxe");
IDRegistry.genItemID("ignatiusAxe");
IDRegistry.genItemID("ignatiusHoe");
IDRegistry.genItemID("shadow_ironSword");
IDRegistry.genItemID("shadow_ironShovel");
IDRegistry.genItemID("shadow_ironPickaxe");
IDRegistry.genItemID("shadow_ironAxe");
IDRegistry.genItemID("shadow_ironHoe");
IDRegistry.genItemID("shadow_steelSword");
IDRegistry.genItemID("shadow_steelShovel");
IDRegistry.genItemID("shadow_steelPickaxe");
IDRegistry.genItemID("shadow_steelAxe");
IDRegistry.genItemID("shadow_steelHoe");
IDRegistry.genItemID("midasiumSword");
IDRegistry.genItemID("midasiumShovel");
IDRegistry.genItemID("midasiumPickaxe");
IDRegistry.genItemID("midasiumAxe");
IDRegistry.genItemID("midasiumHoe");
IDRegistry.genItemID("vyroxeresSword");
IDRegistry.genItemID("vyroxeresShovel");
IDRegistry.genItemID("vyroxeresPickaxe");
IDRegistry.genItemID("vyroxeresAxe");
IDRegistry.genItemID("vyroxeresHoe");
IDRegistry.genItemID("ceruclaseSword");
IDRegistry.genItemID("ceruclaseShovel");
IDRegistry.genItemID("ceruclasePickaxe");
IDRegistry.genItemID("ceruclaseAxe");
IDRegistry.genItemID("ceruclaseHoe");
IDRegistry.genItemID("inolashiteSword");
IDRegistry.genItemID("inolashiteShovel");
IDRegistry.genItemID("inolashitePickaxe");
IDRegistry.genItemID("inolashiteAxe");
IDRegistry.genItemID("inolashiteHoe");
IDRegistry.genItemID("kalendriteSword");
IDRegistry.genItemID("kalendriteShovel");
IDRegistry.genItemID("kalendritePickaxe");
IDRegistry.genItemID("kalendriteAxe");
IDRegistry.genItemID("kalendriteHoe");
IDRegistry.genItemID("amordrineSword");
IDRegistry.genItemID("amordrineShovel");
IDRegistry.genItemID("amordrinePickaxe");
IDRegistry.genItemID("amordrineAxe");
IDRegistry.genItemID("amordrineHoe");
IDRegistry.genItemID("vulcaniteSword");
IDRegistry.genItemID("vulcaniteShovel");
IDRegistry.genItemID("vulcanitePickaxe");
IDRegistry.genItemID("vulcaniteAxe");
IDRegistry.genItemID("vulcaniteHoe");
IDRegistry.genItemID("sanguiniteSword");
IDRegistry.genItemID("sanguiniteShovel");
IDRegistry.genItemID("sanguinitePickaxe");
IDRegistry.genItemID("sanguiniteAxe");
IDRegistry.genItemID("sanguiniteHoe");
IDRegistry.genItemID("prometheumSword");
IDRegistry.genItemID("prometheumShovel");
IDRegistry.genItemID("prometheumPickaxe");
IDRegistry.genItemID("prometheumAxe");
IDRegistry.genItemID("prometheumHoe");
IDRegistry.genItemID("deep_ironSword");
IDRegistry.genItemID("deep_ironShovel");
IDRegistry.genItemID("deep_ironPickaxe");
IDRegistry.genItemID("deep_ironAxe");
IDRegistry.genItemID("deep_ironHoe");
IDRegistry.genItemID("black_steelSword");
IDRegistry.genItemID("black_steelShovel");
IDRegistry.genItemID("black_steelPickaxe");
IDRegistry.genItemID("black_steelAxe");
IDRegistry.genItemID("black_steelHoe");
IDRegistry.genItemID("oureclaseSword");
IDRegistry.genItemID("oureclaseShovel");
IDRegistry.genItemID("oureclasePickaxe");
IDRegistry.genItemID("oureclaseAxe");
IDRegistry.genItemID("oureclaseHoe");
IDRegistry.genItemID("astral_silverSword");
IDRegistry.genItemID("astral_silverShovel");
IDRegistry.genItemID("astral_silverPickaxe");
IDRegistry.genItemID("astral_silverAxe");
IDRegistry.genItemID("astral_silverHoe");
IDRegistry.genItemID("carmotSword");
IDRegistry.genItemID("carmotShovel");
IDRegistry.genItemID("carmotPickaxe");
IDRegistry.genItemID("carmotAxe");
IDRegistry.genItemID("carmotHoe");
IDRegistry.genItemID("mithrilSword");
IDRegistry.genItemID("mithrilShovel");
IDRegistry.genItemID("mithrilPickaxe");
IDRegistry.genItemID("mithrilAxe");
IDRegistry.genItemID("mithrilHoe");
IDRegistry.genItemID("quicksilverSword");
IDRegistry.genItemID("quicksilverShovel");
IDRegistry.genItemID("quicksilverPickaxe");
IDRegistry.genItemID("quicksilverAxe");
IDRegistry.genItemID("quicksilverHoe");
IDRegistry.genItemID("haderothSword");
IDRegistry.genItemID("haderothShovel");
IDRegistry.genItemID("haderothPickaxe");
IDRegistry.genItemID("haderothAxe");
IDRegistry.genItemID("haderothHoe");
IDRegistry.genItemID("orichalcumSword");
IDRegistry.genItemID("orichalcumShovel");
IDRegistry.genItemID("orichalcumPickaxe");
IDRegistry.genItemID("orichalcumAxe");
IDRegistry.genItemID("orichalcumHoe");
IDRegistry.genItemID("celenegilSword");
IDRegistry.genItemID("celenegilShovel");
IDRegistry.genItemID("celenegilPickaxe");
IDRegistry.genItemID("celenegilAxe");
IDRegistry.genItemID("celenegilHoe");
IDRegistry.genItemID("adamantineSword");
IDRegistry.genItemID("adamantineShovel");
IDRegistry.genItemID("adamantinePickaxe");
IDRegistry.genItemID("adamantineAxe");
IDRegistry.genItemID("adamantineHoe");
IDRegistry.genItemID("atlarusSword");
IDRegistry.genItemID("atlarusShovel");
IDRegistry.genItemID("atlarusPickaxe");
IDRegistry.genItemID("atlarusAxe");
IDRegistry.genItemID("atlarusHoe");
IDRegistry.genItemID("tartariteSword");
IDRegistry.genItemID("tartariteShovel");
IDRegistry.genItemID("tartaritePickaxe");
IDRegistry.genItemID("tartariteAxe");
IDRegistry.genItemID("tartariteHoe");
IDRegistry.genItemID("eximiteSword");
IDRegistry.genItemID("eximiteShovel");
IDRegistry.genItemID("eximitePickaxe");
IDRegistry.genItemID("eximiteAxe");
IDRegistry.genItemID("eximiteHoe");
IDRegistry.genItemID("desichalkosSword");
IDRegistry.genItemID("desichalkosShovel");
IDRegistry.genItemID("desichalkosPickaxe");
IDRegistry.genItemID("desichalkosAxe");
IDRegistry.genItemID("desichalkosHoe");
Item.createItem("copperSword", "Copper Sword", {name: "copper_sword", meta: 0}, {stack: 1});
Item.createItem("copperShovel", "Copper Shovel", {name: "copper_shovel", meta: 0}, {stack: 1});
Item.createItem("copperPickaxe", "Copper Pickaxe", {name: "copper_pickaxe", meta: 0}, {stack: 1});
Item.createItem("copperAxe", "Copper Axe", {name: "copper_axe", meta: 0}, {stack: 1});
Item.createItem("copperHoe", "Copper Hoe", {name: "copper_hoe", meta: 0}, {stack: 1});
Item.createItem("bronzeSword", "Bronze Sword", {name: "bronze_sword", meta: 0}, {stack: 1});
Item.createItem("bronzeShovel", "Bronze Shovel", {name: "bronze_shovel", meta: 0}, {stack: 1});
Item.createItem("bronzePickaxe", "Bronze Pickaxe", {name: "bronze_pickaxe", meta: 0}, {stack: 1});
Item.createItem("bronzeAxe", "Bronze Axe", {name: "bronze_axe", meta: 0}, {stack: 1});
Item.createItem("bronzeHoe", "Bronze Hoe", {name: "bronze_hoe", meta: 0}, {stack: 1});
Item.createItem("hepatizonSword", "Hepatizon Sword", {name: "hepatizon_sword", meta: 0}, {stack: 1});
Item.createItem("hepatizonShovel", "Hepatizon Shovel", {name: "hepatizon_shovel", meta: 0}, {stack: 1});
Item.createItem("hepatizonPickaxe", "Hepatizon Pickaxe", {name: "hepatizon_pickaxe", meta: 0}, {stack: 1});
Item.createItem("hepatizonAxe", "Hepatizon Axe", {name: "hepatizon_axe", meta: 0}, {stack: 1});
Item.createItem("hepatizonHoe", "Hepatizon Hoe", {name: "hepatizon_hoe", meta: 0}, {stack: 1});
Item.createItem("damascus_steelSword", "Damascus Steel Sword", {name: "damascus_steel_sword", meta: 0}, {stack: 1});
Item.createItem("damascus_steelShovel", "Damascus Steel Shovel", {name: "damascus_steel_shovel", meta: 0}, {stack: 1});
Item.createItem("damascus_steelPickaxe", "Damascus Steel Pickaxe", {name: "damascus_steel_pickaxe", meta: 0}, {stack: 1});
Item.createItem("damascus_steelAxe", "Damascus Steel Axe", {name: "damascus_steel_axe", meta: 0}, {stack: 1});
Item.createItem("damascus_steelHoe", "Damascus Steel Hoe", {name: "damascus_steel_hoe", meta: 0}, {stack: 1});
Item.createItem("angmallenSword", "Angmallen Sword", {name: "angmallen_sword", meta: 0}, {stack: 1});
Item.createItem("angmallenShovel", "Angmallen Shovel", {name: "angmallen_shovel", meta: 0}, {stack: 1});
Item.createItem("angmallenPickaxe", "Angmallen Pickaxe", {name: "angmallen_pickaxe", meta: 0}, {stack: 1});
Item.createItem("angmallenAxe", "Angmallen Axe", {name: "angmallen_axe", meta: 0}, {stack: 1});
Item.createItem("angmallenHoe", "Angmallen Hoe", {name: "angmallen_hoe", meta: 0}, {stack: 1});
Item.createItem("steelSword", "Steel Sword", {name: "steel_sword", meta: 0}, {stack: 1});
Item.createItem("steelShovel", "Steel Shovel", {name: "steel_shovel", meta: 0}, {stack: 1});
Item.createItem("steelPickaxe", "Steel Pickaxe", {name: "steel_pickaxe", meta: 0}, {stack: 1});
Item.createItem("steelAxe", "Steel Axe", {name: "steel_axe", meta: 0}, {stack: 1});
Item.createItem("steelHoe", "Steel Hoe", {name: "steel_hoe", meta: 0}, {stack: 1});
Item.createItem("brassSword", "Brass Sword", {name: "brass_sword", meta: 0}, {stack: 1});
Item.createItem("brassShovel", "Brass Shovel", {name: "brass_shovel", meta: 0}, {stack: 1});
Item.createItem("brassPickaxe", "Brass Pickaxe", {name: "brass_pickaxe", meta: 0}, {stack: 1});
Item.createItem("brassAxe", "Brass Axe", {name: "brass_axe", meta: 0}, {stack: 1});
Item.createItem("brassHoe", "Brass Hoe", {name: "brass_hoe", meta: 0}, {stack: 1});
Item.createItem("silverSword", "Silver Sword", {name: "silver_sword", meta: 0}, {stack: 1});
Item.createItem("silverShovel", "Silver Shovel", {name: "silver_shovel", meta: 0}, {stack: 1});
Item.createItem("silverPickaxe", "Silver Pickaxe", {name: "silver_pickaxe", meta: 0}, {stack: 1});
Item.createItem("silverAxe", "Silver Axe", {name: "silver_axe", meta: 0}, {stack: 1});
Item.createItem("silverHoe", "Silver Hoe", {name: "silver_hoe", meta: 0}, {stack: 1});
Item.createItem("electrumSword", "Electrum Sword", {name: "electrum_sword", meta: 0}, {stack: 1});
Item.createItem("electrumShovel", "Electrum Shovel", {name: "electrum_shovel", meta: 0}, {stack: 1});
Item.createItem("electrumPickaxe", "Electrum Pickaxe", {name: "electrum_pickaxe", meta: 0}, {stack: 1});
Item.createItem("electrumAxe", "Electrum Axe", {name: "electrum_axe", meta: 0}, {stack: 1});
Item.createItem("electrumHoe", "Electrum Hoe", {name: "electrum_hoe", meta: 0}, {stack: 1});
Item.createItem("platinumSword", "Platinum Sword", {name: "platinum_sword", meta: 0}, {stack: 1});
Item.createItem("platinumShovel", "Platinum Shovel", {name: "platinum_shovel", meta: 0}, {stack: 1});
Item.createItem("platinumPickaxe", "Platinum Pickaxe", {name: "platinum_pickaxe", meta: 0}, {stack: 1});
Item.createItem("platinumAxe", "Platinum Axe", {name: "platinum_axe", meta: 0}, {stack: 1});
Item.createItem("platinumHoe", "Platinum Hoe", {name: "platinum_hoe", meta: 0}, {stack: 1});
Item.createItem("ignatiusSword", "Ignatius Sword", {name: "ignatius_sword", meta: 0}, {stack: 1});
Item.createItem("ignatiusShovel", "Ignatius Shovel", {name: "ignatius_shovel", meta: 0}, {stack: 1});
Item.createItem("ignatiusPickaxe", "Ignatius Pickaxe", {name: "ignatius_pickaxe", meta: 0}, {stack: 1});
Item.createItem("ignatiusAxe", "Ignatius Axe", {name: "ignatius_axe", meta: 0}, {stack: 1});
Item.createItem("ignatiusHoe", "Ignatius Hoe", {name: "ignatius_hoe", meta: 0}, {stack: 1});
Item.createItem("shadow_ironSword", "Shadow Iron Sword", {name: "shadow_iron_sword", meta: 0}, {stack: 1});
Item.createItem("shadow_ironShovel", "Shadow Iron Shovel", {name: "shadow_iron_shovel", meta: 0}, {stack: 1});
Item.createItem("shadow_ironPickaxe", "Shadow Iron Pickaxe", {name: "shadow_iron_pickaxe", meta: 0}, {stack: 1});
Item.createItem("shadow_ironAxe", "Shadow Iron Axe", {name: "shadow_iron_axe", meta: 0}, {stack: 1});
Item.createItem("shadow_ironHoe", "Shadow Iron Hoe", {name: "shadow_iron_hoe", meta: 0}, {stack: 1});
Item.createItem("shadow_steelSword", "Shadow Steel Sword", {name: "shadow_steel_sword", meta: 0}, {stack: 1});
Item.createItem("shadow_steelShovel", "Shadow Steel Shovel", {name: "shadow_steel_shovel", meta: 0}, {stack: 1});
Item.createItem("shadow_steelPickaxe", "Shadow Steel Pickaxe", {name: "shadow_steel_pickaxe", meta: 0}, {stack: 1});
Item.createItem("shadow_steelAxe", "Shadow Steel Axe", {name: "shadow_steel_axe", meta: 0}, {stack: 1});
Item.createItem("shadow_steelHoe", "Shadow Steel Hoe", {name: "shadow_steel_hoe", meta: 0}, {stack: 1});
Item.createItem("midasiumSword", "Midasium Sword", {name: "midasium_sword", meta: 0}, {stack: 1});
Item.createItem("midasiumShovel", "Midasium Shovel", {name: "midasium_shovel", meta: 0}, {stack: 1});
Item.createItem("midasiumPickaxe", "Midasium Pickaxe", {name: "midasium_pickaxe", meta: 0}, {stack: 1});
Item.createItem("midasiumAxe", "Midasium Axe", {name: "midasium_axe", meta: 0}, {stack: 1});
Item.createItem("midasiumHoe", "Midasium Hoe", {name: "midasium_hoe", meta: 0}, {stack: 1});
Item.createItem("vyroxeresSword", "Vyroxeres Sword", {name: "vyroxeres_sword", meta: 0}, {stack: 1});
Item.createItem("vyroxeresShovel", "Vyroxeres Shovel", {name: "vyroxeres_shovel", meta: 0}, {stack: 1});
Item.createItem("vyroxeresPickaxe", "Vyroxeres Pickaxe", {name: "vyroxeres_pickaxe", meta: 0}, {stack: 1});
Item.createItem("vyroxeresAxe", "Vyroxeres Axe", {name: "vyroxeres_axe", meta: 0}, {stack: 1});
Item.createItem("vyroxeresHoe", "Vyroxeres Hoe", {name: "vyroxeres_hoe", meta: 0}, {stack: 1});
Item.createItem("ceruclaseSword", "Ceruclase Sword", {name: "ceruclase_sword", meta: 0}, {stack: 1});
Item.createItem("ceruclaseShovel", "Ceruclase Shovel", {name: "ceruclase_shovel", meta: 0}, {stack: 1});
Item.createItem("ceruclasePickaxe", "Ceruclase Pickaxe", {name: "ceruclase_pickaxe", meta: 0}, {stack: 1});
Item.createItem("ceruclaseAxe", "Ceruclase Axe", {name: "ceruclase_axe", meta: 0}, {stack: 1});
Item.createItem("ceruclaseHoe", "Ceruclase Hoe", {name: "ceruclase_hoe", meta: 0}, {stack: 1});
Item.createItem("inolashiteSword", "Inolashite Sword", {name: "inolashite_sword", meta: 0}, {stack: 1});
Item.createItem("inolashiteShovel", "Inolashite Shovel", {name: "inolashite_shovel", meta: 0}, {stack: 1});
Item.createItem("inolashitePickaxe", "Inolashite Pickaxe", {name: "inolashite_pickaxe", meta: 0}, {stack: 1});
Item.createItem("inolashiteAxe", "Inolashite Axe", {name: "inolashite_axe", meta: 0}, {stack: 1});
Item.createItem("inolashiteHoe", "Inolashite Hoe", {name: "inolashite_hoe", meta: 0}, {stack: 1});
Item.createItem("kalendriteSword", "Kalendrite Sword", {name: "kalendrite_sword", meta: 0}, {stack: 1});
Item.createItem("kalendriteShovel", "Kalendrite Shovel", {name: "kalendrite_shovel", meta: 0}, {stack: 1});
Item.createItem("kalendritePickaxe", "Kalendrite Pickaxe", {name: "kalendrite_pickaxe", meta: 0}, {stack: 1});
Item.createItem("kalendriteAxe", "Kalendrite Axe", {name: "kalendrite_axe", meta: 0}, {stack: 1});
Item.createItem("kalendriteHoe", "Kalendrite Hoe", {name: "kalendrite_hoe", meta: 0}, {stack: 1});
Item.createItem("amordrineSword", "Amordrine Sword", {name: "amordrine_sword", meta: 0}, {stack: 1});
Item.createItem("amordrineShovel", "Amordrine Shovel", {name: "amordrine_shovel", meta: 0}, {stack: 1});
Item.createItem("amordrinePickaxe", "Amordrine Pickaxe", {name: "amordrine_pickaxe", meta: 0}, {stack: 1});
Item.createItem("amordrineAxe", "Amordrine Axe", {name: "amordrine_axe", meta: 0}, {stack: 1});
Item.createItem("amordrineHoe", "Amordrine Hoe", {name: "amordrine_hoe", meta: 0}, {stack: 1});
Item.createItem("vulcaniteSword", "Vulcanite Sword", {name: "vulcanite_sword", meta: 0}, {stack: 1});
Item.createItem("vulcaniteShovel", "Vulcanite Shovel", {name: "vulcanite_shovel", meta: 0}, {stack: 1});
Item.createItem("vulcanitePickaxe", "Vulcanite Pickaxe", {name: "vulcanite_pickaxe", meta: 0}, {stack: 1});
Item.createItem("vulcaniteAxe", "Vulcanite Axe", {name: "vulcanite_axe", meta: 0}, {stack: 1});
Item.createItem("vulcaniteHoe", "Vulcanite Hoe", {name: "vulcanite_hoe", meta: 0}, {stack: 1});
Item.createItem("sanguiniteSword", "Sanguinite Sword", {name: "sanguinite_sword", meta: 0}, {stack: 1});
Item.createItem("sanguiniteShovel", "Sanguinite Shovel", {name: "sanguinite_shovel", meta: 0}, {stack: 1});
Item.createItem("sanguinitePickaxe", "Sanguinite Pickaxe", {name: "sanguinite_pickaxe", meta: 0}, {stack: 1});
Item.createItem("sanguiniteAxe", "Sanguinite Axe", {name: "sanguinite_axe", meta: 0}, {stack: 1});
Item.createItem("sanguiniteHoe", "Sanguinite Hoe", {name: "sanguinite_hoe", meta: 0}, {stack: 1});
Item.createItem("prometheumSword", "Prometheum Sword", {name: "prometheum_sword", meta: 0}, {stack: 1});
Item.createItem("prometheumShovel", "Prometheum Shovel", {name: "prometheum_shovel", meta: 0}, {stack: 1});
Item.createItem("prometheumPickaxe", "Prometheum Pickaxe", {name: "prometheum_pickaxe", meta: 0}, {stack: 1});
Item.createItem("prometheumAxe", "Prometheum Axe", {name: "prometheum_axe", meta: 0}, {stack: 1});
Item.createItem("prometheumHoe", "Prometheum Hoe", {name: "prometheum_hoe", meta: 0}, {stack: 1});
Item.createItem("deep_ironSword", "Deep Iron Sword", {name: "deep_iron_sword", meta: 0}, {stack: 1});
Item.createItem("deep_ironShovel", "Deep Iron Shovel", {name: "deep_iron_shovel", meta: 0}, {stack: 1});
Item.createItem("deep_ironPickaxe", "Deep Iron Pickaxe", {name: "deep_iron_pickaxe", meta: 0}, {stack: 1});
Item.createItem("deep_ironAxe", "Deep Iron Axe", {name: "deep_iron_axe", meta: 0}, {stack: 1});
Item.createItem("deep_ironHoe", "Deep Iron Hoe", {name: "deep_iron_hoe", meta: 0}, {stack: 1});
Item.createItem("black_steelSword", "Black Steel Sword", {name: "black_steel_sword", meta: 0}, {stack: 1});
Item.createItem("black_steelShovel", "Black Steel Shovel", {name: "black_steel_shovel", meta: 0}, {stack: 1});
Item.createItem("black_steelPickaxe", "Black Steel Pickaxe", {name: "black_steel_pickaxe", meta: 0}, {stack: 1});
Item.createItem("black_steelAxe", "Black Steel Axe", {name: "black_steel_axe", meta: 0}, {stack: 1});
Item.createItem("black_steelHoe", "Black Steel Hoe", {name: "black_steel_hoe", meta: 0}, {stack: 1});
Item.createItem("oureclaseSword", "Oureclase Sword", {name: "oureclase_sword", meta: 0}, {stack: 1});
Item.createItem("oureclaseShovel", "Oureclase Shovel", {name: "oureclase_shovel", meta: 0}, {stack: 1});
Item.createItem("oureclasePickaxe", "Oureclase Pickaxe", {name: "oureclase_pickaxe", meta: 0}, {stack: 1});
Item.createItem("oureclaseAxe", "Oureclase Axe", {name: "oureclase_axe", meta: 0}, {stack: 1});
Item.createItem("oureclaseHoe", "Oureclase Hoe", {name: "oureclase_hoe", meta: 0}, {stack: 1});
Item.createItem("astral_silverSword", "Astral Silver Sword", {name: "astral_silver_sword", meta: 0}, {stack: 1});
Item.createItem("astral_silverShovel", "Astral Silver Shovel", {name: "astral_silver_shovel", meta: 0}, {stack: 1});
Item.createItem("astral_silverPickaxe", "Astral Silver Pickaxe", {name: "astral_silver_pickaxe", meta: 0}, {stack: 1});
Item.createItem("astral_silverAxe", "Astral Silver Axe", {name: "astral_silver_axe", meta: 0}, {stack: 1});
Item.createItem("astral_silverHoe", "Astral Silver Hoe", {name: "astral_silver_hoe", meta: 0}, {stack: 1});
Item.createItem("carmotSword", "Carmot Sword", {name: "carmot_sword", meta: 0}, {stack: 1});
Item.createItem("carmotShovel", "Carmot Shovel", {name: "carmot_shovel", meta: 0}, {stack: 1});
Item.createItem("carmotPickaxe", "Carmot Pickaxe", {name: "carmot_pickaxe", meta: 0}, {stack: 1});
Item.createItem("carmotAxe", "Carmot Axe", {name: "carmot_axe", meta: 0}, {stack: 1});
Item.createItem("carmotHoe", "Carmot Hoe", {name: "carmot_hoe", meta: 0}, {stack: 1});
Item.createItem("mithrilSword", "Mithril Sword", {name: "mithril_sword", meta: 0}, {stack: 1});
Item.createItem("mithrilShovel", "Mithril Shovel", {name: "mithril_shovel", meta: 0}, {stack: 1});
Item.createItem("mithrilPickaxe", "Mithril Pickaxe", {name: "mithril_pickaxe", meta: 0}, {stack: 1});
Item.createItem("mithrilAxe", "Mithril Axe", {name: "mithril_axe", meta: 0}, {stack: 1});
Item.createItem("mithrilHoe", "Mithril Hoe", {name: "mithril_hoe", meta: 0}, {stack: 1});
Item.createItem("quicksilverSword", "Quicksilver Sword", {name: "quicksilver_sword", meta: 0}, {stack: 1});
Item.createItem("quicksilverShovel", "Quicksilver Shovel", {name: "quicksilver_shovel", meta: 0}, {stack: 1});
Item.createItem("quicksilverPickaxe", "Quicksilver Pickaxe", {name: "quicksilver_pickaxe", meta: 0}, {stack: 1});
Item.createItem("quicksilverAxe", "Quicksilver Axe", {name: "quicksilver_axe", meta: 0}, {stack: 1});
Item.createItem("quicksilverHoe", "Quicksilver Hoe", {name: "quicksilver_hoe", meta: 0}, {stack: 1});
Item.createItem("haderothSword", "Haderoth Sword", {name: "haderoth_sword", meta: 0}, {stack: 1});
Item.createItem("haderothShovel", "Haderoth Shovel", {name: "haderoth_shovel", meta: 0}, {stack: 1});
Item.createItem("haderothPickaxe", "Haderoth Pickaxe", {name: "haderoth_pickaxe", meta: 0}, {stack: 1});
Item.createItem("haderothAxe", "Haderoth Axe", {name: "haderoth_axe", meta: 0}, {stack: 1});
Item.createItem("haderothHoe", "Haderoth Hoe", {name: "haderoth_hoe", meta: 0}, {stack: 1});
Item.createItem("orichalcumSword", "Orichalcum Sword", {name: "orichalcum_sword", meta: 0}, {stack: 1});
Item.createItem("orichalcumShovel", "Orichalcum Shovel", {name: "orichalcum_shovel", meta: 0}, {stack: 1});
Item.createItem("orichalcumPickaxe", "Orichalcum Pickaxe", {name: "orichalcum_pickaxe", meta: 0}, {stack: 1});
Item.createItem("orichalcumAxe", "Orichalcum Axe", {name: "orichalcum_axe", meta: 0}, {stack: 1});
Item.createItem("orichalcumHoe", "Orichalcum Hoe", {name: "orichalcum_hoe", meta: 0}, {stack: 1});
Item.createItem("celenegilSword", "Celenegil Sword", {name: "celenegil_sword", meta: 0}, {stack: 1});
Item.createItem("celenegilShovel", "Celenegil Shovel", {name: "celenegil_shovel", meta: 0}, {stack: 1});
Item.createItem("celenegilPickaxe", "Celenegil Pickaxe", {name: "celenegil_pickaxe", meta: 0}, {stack: 1});
Item.createItem("celenegilAxe", "Celenegil Axe", {name: "celenegil_axe", meta: 0}, {stack: 1});
Item.createItem("celenegilHoe", "Celenegil Hoe", {name: "celenegil_hoe", meta: 0}, {stack: 1});
Item.createItem("adamantineSword", "Adamantine Sword", {name: "adamantine_sword", meta: 0}, {stack: 1});
Item.createItem("adamantineShovel", "Adamantine Shovel", {name: "adamantine_shovel", meta: 0}, {stack: 1});
Item.createItem("adamantinePickaxe", "Adamantine Pickaxe", {name: "adamantine_pickaxe", meta: 0}, {stack: 1});
Item.createItem("adamantineAxe", "Adamantine Axe", {name: "adamantine_axe", meta: 0}, {stack: 1});
Item.createItem("adamantineHoe", "Adamantine Hoe", {name: "adamantine_hoe", meta: 0}, {stack: 1});
Item.createItem("atlarusSword", "Atlarus Sword", {name: "atlarus_sword", meta: 0}, {stack: 1});
Item.createItem("atlarusShovel", "Atlarus Shovel", {name: "atlarus_shovel", meta: 0}, {stack: 1});
Item.createItem("atlarusPickaxe", "Atlarus Pickaxe", {name: "atlarus_pickaxe", meta: 0}, {stack: 1});
Item.createItem("atlarusAxe", "Atlarus Axe", {name: "atlarus_axe", meta: 0}, {stack: 1});
Item.createItem("atlarusHoe", "Atlarus Hoe", {name: "atlarus_hoe", meta: 0}, {stack: 1});
Item.createItem("tartariteSword", "Tartarite Sword", {name: "tartarite_sword", meta: 0}, {stack: 1});
Item.createItem("tartariteShovel", "Tartarite Shovel", {name: "tartarite_shovel", meta: 0}, {stack: 1});
Item.createItem("tartaritePickaxe", "Tartarite Pickaxe", {name: "tartarite_pickaxe", meta: 0}, {stack: 1});
Item.createItem("tartariteAxe", "Tartarite Axe", {name: "tartarite_axe", meta: 0}, {stack: 1});
Item.createItem("tartariteHoe", "Tartarite Hoe", {name: "tartarite_hoe", meta: 0}, {stack: 1});
Item.createItem("eximiteSword", "Eximite Sword", {name: "eximite_sword", meta: 0}, {stack: 1});
Item.createItem("eximiteShovel", "Eximite Shovel", {name: "eximite_shovel", meta: 0}, {stack: 1});
Item.createItem("eximitePickaxe", "Eximite Pickaxe", {name: "eximite_pickaxe", meta: 0}, {stack: 1});
Item.createItem("eximiteAxe", "Eximite Axe", {name: "eximite_axe", meta: 0}, {stack: 1});
Item.createItem("eximiteHoe", "Eximite Hoe", {name: "eximite_hoe", meta: 0}, {stack: 1});
Item.createItem("desichalkosSword", "Desichalkos Sword", {name: "desichalkos_sword", meta: 0}, {stack: 1});
Item.createItem("desichalkosShovel", "Desichalkos Shovel", {name: "desichalkos_shovel", meta: 0}, {stack: 1});
Item.createItem("desichalkosPickaxe", "Desichalkos Pickaxe", {name: "desichalkos_pickaxe", meta: 0}, {stack: 1});
Item.createItem("desichalkosAxe", "Desichalkos Axe", {name: "desichalkos_axe", meta: 0}, {stack: 1});
Item.createItem("desichalkosHoe", "Desichalkos Hoe", {name: "desichalkos_hoe", meta: 0}, {stack: 1});
ToolAPI.setTool(ItemID.copperSword, "copper", MTT.sword);
ToolAPI.setTool(ItemID.copperShovel, "copper", MTT.shovel);
ToolAPI.setTool(ItemID.copperPickaxe, "copper", MTT.pickaxe);
ToolAPI.setTool(ItemID.copperAxe, "copper", MTT.axe);
ToolAPI.setTool(ItemID.copperHoe, "copper", MTT.hoe);
ToolAPI.setTool(ItemID.bronzeSword, "bronze", MTT.sword);
ToolAPI.setTool(ItemID.bronzeShovel, "bronze", MTT.shovel);
ToolAPI.setTool(ItemID.bronzePickaxe, "bronze", MTT.pickaxe);
ToolAPI.setTool(ItemID.bronzeAxe, "bronze", MTT.axe);
ToolAPI.setTool(ItemID.bronzeHoe, "bronze", MTT.hoe);
ToolAPI.setTool(ItemID.hepatizonSword, "hepatizon", MTT.sword);
ToolAPI.setTool(ItemID.hepatizonShovel, "hepatizon", MTT.shovel);
ToolAPI.setTool(ItemID.hepatizonPickaxe, "hepatizon", MTT.pickaxe);
ToolAPI.setTool(ItemID.hepatizonAxe, "hepatizon", MTT.axe);
ToolAPI.setTool(ItemID.hepatizonHoe, "hepatizon", MTT.hoe);
ToolAPI.setTool(ItemID.damascus_steelSword, "damascus_steel", MTT.sword);
ToolAPI.setTool(ItemID.damascus_steelShovel, "damascus_steel", MTT.shovel);
ToolAPI.setTool(ItemID.damascus_steelPickaxe, "damascus_steel", MTT.pickaxe);
ToolAPI.setTool(ItemID.damascus_steelAxe, "damascus_steel", MTT.axe);
ToolAPI.setTool(ItemID.damascus_steelHoe, "damascus_steel", MTT.hoe);
ToolAPI.setTool(ItemID.angmallenSword, "angmallen", MTT.sword);
ToolAPI.setTool(ItemID.angmallenShovel, "angmallen", MTT.shovel);
ToolAPI.setTool(ItemID.angmallenPickaxe, "angmallen", MTT.pickaxe);
ToolAPI.setTool(ItemID.angmallenAxe, "angmallen", MTT.axe);
ToolAPI.setTool(ItemID.angmallenHoe, "angmallen", MTT.hoe);
ToolAPI.setTool(ItemID.steelSword, "steel", MTT.sword);
ToolAPI.setTool(ItemID.steelShovel, "steel", MTT.shovel);
ToolAPI.setTool(ItemID.steelPickaxe, "steel", MTT.pickaxe);
ToolAPI.setTool(ItemID.steelAxe, "steel", MTT.axe);
ToolAPI.setTool(ItemID.steelHoe, "steel", MTT.hoe);
ToolAPI.setTool(ItemID.brassSword, "brass", MTT.sword);
ToolAPI.setTool(ItemID.brassShovel, "brass", MTT.shovel);
ToolAPI.setTool(ItemID.brassPickaxe, "brass", MTT.pickaxe);
ToolAPI.setTool(ItemID.brassAxe, "brass", MTT.axe);
ToolAPI.setTool(ItemID.brassHoe, "brass", MTT.hoe);
ToolAPI.setTool(ItemID.silverSword, "silver", MTT.sword);
ToolAPI.setTool(ItemID.silverShovel, "silver", MTT.shovel);
ToolAPI.setTool(ItemID.silverPickaxe, "silver", MTT.pickaxe);
ToolAPI.setTool(ItemID.silverAxe, "silver", MTT.axe);
ToolAPI.setTool(ItemID.silverHoe, "silver", MTT.hoe);
ToolAPI.setTool(ItemID.electrumSword, "electrum", MTT.sword);
ToolAPI.setTool(ItemID.electrumShovel, "electrum", MTT.shovel);
ToolAPI.setTool(ItemID.electrumPickaxe, "electrum", MTT.pickaxe);
ToolAPI.setTool(ItemID.electrumAxe, "electrum", MTT.axe);
ToolAPI.setTool(ItemID.electrumHoe, "electrum", MTT.hoe);
ToolAPI.setTool(ItemID.platinumSword, "platinum", MTT.sword);
ToolAPI.setTool(ItemID.platinumShovel, "platinum", MTT.shovel);
ToolAPI.setTool(ItemID.platinumPickaxe, "platinum", MTT.pickaxe);
ToolAPI.setTool(ItemID.platinumAxe, "platinum", MTT.axe);
ToolAPI.setTool(ItemID.platinumHoe, "platinum", MTT.hoe);
ToolAPI.setTool(ItemID.ignatiusSword, "ignatius", MTT.sword);
ToolAPI.setTool(ItemID.ignatiusShovel, "ignatius", MTT.shovel);
ToolAPI.setTool(ItemID.ignatiusPickaxe, "ignatius", MTT.pickaxe);
ToolAPI.setTool(ItemID.ignatiusAxe, "ignatius", MTT.axe);
ToolAPI.setTool(ItemID.ignatiusHoe, "ignatius", MTT.hoe);
ToolAPI.setTool(ItemID.shadow_ironSword, "shadow_iron", MTT.sword);
ToolAPI.setTool(ItemID.shadow_ironShovel, "shadow_iron", MTT.shovel);
ToolAPI.setTool(ItemID.shadow_ironPickaxe, "shadow_iron", MTT.pickaxe);
ToolAPI.setTool(ItemID.shadow_ironAxe, "shadow_iron", MTT.axe);
ToolAPI.setTool(ItemID.shadow_ironHoe, "shadow_iron", MTT.hoe);
ToolAPI.setTool(ItemID.shadow_steelSword, "shadow_steel", MTT.sword);
ToolAPI.setTool(ItemID.shadow_steelShovel, "shadow_steel", MTT.shovel);
ToolAPI.setTool(ItemID.shadow_steelPickaxe, "shadow_steel", MTT.pickaxe);
ToolAPI.setTool(ItemID.shadow_steelAxe, "shadow_steel", MTT.axe);
ToolAPI.setTool(ItemID.shadow_steelHoe, "shadow_steel", MTT.hoe);
ToolAPI.setTool(ItemID.midasiumSword, "midasium", MTT.sword);
ToolAPI.setTool(ItemID.midasiumShovel, "midasium", MTT.shovel);
ToolAPI.setTool(ItemID.midasiumPickaxe, "midasium", MTT.pickaxe);
ToolAPI.setTool(ItemID.midasiumAxe, "midasium", MTT.axe);
ToolAPI.setTool(ItemID.midasiumHoe, "midasium", MTT.hoe);
ToolAPI.setTool(ItemID.vyroxeresSword, "vyroxeres", MTT.sword);
ToolAPI.setTool(ItemID.vyroxeresShovel, "vyroxeres", MTT.shovel);
ToolAPI.setTool(ItemID.vyroxeresPickaxe, "vyroxeres", MTT.pickaxe);
ToolAPI.setTool(ItemID.vyroxeresAxe, "vyroxeres", MTT.axe);
ToolAPI.setTool(ItemID.vyroxeresHoe, "vyroxeres", MTT.hoe);
ToolAPI.setTool(ItemID.ceruclaseSword, "ceruclase", MTT.sword);
ToolAPI.setTool(ItemID.ceruclaseShovel, "ceruclase", MTT.shovel);
ToolAPI.setTool(ItemID.ceruclasePickaxe, "ceruclase", MTT.pickaxe);
ToolAPI.setTool(ItemID.ceruclaseAxe, "ceruclase", MTT.axe);
ToolAPI.setTool(ItemID.ceruclaseHoe, "ceruclase", MTT.hoe);
ToolAPI.setTool(ItemID.inolashiteSword, "inolashite", MTT.sword);
ToolAPI.setTool(ItemID.inolashiteShovel, "inolashite", MTT.shovel);
ToolAPI.setTool(ItemID.inolashitePickaxe, "inolashite", MTT.pickaxe);
ToolAPI.setTool(ItemID.inolashiteAxe, "inolashite", MTT.axe);
ToolAPI.setTool(ItemID.inolashiteHoe, "inolashite", MTT.hoe);
ToolAPI.setTool(ItemID.kalendriteSword, "kalendrite", MTT.sword);
ToolAPI.setTool(ItemID.kalendriteShovel, "kalendrite", MTT.shovel);
ToolAPI.setTool(ItemID.kalendritePickaxe, "kalendrite", MTT.pickaxe);
ToolAPI.setTool(ItemID.kalendriteAxe, "kalendrite", MTT.axe);
ToolAPI.setTool(ItemID.kalendriteHoe, "kalendrite", MTT.hoe);
ToolAPI.setTool(ItemID.amordrineSword, "amordrine", MTT.sword);
ToolAPI.setTool(ItemID.amordrineShovel, "amordrine", MTT.shovel);
ToolAPI.setTool(ItemID.amordrinePickaxe, "amordrine", MTT.pickaxe);
ToolAPI.setTool(ItemID.amordrineAxe, "amordrine", MTT.axe);
ToolAPI.setTool(ItemID.amordrineHoe, "amordrine", MTT.hoe);
ToolAPI.setTool(ItemID.vulcaniteSword, "vulcanite", MTT.sword);
ToolAPI.setTool(ItemID.vulcaniteShovel, "vulcanite", MTT.shovel);
ToolAPI.setTool(ItemID.vulcanitePickaxe, "vulcanite", MTT.pickaxe);
ToolAPI.setTool(ItemID.vulcaniteAxe, "vulcanite", MTT.axe);
ToolAPI.setTool(ItemID.vulcaniteHoe, "vulcanite", MTT.hoe);
ToolAPI.setTool(ItemID.sanguiniteSword, "sanguinite", MTT.sword);
ToolAPI.setTool(ItemID.sanguiniteShovel, "sanguinite", MTT.shovel);
ToolAPI.setTool(ItemID.sanguinitePickaxe, "sanguinite", MTT.pickaxe);
ToolAPI.setTool(ItemID.sanguiniteAxe, "sanguinite", MTT.axe);
ToolAPI.setTool(ItemID.sanguiniteHoe, "sanguinite", MTT.hoe);
ToolAPI.setTool(ItemID.prometheumSword, "prometheum", MTT.sword);
ToolAPI.setTool(ItemID.prometheumShovel, "prometheum", MTT.shovel);
ToolAPI.setTool(ItemID.prometheumPickaxe, "prometheum", MTT.pickaxe);
ToolAPI.setTool(ItemID.prometheumAxe, "prometheum", MTT.axe);
ToolAPI.setTool(ItemID.prometheumHoe, "prometheum", MTT.hoe);
ToolAPI.setTool(ItemID.deep_ironSword, "deep_iron", MTT.sword);
ToolAPI.setTool(ItemID.deep_ironShovel, "deep_iron", MTT.shovel);
ToolAPI.setTool(ItemID.deep_ironPickaxe, "deep_iron", MTT.pickaxe);
ToolAPI.setTool(ItemID.deep_ironAxe, "deep_iron", MTT.axe);
ToolAPI.setTool(ItemID.deep_ironHoe, "deep_iron", MTT.hoe);
ToolAPI.setTool(ItemID.black_steelSword, "black_steel", MTT.sword);
ToolAPI.setTool(ItemID.black_steelShovel, "black_steel", MTT.shovel);
ToolAPI.setTool(ItemID.black_steelPickaxe, "black_steel", MTT.pickaxe);
ToolAPI.setTool(ItemID.black_steelAxe, "black_steel", MTT.axe);
ToolAPI.setTool(ItemID.black_steelHoe, "black_steel", MTT.hoe);
ToolAPI.setTool(ItemID.oureclaseSword, "oureclase", MTT.sword);
ToolAPI.setTool(ItemID.oureclaseShovel, "oureclase", MTT.shovel);
ToolAPI.setTool(ItemID.oureclasePickaxe, "oureclase", MTT.pickaxe);
ToolAPI.setTool(ItemID.oureclaseAxe, "oureclase", MTT.axe);
ToolAPI.setTool(ItemID.oureclaseHoe, "oureclase", MTT.hoe);
ToolAPI.setTool(ItemID.astral_silverSword, "astral_silver", MTT.sword);
ToolAPI.setTool(ItemID.astral_silverShovel, "astral_silver", MTT.shovel);
ToolAPI.setTool(ItemID.astral_silverPickaxe, "astral_silver", MTT.pickaxe);
ToolAPI.setTool(ItemID.astral_silverAxe, "astral_silver", MTT.axe);
ToolAPI.setTool(ItemID.astral_silverHoe, "astral_silver", MTT.hoe);
ToolAPI.setTool(ItemID.carmotSword, "carmot", MTT.sword);
ToolAPI.setTool(ItemID.carmotShovel, "carmot", MTT.shovel);
ToolAPI.setTool(ItemID.carmotPickaxe, "carmot", MTT.pickaxe);
ToolAPI.setTool(ItemID.carmotAxe, "carmot", MTT.axe);
ToolAPI.setTool(ItemID.carmotHoe, "carmot", MTT.hoe);
ToolAPI.setTool(ItemID.mithrilSword, "mithril", MTT.sword);
ToolAPI.setTool(ItemID.mithrilShovel, "mithril", MTT.shovel);
ToolAPI.setTool(ItemID.mithrilPickaxe, "mithril", MTT.pickaxe);
ToolAPI.setTool(ItemID.mithrilAxe, "mithril", MTT.axe);
ToolAPI.setTool(ItemID.mithrilHoe, "mithril", MTT.hoe);
ToolAPI.setTool(ItemID.quicksilverSword, "quicksilver", MTT.sword);
ToolAPI.setTool(ItemID.quicksilverShovel, "quicksilver", MTT.shovel);
ToolAPI.setTool(ItemID.quicksilverPickaxe, "quicksilver", MTT.pickaxe);
ToolAPI.setTool(ItemID.quicksilverAxe, "quicksilver", MTT.axe);
ToolAPI.setTool(ItemID.quicksilverHoe, "quicksilver", MTT.hoe);
ToolAPI.setTool(ItemID.haderothSword, "haderoth", MTT.sword);
ToolAPI.setTool(ItemID.haderothShovel, "haderoth", MTT.shovel);
ToolAPI.setTool(ItemID.haderothPickaxe, "haderoth", MTT.pickaxe);
ToolAPI.setTool(ItemID.haderothAxe, "haderoth", MTT.axe);
ToolAPI.setTool(ItemID.haderothHoe, "haderoth", MTT.hoe);
ToolAPI.setTool(ItemID.orichalcumSword, "orichalcum", MTT.sword);
ToolAPI.setTool(ItemID.orichalcumShovel, "orichalcum", MTT.shovel);
ToolAPI.setTool(ItemID.orichalcumPickaxe, "orichalcum", MTT.pickaxe);
ToolAPI.setTool(ItemID.orichalcumAxe, "orichalcum", MTT.axe);
ToolAPI.setTool(ItemID.orichalcumHoe, "orichalcum", MTT.hoe);
ToolAPI.setTool(ItemID.celenegilSword, "celenegil", MTT.sword);
ToolAPI.setTool(ItemID.celenegilShovel, "celenegil", MTT.shovel);
ToolAPI.setTool(ItemID.celenegilPickaxe, "celenegil", MTT.pickaxe);
ToolAPI.setTool(ItemID.celenegilAxe, "celenegil", MTT.axe);
ToolAPI.setTool(ItemID.celenegilHoe, "celenegil", MTT.hoe);
ToolAPI.setTool(ItemID.adamantineSword, "adamantine", MTT.sword);
ToolAPI.setTool(ItemID.adamantineShovel, "adamantine", MTT.shovel);
ToolAPI.setTool(ItemID.adamantinePickaxe, "adamantine", MTT.pickaxe);
ToolAPI.setTool(ItemID.adamantineAxe, "adamantine", MTT.axe);
ToolAPI.setTool(ItemID.adamantineHoe, "adamantine", MTT.hoe);
ToolAPI.setTool(ItemID.atlarusSword, "atlarus", MTT.sword);
ToolAPI.setTool(ItemID.atlarusShovel, "atlarus", MTT.shovel);
ToolAPI.setTool(ItemID.atlarusPickaxe, "atlarus", MTT.pickaxe);
ToolAPI.setTool(ItemID.atlarusAxe, "atlarus", MTT.axe);
ToolAPI.setTool(ItemID.atlarusHoe, "atlarus", MTT.hoe);
ToolAPI.setTool(ItemID.tartariteSword, "tartarite", MTT.sword);
ToolAPI.setTool(ItemID.tartariteShovel, "tartarite", MTT.shovel);
ToolAPI.setTool(ItemID.tartaritePickaxe, "tartarite", MTT.pickaxe);
ToolAPI.setTool(ItemID.tartariteAxe, "tartarite", MTT.axe);
ToolAPI.setTool(ItemID.tartariteHoe, "tartarite", MTT.hoe);
ToolAPI.setTool(ItemID.eximiteSword, "eximite", MTT.sword);
ToolAPI.setTool(ItemID.eximiteShovel, "eximite", MTT.shovel);
ToolAPI.setTool(ItemID.eximitePickaxe, "eximite", MTT.pickaxe);
ToolAPI.setTool(ItemID.eximiteAxe, "eximite", MTT.axe);
ToolAPI.setTool(ItemID.eximiteHoe, "eximite", MTT.hoe);
ToolAPI.setTool(ItemID.desichalkosSword, "desichalkos", MTT.sword);
ToolAPI.setTool(ItemID.desichalkosShovel, "desichalkos", MTT.shovel);
ToolAPI.setTool(ItemID.desichalkosPickaxe, "desichalkos", MTT.pickaxe);
ToolAPI.setTool(ItemID.desichalkosAxe, "desichalkos", MTT.axe);
ToolAPI.setTool(ItemID.desichalkosHoe, "desichalkos", MTT.hoe);
ToolAPI.addToolMaterial("fai", {durability: 150, level: 0, efficiency: 0, damage: 1, enchantability: 0});
IDRegistry.genItemID("fai");
Item.createItem("fai", "Flint And Ignatius", {name: "flint_and_ignatius", meta: 0}, {stack: 1});
ToolAPI.setTool(ItemID.fai, "fai", MTT.fai);
ToolAPI.addToolMaterial("fav", {durability: 150, level: 0, efficiency: 0, damage: 1, enchantability: 0});
IDRegistry.genItemID("fav");
Item.createItem("fav", "Flint And Vulcanite", {name: "flint_and_vulcanite", meta: 0}, {stack: 1});
ToolAPI.setTool(ItemID.fav, "fav", MTT.fav);

