KEX.LootModule.createLootTableModifier("entities/wither_skeleton")
    .createNewPool()
        .addEntry()
            .describeItem(ItemID.Witherbone)
            .setCount(0, 3)
            .beginFunctions()
                .addLootingEnchantFunction(0, 1)
            .endFunctions()
        .endEntry()
    .endPool()