Chemistry.registerElement(1, "H", "Hydrogen", "orange", "gas");
Chemistry.registerElement(2, "He", "Helium", "lightblue", "gas");
Chemistry.registerElement(3, "Li", "Lithium", "green");
Chemistry.registerElement(4, "Be", "Beryllium", "darkblue");
Chemistry.registerElement(5, "B", "Boron", "bluegreen");
Chemistry.registerElement(6, "C", "Carbon", "orange");
Chemistry.registerElement(7, "N", "Nitrogen", "orange", "gas");
Chemistry.registerElement(8, "O", "Oxygen", "orange", "gas");
Chemistry.registerElement(9, "F", "Fluorine", "yellow", "gas");
Chemistry.registerElement(10, "Ne", "Neon", "lightblue", "gas");
Chemistry.registerElement(11, "Na", "Sodium", "green");
Chemistry.registerElement(12, "Mg", "Magnesium", "darkblue");
Chemistry.registerElement(13, "Al", "Aluminium", "lightgreen");
Chemistry.registerElement(14, "Si", "Silicon", "lightgreen");
Chemistry.registerElement(15, "P", "Phosphorus", "orange");
Chemistry.registerElement(16, "S", "Sulfur", "orange");
Chemistry.registerElement(17, "Cl", "Chlorine", "yellow", "gas");
Chemistry.registerElement(18, "Ar", "Argon", "lightblue", "gas");
Chemistry.registerElement(19, "K", "Potassium", "green");
Chemistry.registerElement(20, "Ca", "Calcium", "darkblue");
Chemistry.registerElement(21, "Sc", "Scandium", "blue");
Chemistry.registerElement(22, "Ti", "Titanium", "blue");
Chemistry.registerElement(23, "V", "Vanadium", "blue");
Chemistry.registerElement(24, "Cr", "Chromium", "blue");
Chemistry.registerElement(25, "Mn", "Manganese", "blue");
Chemistry.registerElement(26, "Fe", "Iron", "blue");
Chemistry.registerElement(27, "Co", "Cobalt", "blue");
Chemistry.registerElement(28, "Ni", "Nickel", "blue");
Chemistry.registerElement(29, "Cu", "Copper", "blue");
Chemistry.registerElement(30, "Zn", "Zinc", "blue");
Chemistry.registerElement(31, "Ga", "Gallium", "lightgreen");
Chemistry.registerElement(32, "Ge", "Germanium", "bluegreen");
Chemistry.registerElement(33, "As", "Arsenic", "bluegreen");
Chemistry.registerElement(34, "Se", "Selenium", "orange");
Chemistry.registerElement(35, "Br", "Bromine", "yellow", "liquid");
Chemistry.registerElement(36, "Kr", "Krypton", "lightblue", "gas");
Chemistry.registerElement(37, "Rb", "Rubidium", "green");
Chemistry.registerElement(38, "Sr", "Strontium", "darkblue");
Chemistry.registerElement(39, "Y", "Yttrium", "blue");
Chemistry.registerElement(40, "Zr", "Zirconium", "blue");
Chemistry.registerElement(41, "Nb", "Niobium", "blue");
Chemistry.registerElement(42, "Mo", "Molybdenum", "blue");
Chemistry.registerElement(43, "Tc", "Technetium", "blue");
Chemistry.registerElement(44, "Ru", "Ruthenium", "blue");
Chemistry.registerElement(45, "Rh", "Rhodium", "blue");
Chemistry.registerElement(46, "Pd", "Palladium", "blue");
Chemistry.registerElement(47, "Ag", "Silver", "blue");
Chemistry.registerElement(48, "Cd", "Cadmium", "blue");
Chemistry.registerElement(49, "In", "Indium", "lightgreen");
Chemistry.registerElement(50, "Sn", "Tin", "lightgreen");
Chemistry.registerElement(51, "Sb", "Antimony", "bluegreen");
Chemistry.registerElement(52, "Te", "Tellurium", "bluegreen");
Chemistry.registerElement(53, "I", "Iodine", "yellow");
Chemistry.registerElement(54, "Xe", "Xenon", "lightblue", "gas");
Chemistry.registerElement(55, "Cs", "Caesium", "green");
Chemistry.registerElement(56, "Ba", "Barium", "darkblue");
Chemistry.registerElement(57, "La", "Lanthanum", "pink");
Chemistry.registerElement(58, "Ce", "Cerium", "pink");
Chemistry.registerElement(59, "Pr", "Praseodymium", "pink");
Chemistry.registerElement(60, "Nd", "Neodymium", "pink");
Chemistry.registerElement(61, "Pm", "Promethium", "pink");
Chemistry.registerElement(62, "Sm", "Samarium", "pink");
Chemistry.registerElement(63, "Eu", "Europium", "pink");
Chemistry.registerElement(64, "Gd", "Gadolinium", "pink");
Chemistry.registerElement(65, "Tb", "Terbium", "pink");
Chemistry.registerElement(66, "Dy", "Dysprosium", "pink");
Chemistry.registerElement(67, "Ho", "Holmium", "pink");
Chemistry.registerElement(68, "Er", "Erbium", "pink");
Chemistry.registerElement(69, "Tm", "Thulium", "pink");
Chemistry.registerElement(70, "Yb", "Ytterbium", "pink");
Chemistry.registerElement(71, "Lu", "Lutetium", "pink");
Chemistry.registerElement(72, "Hf", "Hafnium", "blue");
Chemistry.registerElement(73, "Ta", "Tantalum", "blue");
Chemistry.registerElement(74, "W", "Tungsten", "blue");
Chemistry.registerElement(75, "Re", "Rhenium", "blue");
Chemistry.registerElement(76, "Os", "Osmium", "blue");
Chemistry.registerElement(77, "Ir", "Iridium", "blue");
Chemistry.registerElement(78, "Pt", "Platinum", "blue");
Chemistry.registerElement(79, "Au", "Gold", "blue");
Chemistry.registerElement(80, "Hg", "Mercury", "blue", "liquid");
Chemistry.registerElement(81, "Tl", "Thallium", "lightgreen");
Chemistry.registerElement(82, "Pb", "Lead", "lightgreen");
Chemistry.registerElement(83, "Bi", "Bismuth", "lightgreen");
Chemistry.registerElement(84, "Po", "Polonium", "bluegreen");
Chemistry.registerElement(85, "At", "Astatine", "yellow");
Chemistry.registerElement(86, "Rn", "Radon", "lightblue", "gas");
Chemistry.registerElement(87, "Fr", "Francium", "green");
Chemistry.registerElement(88, "Ra", "Radium", "darkblue");
Chemistry.registerElement(89, "Ac", "Actinium", "red");
Chemistry.registerElement(90, "Th", "Thorium", "red");
Chemistry.registerElement(91, "Pa", "Protactinium", "red");
Chemistry.registerElement(92, "U", "Uranium", "red");
Chemistry.registerElement(93, "Np", "Neptunium", "red");
Chemistry.registerElement(94, "Pu", "Plutonium", "red");
Chemistry.registerElement(95, "Am", "Americium", "red");
Chemistry.registerElement(96, "Cm", "Curium", "red");
Chemistry.registerElement(97, "Bk", "Berkelium", "red");
Chemistry.registerElement(98, "Cf", "Californium", "red");
Chemistry.registerElement(99, "Es", "Einsteinium", "red");
Chemistry.registerElement(100, "Fm", "Fermium", "red");
Chemistry.registerElement(101, "Md", "Mendelevium", "red");
Chemistry.registerElement(102, "No", "Nobelium", "red");
Chemistry.registerElement(103, "Lr", "Lawrencium", "red");
Chemistry.registerElement(104, "Rf", "Rutherfordium", "blue");
Chemistry.registerElement(105, "Db", "Dubnium", "blue");
Chemistry.registerElement(106, "Sg", "Seaborgium", "blue");
Chemistry.registerElement(107, "Bh", "Bohrium", "blue");
Chemistry.registerElement(108, "Hs", "Hassium", "blue");
Chemistry.registerElement(109, "Mt", "Meitnerium", "blue");
Chemistry.registerElement(110, "Ds", "Darmstadtium", "blue");
Chemistry.registerElement(111, "Rg", "Roentgenium", "blue");
Chemistry.registerElement(112, "Cn", "Copernicium", "blue");
Chemistry.registerElement(113, "Nh", "Nihonium", "blue");

Recipes.addFurnaceFuel(Elem.C, 0, 200);
Recipes.addFurnaceFuel(Elem.H, 0, 100);
Recipes.addFurnaceFuel(Elem.S, 0, 300);
Recipes.addFurnaceFuel(Elem.P, 0, 250);