IDRegistry.genBlockID("survivalist_iron_ore_one");
IDRegistry.genBlockID("survivalist_iron_ore_two");
IDRegistry.genBlockID("survivalist_gold_ore_one");
IDRegistry.genBlockID("survivalist_gold_ore_two");
IDRegistry.genBlockID("copper_ore");
IDRegistry.genBlockID("lead_ore");
IDRegistry.genBlockID("tin_ore");
Block.createBlock("survivalist_iron_ore_one", [{name: "Iron Ore\n(1)", texture: [["survivalist_iron_ore", 1]], inCreative: true}], Block.createSpecialType({base: 15}));
Block.createBlock("survivalist_iron_ore_two", [{name: "Iron Ore\n(2)", texture: [["survivalist_iron_ore", 2]], inCreative: true}], Block.createSpecialType({base: 15}));
Block.createBlock("survivalist_gold_ore_one", [{name: "Gold Ore\n(1)", texture: [["survivalist_gold_ore", 1]], inCreative: true}], Block.createSpecialType({base: 14}));
Block.createBlock("survivalist_gold_ore_two", [{name: "Gold Ore\n(2)", texture: [["survivalist_gold_ore", 2]], inCreative: true}], Block.createSpecialType({base: 14}));
Block.createBlock("copper_ore", [{name: "Copper Ore", texture: [["ore_copper", 0]], inCreative: true}], Block.createSpecialType({base: 15}));
Block.createBlock("lead_ore", [{name: "Lead Ore", texture: [["ore_lead", 0]], inCreative: true}], Block.createSpecialType({base: 15}));
Block.createBlock("tin_ore", [{name: "Tin Ore", texture: [["ore_tin", 0]], inCreative: true}], Block.createSpecialType({base: 15}));
Block.setBlockMaterial(BlockID.survivalist_iron_ore_one, "stone", 2);
Block.setBlockMaterial(BlockID.survivalist_iron_ore_two, "stone", 2);
Block.setBlockMaterial(BlockID.survivalist_gold_ore_one, "stone", 3);
Block.setBlockMaterial(BlockID.survivalist_gold_ore_two, "stone", 3);
Block.setBlockMaterial(BlockID.copper_ore, "stone", 2);
Block.setBlockMaterial(BlockID.lead_ore, "stone", 3);
Block.setBlockMaterial(BlockID.tin_ore, "stone", 3);
Block.setDestroyLevel("survivalist_iron_ore_one", 2);
Block.setDestroyLevel("survivalist_iron_ore_two", 2);
Block.setDestroyLevel("survivalist_gold_ore_one", 3);
Block.setDestroyLevel("survivalist_gold_ore_two", 3);
Block.setDestroyLevel("copper_ore", 2);
Block.setDestroyLevel("lead_ore", 3);
Block.setDestroyLevel("tin_ore", 3);
Block.setDestroyTime(BlockID.survivalist_iron_ore_one, 30);
Block.setDestroyTime(BlockID.survivalist_iron_ore_two, 30);
Block.setDestroyTime(BlockID.survivalist_gold_ore_one, 30);
Block.setDestroyTime(BlockID.survivalist_gold_ore_two, 30);
Block.setDestroyTime(BlockID.copper_ore, 23);
Block.setDestroyTime(BlockID.lead_ore, 40);
Block.setDestroyTime(BlockID.tin_ore, 40);

