Item.addCreativeGroup("musicDisc", "Music Disc", [DiscLib.createMusicDisc("Secret - ???", "secret"), DiscLib.createMusicDisc("I'm A Master Of Minds - Dr.Stone", "track32"), DiscLib.createMusicDisc("Get Exited!! - Dr.Stone", "getexited"), DiscLib.createMusicDisc("Dr.Stone - Dr.Stone", "drstone")]);
Item.addCreativeGroup("rock", "Rock", [IDRegistry.genItemID("rock"), IDRegistry.genItemID("andesite_rock"), IDRegistry.genItemID("diorite_rock"), IDRegistry.genItemID("granite_rock"), IDRegistry.genItemID("netherrack_rock"), IDRegistry.genItemID("end_stone_rock"), IDRegistry.genItemID("halite_rock_salt")]);
Item.addCreativeGroup("oreRock", "Ore Rock", [IDRegistry.genItemID("iron_ore_rock"), IDRegistry.genItemID("gold_ore_rock"), IDRegistry.genItemID("copper_ore_rock"), IDRegistry.genItemID("lead_ore_rock"), IDRegistry.genItemID("tin_ore_rock"), IDRegistry.genItemID("silver_ore_rock"), IDRegistry.genItemID("aluminum_ore_rock")]);
Item.addCreativeGroup("flake", "Flake", [IDRegistry.genItemID("flaked_flint"), IDRegistry.genItemID("flaked_bone"), IDRegistry.genItemID("flaked_quartz"), IDRegistry.genItemID("flaked_obsidian"), IDRegistry.genItemID("flaked_opal"), IDRegistry.genItemID("flaked_emerald"), IDRegistry.genItemID("flaked_diamond")]);
Item.addCreativeGroup("point", "Point", [IDRegistry.genItemID("flaked_flint_point"), IDRegistry.genItemID("flaked_bone_point"), IDRegistry.genItemID("flaked_quartz_point"), IDRegistry.genItemID("flaked_obsidian_point"), IDRegistry.genItemID("flaked_opal_point"), IDRegistry.genItemID("flaked_emerald_point"), IDRegistry.genItemID("flaked_diamond_point")]);
Item.addCreativeGroup("nugget", "Nugget", [IDRegistry.genItemID("copper_nugget"), IDRegistry.genItemID("lead_nugget"), IDRegistry.genItemID("tin_nugget")]);
Item.addCreativeGroup("ingot", "Ingot", [IDRegistry.genItemID("copper_ingot"), IDRegistry.genItemID("lead_ingot"), IDRegistry.genItemID("tin_ingot")]);
Item.addCreativeGroup("bark", "Bark", [IDRegistry.genItemID("bark_oak"), IDRegistry.genItemID("bark_birch"), IDRegistry.genItemID("bark_spruce"), IDRegistry.genItemID("bark_jungle"), IDRegistry.genItemID("bark_acacia"), IDRegistry.genItemID("bark_dark_oak")]);
IDRegistry.genItemID("bread_dough");
IDRegistry.genItemID("round_bread");
IDRegistry.genItemID("plant_fiber");
IDRegistry.genItemID("plant_cordage");
Item.createItem("rock", "Rock", {name: "rock"}, {});
Item.createItem("andesite_rock", "Andesite Rock", {name: "rock_andesite"}, {});
Item.createItem("diorite_rock", "Diorite Rock", {name: "rock_diorite"}, {});
Item.createItem("granite_rock", "Granite Rock", {name: "rock_granite"}, {});
Item.createItem("netherrack_rock", "Netherrack Rock", {name: "rock_netherrack"}, {});
Item.createItem("end_stone_rock", "End Stone Rock", {name: "rock_end"}, {});
Item.createItem("halite_rock_salt", "Halite Rock Salt", {name: "salt_dust_rock"}, {});
Item.createItem("iron_ore_rock", "Iron Ore Rock", {name: "iron_ore_rock"}, {});
Item.createItem("gold_ore_rock", "Gold Ore Rock", {name: "gold_ore_rock"}, {});
Item.createItem("copper_ore_rock", "Copper Ore Rock", {name: "copper_ore_rock"}, {});
Item.createItem("tin_ore_rock", "Tin Ore Rock", {name: "tin_ore_rock"}, {});
Item.createItem("lead_ore_rock", "Lead Ore Rock", {name: "lead_ore_rock"}, {});
Item.createItem("silver_ore_rock", "Silver Ore Rock", {name: "silver_ore_rock"}, {});
Item.createItem("aluminum_ore_rock", "Aluminum Ore Rock", {name: "aluminum_ore_rock"}, {});
Item.createItem("flaked_flint", "Flaked Flint", {name: "flint_flake"}, {});
Item.createItem("flaked_bone", "Flaked Bone", {name: "bone_flake"}, {});
Item.createItem("flaked_quartz", "Flaked Quartz", {name: "quartz_flake"}, {});
Item.createItem("flaked_obsidian", "Flaked Obsidian", {name: "obsidian_flake"}, {});
Item.createItem("flaked_opal", "Flaked Opal", {name: "opal_flake"}, {});
Item.createItem("flaked_emerald", "Flaked Emerald", {name: "emerald_flake"}, {});
Item.createItem("flaked_diamond", "Flaked Diamond", {name: "diamond_flake"}, {});
Item.createItem("flaked_flint_point", "Flaked Flint Point", {name: "flint_point"}, {});
Item.createItem("flaked_bone_point", "Flaked Bone Point", {name: "bone_point"}, {});
Item.createItem("flaked_quartz_point", "Flaked Quartz Point", {name: "quartz_point"}, {});
Item.createItem("flaked_obsidian_point", "Flaked Obsidian Point", {name: "obsidian_point"}, {});
Item.createItem("flaked_opal_point", "Flaked Opal Point", {name: "opal_point"}, {});
Item.createItem("flaked_emerald_point", "Flaked Emerald Point", {name: "emerald_point"}, {});
Item.createItem("flaked_diamond_point", "Flaked Diamond Point", {name: "diamond_point"}, {});
Item.createItem("copper_nugget", "Copper Nugget", {name: "copper_nugget"}, {});
Item.createItem("lead_nugget", "Lead Nugget", {name: "lead_nugget"}, {});
Item.createItem("tin_nugget", "Tin Nugget", {name: "tin_nugget"}, {});
Item.createItem("copper_ingot", "Copper Ingot", {name: ""}, {});
Item.createItem("lead_ingot", "Lead Ingot", {name: ""}, {});
Item.createItem("tin_ingot", "Tin Ingot", {name: ""}, {});
Item.createItem("bark_oak", "Bark Oak", {name: "bark_oak"}, {});
Item.createItem("bark_birch", "Bark Birch", {name: "bark_birch"}, {});
Item.createItem("bark_spruce", "Bark Spruce", {name: "bark_spruce"}, {});
Item.createItem("bark_jungle", "Bark Jungle", {name: "bark_jungle"}, {});
Item.createItem("bark_acacia", "Bark Acacia", {name: "bark_acacia"}, {});
Item.createItem("bark_dark_oak", "Bark Dark Oak", {name: "bark_dark_oak"}, {});
Item.createItem("bread_dough", "Bread Dough", {name: "dough"}, {});
Item.createFoodItem("round_bread", "Round Bread", {name: "round_bread"}, {food: 8});
Item.createItem("plant_fiber", "Plant Fiber", {name: "plant_fiber"}, {});
Item.createItem("plant_cordage", "Plant Cordage", {name: "plant_cordage"}, {});

