Recipes.addFurnace(ItemID.copper_ore_rock, 0, ItemID.copper_nugget, 0);
Recipes.addFurnace(ItemID.lead_ore_rock, 0, ItemID.lead_nugget, 0);
Recipes.addFurnace(ItemID.tin_ore_rock, 0, ItemID.tin_nugget, 0);
Recipes.addFurnace(ItemID.bread_dough, 0, ItemID.round_bread, 0);
Recipes.addFurnace(ItemID.iron_ore_rock, 0, 452, 0);
Recipes.addFurnace(ItemID.gold_ore_rock, 0, 371, 0);
Recipes.addFurnaceFuel(ItemID.bark_oak, 0, 200);
Recipes.addFurnaceFuel(ItemID.bark_birch, 0, 200);
Recipes.addFurnaceFuel(ItemID.bark_spruce, 0, 200);
Recipes.addFurnaceFuel(ItemID.bark_jungle, 0, 200);
Recipes.addFurnaceFuel(ItemID.bark_acacia, 0, 200);
Recipes.addFurnaceFuel(ItemID.bark_dark_oak, 0, 200);
Recipes.addShapeless({id: ItemID.bread_dough, count: 1, data: 0}, [{id: 296, data: 0}, {id: 296, data: 0}, {id: 296, data: 0}, {id: 296, data: 0}]);
Recipes.addShapeless({id: 318, count: 1, data: 0}, [{id: 13, data: 0}, {id: 13, data: 0}, {id: 13, data: 0}, {id: 13, data: 0}]);
Recipes.addShapeless({id: ItemID.flaked_flint, count: 1, data: 0}, [{id: 318, data: 0}, {id: ItemID.rock, data: 0}]);
Recipes.addShapeless({id: ItemID.flaked_flint, count: 1, data: 0}, [{id: 318, data: 0}, {id: ItemID.andesite_rock, data: 0}]);
Recipes.addShapeless({id: ItemID.flaked_flint, count: 1, data: 0}, [{id: 318, data: 0}, {id: ItemID.diorite_rock, data: 0}]);
Recipes.addShapeless({id: ItemID.flaked_flint, count: 1, data: 0}, [{id: 318, data: 0}, {id: ItemID.granite_rock, data: 0}]);
Recipes.addShapeless({id: ItemID.flaked_flint, count: 1, data: 0}, [{id: 318, data: 0}, {id: ItemID.netherrack_rock, data: 0}]);
Recipes.addShapeless({id: ItemID.flaked_flint, count: 1, data: 0}, [{id: 318, data: 0}, {id: ItemID.end_stone_rock, data: 0}]);
Recipes.addShapeless({id: ItemID.plant_cordage, count: 1, data: 0}, [{id: ItemID.plant_fiber, data: 0}, {id: ItemID.plant_fiber, data: 0}, {id: ItemID.plant_fiber, data: 0}]);
Recipes.addShapeless({id: ItemID.flint_hatchet, count: 1, data: 0}, [{id: ItemID.plant_cordage, data: 0}, {id: ItemID.flaked_flint, data: 0}, {id: 280, data: 0}]);
Recipes.addShapeless({id: ItemID.flint_hoe, count: 1, data: 0}, [{id: ItemID.flaked_flint, data: 0}, {id: ItemID.plant_cordage, data: 0}, {id: 280, data: 0}]);
Recipes.addShapeless({id: ItemID.sharp_bone, count: 1, data: 0}, [{id: 352, data: 0}, {id: ItemID.flaked_flint, data: 0}]);
Recipes.addShaped({id: ItemID.flint_shears, count: 1, data: 0}, [" f ", "fp ", "   "], ["f", ItemID.flaked_flint_point, 0, "p", ItemID.plant_cordage, 0]);
Recipes.addShaped({id: ItemID.flint_shears, count: 1, data: 0}, [" f ", "fp ", "   "], ["f", ItemID.flaked_bone_point, 0, "p", ItemID.plant_cordage, 0]);
Recipes.addShaped({id: ItemID.flint_shears, count: 1, data: 0}, [" f ", "fp ", "   "], ["f", ItemID.flaked_quartz_point, 0, "p", ItemID.plant_cordage, 0]);
Recipes.addShaped({id: 4, count: 1, data: 0}, ["rrr", "rcr", "rrr"], ["r", ItemID.rock, 0, "c", 337, 0]);
Recipes.addShaped({id: 1, count: 1, data: 1}, ["rrr", "rcr", "rrr"], ["r", ItemID.granite_rock, 0, "c", 337, 0]);
Recipes.addShaped({id: 1, count: 1, data: 3}, ["rrr", "rcr", "rrr"], ["r", ItemID.diorite_rock, 0, "c", 337, 0]);
Recipes.addShaped({id: 1, count: 1, data: 5}, ["rrr", "rcr", "rrr"], ["r", ItemID.andesite_rock, 0, "c", 337, 0]);
Recipes.addShaped({id: 87, count: 1, data: 0}, ["rrr", "rcr", "rrr"], ["r", ItemID.netherrack_rock, 0, "c", 337, 0]);
Recipes.addShaped({id: 121, count: 1, data: 0}, ["rrr", "rcr", "rrr"], ["r", ItemID.end_stone_rock, 0, "c", 337, 0]);
Recipes.addShaped({id: ItemID.flint_pickaxe, count: 1, data: 0}, ["fpf", "fsf", " s "], ["f", ItemID.flaked_flint, 0, "p", ItemID.plant_cordage, 0, "s", 280, 0]);
Recipes.addShaped({id: ItemID.flint_shovel, count: 1, data: 0}, [" f ", " p ", " s "], ["f", 318, 0, "p", ItemID.plant_cordage, 0, "s", 280, 0]);
Recipes.addShaped({id: ItemID.flint_axe, count: 1, data: 0}, ["fpf", "fs ", " s"], ["f", ItemID.flaked_flint, 0, "p", ItemID.plant_cordage, 0, "s", 280, 0]);

