Item.addCreativeGroup("flintTools", "Flint Tools", [IDRegistry.genItemID("flint_hatchet"), IDRegistry.genItemID("flint_pickaxe"), IDRegistry.genItemID("flint_axe"), IDRegistry.genItemID("flint_shovel"), IDRegistry.genItemID("flint_hoe"), IDRegistry.genItemID("flint_shears")]);
Item.addCreativeGroup("boneTools", "Bone Tools", [IDRegistry.genItemID("sharp_bone"), IDRegistry.genItemID("bone_hatchet"), IDRegistry.genItemID("bone_pickaxe"), IDRegistry.genItemID("bone_shovel"), IDRegistry.genItemID("bone_hoe"), IDRegistry.genItemID("bone_shears")]);
Item.addCreativeGroup("quartzTools", "Quartz Tools", [IDRegistry.genItemID("quartz_hatchet"), IDRegistry.genItemID("quartz_pickaxe"), IDRegistry.genItemID("quartz_axe"), IDRegistry.genItemID("quartz_shovel"), IDRegistry.genItemID("quartz_hoe"), IDRegistry.genItemID("quartz_shears")]);
Item.addCreativeGroup("obsidianTools", "Obsidian Tools", [IDRegistry.genItemID("obsidian_hatchet"), IDRegistry.genItemID("obsidian_pickaxe"), IDRegistry.genItemID("obsidian_axe"), IDRegistry.genItemID("obsidian_shovel"), IDRegistry.genItemID("obsidian_hoe")]);
Item.addCreativeGroup("opalTools", "Opal Tools", [IDRegistry.genItemID("opal_hatchet"), IDRegistry.genItemID("opal_pickaxe"), IDRegistry.genItemID("opal_axe"), IDRegistry.genItemID("opal_shovel"), IDRegistry.genItemID("opal_hoe")]);
Item.addCreativeGroup("emeraldTools", "Emerald Tools", [IDRegistry.genItemID("emerald_hatchet"), IDRegistry.genItemID("emerald_pickaxe"), IDRegistry.genItemID("emerald_axe"), IDRegistry.genItemID("emerald_shovel"), IDRegistry.genItemID("emerald_hoe")]);
Item.addCreativeGroup("diamondTools", "Diamond Tools", [IDRegistry.genItemID("diamond_hatchet"), IDRegistry.genItemID("diamond_pickaxe"), IDRegistry.genItemID("diamond_axe"), IDRegistry.genItemID("diamond_shovel"), IDRegistry.genItemID("diamond_hoe")]);
Item.createItem("flint_hatchet", "Flint Hatchet", {name: "flint_hatchet"}, {stack: 1});
Item.createItem("flint_pickaxe", "Flint Pickaxe", {name: "flint_pickaxe"}, {stack: 1});
Item.createItem("flint_axe", "Flint Axe", {name: "flint_axe"}, {stack: 1});
Item.createItem("flint_shovel", "Flint Shovel", {name: "flint_shovel"}, {stack: 1});
Item.createItem("flint_hoe", "Flint Hoe", {name: "flint_hoe"}, {stack: 1});
Item.createItem("flint_shears", "Flint Shears", {name: "flint_shears"}, {stack: 1});
Item.createItem("sharp_bone", "Sharp Bone", {name: "sharp_bone"}, {stack: 1});
Item.createItem("bone_hatchet", "Bone Hatchet", {name: "bone_hatchet"}, {stack: 1});
Item.createItem("bone_pickaxe", "Bone Pickaxe", {name: "bone_pickaxe"}, {stack: 1});
Item.createItem("bone_shovel", "Bone Shovel", {name: "bone_shovel"}, {stack: 1});
Item.createItem("bone_hoe", "Bone Hoe", {name: "bone_hoe"}, {stack: 1});
Item.createItem("bone_shears", "Bone Shears", {name: "bone_shears"}, {stack: 1});
Item.createItem("quartz_hatchet", "Quartz Hatchet", {name: "quartz_hatchet"}, {stack: 1});
Item.createItem("quartz_pickaxe", "Quartz Pickaxe", {name: "quartz_pickaxe"}, {stack: 1});
Item.createItem("quartz_axe", "Quartz Axe", {name: "quartz_axe"}, {stack: 1});
Item.createItem("quartz_shovel", "Quartz Shovel", {name: "quartz_shovel"}, {stack: 1});
Item.createItem("quartz_hoe", "Quartz Hoe", {name: "quartz_hoe"}, {stack: 1});
Item.createItem("quartz_shears", "Quartz Shears", {name: "quartz_shears"}, {stack: 1});
Item.createItem("obsidian_hatchet", "Obsidian Hatchet", {name: "obsidian_hatchet"}, {stack: 1});
Item.createItem("obsidian_pickaxe", "Obsidian Pickaxe", {name: "obsidian_pickaxe"}, {stack: 1});
Item.createItem("obsidian_axe", "Obsidian Axe", {name: "obsidian_axe"}, {stack: 1});
Item.createItem("obsidian_shovel", "Obsidian Shovel", {name: "obsidian_shovel"}, {stack: 1});
Item.createItem("obsidian_hoe", "Obsidian Hoe", {name: "obsidian_hoe"}, {stack: 1});
Item.createItem("opal_hatchet", "Opal Hatchet", {name: "opal_hatchet"}, {stack: 1});
Item.createItem("opal_pickaxe", "Opal Pickaxe", {name: "opal_pickaxe"}, {stack: 1});
Item.createItem("opal_axe", "Opal Axe", {name: "opal_axe"}, {stack: 1});
Item.createItem("opal_shovel", "Opal Shovel", {name: "opal_shovel"}, {stack: 1});
Item.createItem("opal_hoe", "Opal Hoe", {name: "opal_hoe"}, {stack: 1});
Item.createItem("emerald_hatchet", "Emerald Hatchet", {name: "emerald_hatchet"}, {stack: 1});
Item.createItem("emerald_pickaxe", "Emerald Pickaxe", {name: "emerald_pickaxe"}, {stack: 1});
Item.createItem("emerald_axe", "Emerald Axe", {name: "emerald_axe"}, {stack: 1});
Item.createItem("emerald_shovel", "Emerald Shovel", {name: "emerald_shovel"}, {stack: 1});
Item.createItem("emerald_hoe", "Emerald Hoe", {name: "emerald_hoe"}, {stack: 1});
Item.createItem("diamond_hatchet", "Diamond Hatchet", {name: "diamond_hatchet"}, {stack: 1});
Item.createItem("diamond_pickaxe", "Diamond Pickaxe", {name: "diamond_pickaxe"}, {stack: 1});
Item.createItem("diamond_axe", "Diamond Axe", {name: "diamond_axe"}, {stack: 1});
Item.createItem("diamond_shovel", "Diamond Shovel", {name: "diamond_shovel"}, {stack: 1});
Item.createItem("diamond_hoe", "Diamond Hoe", {name: "diamond_hoe"}, {stack: 1});
ToolType.shears = {damage: 0};
ToolAPI.addToolMaterial("obsidian", {durability: 2032, level: 4, efficiency: 32, damage: 14, enchantability: 30});
ToolAPI.addToolMaterial("quartz", {durability: 256, level: 4, efficiency: 16, damage: 4, enchantability: 30});
ToolAPI.addToolMaterial("opal", {durability: 1561, level: 4, efficiency: 16, damage: 8, enchantability: 30});
ToolAPI.addToolMaterial("emerald", {durability: 512, level: 4, efficiency: 16, damage: 7, enchantability: 30});
ToolAPI.setTool(ItemID.flint_hatchet, "stone", ToolType.axe);
ToolAPI.setTool(ItemID.flint_pickaxe, "stone", ToolType.pickaxe);
ToolAPI.setTool(ItemID.flint_axe, "stone", ToolType.axe);
ToolAPI.setTool(ItemID.flint_shovel, "stone", ToolType.shovel);
ToolAPI.setTool(ItemID.flint_hoe, "stone", ToolType.hoe);
ToolAPI.setTool(ItemID.flint_shears, "stone", ToolType.shears);
ToolAPI.setTool(ItemID.sharp_bone, "stone", ToolType.sword);
ToolAPI.setTool(ItemID.bone_hatchet, "stone", ToolType.axe);
ToolAPI.setTool(ItemID.bone_pickaxe, "stone", ToolType.pickaxe);
ToolAPI.setTool(ItemID.bone_shovel, "stone", ToolType.shovel);
ToolAPI.setTool(ItemID.bone_hoe, "stone", ToolType.hoe);
ToolAPI.setTool(ItemID.bone_shears, "stone", ToolType.shears);
ToolAPI.setTool(ItemID.quartz_hatchet, "quartz", ToolType.axe);
ToolAPI.setTool(ItemID.quartz_pickaxe, "quartz", ToolType.pickaxe);
ToolAPI.setTool(ItemID.quartz_axe, "quartz", ToolType.axe);
ToolAPI.setTool(ItemID.quartz_shovel, "quartz", ToolType.shovel);
ToolAPI.setTool(ItemID.quartz_hoe, "quartz", ToolType.hoe);
ToolAPI.setTool(ItemID.quartz_shears, "quartz", ToolType.shears);
ToolAPI.setTool(ItemID.obsidian_hatchet, "obsidian", ToolType.axe);
ToolAPI.setTool(ItemID.obsidian_pickaxe, "obsidian", ToolType.pickaxe);
ToolAPI.setTool(ItemID.obsidian_axe, "obsidian", ToolType.axe);
ToolAPI.setTool(ItemID.obsidian_shovel, "obsidian", ToolType.shovel);
ToolAPI.setTool(ItemID.obsidian_hoe, "obsidian", ToolType.hoe);
ToolAPI.setTool(ItemID.opal_hatchet, "opal", ToolType.axe);
ToolAPI.setTool(ItemID.opal_pickaxe, "opal", ToolType.pickaxe);
ToolAPI.setTool(ItemID.opal_axe, "opal", ToolType.axe);
ToolAPI.setTool(ItemID.opal_shovel, "opal", ToolType.shovel);
ToolAPI.setTool(ItemID.opal_hoe, "opal", ToolType.hoe);
ToolAPI.setTool(ItemID.emerald_hatchet, "emerald", ToolType.axe);
ToolAPI.setTool(ItemID.emerald_pickaxe, "emerald", ToolType.pickaxe);
ToolAPI.setTool(ItemID.emerald_axe, "emerald", ToolType.axe);
ToolAPI.setTool(ItemID.emerald_shovel, "emerald", ToolType.shovel);
ToolAPI.setTool(ItemID.emerald_hoe, "emerald", ToolType.hoe);
ToolAPI.setTool(ItemID.diamond_hatchet, "diamond", ToolType.axe);
ToolAPI.setTool(ItemID.diamond_pickaxe, "diamond", ToolType.pickaxe);
ToolAPI.setTool(ItemID.diamond_axe, "diamond", ToolType.axe);
ToolAPI.setTool(ItemID.diamond_shovel, "diamond", ToolType.shovel);
ToolAPI.setTool(ItemID.diamond_hoe, "diamond", ToolType.hoe);

