let ModBlocks = (function (ModBlocks) {
    let livingrock = ModBlocks.livingrock = new BlockMod("livingrock", "stone");
    let livingwood = ModBlocks.livingwood = new BlockMod("livingwood", "wood");
    let livingwoodGlimmering = ModBlocks.livingwoodGlimmering = new BlockMod("livingwoodGlimmering", "wood");
    let petalBlock = ModBlocks.petalBlock = new BlockPetalBlock("petalBlock");
    let enchantedSoil = ModBlocks.enchantedSoil = new BlockEnchantedSoil("enchantedSoil", "dirt");
    let mysticalFlower = ModBlocks.mysticalFlower = new BlockColoredFlower("mysticalFlower");
    let mushroom = ModBlocks.mushroom = new BlockModMushroom("mushroom");
    let doubleFlower = ModBlocks.doubleFlower = new BlockDoubleFlower("doubleFlower");
    let buriedPetals = ModBlocks.buriedPetals = new BlockBuriedPetals("buriedPetals");
    let pureDaisy = ModBlocks.pureDaisy = new BlockSpecialFlower("pureDaisy", new SubTilePureDaisy());
    let manastar = ModBlocks.manastar = new BlockSpecialFlower("manastar", new SubTileManastar());
    let agricarnation = ModBlocks.agricarnation = new BlockSpecialFlower("agricarnation", new SubTileAgricarnation());
    let agricarnationChibi = ModBlocks.agricarnationChibi = new BlockSpecialFlower("agricarnationChibi", new SubTileAgricarnationChibi());
    let bellethorn = ModBlocks.bellethorn = new BlockSpecialFlower("bellethorn", new SubTileBellethorn());
    let bellethornChibi = ModBlocks.bellethornChibi = new BlockSpecialFlower("bellethornChibi", new SubTileBellethornChibi());
    let bubbell = ModBlocks.bubbell = new BlockSpecialFlower("bubbell", new SubTileBubbell());
    let bubbellChibi = ModBlocks.bubbellChibi = new BlockSpecialFlower("bubbellChibi", new SubTileBubbellChibi());
    let clayconia = ModBlocks.clayconia = new BlockSpecialFlower("clayconia", new SubTileClayconia());
    let clayconiaChibi = ModBlocks.clayconiaChibi = new BlockSpecialFlower("clayconiaChibi", new SubTileClayconiaChibi());
    let dreadthorn = ModBlocks.dreadthorn = new BlockSpecialFlower("dreadthorn", new SubTileDreadthorn());
    let fallenKanade = ModBlocks.fallenKanade = new BlockSpecialFlower("fallenKanade", new SubTileFallenKanade());
    let heiseiDream = ModBlocks.heiseiDream = new BlockSpecialFlower("heiseiDream", new SubTileHeiseiDream());
    let hyacidus = ModBlocks.hyacidus = new BlockSpecialFlower("hyacidus", new SubTileHyacidus());
    let jadedAmaranthus = ModBlocks.jadedAmaranthus = new BlockSpecialFlower("jadedAmaranthus", new SubTileJadedAmaranthus());
    let jiyuulia = ModBlocks.jiyuulia = new BlockSpecialFlower("jiyuulia", new SubTileJiyuulia());
    let medumone = ModBlocks.medumone = new BlockSpecialFlower("medumone", new SubTileMedumone());
    let orechid = ModBlocks.orechid = new BlockSpecialFlower("orechid", new SubTileOrechid());
    let orechidIgnem = ModBlocks.orechidIgnem = new BlockSpecialFlower("orechidIgnem", new SubTileOrechidIgnem());
    let tangleberrie = ModBlocks.tangleberrie = new BlockSpecialFlower("tangleberrie", new SubTileTangleberrie());
    let arcaneRose = ModBlocks.arcaneRose = new BlockSpecialFlower("arcaneRose", new SubTileArcaneRose());
    let endoflame = ModBlocks.endoflame = new BlockSpecialFlower("endoflame", new SubTileEndoflame());
    let entropinnyum = ModBlocks.entropinnyum = new BlockSpecialFlower("entropinnyum", new SubTileEntropinnyum());
    let gourmaryllis = ModBlocks.gourmaryllis = new BlockSpecialFlower("gourmaryllis", new SubTileGourmaryllis());
    let hydroangeas = ModBlocks.hydroangeas = new BlockSpecialFlower("hydroangeas", new SubTileHydroangeas());
    let kekimurus = ModBlocks.kekimurus = new BlockSpecialFlower("kekimurus", new SubTileKekimurus());
    let munchdew = ModBlocks.munchdew = new BlockSpecialFlower("munchdew", new SubTileMunchdew());
    let narslimmus = ModBlocks.narslimmus = new BlockSpecialFlower("narslimmus", new SubTileNarslimmus());
    let rafflowsia = ModBlocks.rafflowsia = new BlockSpecialFlower("rafflowsia", new SubTileRafflowsia());
    let shulkMeNot = ModBlocks.shulkMeNot = new BlockSpecialFlower("shulkMeNot", new SubTileShulkMeNot());
    let spectrolus = ModBlocks.spectrolus = new BlockSpecialFlower("spectrolus", new SubTileSpectrolus());
    let thermalily = ModBlocks.thermalily = new BlockSpecialFlower("thermalily", new SubTileThermalily());
    let manaPool = ModBlocks.manaPool = new BlockPool("manaPool", new TilePool(1000000));
    let dilutedPool = ModBlocks.dilutedPool = new BlockPool("dilutedPool", new TilePool(10000));
    let creativePool = ModBlocks.creativePool = new BlockPool("creativePool", new TilePool(-1));
    let alfPortal = ModBlocks.alfPortal = new BlockAlfPortal("alfPortal", new TileAlfPortal());
    let apothecaryDefault = ModBlocks.apothecaryDefault = new BlockAltar("apothecaryDefault", new TileAltar());
    let runicAltar = ModBlocks.runicAltar = new BlockRuneAltar("runicAltar", new TileRuneAltar());
    let spreaderMana = ModBlocks.spreaderMana = new BlockSpreader("spreaderMana", new TileSpreader(160, 1000, 2162464, 65280, 60, 4, 1, false));
    let terraPlate = ModBlocks.terraPlate = new BlockTerraPlate("terraPlate", new TileTerraPlate());
    let manaPylon = ModBlocks.manaPylon = new BlockPylon("manaPylon", BlockPylon.Variant.MANA, new TilePylon());
    let naturaPylon = ModBlocks.naturaPylon = new BlockPylon("naturaPylon", BlockPylon.Variant.NATURA, new TilePylon());
    let gaiaPylon = ModBlocks.gaiaPylon = new BlockPylon("gaiaPylon", BlockPylon.Variant.GAIA, new TilePylon());
    function registerBlocks() {
        register(livingrock);
        register(livingwood);
        register(livingwoodGlimmering);
        register(petalBlock);
        register(enchantedSoil);
        register(mysticalFlower);
        register(mushroom);
        register(doubleFlower);
        register(buriedPetals);
        register(pureDaisy);
        register(manastar);
        register(agricarnation);
        register(agricarnationChibi);
        register(bellethorn);
        register(bellethornChibi);
        register(bubbell);
        register(bubbellChibi);
        register(clayconia);
        register(clayconiaChibi);
        register(dreadthorn);
        register(fallenKanade);
        register(heiseiDream);
        register(hyacidus);
        register(jadedAmaranthus);
        register(jiyuulia);
        register(medumone);
        register(orechid);
        register(orechidIgnem);
        register(tangleberrie);
        register(arcaneRose);
        register(endoflame);
        register(entropinnyum);
        register(gourmaryllis);
        register(hydroangeas);
        register(kekimurus);
        register(munchdew);
        register(narslimmus);
        register(rafflowsia);
        register(shulkMeNot);
        register(spectrolus);
        register(thermalily);
        register(manaPool);
        register(dilutedPool);
        register(creativePool);
        register(alfPortal);
        register(apothecaryDefault);
        register(runicAltar);
        register(spreaderMana);
        register(terraPlate);
        register(manaPylon);
        register(naturaPylon);
        register(gaiaPylon);
    }
    ModBlocks.registerBlocks = registerBlocks;
    function register(block) {
        if (block.register) {
            block.register();
        } else {
            BlockRegistry.registerBlock(block);
        }
    }
    ModBlocks.register = register;
    return ModBlocks;
}(ModBlocks || (ModBlocks = {})));

