let ModelArmorManasteel = (function (_super) {
    __extends(ModelArmorManasteel, _super);
    function ModelArmorManasteel(templateName) {
        _super.call(this, templateName);
        this.textureWidth = 64;
        this.textureHeight = 128;
        let s = 0.01;
        this.helmAnchor = new ModelRenderer(this, 0, 0);
        this.helmAnchor.setRotationPoint(0, 0, 0);
        this.helmAnchor.addBox(-1, -2, 0, 2, 2, 2);
        this.helmAnchor.end();
        this.helm = new ModelRenderer(this, 0, 0);
        this.helm.setRotationPoint(0, 0, 0);
        this.helm.addBox(-4.5, -8.5, -4.5, 9, 9, 9);
        this.helmTop = new ModelRenderer(this, 36, 6);
        this.helmTop.setRotationPoint(0, -8.5, 3.5);
        this.helmTop.addBox(-1.5, 0, -7, 3, 3, 7);
        this.helmTop.setRotation(-0.2617993877991494, 0, 0);
        this.helmCrystal = new ModelRenderer(this, 36, 0);
        this.helmCrystal.setRotationPoint(0, -7.5, -4.5);
        this.helmCrystal.addBox(-1.5, -4, -1, 3, 5, 1);
        this.helmCrystal.setRotation(0.08726646259971647, 0, 0);
        this.bodyAnchor = new ModelRenderer(this, 0, 0);
        this.bodyAnchor.setRotationPoint(0, 0, 0);
        this.bodyAnchor.addBox(-1, 0, -1, 2, 2, 2);
        this.bodyTop = new ModelRenderer(this, 0, 18);
        this.bodyTop.setRotationPoint(0, 0, 0);
        this.bodyTop.addBox(-4.5, -0.5, -3, 9, 6, 6);
        this.bodyTop.setRotation(0, 0, 0);
        this.bodyBottom = new ModelRenderer(this, 0, 30);
        this.bodyBottom.setRotationPoint(0, 0, 0);
        this.bodyBottom.addBox(-2.5, 5.5, -2.5, 5, 3, 5);
        this.armLAnchor = new ModelRenderer(this, 0, 0);
        this.armLAnchor.setMirrored(true);
        this.armLAnchor.setRotationPoint(4, 2, 0);
        this.armLAnchor.addBox(0, -1, -1, 2, 2, 2);
        this.armL = new ModelRenderer(this, 22, 40);
        this.armL.setMirrored(true);
        this.armL.setRotationPoint(0, 0, 0);
        this.armL.addBox(1.5, 2, -2.49, 2, 6, 5);
        this.armLpauldron = new ModelRenderer(this, 0, 40);
        this.armLpauldron.setMirrored(true);
        this.armLpauldron.setRotationPoint(0, 0, 0);
        this.armLpauldron.addBox(-0.5, -3, -3, 5, 4, 6);
        this.armLcrystal = new ModelRenderer(this, 36, 40);
        this.armLcrystal.setMirrored(true);
        this.armLcrystal.setRotationPoint(2, -2.5, 0);
        this.armLcrystal.addBox(-0.5, -2.5, -1.5, 2, 3, 3);
        this.armLcrystal.setRotation(0, 0, -0.08726646259971647);
        this.armRAnchor = new ModelRenderer(this, 0, 0);
        this.armRAnchor.setMirrored(true);
        this.armRAnchor.setRotationPoint(-4, 2, 0);
        this.armRAnchor.addBox(-2, -1, -1, 2, 2, 2);
        this.armR = new ModelRenderer(this, 22, 40);
        this.armR.setRotationPoint(0, 0, 0);
        this.armR.addBox(-3.5, 2, -2.51, 2, 6, 5);
        this.armRpauldron = new ModelRenderer(this, 0, 40);
        this.armRpauldron.setRotationPoint(0, 0, 0);
        this.armRpauldron.addBox(-4.5, -3, -3, 5, 4, 6);
        this.armRcrystal = new ModelRenderer(this, 36, 40);
        this.armRcrystal.setRotationPoint(-2, -2.5, 0);
        this.armRcrystal.addBox(-1.5, -2.5, -1.5, 2, 3, 3);
        this.armRcrystal.setRotation(0, 0, 0.08726646259971647);
        this.pantsAnchor = new ModelRenderer(this, 0, 0);
        this.pantsAnchor.setRotationPoint(0, 0, 0);
        this.pantsAnchor.addBox(-1, 0, -1, 2, 2, 2);
        this.belt = new ModelRenderer(this, 0, 51);
        this.belt.setRotationPoint(0, 0, 0);
        this.belt.addBox(-4.5, 9, -3, 9, 3, 6);
        this.legL = new ModelRenderer(this, 0, 60);
        this.legL.setMirrored(true);
        this.legL.setRotationPoint(1.9, 12, 0);
        this.legL.addBox(-0.39, 0, -2.49, 3, 6, 5);
        this.legR = new ModelRenderer(this, 0, 60);
        this.legR.setRotationPoint(-1.9, 12, 0);
        this.legR.addBox(-2.61, 0, -2.51, 3, 6, 5);
        this.bootL = new ModelRenderer(this, 0, 71);
        this.bootL.setMirrored(true);
        this.bootL.setRotationPoint(1.9, 12, 0);
        this.bootL.addBox(-2.39, 8.5, -2.49, 5, 4, 5);
        this.bootLcrystal = new ModelRenderer(this, 36, 46);
        this.bootLcrystal.setMirrored(true);
        this.bootLcrystal.setRotationPoint(2.5, 9, 2);
        this.bootLcrystal.addBox(-1, -2, -1.5, 2, 3, 3);
        this.bootLcrystal.setRotation(0, 0, 0.08726646259971647);
        this.bootR = new ModelRenderer(this, 0, 71);
        this.bootR.setRotationPoint(-2, 12, 0);
        this.bootR.addBox(-2.5, 8.5, -2.51, 5, 4, 5);
        this.bootRcrystal = new ModelRenderer(this, 36, 46);
        this.bootRcrystal.setRotationPoint(-2.5, 9, 2);
        this.bootRcrystal.addBox(-1, -2, -1.5, 2, 3, 3);
        this.bootRcrystal.setRotation(0, 0, -0.08726646259971647);
        this._head.addChild(this.helmAnchor);
        this.helmAnchor.addChild(this.helm);
        this.helm.addChild(this.helmTop);
        this.helm.addChild(this.helmCrystal);
        this._body.addChild(this.bodyAnchor);
        this.bodyAnchor.addChild(this.bodyTop);
        this.bodyTop.addChild(this.bodyBottom);
        this._leftArm.addChild(this.armLAnchor);
        this.armLAnchor.addChild(this.armL);
        this.armL.addChild(this.armLpauldron);
        this.armLpauldron.addChild(this.armLcrystal);
        this._rightArm.addChild(this.armRAnchor);
        this.armRAnchor.addChild(this.armR);
        this.armR.addChild(this.armRpauldron);
        this.armRpauldron.addChild(this.armRcrystal);
        this._body.addChild(this.pantsAnchor);
        this.pantsAnchor.addChild(this.belt);
        this._leftLeg.addChild(this.legL);
        this._rightLeg.addChild(this.legR);
        this._leftLeg.addChild(this.bootL);
        this.bootL.addChild(this.bootLcrystal);
        this._rightLeg.addChild(this.bootR);
        this.bootR.addChild(this.bootRcrystal);
        this.end();
        return this;
    }
    return ModelArmorManasteel;
}(ModelBiped));

