importLib("BackpackAPI", "*");
IDRegistry.genItemID("bitcoinBackpack");
Item.createItem("bitcoinBackpack", "Bitcoin Backpack", {name: "bitcoin_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.bitcoinBackpack, {slots: 68, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("wondercoinBackpack");
Item.createItem("wondercoinBackpack", "Wondercoin Backpack", {name: "wondercoin_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.wondercoinBackpack, {slots: 46, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("ethereumBackpack");
Item.createItem("ethereumBackpack", "Etherum Backpack", {name: "ethereum_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.ethereumBackpack, {slots: 56, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("arkcoinBackpack");
Item.createItem("arkcoinBackpack", "Arkcoin Backpack", {name: "arkcoin_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.arkcoinBackpack, {slots: 50, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("cosmocashBackpack");
Item.createItem("cosmocashBackpack", "Cosmocash Backpack", {name: "cosmocash_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.cosmocashBackpack, {slots: 42, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("augurBackpack");
Item.createItem("augurBackpack", "Augur Backpack", {name: "augur_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.augurBackpack, {slots: 40, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("liskBackpack");
Item.createItem("liskBackpack", "Lisk Backpack", {name: "lisk_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.liskBackpack, {slots: 38, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("firecoinBackpack");
Item.createItem("firecoinBackpack", "Firecoin Backpack", {name: "firecoin_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.firecoinBackpack, {slots: 34, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("zerocashBackpack");
Item.createItem("zerocashBackpack", "Zerocash Backpack", {name: "zerocash_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.zerocashBackpack, {slots: 30, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("dashcoinBackpack");
Item.createItem("dashcoinBackpack", "dashcoin Backpack", {name: "dashcoin_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.dashcoinBackpack, {slots: 28, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("moneroBackpack");
Item.createItem("moneroBackpack", "Monero Backpack", {name: "monero_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.moneroBackpack, {slots: 26, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("rippleBackpack");
Item.createItem("rippleBackpack", "Ripple Backpack", {name: "ripple_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.rippleBackpack, {slots: 22, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("windcoinBackpack");
Item.createItem("windcoinBackpack", "Windcoin Backpack", {name: "windcoin_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.windcoinBackpack, {slots: 14, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("litecoinBackpack");
Item.createItem("litecoinBackpack", "Litecoin Backpack", {name: "litecoin_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.litecoinBackpack, {slots: 8, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("dogecoinBackpack");
Item.createItem("dogecoinBackpack", "Dogecoin Backpack", {name: "dogecoin_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.dogecoinBackpack, {slots: 6, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("peercoinBackpack");
Item.createItem("peercoinBackpack", "Peercoin Backpack", {name: "peercoin_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.peercoinBackpack, {slots: 2, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("concoinBackpack");
Item.createItem("concoinBackpack", "Concoin Backpack", {name: "concoin_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.concoinBackpack, {slots: 52, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("buzcoinBackpack");
Item.createItem("buzcoinBackpack", "Buzcoin Backpack", {name: "buzcoin_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.buzcoinBackpack, {slots: 4, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("mooncoinBackpack");
Item.createItem("mooncoinBackpack", "Mooncoin Backpack", {name: "mooncoin_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.mooncoinBackpack, {slots: 84, slotsCenter: true, inRow: 9});
IDRegistry.genItemID("marscoinBackpack");
Item.createItem("marscoinBackpack", "Marscoin Backpack", {name: "marscoin_backpack", meta: 0}, {stack: 1});
BackpackRegistry.register(ItemID.marscoinBackpack, {slots: 108, slotsCenter: true, inRow: 9});

