IDRegistry.genItemID("bitcoinPickaxePart");
Item.createItem("bitcoinPickaxePart", "Bitcoin Pickaxe Part", {name: "bitcoin_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.bitcoinPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.bitcoin,0]);
IDRegistry.genItemID("wondercoinPickaxePart");
Item.createItem("wondercoinPickaxePart", "Wondercoin Pickaxe Part", {name: "wondercoin_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.wondercoinPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.wondercoin,0]);
IDRegistry.genItemID("ethereumPickaxePart");
Item.createItem("ethereumPickaxePart", "Ethereum Pickaxe Part", {name: "ethereum_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.ethereumPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.ethereum,0]);
IDRegistry.genItemID("arkcoinPickaxePart");
Item.createItem("arkcoinPickaxePart", "Arkcoin Pickaxe Part", {name: "arkcoin_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.arkcoinPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.arkcoin,0]);
IDRegistry.genItemID("cosmocashPickaxePart");
Item.createItem("cosmocashPickaxePart", "Cosmocash Pickaxe Part", {name: "cosmocash_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.cosmocashPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.cosmocash,0]);
IDRegistry.genItemID("augurPickaxePart");
Item.createItem("augurPickaxePart", "Augur Pickaxe Part", {name: "augur_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.augurPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.augur,0]);
IDRegistry.genItemID("liskPickaxePart");
Item.createItem("liskPickaxePart", "Lisk Pickaxe Part", {name: "lisk_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.liskPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.lisk,0]);
IDRegistry.genItemID("firecoinPickaxePart");
Item.createItem("firecoinPickaxePart", "Firecoin Pickaxe Part", {name: "firecoin_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.firecoinPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.firecoin,0]);
IDRegistry.genItemID("zerocashPickaxePart");
Item.createItem("zerocashPickaxePart", "Zerocash Pickaxe Part", {name: "zerocash_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.zerocashPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.zerocash,0]);
IDRegistry.genItemID("dashcoinPickaxePart");
Item.createItem("dashcoinPickaxePart", "Dashcoin Pickaxe Part", {name: "dashcoin_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.dashcoinPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.dashcoin,0]);
IDRegistry.genItemID("moneroPickaxePart");
Item.createItem("moneroPickaxePart", "Monero Pickaxe Part", {name: "monero_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.moneroPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.monero,0]);
IDRegistry.genItemID("ripplePickaxePart");
Item.createItem("ripplePickaxePart", "Ripple Pickaxe Part", {name: "ripple_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.ripplePickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.ripple,0]);
IDRegistry.genItemID("windcoinPickaxePart");
Item.createItem("windcoinPickaxePart", "Windcoin Pickaxe Part", {name: "windcoin_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.windcoinPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.windcoin,0]);
IDRegistry.genItemID("litecoinPickaxePart");
Item.createItem("litecoinPickaxePart", "Litecoin Pickaxe Part", {name: "litecoin_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.litecoinPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.litecoin,0]);
IDRegistry.genItemID("dogecoinPickaxePart");
Item.createItem("dogecoinPickaxePart", "Dogecoin Pickaxe Part", {name: "dogecoin_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.dogecoinPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.dogecoin,0]);
IDRegistry.genItemID("peercoinPickaxePart");
Item.createItem("peercoinPickaxePart", "Peercoin Pickaxe Part", {name: "peercoin_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.peercoinPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.peercoin,0]);
IDRegistry.genItemID("concoinPickaxePart");
Item.createItem("concoinPickaxePart", "Concoin Pickaxe Part", {name: "concoin_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.concoinPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.concoin,0]);
IDRegistry.genItemID("buzcoinPickaxePart");
Item.createItem("buzcoinPickaxePart", "Buzcoin Pickaxe Part", {name: "buzcoin_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.buzcoinPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.buzcoin,0]);
IDRegistry.genItemID("mooncoinPickaxePart");
Item.createItem("mooncoinPickaxePart", "Mooncoin Pickaxe Part", {name: "mooncoin_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.mooncoinPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.mooncoin,0]);
IDRegistry.genItemID("marscoinPickaxePart");
Item.createItem("marscoinPickaxePart", "Marscoin Pickaxe Part", {name: "marscoin_pickaxe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.marscoinPickaxePart,count:1,data:0},["aao","oaa","ooa"],['a',ItemID.marscoin,0]);

IDRegistry.genItemID("bitcoinShovelPart");
Item.createItem("bitcoinShovelPart", "Bitcoin Shovel Part", {name: "bitcoin_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.bitcoinShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.bitcoin,0]);
IDRegistry.genItemID("wondercoinShovelPart");
Item.createItem("wondercoinShovelPart", "Wondercoin Shovel Part", {name: "wondercoin_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.wondercoinShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.wondercoin,0]);
IDRegistry.genItemID("ethereumShovelPart");
Item.createItem("ethereumShovelPart", "Ethereum Shovel Part", {name: "ethereum_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.ethereumShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.ethereum,0]);
IDRegistry.genItemID("arkcoinShovelPart");
Item.createItem("arkcoinShovelPart", "Arkcoin Shovel Part", {name: "arkcoin_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.arkcoinShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.arkcoin,0]);
IDRegistry.genItemID("cosmocashShovelPart");
Item.createItem("cosmocashShovelPart", "Cosmocash Shovel Part", {name: "cosmocash_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.cosmocashShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.cosmocash,0]);
IDRegistry.genItemID("augurShovelPart");
Item.createItem("augurShovelPart", "Augur Shovel Part", {name: "augur_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.augurShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.augur,0]);
IDRegistry.genItemID("liskShovelPart");
Item.createItem("liskShovelPart", "Lisk Shovel Part", {name: "lisk_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.liskShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.lisk,0]);
IDRegistry.genItemID("firecoinShovelPart");
Item.createItem("firecoinShovelPart", "Firecoin Shovel Part", {name: "firecoin_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.firecoinShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.firecoin,0]);
IDRegistry.genItemID("zerocashShovelPart");
Item.createItem("zerocashShovelPart", "Zerocash Shovel Part", {name: "zerocash_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.zerocashShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.zerocash,0]);
IDRegistry.genItemID("dashcoinShovelPart");
Item.createItem("dashcoinShovelPart", "Dashcoin Shovel Part", {name: "dashcoin_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.dashcoinShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.dashcoin,0]);
IDRegistry.genItemID("moneroShovelPart");
Item.createItem("moneroShovelPart", "Monero Shovel Part", {name: "monero_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.moneroShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.monero,0]);
IDRegistry.genItemID("rippleShovelPart");
Item.createItem("rippleShovelPart", "Ripple Shovel Part", {name: "ripple_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.rippleShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.ripple,0]);
IDRegistry.genItemID("windcoinShovelPart");
Item.createItem("windcoinShovelPart", "Windcoin Shovel Part", {name: "windcoin_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.windcoinShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.windcoin,0]);
IDRegistry.genItemID("litecoinShovelPart");
Item.createItem("litecoinShovelPart", "Litecoin Shovel Part", {name: "litecoin_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.litecoinShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.litecoin,0]);
IDRegistry.genItemID("dogecoinShovelPart");
Item.createItem("dogecoinShovelPart", "Dogecoin Shovel Part", {name: "dogecoin_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.dogecoinShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.dogecoin,0]);
IDRegistry.genItemID("peercoinShovelPart");
Item.createItem("peercoinShovelPart", "Peercoin Shovel Part", {name: "peercoin_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.peercoinShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.peercoin,0]);
IDRegistry.genItemID("concoinShovelPart");
Item.createItem("concoinShovelPart", "Concoin Shovel Part", {name: "concoin_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.concoinShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.concoin,0]);
IDRegistry.genItemID("buzcoinShovelPart");
Item.createItem("buzcoinShovelPart", "Buzcoin Shovel Part", {name: "buzcoin_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.buzcoinShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.buzcoin,0]);
IDRegistry.genItemID("mooncoinShovelPart");
Item.createItem("mooncoinShovelPart", "Mooncoin Shovel Part", {name: "mooncoin_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.mooncoinShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.mooncoin,0]);
IDRegistry.genItemID("marscoinShovelPart");
Item.createItem("marscoinShovelPart", "Marscoin Shovel Part", {name: "marscoin_shovel_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.marscoinShovelPart,count:1,data:0},["oao","aaa","oao"],['a',ItemID.marscoin,0]);

IDRegistry.genItemID("bitcoinAxePart");
Item.createItem("bitcoinAxePart", "Bitcoin Axe Part", {name: "bitcoin_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.bitcoinAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.bitcoin,0]);
IDRegistry.genItemID("wondercoinAxePart");
Item.createItem("wondercoinAxePart", "Wondercoin Axe Part", {name: "wondercoin_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.wondercoinAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.wondercoin,0]);
IDRegistry.genItemID("ethereumAxePart");
Item.createItem("ethereumAxePart", "Ethereum Axe Part", {name: "ethereum_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.ethereumAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.ethereum,0]);
IDRegistry.genItemID("arkcoinAxePart");
Item.createItem("arkcoinAxePart", "Arkcoin Axe Part", {name: "arkcoin_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.arkcoinAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.arkcoin,0]);
IDRegistry.genItemID("cosmocashAxePart");
Item.createItem("cosmocashAxePart", "Cosmocash Axe Part", {name: "cosmocash_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.cosmocashAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.cosmocash,0]);
IDRegistry.genItemID("augurAxePart");
Item.createItem("augurAxePart", "Augur Axe Part", {name: "augur_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.augurAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.augur,0]);
IDRegistry.genItemID("liskAxePart");
Item.createItem("liskAxePart", "Lisk Axe Part", {name: "lisk_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.liskAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.lisk,0]);
IDRegistry.genItemID("firecoinAxePart");
Item.createItem("firecoinAxePart", "Firecoin Axe Part", {name: "firecoin_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.firecoinAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.firecoin,0]);
IDRegistry.genItemID("zerocashAxePart");
Item.createItem("zerocashAxePart", "Zerocash Axe Part", {name: "zerocash_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.zerocashAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.zerocash,0]);
IDRegistry.genItemID("dashcoinAxePart");
Item.createItem("dashcoinAxePart", "Dashcoin Axe Part", {name: "dashcoin_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.dashcoinAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.dashcoin,0]);
IDRegistry.genItemID("moneroAxePart");
Item.createItem("moneroAxePart", "Monero Axe Part", {name: "monero_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.moneroAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.monero,0]);
IDRegistry.genItemID("rippleAxePart");
Item.createItem("rippleAxePart", "Ripple Axe Part", {name: "ripple_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.rippleAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.ripple,0]);
IDRegistry.genItemID("windcoinAxePart");
Item.createItem("windcoinAxePart", "Windcoin Axe Part", {name: "windcoin_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.windcoinAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.windcoin,0]);
IDRegistry.genItemID("litecoinAxePart");
Item.createItem("litecoinAxePart", "Litecoin Axe Part", {name: "litecoin_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.litecoinAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.litecoin,0]);
IDRegistry.genItemID("dogecoinAxePart");
Item.createItem("dogecoinAxePart", "Dogecoin Axe Part", {name: "dogecoin_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.dogecoinAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.dogecoin,0]);
IDRegistry.genItemID("peercoinAxePart");
Item.createItem("peercoinAxePart", "Peercoin Axe Part", {name: "peercoin_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.peercoinAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.peercoin,0]);
IDRegistry.genItemID("concoinAxePart");
Item.createItem("concoinAxePart", "Concoin Axe Part", {name: "concoin_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.concoinAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.concoin,0]);
IDRegistry.genItemID("buzcoinAxePart");
Item.createItem("buzcoinAxePart", "Buzcoin Axe Part", {name: "buzcoin_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.buzcoinAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.buzcoin,0]);
IDRegistry.genItemID("mooncoinAxePart");
Item.createItem("mooncoinAxePart", "Mooncoin Axe Part", {name: "mooncoin_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.mooncoinAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.mooncoin,0]);
IDRegistry.genItemID("marscoinAxePart");
Item.createItem("marscoinAxePart", "Marscoin Axe Part", {name: "marscoin_axe_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.marscoinAxePart,count:1,data:0},["aao","aaa","ooo"],['a',ItemID.marscoin,0]);

IDRegistry.genItemID("bitcoinSwordPart");
Item.createItem("bitcoinSwordPart", "Bitcoin Sword Part", {name: "bitcoin_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.bitcoinSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.bitcoin,0]);
IDRegistry.genItemID("wondercoinSwordPart");
Item.createItem("wondercoinSwordPart", "Wondercoin Sword Part", {name: "wondercoin_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.wondercoinSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.wondercoin,0]);
IDRegistry.genItemID("ethereumSwordPart");
Item.createItem("ethereumSwordPart", "Ethereum Sword Part", {name: "ethereum_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.ethereumSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.ethereum,0]);
IDRegistry.genItemID("arkcoinSwordPart");
Item.createItem("arkcoinSwordPart", "Arkcoin Sword Part", {name: "arkcoin_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.arkcoinSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.arkcoin,0]);
IDRegistry.genItemID("cosmocashSwordPart");
Item.createItem("cosmocashSwordPart", "Cosmocash Sword Part", {name: "cosmocash_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.cosmocashSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.cosmocash,0]);
IDRegistry.genItemID("augurSwordPart");
Item.createItem("augurSwordPart", "Augur Sword Part", {name: "augur_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.augurSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.augur,0]);
IDRegistry.genItemID("liskSwordPart");
Item.createItem("liskSwordPart", "Lisk Sword Part", {name: "lisk_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.liskSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.lisk,0]);
IDRegistry.genItemID("firecoinSwordPart");
Item.createItem("firecoinSwordPart", "Firecoin Sword Part", {name: "firecoin_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.firecoinSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.firecoin,0]);
IDRegistry.genItemID("zerocashSwordPart");
Item.createItem("zerocashSwordPart", "Zerocash Sword Part", {name: "zerocash_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.zerocashSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.zerocash,0]);
IDRegistry.genItemID("dashcoinSwordPart");
Item.createItem("dashcoinSwordPart", "Dashcoin Sword Part", {name: "dashcoin_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.dashcoinSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.dashcoin,0]);
IDRegistry.genItemID("moneroSwordPart");
Item.createItem("moneroSwordPart", "Monero Sword Part", {name: "monero_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.moneroSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.monero,0]);
IDRegistry.genItemID("rippleSwordPart");
Item.createItem("rippleSwordPart", "Ripple Sword Part", {name: "ripple_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.rippleSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.ripple,0]);
IDRegistry.genItemID("windcoinSwordPart");
Item.createItem("windcoinSwordPart", "Windcoin Sword Part", {name: "windcoin_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.windcoinSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.windcoin,0]);
IDRegistry.genItemID("litecoinSwordPart");
Item.createItem("litecoinSwordPart", "Litecoin Sword Part", {name: "litecoin_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.litecoinSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.litecoin,0]);
IDRegistry.genItemID("dogecoinSwordPart");
Item.createItem("dogecoinSwordPart", "Dogecoin Sword Part", {name: "dogecoin_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.dogecoinSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.dogecoin,0]);
IDRegistry.genItemID("peercoinSwordPart");
Item.createItem("peercoinSwordPart", "Peercoin Sword Part", {name: "peercoin_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.peercoinSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.peercoin,0]);
IDRegistry.genItemID("concoinSwordPart");
Item.createItem("concoinSwordPart", "Concoin Sword Part", {name: "concoin_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.concoinSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.concoin,0]);
IDRegistry.genItemID("buzcoinSwordPart");
Item.createItem("buzcoinSwordPart", "Buzcoin Sword Part", {name: "buzcoin_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.buzcoinSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.buzcoin,0]);
IDRegistry.genItemID("mooncoinSwordPart");
Item.createItem("mooncoinSwordPart", "Mooncoin Sword Part", {name: "mooncoin_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.mooncoinSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.mooncoin,0]);
IDRegistry.genItemID("marscoinSwordPart");
Item.createItem("marscoinSwordPart", "Marscoin Sword Part", {name: "marscoin_sword_part", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.marscoinSwordPart,count:1,data:0},["ooa","oao","aoo"],['a',ItemID.marscoin,0]);

IDRegistry.genItemID("toolHand");
Item.createItem("toolHand", "Tool Hand", {name: "crypto_stick", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.toolHand,count:1,data:0},["ooa","oao","aoo"],['a',280,0]);
IDRegistry.genItemID("swordHand");
Item.createItem("swordHand", "Sword Hand", {name: "crypto_hand", meta: 0}, {stack: 1});
Recipes.addShaped({id:ItemID.swordHand,count:1,data:0},["aoo","oao","aoa"],['a',280,0]);

Recipes.addShaped({id:ItemID.bitcoinPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.bitcoinPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.wondercoinPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.wondercoinPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.ethereumPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.ethereumPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.arkcoinPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.arkcoinPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.cosmocashPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.cosmocashPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.augurPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.augurPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.liskPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.liskPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.firecoinPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.firecoinPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.zerocashPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.zerocashPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.dashcoinPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.dashcoinPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.moneroPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.moneroPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.ripplePickaxe,count:1,data:0},["oa","bo"],['a',ItemID.ripplePickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.windcoinPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.windcoinPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.litecoinPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.litecoinPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.dogecoinPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.dogecoinPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.peercoinPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.peercoinPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.concoinPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.concoinPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.buzcoinPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.buzcoinPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.mooncoinPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.mooncoinPickaxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.marscoinPickaxe,count:1,data:0},["oa","bo"],['a',ItemID.marscoinPickaxePart,0,'b',ItemID.toolHand,0]);

Recipes.addShaped({id:ItemID.bitcoinShovel,count:1,data:0},["oa","bo"],['a',ItemID.bitcoinShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.wondercoinShovel,count:1,data:0},["oa","bo"],['a',ItemID.wondercoinShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.ethereumShovel,count:1,data:0},["oa","bo"],['a',ItemID.ethereumShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.arkcoinShovel,count:1,data:0},["oa","bo"],['a',ItemID.arkcoinShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.cosmocashShovel,count:1,data:0},["oa","bo"],['a',ItemID.cosmocashShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.augurShovel,count:1,data:0},["oa","bo"],['a',ItemID.augurShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.liskShovel,count:1,data:0},["oa","bo"],['a',ItemID.liskShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.firecoinShovel,count:1,data:0},["oa","bo"],['a',ItemID.firecoinShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.zerocashShovel,count:1,data:0},["oa","bo"],['a',ItemID.zerocashShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.dashcoinShovel,count:1,data:0},["oa","bo"],['a',ItemID.dashcoinShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.moneroShovel,count:1,data:0},["oa","bo"],['a',ItemID.moneroShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.rippleShovel,count:1,data:0},["oa","bo"],['a',ItemID.rippleShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.windcoinShovel,count:1,data:0},["oa","bo"],['a',ItemID.windcoinShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.litecoinShovel,count:1,data:0},["oa","bo"],['a',ItemID.litecoinShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.dogecoinShovel,count:1,data:0},["oa","bo"],['a',ItemID.dogecoinShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.peercoinShovel,count:1,data:0},["oa","bo"],['a',ItemID.peercoinShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.concoinShovel,count:1,data:0},["oa","bo"],['a',ItemID.concoinShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.buzcoinShovel,count:1,data:0},["oa","bo"],['a',ItemID.buzcoinShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.mooncoinShovel,count:1,data:0},["oa","bo"],['a',ItemID.mooncoinShovelPart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.marscoinShovel,count:1,data:0},["oa","bo"],['a',ItemID.marscoinShovelPart,0,'b',ItemID.toolHand,0]);

Recipes.addShaped({id:ItemID.bitcoinAxe,count:1,data:0},["oa","bo"],['a',ItemID.bitcoinAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.wondercoinAxe,count:1,data:0},["oa","bo"],['a',ItemID.wondercoinAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.ethereumAxe,count:1,data:0},["oa","bo"],['a',ItemID.ethereumAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.arkcoinAxe,count:1,data:0},["oa","bo"],['a',ItemID.arkcoinAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.cosmocashAxe,count:1,data:0},["oa","bo"],['a',ItemID.cosmocashAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.augurAxe,count:1,data:0},["oa","bo"],['a',ItemID.augurAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.liskAxe,count:1,data:0},["oa","bo"],['a',ItemID.liskAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.firecoinAxe,count:1,data:0},["oa","bo"],['a',ItemID.firecoinAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.zerocashAxe,count:1,data:0},["oa","bo"],['a',ItemID.zerocashAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.dashcoinAxe,count:1,data:0},["oa","bo"],['a',ItemID.dashcoinAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.moneroAxe,count:1,data:0},["oa","bo"],['a',ItemID.moneroAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.rippleAxe,count:1,data:0},["oa","bo"],['a',ItemID.rippleAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.windcoinAxe,count:1,data:0},["oa","bo"],['a',ItemID.windcoinAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.litecoinAxe,count:1,data:0},["oa","bo"],['a',ItemID.litecoinAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.dogecoinAxe,count:1,data:0},["oa","bo"],['a',ItemID.dogecoinAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.peercoinAxe,count:1,data:0},["oa","bo"],['a',ItemID.peercoinAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.concoinAxe,count:1,data:0},["oa","bo"],['a',ItemID.concoinAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.buzcoinAxe,count:1,data:0},["oa","bo"],['a',ItemID.buzcoinAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.mooncoinAxe,count:1,data:0},["oa","bo"],['a',ItemID.mooncoinAxePart,0,'b',ItemID.toolHand,0]);
Recipes.addShaped({id:ItemID.marscoinAxe,count:1,data:0},["oa","bo"],['a',ItemID.marscoinAxePart,0,'b',ItemID.toolHand,0]);

Recipes.addShaped({id:ItemID.bitcoinSword,count:1,data:0},["oa","bo"],['a',ItemID.bitcoinSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.wondercoinSword,count:1,data:0},["oa","bo"],['a',ItemID.wondercoinSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.ethereumSword,count:1,data:0},["oa","bo"],['a',ItemID.ethereumSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.arkcoinSword,count:1,data:0},["oa","bo"],['a',ItemID.arkcoinSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.cosmocashSword,count:1,data:0},["oa","bo"],['a',ItemID.cosmocashSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.augurSword,count:1,data:0},["oa","bo"],['a',ItemID.augurSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.liskSword,count:1,data:0},["oa","bo"],['a',ItemID.liskSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.firecoinSword,count:1,data:0},["oa","bo"],['a',ItemID.firecoinSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.zerocashSword,count:1,data:0},["oa","bo"],['a',ItemID.zerocashSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.dashcoinSword,count:1,data:0},["oa","bo"],['a',ItemID.dashcoinSwordPart,0,'b',ItemID.swordlHand,0]);
Recipes.addShaped({id:ItemID.moneroSword,count:1,data:0},["oa","bo"],['a',ItemID.moneroSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.rippleSword,count:1,data:0},["oa","bo"],['a',ItemID.rippleSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.windcoinSword,count:1,data:0},["oa","bo"],['a',ItemID.windcoinSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.litecoinSword,count:1,data:0},["oa","bo"],['a',ItemID.litecoinSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.dogecoinSword,count:1,data:0},["oa","bo"],['a',ItemID.dogecoinSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.peercoinSword,count:1,data:0},["oa","bo"],['a',ItemID.peercoinSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.concoinSword,count:1,data:0},["oa","bo"],['a',ItemID.concoinSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.buzcoinSword,count:1,data:0},["oa","bo"],['a',ItemID.buzcoinSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.mooncoinSword,count:1,data:0},["oa","bo"],['a',ItemID.mooncoinSwordPart,0,'b',ItemID.swordHand,0]);
Recipes.addShaped({id:ItemID.marscoinSword,count:1,data:0},["oa","bo"],['a',ItemID.marscoinSwordPart,0,'b',ItemID.swordHand,0]);

Recipes.addShaped({id:ItemID.bitcoinBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.bitcoin,0,'b',54,0]);
Recipes.addShaped({id:ItemID.wondercoinBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.wondercoin,0,'b',54,0]);
Recipes.addShaped({id:ItemID.ethereumBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.ethereum,0,'b',54,0]);
Recipes.addShaped({id:ItemID.arkcoinBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.arkcoin,0,'b',54,0]);
Recipes.addShaped({id:ItemID.cosmocashBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.cosmocash,0,'b',54,0]);
Recipes.addShaped({id:ItemID.augurBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.augur,0,'b',54,0]);
Recipes.addShaped({id:ItemID.liskBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.lisk,0,'b',54,0]);
Recipes.addShaped({id:ItemID.firecoinBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.firecoin,0,'b',54,0]);
Recipes.addShaped({id:ItemID.zerocashBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.zerocash,0,'b',54,0]);
Recipes.addShaped({id:ItemID.dashcoinBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.dashcoin,0,'b',54,0]);
Recipes.addShaped({id:ItemID.moneroBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.monero,0,'b',54,0]);
Recipes.addShaped({id:ItemID.rippleBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.ripple,0,'b',54,0]);
Recipes.addShaped({id:ItemID.windcoinBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.windcoin,0,'b',54,0]);
Recipes.addShaped({id:ItemID.litecoinBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.litecoin,0,'b',54,0]);
Recipes.addShaped({id:ItemID.dogecoinBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.dogecoin,0,'b',54,0]);
Recipes.addShaped({id:ItemID.peercoinBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.peercoin,0,'b',54,0]);
Recipes.addShaped({id:ItemID.concoinBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.concoin,0,'b',54,0]);
Recipes.addShaped({id:ItemID.buzcoinBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.buzcoin,0,'b',54,0]);
Recipes.addShaped({id:ItemID.mooncoinBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.mooncoin,0,'b',54,0]);
Recipes.addShaped({id:ItemID.marscoinBackpack,count:1,data:0},["aaa","aba","aaa"],['a',ItemID.marscoin,0,'b',54,0]);
