Compress.addBlock("single_compressed_cobblestone", {name: "Single Compressed Cobblestone", texture: "cobblestone_compressed"}, {destroyTime: cobblestone_time});
Compress.addCraft({id: BlockID.single_compressed_cobblestone}, {id: 4});
Compress.addBlock("single_compressed_stone", {name: "Single Compressed Stone", texture: "stone_compressed"}, {destroyTime: stone_time});
Compress.addCraft({id: BlockID.single_compressed_stone}, {id: 1});
Compress.addBlock("single_compressed_blocksand", {name: "Single Compressed Sand", texture: "blocksand_compressed"}, {destroyTime: sand_time});
Compress.addCraft({id: BlockID.single_compressed_blocksand}, {id: 12, data: 0});
Compress.addBlock("single_compressed_dirt", {name: "Single Compressed Dirt", texture: "dirt_compressed"}, {destroyTime: dirt_time});
Compress.addCraft({id: BlockID.single_compressed_dirt}, {id: 3});
Compress.addBlock("single_compressed_gravel", {name: "Single Compressed Gravel", texture: "gravel_compressed"}, {destroyTime: gravel_time});
Compress.addCraft({id: BlockID.single_compressed_gravel}, {id: 13});
Compress.addBlock("single_compressed_cobblestone_mossy", {name: "Single Compressed Mossy Cobblestone", texture: "cobblestonemossy_compressed"}, {destroyTime: cobblestone_mossy_time});
Compress.addCraft({id: BlockID.single_compressed_cobblestone_mossy}, {id: 48});
Compress.addBlock("single_compressed_endstone", {name: "Single Compressed End Stone", texture: "endstone_compressed"}, {destroyTime: endstone_time});
Compress.addCraft({id: BlockID.single_compressed_endstone}, {id: 121});
Compress.addBlock("single_compressed_charcoal", {name: "Single Compressed Charcoal", texture: "charcoal_compressed"}, {destroyTime: charcoal_time});
Compress.addCraft({id: BlockID.single_compressed_charcoal}, {id: 263, data: 1});
Compress.addBlock("single_compressed_netherrack", {name: "Single Compressed Netherrack", texture: "netherrack_compressed"}, {destroyTime: netherrack_time});
Compress.addCraft({id: BlockID.single_compressed_netherrack}, {id: 87});
Compress.addBlock("single_compressed_soulsand", {name: "Single Compressed Soul Sand", texture: "soulsand_compressed"}, {destroyTime: soulsand_time});
Compress.addCraft({id: BlockID.single_compressed_soulsand}, {id: 88});
Compress.addBlock("compressed_logwood", {name: "Block of Log Oak", texture: "logoak_compressed"}, {destroyTime: wood_time});
Compress.addCraft({id: BlockID.compressed_logwood}, {id: 17, data: 0});
Compress.addBlock("compressed_logspruce", {name: "Block of Log Spruce", texture: "logspruce_compressed"}, {destroyTime: wood_time});
Compress.addCraft({id: BlockID.compressed_logspruce}, {id: 17, data: 1});
Compress.addBlock("compressed_logbirch", {name: "Block of Log Birch", texture: "logbirch_compressed"}, {destroyTime: wood_time});
Compress.addCraft({id: BlockID.compressed_logbirch}, {id: 17, data: 2});
Compress.addBlock("compressed_logjungle", {name: "Block of Log Jungle", texture: "logjungle_compressed"}, {destroyTime: wood_time});
Compress.addCraft({id: BlockID.compressed_logjungle}, {id: 17, data: 3});
Compress.addBlock("compressed_logacacia", {name: "Block of Log Acacia", texture: "logacacia_compressed"}, {destroyTime: wood_time});
Compress.addCraft({id: BlockID.compressed_logacacia}, {id: 162, data: 0});
Compress.addBlock("compressed_logdarkoak", {name: "Block of Log Dark Oak", texture: "logbigoak_compressed"}, {destroyTime: wood_time});
Compress.addCraft({id: BlockID.compressed_logdarkoak}, {id: 162, data: 1});
Compress.addBlock("single_compressed_feather", {name: "Single Compressed Feathers", texture: "feather_compressed"}, {destroyTime: feather_time});
Compress.addCraft({id: BlockID.single_compressed_feather}, {id: 288});
Compress.addBlock("compressed_string", {name: "Block of Strings", texture: "string_compressed"}, {destroyTime: string_time});
Compress.addCraft({id: BlockID.compressed_string}, {id: 287});
Compress.addBlock("single_compressed_porkchop", {name: "Single Compressed Porkchop", texture: "meatporkchop_compressed"}, {destroyTime: meat_time});
Compress.addCraft({id: BlockID.single_compressed_porkchop}, {id: 319});
Compress.addBlock("single_compressed_chicken", {name: "Single Compressed Chicken", texture: "meatchicken_compressed"}, {destroyTime: meat_time});
Compress.addCraft({id: BlockID.single_compressed_chicken}, {id: 365});
Compress.addBlock("single_compressed_beef", {name: "Single Compressed Beef", texture: "meatbeef_compressed"}, {destroyTime: meat_time});
Compress.addCraft({id: BlockID.single_compressed_beef}, {id: 363});
Compress.addBlock("single_compressed_fish", {name: "Single Compressed Fish", texture: "meatfish_compressed"}, {destroyTime: meat_time});
Compress.addCraft({id: BlockID.single_compressed_fish}, {id: 349});
Compress.addBlock("single_compressed_bone", {name: "Single Compressed Bones", texture: "bone_compressed"}, {destroyTime: bone_time});
Compress.addCraft({id: BlockID.single_compressed_bone}, {id: 352});
Compress.addBlock("single_compressed_egg", {name: "Single Compressed Eggs", texture: "egg_compressed"}, {destroyTime: egg_time});
Compress.addCraft({id: BlockID.single_compressed_egg}, {id: 344, data: 0});
Compress.addBlock("single_compressed_leather", {name: "Single Compressed Leather", texture: "leather_compressed"}, {destroyTime: leather_time});
Compress.addCraft({id: BlockID.single_compressed_leather}, {id: 334});
Compress.addBlock("compressed_bread", {name: "Block of Bread", texture: "bread_compressed"}, {destroyTime: bread_time});
Compress.addCraft({id: BlockID.compressed_bread}, {id: 297});
Compress.addBlock("compressed_cookie", {name: "Block of Cookies", texture: "cookie_compressed"}, {destroyTime: cookie_time});
Compress.addCraft({id: BlockID.compressed_cookie}, {id: 357});
Compress.addBlock("single_compressed_potato", {name: "Single Compressed Potatoes", texture: "croppotato_compressed"}, {destroyTime: potato_time});
Compress.addCraft({id: BlockID.single_compressed_potato}, {id: 392});
Compress.addBlock("single_compressed_carrot", {name: "Single Compressed Carrots", texture: "cropcarrot_compressed"}, {destroyTime: carrot_time});
Compress.addCraft({id: BlockID.single_compressed_carrot}, {id: 391});
Compress.addBlock("single_compressed_netherwart", {name: "Single Compressed Nether Wart", texture: "cropnetherwart_compressed"}, {destroyTime: netherwart_time});
Compress.addCraft({id: BlockID.single_compressed_netherwart}, {id: 372});
Compress.addBlock("single_compressed_melon", {name: "Single Compressed Melon", texture: "cropmelon_compressed", textureData: 1}, {destroyTime: melon_time});
Compress.addCraft({id: BlockID.single_compressed_melon}, {id: 360});
Compress.addBlock("single_compressed_apple", {name: "Single Compressed Apples", texture: "cropapple_compressed"}, {destroyTime: apple_time});
Compress.addCraft({id: BlockID.single_compressed_apple}, {id: 260});
Compress.addBlock("single_compressed_rotten", {name: "Single Compressed Rotten Flesh", texture: "meatrotten_compressed"}, {destroyTime: rotten_flesh_time});
Compress.addCraft({id: BlockID.single_compressed_rotten}, {id: 367});
Compress.addBlock("single_compressed_blazerod", {name: "Single Compressed Blaze", texture: "rodblaze_compressed"}, {destroyTime: blazerod_time});
Compress.addCraft({id: BlockID.single_compressed_blazerod}, {id: 369});
Compress.addBlock("single_compressed_spider_eye", {name: "Single Compressed Spider Eyes", texture: "spidereye_compressed"}, {destroyTime: spidereye_time});
Compress.addCraft({id: BlockID.single_compressed_spider_eye}, {id: 375});
Compress.addBlock("single_compressed_enderpearl", {name: "Single Compressed Ender Pearl", texture: "pearlender_compressed"}, {destroyTime: enderpearl_time});
Compress.addCraft({id: BlockID.single_compressed_enderpearl}, {id: 368});
Compress.addBlock("single_compressed_sugar", {name: "Single Compressed Sugar", texture: "dustsugar_compressed"}, {destroyTime: sugar_time});
Compress.addCraft({id: BlockID.single_compressed_sugar}, {id: 353});
Compress.addBlock("single_compressed_gunpowder", {name: "Single Compressed Gunpowder", texture: "dustgunpowder_compressed"}, {destroyTime: gunpowder_time});
Compress.addCraft({id: BlockID.single_compressed_gunpowder}, {id: 289});
Compress.addBlock("single_compressed_sugarcane", {name: "Single Compressed Sugar Cane", texture: "cropsugarcane_compressed"}, {destroyTime: sugarcane_time});
Compress.addCraft({id: BlockID.single_compressed_sugarcane}, {id: 338});
Compress.addBlock("compressed_netherstar", {name: "Block of Nether Star", texture: "itemnetherstar_compressed"}, {destroyTime: netherstar_time});
Compress.addCraft({id: BlockID.compressed_netherstar}, {id: 399});
Compress.addBlock("single_compressed_clay", {name: "Single Compressed Clay", texture: "clay_compressed"}, {destroyTime: clay_time});
Compress.addCraft({id: BlockID.single_compressed_clay}, {id: 82, data: 0});
Compress.addBlock("single_compressed_flint", {name: "Single Compressed Flint", texture: "flint_compressed"}, {destroyTime: flint_time});
Compress.addCraft({id: BlockID.single_compressed_flint}, {id: 318});

