Compress.addBlock("triple_compressed_cobblestone", {name: "Triple Compressed Cobblestone", texture: "cobblestone_compressed", textureData: 2}, {destroyTime: cobblestone_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_cobblestone}, {id: BlockID.double_compressed_cobblestone});
Compress.addBlock("triple_compressed_stone", {name: "Triple Compressed Stone", texture: "stone_compressed", textureData: 2}, {destroyTime: stone_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_stone}, {id: BlockID.double_compressed_stone});
Compress.addBlock("triple_compressed_blocksand", {name: "Triple Compressed Sand", texture: "blocksand_compressed", textureData: 2}, {destroyTime: sand_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_blocksand}, {id: BlockID.double_compressed_blocksand});
Compress.addBlock("triple_compressed_dirt", {name: "Triple Compressed Dirt", texture: "dirt_compressed", textureData: 2}, {destroyTime: dirt_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_dirt}, {id: BlockID.double_compressed_dirt});
Compress.addBlock("triple_compressed_gravel", {name: "Triple Compressed Gravel", texture: "gravel_compressed", textureData: 2}, {destroyTime: gravel_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_gravel}, {id: BlockID.double_compressed_gravel});
Compress.addBlock("triple_compressed_cobblestone_mossy", {name: "Triple Compressed Mossy Cobblestone", texture: "cobblestonemossy_compressed", textureData: 2}, {destroyTime: cobblestone_mossy_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_cobblestone_mossy}, {id: BlockID.double_compressed_cobblestone_mossy});
Compress.addBlock("triple_compressed_endstone", {name: "Triple Compressed End Stone", texture: "endstone_compressed", textureData: 2}, {destroyTime: endstone_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_endstone}, {id: BlockID.double_compressed_endstone});
Compress.addBlock("triple_compressed_charcoal", {name: "Triple Compressed Charcoal", texture: "charcoal_compressed", textureData: 2}, {destroyTime: charcoal_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_charcoal}, {id: BlockID.double_compressed_charcoal});
Compress.addBlock("triple_compressed_coal", {name: "Triple Compressed Coal", texture: "coal_compressed", textureData: 2}, {destroyTime: coal_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_coal}, {id: BlockID.double_compressed_coal});
Compress.addBlock("triple_compressed_netherrack", {name: "Triple Compressed Netherrack", texture: "netherrack_compressed", textureData: 2}, {destroyTime: netherrack_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_netherrack}, {id: BlockID.double_compressed_netherrack});
Compress.addBlock("triple_compressed_soulsand", {name: "Triple Compressed Soul Sand", texture: "soulsand_compressed", textureData: 2}, {destroyTime: soulsand_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_soulsand}, {id: BlockID.double_compressed_soulsand});
Compress.addBlock("triple_compressed_feather", {name: "Triple Compressed Feathers", texture: "feather_compressed", textureData: 2}, {destroyTime: feather_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_feather}, {id: BlockID.double_compressed_feather});
Compress.addBlock("triple_compressed_porkchop", {name: "Triple Compressed Porkchop", texture: "meatporkchop_compressed", textureData: 2}, {destroyTime: meat_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_porkchop}, {id: BlockID.double_compressed_porkchop});
Compress.addBlock("triple_compressed_chicken", {name: "Triple Compressed Chicken", texture: "meatchicken_compressed", textureData: 2}, {destroyTime: meat_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_chicken}, {id: BlockID.double_compressed_chicken});
Compress.addBlock("triple_compressed_beef", {name: "Triple Compressed Beef", texture: "meatbeef_compressed", textureData: 2}, {destroyTime: meat_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_beef}, {id: BlockID.double_compressed_beef});
Compress.addBlock("triple_compressed_fish", {name: "Triple Compressed Fish", texture: "meatfish_compressed", textureData: 2}, {destroyTime: meat_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_fish}, {id: BlockID.double_compressed_fish});
Compress.addBlock("triple_compressed_bone", {name: "Triple Compressed Bones", texture: "bone_compressed", textureData: 2}, {destroyTime: bone_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_bone}, {id: BlockID.double_compressed_bone});
Compress.addBlock("triple_compressed_egg", {name: "Triple Compressed Eggs", texture: "egg_compressed", textureData: 2}, {destroyTime: egg_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_egg}, {id: BlockID.double_compressed_egg});
Compress.addBlock("triple_compressed_leather", {name: "Triple Compressed Leather", texture: "leather_compressed", textureData: 2}, {destroyTime: leather_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_leather}, {id: BlockID.double_compressed_leather});
Compress.addBlock("triple_compressed_potato", {name: "Triple Compressed Potatoes", texture: "croppotato_compressed", textureData: 2}, {destroyTime: potato_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_potato}, {id: BlockID.double_compressed_potato});
Compress.addBlock("triple_compressed_carrot", {name: "Triple Compressed Carrots", texture: "cropcarrot_compressed", textureData: 2}, {destroyTime: carrot_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_carrot}, {id: BlockID.double_compressed_carrot});
Compress.addBlock("triple_compressed_netherwart", {name: "Triple Compressed Nether Wart", texture: "cropnetherwart_compressed", textureData: 2}, {destroyTime: netherwart_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_netherwart}, {id: BlockID.double_compressed_netherwart});
Compress.addBlock("triple_compressed_apple", {name: "Triple Compressed Apples", texture: "cropapple_compressed", textureData: 2}, {destroyTime: apple_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_apple}, {id: BlockID.double_compressed_apple});
Compress.addBlock("triple_compressed_rotten", {name: "Triple Compressed Rotten Flesh", texture: "meatrotten_compressed", textureData: 2}, {destroyTime: rotten_flesh_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_rotten}, {id: BlockID.double_compressed_rotten});
Compress.addBlock("triple_compressed_blazerod", {name: "Triple Compressed Blaze", texture: "rodblaze_compressed", textureData: 2}, {destroyTime: blazerod_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_blazerod}, {id: BlockID.double_compressed_blazerod});
Compress.addBlock("triple_compressed_spider_eye", {name: "Triple Compressed Spider Eyes", texture: "spidereye_compressed", textureData: 2}, {destroyTime: spidereye_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_spider_eye}, {id: BlockID.double_compressed_spider_eye});
Compress.addBlock("triple_compressed_enderpearl", {name: "Triple Compressed Ender Pearl", texture: "pearlender_compressed", textureData: 2}, {destroyTime: enderpearl_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_enderpearl}, {id: BlockID.double_compressed_enderpearl});
Compress.addBlock("triple_compressed_sugar", {name: "Triple Compressed Sugar", texture: "dustsugar_compressed", textureData: 2}, {destroyTime: sugar_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_sugar}, {id: BlockID.double_compressed_sugar});
Compress.addBlock("triple_compressed_gunpowder", {name: "Triple Compressed Gunpowder", texture: "dustgunpowder_compressed", textureData: 2}, {destroyTime: gunpowder_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_gunpowder}, {id: BlockID.double_compressed_gunpowder});
Compress.addBlock("triple_compressed_sugarcane", {name: "Triple Compressed Sugar Cane", texture: "cropsugarcane_compressed", textureData: 2}, {destroyTime: sugarcane_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_sugarcane}, {id: BlockID.double_compressed_sugarcane});
Compress.addBlock("triple_compressed_iron", {name: "Triple Compressed Iron Block", texture: "ingotiron_compressed", textureData: 2}, {level: 2, destroyTime: iron_block_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_iron}, {id: BlockID.double_compressed_iron});
Compress.addBlock("triple_compressed_gold", {name: "Triple Compressed Gold Block", texture: "ingotgold_compressed", textureData: 2}, {level: 2, destroyTime: gold_block_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_gold}, {id: BlockID.double_compressed_gold});
Compress.addBlock("triple_compressed_diamond", {name: "Triple Compressed Diamond Block", texture: "gemdiamond_compressed", textureData: 2}, {level: 2, destroyTime: diamond_block_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_diamond}, {id: BlockID.double_compressed_diamond});
Compress.addBlock("triple_compressed_emerald", {name: "Triple Compressed Emerald Block", texture: "gememerald_compressed", textureData: 2}, {level: 2, destroyTime: emerald_block_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_emerald}, {id: BlockID.double_compressed_emerald});
Compress.addBlock("triple_compressed_lapis", {name: "Triple Compressed Lazurite Block", texture: "gemlapis_compressed", textureData: 2}, {level: 2, destroyTime: lazurite_block_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_lapis}, {id: BlockID.double_compressed_lapis});
Compress.addBlock("triple_compressed_redstone", {name: "Triple Compressed Redstone Block", texture: "dustredstone_compressed", textureData: 2}, {level: 2, destroyTime: redstone_block_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_redstone}, {id: BlockID.double_compressed_redstone});
Compress.addBlock("triple_compressed_hay", {name: "Triple Compressed Hay", texture: "cropwheat_compressed", textureData: 2}, {destroyTime: hay_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_hay}, {id: BlockID.double_compressed_hay});
Compress.addBlock("triple_compressed_clay", {name: "Triple Compressed Clay", texture: "clay_compressed", textureData: 2}, {destroyTime: clay_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_clay}, {id: BlockID.double_compressed_clay});
Compress.addBlock("triple_compressed_slime", {name: "Triple Compressed Slime", texture: "slime_compressed", textureData: 2}, {destroyTime: slime_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_slime}, {id: BlockID.double_compressed_slime});
Compress.addBlock("triple_compressed_flint", {name: "Triple Compressed Flint", texture: "flint_compressed", textureData: 2}, {destroyTime: flint_time * increasing_time * increasing_time});
Compress.addCraft({id: BlockID.triple_compressed_flint}, {id: BlockID.double_compressed_flint});

