const ATTACHMENT_SCOPE = 1;
const ATTACH_SCOPE = ATTACHMENT_SCOPE;
const ATTACHMENT_UNDERBARREL = 2;
const ATTACH_UNDERBARREL = ATTACHMENT_UNDERBARREL;
const ATTACHMENT_BARREL = 3;
const ATTACH_BARREL = ATTACHMENT_BARREL;

