const ACCURACY = 1;
const BUTTON_TYPE_CLICK = 1;
const BUTTON_TYPE_TOUCH = 2;
const SHOT_TYPE_NORMAL = 1;
const SHOT_TYPE_SINGLE = 1;
const SHOT_TYPE_SHOTGUN = 2;
const SHOT_TYPE_MULTIPLE = 2;
const SHOOTING_MODE_GRANADE = -1;
const SHOOTING_MODE_AUTO = 0;
const SHOOTING_MODE_SINGLE = 1;
const SHOOTING_MODE_DOUBLE = 2;
const SHOOTING_MODE_TRIPLE = 3;
const GUN_MAX_DAMAGE = -1;
var DEFAULT_FOV = 70;
var thisGunItem = null;
var thisGun = null;
var thisGunRate = 0;
var thisGunMode = 0;
var thisGunBullet = 0;
var thisGunAmmo = "";
var thisGunGranadeMode = false;
var thisGunGranadeBullet = 0;
var thisGunGranadeAmmo = "";
var thisGunAttachScope = "";
var thisGunAttachUnderbarrel = "";
var thisGunAttachBarrel = "";
var isShooting = false;
var shooting = false;
var countShots = 0;
var currentShotTicks = 0;
var shotTickEvent = null;
var emptyGunNotice = false;
var isReloading = false;
var isReloadingBullet = false;
var isAiming = false;
var isAimingGUI = false;
var bullets = {};
var entitys_hurt = {};
var gunSwitchSound = new Sound();
var gunEmptySound = new Sound();
var gunSound = new Sound();
var gunReloadSound = new Sound();
var gunReloadSoundOpen = new Sound();
var gunReloadSoundLoad = new Sound();
var gunReloadSoundClose = new Sound();
gunReloadSoundClose.setOnCompletion(function () {
    isReloadingBullet = false;
    isReloading = false;
});
var gunExtra = new ItemExtraData();
gunExtra.putString("ammo", "");
gunExtra.putInt("bullet", 0);
gunExtra.putBoolean("granade", false);
gunExtra.putString("ammoG", "");
gunExtra.putInt("bulletG", 0);
gunExtra.putString("attach_scope", "");
gunExtra.putString("attach_underbarrel", "");
gunExtra.putString("attach_barrel", "");

